### ISSUE TITLE
Resources: Update work of shenzhen(Fixed)

### ISSUE THREAD

**Issue by 0PYR0** [railmapgen/rmp-gallery#1003]
Hi RMP team! I would like to contribute to the gallery with the data below.

Paste or Upload below. They are meant for BOTS ONLY!!!

[SZMC (2).txt](https://github.com/railmapgen/rmp-gallery/files/13467126/SZMC.2.txt)

**Comment by thekingofcity** [comment]
Hi, upload the file without any changes after downloading from Gallery :)
