### ISSUE TITLE
Resources: Update work of kunming

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#1004]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1701162764189.txt](https://github.com/railmapgen/rmp-gallery/files/13485967/1701162764189.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your work is merged and will be available in Gallery soon :)
