### ISSUE TITLE
Resources: New work of wenzhou (incloud cr line)

### ISSUE THREAD

**Issue by AndreaFrederica** [railmapgen/rmp-gallery#1009]
[wenzhouincloudcrline.txt](https://github.com/railmapgen/rmp-gallery/files/13503513/wenzhouincloudcrline.txt)
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

**Comment by thekingofcity** [comment]
嗨，您需要重新打开一个新的议题，请遵循画廊的指示。另外，包含国铁也无需在名称上标明，直接使用 温州/Wenzhou 即可 :)
