### ISSUE TITLE
Resources: Update work of chengdu

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#1020]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1701443235351.txt](https://github.com/railmapgen/rmp-gallery/files/13528137/1701443235351.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your works is merged and should be available in Gallery soon :)
