### ISSUE TITLE
Resources: New work of Adelaide

### ISSUE THREAD

**Issue by Jimmilily** [railmapgen/rmp-gallery#1037]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[adelaide.txt](https://github.com/railmapgen/rmp-gallery/files/13557292/adelaide.txt)

**Comment by 28yfang** [comment]
您好，感谢您的贡献。
经检查，您的作品含有以下问题：
1. 红线Smithfield Interchange站英文名错误
2. 橘线Warradale站英文名错误

请在修正后重新提交，并附上本议题编号（#1037），感谢！
