### ISSUE TITLE
Resources: Update work of Brisbane

### ISSUE THREAD

**Issue by Jimmilily** [railmapgen/rmp-gallery#1039]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[brisbane (1).txt](https://github.com/railmapgen/rmp-gallery/files/13583156/brisbane.1.txt)

**Comment by thekingofcity** [comment]
Hi, there must not be any simple path with single color to be submitted to the gallery :)
