### ISSUE TITLE
Resources: Update work of macao

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#1041]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Macao",
        "zh-Hans": "澳门",
        "zh-Hant": "澳門",
        "pt": "Macau"
    },
    "desc": {
        "en": ""
    },
    "reference": "https://www.mlm.com.mo/tc/taipa_line.html",
    "justification": "Add Barra Station which opened in 8th December 2023."
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="macao">{¨svgViewBoxZoom¨¤y¨svgViewBoxMin¨{´x´£-1G.-CQ´y´£4B.4E}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨mtr¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨¨rotate¨¨transfer¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨right¨¨middle¨|¨海洋¨¨Oceano\\Ocean¨÷É||÷÷ßA»¢4q¢6IÉ¨stn_mp_yBAKHkx¨ßJ¨top¨|¨馬會¨¨Jockey Clube\\Jockey Club¨÷É||÷÷ßA»¢5K¢6mÉ¨stn_IbmsB2w71o¨ßJßK|¨運動場¨¨Estádio\\Stadium¨÷É||÷÷ßA»¢5o¢7BÉ¨stn_tV507VW6cO¨ßJßK|¨排角¨¨Pai Kok\\Pai Kok¨÷É||÷÷ßA»º4¢7fÉ¨stn_imIAv8KACr¨ßJßK|¨路氹西¨¨Cotai Oeste\\Cotai West¨÷É||÷÷ßA»º4¢89É¨stn__UPrxUpeJc¨ßK¨bottom¨|¨蓮花¨¨Lotus\\Lótus¨÷É||÷÷ßA»¢6S¢8YÉ¨stn_Xz3jUnHK-X¨ßJßK|¨東亞運¨¨Jogos da Ásia Oriental\\East Asian Games¨÷É||÷÷ßA»¢76º7É¨stn_RRhXuGEzSe¨ßJßK|¨路氹東¨¨Cotai Leste\\Cotai East¨÷É||÷÷ßA»ºAº6É¨stn_cQPSeFsDuL¨ßJßK|¨科大¨¨UCTM\\MUST¨÷É||÷÷ßA»ºAº5É¨stn_VaRXP9CAf9¨ßJßK|¨機場¨¨Aeroporto \\Airport¨÷É||÷÷ßA»¢7k¢6cÉ¨stn_Wbc-0BtGIT¨ßJßK|¨氹仔碼頭¨¨Terminal Marítimo da Taipa\\Taipa Ferry Terminal¨÷É||÷÷ßA»ºB¢68É¨stn_jRG7al2w_Q¨—{ßI¨misc_node_fMJcjAWGY0¨ß8{ßG»ßHÉ´x´¢7Q´y´¢6rß4¨virtual¨ßv{}}}{ßI¨misc_node_RgUeol94UY¨ß8{ßG»ßHÉ´x´¢4M´y´¢5eß4ßvßv{}}}{ßI¨stn_gi4FgU8wm8¨ß8{ßG»ßHÉ´x´¢3s´y´¢55ß4ßAßA{ßD|¨媽閣¨¨Barra\\Barra¨÷ßBßJßCßKßEÉßF||÷÷}}}÷¨edges¨|¦ß8¦¨perpendicular¨¦¨offsetFrom¨¨offsetTo¨¨roundCornerFactor¨¨startFrom¨‡¨reconcileId¨¨single-color¨¦¨color¨‡¨style¨ß4ßGßH‡ßI¨source¨¨target¨‡ÉÉ£I.5K´to´´´|¨macao¨¨taipa¨¨#A4D65E¨¨#fff¨÷ß17ß11»É¨line_dfQo7_bBTE¨ßNßRÉÉÝ2¨from¨´´|ß1Cß1Dß1Eß1F÷ß17ß11»É¨line_NoCdP3Uw-P¨ßRßUÉÉÝ2ß1H´´|ß1Cß1Dß1Eß1F÷ß17ß11»É¨line_SksJ8-BCYa¨ßUßXÉÉÝ2ß1H´´|ß1Cß1Dß1Eß1F÷ß17ß11»É¨line_ESVWubVMuJ¨ßXßaÉÉÝ2ß1H´´|ß1Cß1Dß1Eß1F÷ß17ß11»É¨line_kSvBrTEtxM¨ßeßaÉÉÝ2ß1H´´|ß1Cß1Dß1Eß1F÷ß17ß11»É¨line_Ym6QJs4CP1¨ßeßhÉÉÝ2ß1H´´|ß1Cß1Dß1Eß1F÷ß17ß11»É¨line_m9XP_4V-Rl¨ßhßkÉÉÝ2ß1H´´|ß1Cß1Dß1Eß1F÷ß17ß11»É¨line_CxvDHte5LE¨ßkßnÉÉÝ2ß1H´´|ß1Cß1Dß1Eß1F÷ß17ß11»É¨line_-4e57VMzZm¨ßußnÉÉÝ2ß1H´´|ß1Cß1Dß1Eß1F÷ß17ß11»É¨line_NnYDnXWAwO¨ßußqÉÉÝ2ß1H´´|ß1Cß1Dß1Eß1F÷ß17ß11»É¨line_hA_hrsMPeC¨ßqßtÉÉÝ2ß1H´´|ß1Cß1Dß1Eß1F÷ß17ß11»É¨line_m1q3sW2xr-¨ßwßNÉÉÝ2´to´´´|ß1Cß1Dß1Eß1F÷ß17ß11»É¨line_U3bWI2kGf4¨ßxßw—÷}¨version¨¤L}</details>

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板没有问题，请您等待管理员最终汇入，感谢您的贡献。
