### ISSUE TITLE
Resources: Update work of macao

### ISSUE THREAD

**Issue by 0PYR0** [railmapgen/rmp-gallery#1043]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Macao",
        "zh-Hans": "澳门",
        "zh-Hant": "澳門",
        "pt": "Macau"
    },
    "desc": {
        "en": ""
    },
    "reference": "https://www.mlm.com.mo/tc/taipa_line.html",
    "justification": "added north extension of taipa line"
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="macao">{¨svgViewBoxZoom¨¤o¨svgViewBoxMin¨{´x´£d.6S´y´£2q.AD}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨mtr¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨¨rotate¨¨transfer¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨right¨¨middle¨|¨海洋¨¨Oceano\\Ocean¨÷É||÷÷ßA»¢4q¢6IÉ¨stn_mp_yBAKHkx¨ßJ¨top¨|¨馬會¨¨Jockey Clube\\Jockey Club¨÷É||÷÷ßA»¢5K¢6mÉ¨stn_IbmsB2w71o¨ßJßK|¨運動場¨¨Estádio\\Stadium¨÷É||÷÷ßA»¢5o¢7BÉ¨stn_tV507VW6cO¨ßJßK|¨排角¨¨Pai Kok\\Pai Kok¨÷É||÷÷ßA»º4¢7fÉ¨stn_imIAv8KACr¨ßJßK|¨路氹西¨¨Cotai Oeste\\Cotai West¨÷É||÷÷ßA»º4¢89É¨stn__UPrxUpeJc¨ßK¨bottom¨|¨蓮花¨¨Lotus\\Lótus¨÷É||÷÷ßA»¢6S¢8YÉ¨stn_Xz3jUnHK-X¨ßJßK|¨東亞運¨¨Jogos da Ásia Oriental\\East Asian Games¨÷É||÷÷ßA»¢76º7É¨stn_RRhXuGEzSe¨ßJßK|¨路氹東¨¨Cotai Leste\\Cotai East¨÷É||÷÷ßA»ºAº6É¨stn_cQPSeFsDuL¨ßJßK|¨科大¨¨UCTM\\MUST¨÷É||÷÷ßA»ºAº5É¨stn_VaRXP9CAf9¨ßJßK|¨機場¨¨Aeroporto \\Airport¨÷É||÷÷ßA»¢7uº8É¨stn_Wbc-0BtGIT¨ßJßK|¨氹仔碼頭¨¨Terminal Marítimo da Taipa\\Taipa Ferry Terminal¨÷É||÷÷ßA»ºB¢5yÉ¨stn_jRG7al2w_Q¨—{ßI¨misc_node_fMJcjAWGY0¨ß8{ßG»ßHÉ´x´¢7V´y´º3ß4¨virtual¨ßv{}}}{ßI¨stn_UH1YobYOwH¨ß8{ßG»ßHÉ´x´º0´y´º2ß4ßAßA{ßD|¨媽閣¨¨Barra\\Barra¨÷ßBßJßCßKßEÉßF||÷÷}}}÷¨edges¨|¦ß8¦¨perpendicular¨¦¨offsetFrom¨¨offsetTo¨¨roundCornerFactor¨¨startFrom¨‡¨reconcileId¨¨single-color¨¦¨color¨‡¨style¨ß4ßGßH‡ßI¨source¨¨target¨‡ÉÉ£I.5K´to´´´|¨macao¨¨taipa¨¨#A4D65E¨¨#fff¨÷ß16ß10»É¨line_dfQo7_bBTE¨ßNßRÉÉÝ2¨from¨´´|ß1Bß1Cß1Dß1E÷ß16ß10»É¨line_NoCdP3Uw-P¨ßRßUÉÉÝ2ß1G´´|ß1Bß1Cß1Dß1E÷ß16ß10»É¨line_SksJ8-BCYa¨ßUßXÉÉÝ2ß1G´´|ß1Bß1Cß1Dß1E÷ß16ß10»É¨line_ESVWubVMuJ¨ßXßaÉÉÝ2ß1G´´|ß1Bß1Cß1Dß1E÷ß16ß10»É¨line_kSvBrTEtxM¨ßeßaÉÉÝ2ß1G´´|ß1Bß1Cß1Dß1E÷ß16ß10»É¨line_Ym6QJs4CP1¨ßeßhÉÉÝ2ß1G´´|ß1Bß1Cß1Dß1E÷ß16ß10»É¨line_m9XP_4V-Rl¨ßhßkÉÉÝ2ß1G´´|ß1Bß1Cß1Dß1E÷ß16ß10»É¨line_CxvDHte5LE¨ßkßnÉÉÝ2ß1G´´|ß1Bß1Cß1Dß1E÷ß16ß10»É¨line_-4e57VMzZm¨ßußnÉÉÝ2ß1G´´|ß1Bß1Cß1Dß1E÷ß16ß10»É¨line_NnYDnXWAwO¨ßußqÉÉÝ2ß1G´´|ß1Bß1Cß1Dß1E÷ß16ß10»É¨line_hA_hrsMPeC¨ßqßt—{ßI¨line_gAxQQwV3WC¨ß19ßwß1AßNß8{ßG»ßHÉß4¨diagonal¨ß1S{ß14ß1Gß11Éß12Éß13¤A}ß18ß16ß16{ß17|ß1Bß1Cß1Dß1E÷}ß15´´}}÷}¨version¨¤L}</details>

**Comment by langonginc** [comment]
很抱歉，在您前面已有贡献者提交了修改，遵循先到先得的原则，我们不能应用您的修改。感谢您的贡献。

参见 #1041

**Comment by thekingofcity** [comment]
嗨，您可以在修改后的作品基础上再更新，如果必要的话 :)
