### ISSUE TITLE
Resources: New work of Perth

### ISSUE THREAD

**Issue by Jimmilily** [railmapgen/rmp-gallery#1045]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[perth.txt](https://github.com/railmapgen/rmp-gallery/files/13617547/perth.txt)

**Comment by linchen1965** [comment]
您好，经检查我们发现以下问题：
Claremont站和Loch Street站之间缺少Showgrounds站
![QYYM1 WLR}J764{T{ERV(~6](https://github.com/railmapgen/rmp-gallery/assets/92020676/c0c36aef-9c2a-4348-b526-b47fe8e550ce)

Greenwood站缺少中文名
![Q5449V0S{TL5OJ)@GI NN G](https://github.com/railmapgen/rmp-gallery/assets/92020676/99c8381b-6633-468d-a82b-4a1faf04bece)

Beckenham站应位于主线而不是支线
![N TW}SHWOU@KN9235UUALQF](https://github.com/railmapgen/rmp-gallery/assets/92020676/67046605-2913-4972-ab94-bab6a3bb28a1)

请在修正上述问题后重新开启一个新的Issue，并在新Issue中附上本Issue的编号（https://github.com/railmapgen/rmp-gallery/issues/1045 ），感谢您的支持。

检查参照：https://www.transperth.wa.gov.au/Tickets-Fares/Zone-Map
