### ISSUE TITLE
Resources: Update work of pyongyang

### ISSUE THREAD

**Issue by Bit103** [railmapgen/rmp-gallery#1049]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Pyongyang"
    },
    "desc": {
        "en": ""
    },
    "reference": "https://zh.wikipedia.org/wiki/平壤地鐵",
    "justification": " "
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="pyongyang">{¨svgViewBoxZoom¨¤p¨svgViewBoxMin¨{´x´£Aq.8Y´y´£r.9M}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨mtr¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨¨rotate¨¨transfer¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨right¨¨top¨|¨광복¨¨Kwangbok¨÷É||÷÷ßA»¢EW¢3OÉ¨stn_Jz0N9Up157¨ßJßK|¨건국¨¨Konguk¨÷É||÷÷ßA»¢FKº1É¨stn_GUn1e_EGWK¨ßJßK|¨건설¨¨Konsol¨÷É||÷÷ßA»¢G8¢39É¨stn_IqMm2o0wBU¨ßJßK|¨车站¨¨Stn¨÷É||÷÷ßA»¢Gm¢2VÉ¨stn_5WTcCLkPDs¨ßJßK|¨혁신¨¨Hyoksin¨÷É||÷÷ßA»¢Ha¢1rÉ¨stn_JGShTbgcsF¨—÷¨edges¨|¦ß8¦¨diagonal¨¦¨offsetFrom¨¨offsetTo¨¨roundCornerFactor¨¨startFrom¨‡¨reconcileId¨¨single-color¨¦¨color¨‡¨style¨ß4ßGßH‡ßI¨source¨¨target¨‡ÉÉ¤A¨from¨´´|¨other¨ßn¨#33c759¨¨#fff¨÷ßhßb»É¨line_DbEkqRGrdt¨ßNßQÉÉ¤Aßm´´|ßnþßoßp÷ßhßb»É¨line_7c0RlGHKoZ¨ßQßTÉÉ¤Aßm´´|ßnþßoßp÷ßhßb»É¨line_oc-GcM8FNw¨ßWßT—÷}¨version¨¤L}</details>

**Comment by 28yfang** [comment]
Hi, please explain what you updated in the Justification text box. Also, I see that you have deleted the original lines and added your own line. Can you please explain why you deleted them?
