### ISSUE TITLE
Compress thumbnails to reduce loading time and size of built artefacts

### ISSUE THREAD

**Issue by wongchito** [railmapgen/rmp-gallery#1073]
Since the launch of RMP Gallery in April, the user population has grown significantly and a huge number of _works_ have been added to the gallery. Thanks to all the donators and contributors!

While celebrating what we've achieved this year, we also need to review what we can improve to make the platform more stable and reliable as things grow. Recently when I was refactoring the workflow of pushing/pulling artefacts (railmapgen/upload-artefacts#1), I noticed that RMP Gallery is uploading big artefacts to the repositories, and due to the nature of the project, it's uploading this size of artefacts every few days. 

> remote: warning: File rmp-gallery/1.8.7.tar.gz is 82.52 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB 

According to [Github's documentation](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#file-size-limits), files larger than 100 MB will be blocked from pushing. 

By checking the artefacts, it's not hard to tell that the thumbnails of all the _works_ take most of the space. A 300px thumbnail is about 40KB to 100KB, and a full-size thumbnail is about 700KB to 2MB. The size can also potentially impact the user experience when loading the UI, as most of our users located in China.

<img width="1440" alt="image" src="https://github.com/railmapgen/rmp-gallery/assets/9390786/b1464c23-59bd-487f-b398-34edc6662b64">

It's about time for us to rethink how we manage these thumbnails. Google suggests that [using WebP format for images can reduce 26% in size](https://developers.google.com/speed/webp) and make the web faster. Also, [Sharp](https://www.npmjs.com/package/sharp) seems to be a useful package to do this job. We should start trying if the solution suits us and enhance the image generation logic if the testing result is positive.

**Comment by wongchito** [comment]
As discussed offline, we agreed to enhance the release workflow by getting rid of `rmg-repositories`. Instead, we're using the new railmapgen/releaser action to deploy to both GitHub and GitLab directly after project is built. See #1090 

However, it's still worth considering compress thumbnails for saving network connection time for a better user experience. @thekingofcity

**Comment by thekingofcity** [comment]
I tried adjusting the `compressionLevel` in sharp but the size won't change :(

```node
import sharp from 'sharp';
import { resolve } from 'path';

const cityName = 'wuhan';
const path = resolve('..', 'public', 'resources', 'thumbnails', `${cityName}.png`);
const original = await readFile(path);
const img = sharp(original, { limitInputPixels: 1024000000 });
console.log((await img.metadata()).size);
console.log((await(img.png({ compressionLevel: 9 })).metadata()).size);
```

```bash
rmp-gallery\scripts> node --loader ts-node/esm .\compress.ts
(node:28516) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
1628854
1628854
```

And the width and height should not be smaller anymore. Actually, the original image is made with a 200% zoom level as the default font size is too small to distinguish in 100% zoom level. And the thumbnail with the `@300` suffix is the additional method to save the network bandwidth.

**Comment by wongchito** [comment]
If that's the case, then I think there's nothing else we could do for now except for #1090.
