### ISSUE TITLE
Resources: Update work of foshan

### ISSUE THREAD

**Issue by 0PYR0** [railmapgen/rmp-gallery#1093]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[foshan.txt](https://github.com/railmapgen/rmp-gallery/files/13778865/foshan.txt)

**Comment by 28yfang** [comment]
您好，感谢您的贡献。
经检查，您的作品中含有以下问题：
1. 7号线深井站英文名错误，正确的为Shenjing
2. 7号线大沙东站英文名未填，正确的为Dashadong
3. 建议将大学城南站名称偏移改为right，bottom并删除旁边的广州7号线标识。

请在修正后重新提交，并附上本议题编号（#1093），感谢。
