### ISSUE TITLE
Resources: Update work of Guangzhou

### ISSUE THREAD

**Issue by 0PYR0** [railmapgen/rmp-gallery#1095]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[guangzhou (1).txt](https://github.com/railmapgen/rmp-gallery/files/13874418/guangzhou.1.txt)

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板包括但不限于以下问题：

- 科丰路站英文站名错误，应为“Kefeng Lu”不为"Kefeng Road"
- 黄埔有轨2号线暂未开通，但我们没看到您的未开通标识

_（如您有异议，请留下您的证明来源）_

请您修改后重新提交，感谢您的贡献。
