### ISSUE TITLE
Resources: Update work of nanjing

### ISSUE THREAD

**Issue by G9913** [railmapgen/rmp-gallery#1101]
[nanjing (1).txt](https://github.com/railmapgen/rmp-gallery/files/13785058/nanjing.1.txt)
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板没有问题。
以下是一个建议：其他贡献者提交的线路图在终点站后都有一小部分延长线。请问您要做修改吗？
<img width="50" alt="截屏2024-01-27 10 07 44" src="https://github.com/railmapgen/rmp-gallery/assets/99594702/0cba71f7-33b2-4aea-bcf8-73935d80a89b">
<img width="27" alt="截屏2024-01-27 10 07 53" src="https://github.com/railmapgen/rmp-gallery/assets/99594702/da6ddd73-e366-4355-98cc-a55f8abf607d">

_（如果您在一个月内未按时回复，我们将不采纳我们的建议直接汇入。）_

**Comment by G9913** [comment]
> 您好，您所提交的模板没有问题。 以下是一个建议：其他贡献者提交的线路图在终点站后都有一小部分延长线。请问您要做修改吗？ <img alt="截屏2024-01-27 10 07 44" width="50" src="https://private-user-images.githubusercontent.com/99594702/300146116-0cba71f7-33b2-4aea-bcf8-73935d80a89b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMjk0ODEsIm5iZiI6MTcwODIyOTE4MSwicGF0aCI6Ii85OTU5NDcwMi8zMDAxNDYxMTYtMGNiYTcxZjctMzNiMi00YWVhLWJjZjgtNzM5MzVkODBhODliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA0MDYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4OWY5ZTI2ZTdlYTMyMGQwZDNkZTczOTU3OTIwZDBlYTc5M2E3YTFkMzc4YTRhZDU2Y2IxYTQ4OWUyZDA2NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pBV6k9ALqL5Xdx_5ucpwtOydEPyLqls6TZ2AYFvxZB8"> <img alt="截屏2024-01-27 10 07 53" width="27" src="https://private-user-images.githubusercontent.com/99594702/300146119-da6ddd73-e366-4355-98cc-a55f8abf607d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMjk0ODEsIm5iZiI6MTcwODIyOTE4MSwicGF0aCI6Ii85OTU5NDcwMi8zMDAxNDYxMTktZGE2ZGRkNzMtZTM2Ni00MzU1LTk4Y2MtYTU1ZjhhYmY2MDdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA0MDYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZDhmYWM3ODBmZDQyOTY5NWM4NGQ0NWU1NWVmZWNlMDI1NGQ0YTE4NGUwNTMyMTlhZjk4Yjk0OTU0YWVlNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9B_psy0wb-73Oi9Q3ps1aDDVGYpxafur3Hx2UjtfOO8">
> 
> _（如果您在一个月内未按时回复，我们将不采纳我们的建议直接汇入。）_

不用了
