### ISSUE TITLE
Resources: Update work of shenzhen

### ISSUE THREAD

**Issue by KuKingTinKimi** [railmapgen/rmp-gallery#1105]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[shenzhen.txt](https://github.com/railmapgen/rmp-gallery/files/13785400/shenzhen.txt)

**Comment by Windows-Taskmgr** [comment]
您好，由于有贡献者已经在 #1091 中提交了，我们遵循“先到先得”原则，所以我们不会汇入您的模板，再此我们深表歉意，感谢您的贡献。
