### ISSUE TITLE
Resources: Update work of chengdu

### ISSUE THREAD

**Issue by fwj6666** [railmapgen/rmp-gallery#1119]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[chengdu.txt](https://github.com/railmapgen/rmp-gallery/files/13802218/chengdu.txt)

**Comment by 28yfang** [comment]
您好，画廊中的成都的模版中已有19号线二期，也就是说您的作品没有更新任何线路，并且美观性也下降了，因此我们不会汇入此作品。感谢您的贡献。
