### ISSUE TITLE
资源：更新北京的工作

### ISSUE THREAD

**Issue by 8-0-2** [railmapgen/rmp-gallery#1123]
嗨，RMP团队！我想用以下数据为画廊做出贡献。**粘贴或上传到下面。它们仅供机器人使用！！！**

[beijing.txt](https://github.com/railmapgen/rmp-gallery/files/13803626/beijing.txt)

**Comment by langonginc** [comment]
您好，请勿翻译这个页面，也不要删除加粗字，谢谢。
