### ISSUE TITLE
Resources: Update work of beijing

### ISSUE THREAD

**Issue by 8-0-2** [railmapgen/rmp-gallery#1124]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**
[beijing-2.txt](https://github.com/railmapgen/rmp-gallery/files/13803633/beijing-2.txt)

**Comment by Windows-Taskmgr** [comment]
您好，由于有贡献者已经在 https://github.com/railmapgen/rmp-gallery/issues/1117 中提交了，我们遵循“先到先得”原则，所以我们不会汇入您的模板，再此我们深表歉意，感谢您的贡献。
