### ISSUE TITLE
Resources: Update work of guangzhou

### ISSUE THREAD

**Issue by splovl** [railmapgen/rmp-gallery#1127]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[guangzhou.txt](https://github.com/railmapgen/rmp-gallery/files/13803739/guangzhou.txt)

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板包括但不限于以下问题：

- 深井、长洲站均被您误写成板桥站
- 萝岗站-市民广场站站外换乘未标出
- 广州南站现可以站内换乘

_（如您有异议，请留下您的证明来源。）_

请您修改后重新提交，感谢您的贡献。
