### ISSUE TITLE
Resources: Update work of kaohsiung

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#1129]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1704094274430.txt](https://github.com/railmapgen/rmp-gallery/files/13803841/1704094274430.txt)

**Comment by 28yfang** [comment]
您好，感谢您对画廊的贡献。
经检查，您的模版含有以下问题：
1. 红线草衙站英文名错误，正确的为Caoya
2. 轻轨与橘线的换乘站遗漏轻轨站名（哈瑪星 Hamasen）

请在修正后重新提交，并附上本议题编号（#1129），感谢！
