### ISSUE TITLE
Resources: Update work of toronto

### ISSUE THREAD

**Issue by 52PD** [railmapgen/rmp-gallery#1140]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[toronto.txt](https://github.com/railmapgen/rmp-gallery/files/13855257/toronto.txt)

**Comment by 28yfang** [comment]
您好，感谢您的贡献。
经检查，您的模版含有以下问题：
在3号线永久停运的提示中，网址漏写了数字3，正确的应为 ttc.ca/line3
请在修正后重新提交，并附上本议题编号 （#1140），感谢！
