### ISSUE TITLE
Resources: Update work of beijing

### ISSUE THREAD

**Issue by Xiao-qian111** [railmapgen/rmp-gallery#1148]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[beijing.txt](https://github.com/railmapgen/rmp-gallery/files/13915783/beijing.txt)

**Comment by Windows-Taskmgr** [comment]
您好，参考链接应选自在线网站而不选自本地文件。且由于有贡献者在 #1163 中也提交了，所以我们将不会汇入您的模板，感谢您的贡献。由此给您带来的不便，我们深表歉意。
