### ISSUE TITLE
Resources: New work of nagpur

### ISSUE THREAD

**Issue by DQB061204** [railmapgen/rmp-gallery#1151]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Nagpur",
        "zh-Hans": "那格浦尔",
        "zh-Hant": "那格浦爾",
        "hi": "नागपूर"
    },
    "desc": {
        "en": "Nagpur is a city in Middle India and have 2 metro lines. The two lines are Orange Line and Aqua Line.",
        "zh-Hans": "那格浦尔是印度中部的一座城市，有2条地铁线。 两条线路分别是橙线和水线。",
        "zh-Hant": "那格浦爾是印度中部的城市，有2條地鐵線。 兩條線路分別是橘線和水線。",
        "hi": "नागपुर मध्य भारत का एक शहर है जहाँ 2 मेट्रो लाइनें हैं। ये दो रेखाएं हैं ऑरेंज रेखा और जल रेखा।"
    },
    "reference": "https://www.metrorailnagpur.com/project-profile",
    "justification": "New template of Nagpur"
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="nagpur">{¨svgViewBoxZoom¨¤y¨svgViewBoxMin¨{´x´£20.4q´y´£2C.9g}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨shmetro-basic-2020¨¦¨color¨¨names¨¨rotate¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡|¨nagpur¨¨orange¨¨#f57c00¨¨#fff¨÷|¨汽车广场¨¨ऑटोमोटिव्ह चौक\\Automotive Square¨÷¢55ßA»¢8s¢47É¨stn_aZXqUISR2s¨|ßHßIßJßK÷|¨纳里路¨¨नारी रोड\\Nari Road¨÷º0ßA»¢8J¢4gÉ¨stn_Q_WBypON1Q¨|ßHßIßJßK÷|¨卡德比广场¨¨कडबी स्क्वेअर\\Kadbi Square¨÷º0ßA»¢7p¢5AÉ¨stn_huzUrRy-V-¨|ßHßIßJßK÷|¨卡斯特昌德公园¨¨कस्तूरचंद पार्क\\Kasturchand Park¨÷¢4MßA»¢7L¢5yÉ¨stn_hvv9Id4MKz¨|ßHßIßJßK÷|¨零英里自由公园¨¨झिरो माईल फ्रीडम पार्क\\Zero Mile Freedom Park¨÷º7ßA»º8¢6cÉ¨stn_0pudY-B1FY¨—{ßG¨stn_EtMkQgze9-¨ß8{ßE»ßFÉ´x´º8´y´¢7aß4¨shmetro-int¨ßb{ßC|¨西塔布尔迪¨¨सिताबुल्डी\\Sitabuldi¨÷¨nameOffsetX¨¨right¨¨nameOffsetY¨¨top¨ßDÉ¨height¨¤A¨width¨¤D}}}{ßG¨misc_node_KWMa6pvdlK¨ß8{ßE»ßFÉ´x´¢7k´y´¢8Eß4¨virtual¨ßl{}}}{ßG¨stn_5iF3v1rLg9¨ß8{ßE»ßFÉ´x´¢84´y´¢8iß4ßAßA{ßC|¨那加尔国会¨¨कांग्रेस नगर\\Congress Nagar¨÷ßD¢1SßB|ßHßIßJßK÷}}}{ßG¨misc_node_u7sfySo5_K¨ß8{ßE»ßFÉ´x´¢7f´y´¢9Cß4ßlßl{}}}{ßG¨stn_LFm7doY5ZY¨ß8{ßE»ßFÉ´x´º8´y´¢A5ß4ßAßA{ßC|¨拉哈特殖民地¨¨राहते कॉलनी\\Rahate Colony¨÷ßDºGßB|ßHßIßJßK÷}}}{ßG¨stn_ykdzmJO9eS¨ß8{ßE»ßFÉ´x´º8´y´¢Ajß4ßAßA{ßC|¨阿吉尼广场¨¨अजनी चौक\\Ajni Square¨÷ßDºGßB|ßHßIßJßK÷}}}{ßG¨stn_b2t5kxXI_u¨ß8{ßE»ßFÉ´x´º8´y´¢BNß4ßAßA{ßC|¨贾特拉帕蒂广场¨¨छत्रपती चौक\\Chhatrapati Square¨÷ßDºGßB|ßHßIßJßK÷}}}{ßG¨stn_DeF-U2T9_N¨ß8{ßE»ßFÉ´x´º8´y´¢C1ß4ßAßA{ßC|¨贾普拉卡什纳加尔¨¨जयप्रकाश नगर\\Jaiprakash Nagar¨÷ßDºGßB|ßHßIßJßK÷}}}{ßG¨stn_vFHWU1gBIf¨ß8{ßE»ßFÉ´x´º8´y´¢Cfß4ßAßA{ßC|¨乌吉瓦尔纳加尔¨¨उज्ज्वल नगर\\Ujjwal Nagar¨÷ßDºGßB|ßHßIßJßK÷}}}{ßG¨stn_8GfjW8f0Dx¨ß8{ßE»ßFÉ´x´º8´y´¢DJß4ßAßA{ßC|´机场´¨एअरपोर्ट\\Airport¨÷ßDºGßB|ßHßIßJßK÷}}}{ßG¨stn_mZj1U5CcbB¨ß8{ßE»ßFÉ´x´º8´y´¢Dxß4ßAßA{ßC|¨机场南¨¨एअरपोर्ट साउथ\\Airport South¨÷ßDºGßB|ßHßIßJßK÷}}}{ßG¨stn_nNEzFcx4Pk¨ß8{ßE»ßFÉ´x´º8´y´¢Eqß4ßAßA{ßC|¨新机场¨¨नव एअरपोर्ट\\New Airport¨÷ßDºGßB|ßHßIßJßK÷}}}{ßG¨stn_gpvxP545uc¨ß8{ßE»ßFÉ´x´º8´y´¢Ftß4ßAßA{ßC|¨卡普里¨¨खापरी\\Khapri¨÷ßDºGßB|ßHßIßJßK÷}}}{ßG¨stn_9ngvFFcvg9¨ß8{ßE»ßFÉ´x´¢8Y´y´¢6rß4ßAßA{ßC|¨那格浦尔火车站¨¨नागपूर रेल्वे स्टेशन\\Nagpur Railway Station¨÷ßDºGßB|ßH¨aqua¨¨#0288d1¨ßK÷}}}{ßG¨stn_fX0KPsXpxq¨ß8{ßE»ßFÉ´x´¢9b´y´¢63ß4ßAßA{ßC|¨多萨尔吠舍广场¨¨दोसर वैश्य चौक\\Dosar Vaishya Square¨÷ßD¢2ußB|ßHß1Jß1KßK÷}}}{ßG¨stn_UqGYFaTrhj¨ß8{ßE»ßFÉ´x´¢AU´y´ºVß4ßAßA{ßC|¨阿格拉森广场¨¨अग्रसेन चौक\\Agrasen Square¨÷ßDÉßB|ßHß1Jß1KßK÷}}}{ßG¨stn_8xHt4Ac2o4¨ß8{ßE»ßFÉ´x´ºL´y´ºVß4ßAßA{ßC|¨奇特罗利广场¨¨चित्रोली चौक\\Chitroli Square¨÷ßDºWßB|ßHß1Jß1KßK÷}}}{ßG¨stn_YlPV0OnVA7¨ß8{ßE»ßFÉ´x´¢CL´y´ºVß4ßAßA{ßC|¨电信交易中心¨¨टेलिफोन एक्सचेंज\\Telephone Exchange¨÷ßDÉßB|ßHß1Jß1KßK÷}}}{ßG¨stn_cVFSDkj7sA¨ß8{ßE»ßFÉ´x´¢DE´y´ºVß4ßAßA{ßC|¨安贝德卡广场¨¨आंबेडकर स्क्वेअर\\Ambedkar Square¨÷ßDºWßB|ßHß1Jß1KßK÷}}}{ßG¨stn_4qunExH-F3¨ß8{ßE»ßFÉ´x´¢E7´y´ºVß4ßAßA{ßC|¨外什诺德维广场¨¨वैष्णोदेवी चौक\\Vaishnodevi Square¨÷ßDÉßB|ßHß1Jß1KßK÷}}}{ßG¨stn_T_C8nJ4sTT¨ß8{ßE»ßFÉ´x´¢F0´y´¢5jß4ßAßA{ßC|¨帕贾帕蒂纳加尔¨¨प्रजापती नगर\\Prajapati Nagar¨÷ßD¢2BßB|ßHß1Jß1KßK÷}}}{ßG¨stn_-8fsds6u14¨ß8{ßE»ßFÉ´x´ºA´y´ºBß4ßAßA{ßC|¨占西拉尼广场¨¨झंसी रानी चौक\\Jhansi Rani Square¨÷ßDÉßB|ßHß1Jß1KßK÷}}}{ßG¨stn_3pHwITfC5M¨ß8{ßE»ßFÉ´x´¢5e´y´ºBß4ßAßA{ßC|¨香卡纳加尔广场¨¨शंकर नगर चौक\\Shankar Nagar Square¨÷ßDºWßB|ßHß1Jß1KßK÷}}}{ßG¨stn_FOXnfm8v4c¨ß8{ßE»ßFÉ´x´º4´y´ºBß4ßAßA{ßC|¨拉德广场¨¨एलएडी चौक\\LAD Square¨÷ßDÉßB|ßHß1Jß1KßK÷}}}{ßG¨stn_TGweqG7MPL¨ß8{ßE»ßFÉ´x´º2´y´¢8Tß4ßAßA{ßC|¨达兰佩斯学院¨¨धरमपेठ कॉलेज\\Dharampeth College¨÷ßDºGßB|ßHß1Jß1KßK÷}}}{ßG¨stn_afdHqaGJXX¨ß8{ßE»ßFÉ´x´¢3O´y´¢97ß4ßAßA{ßC|¨苏巴斯纳加尔¨¨सुभाष नगर\\Subhash Nagar¨÷ßDÉßB|ßHß1Jß1KßK÷}}}{ßG¨stn_3p9oDB8-10¨ß8{ßE»ßFÉ´x´¢2L´y´ºhß4ßAßA{ßC|¨拉查纳环路路口¨¨रचना रिंग रोड जंक्शन\\Rachana Ring Road Junction¨÷ßDºWßB|ßHß1Jß1KßK÷}}}{ßG¨stn_qBQzzlxQHm¨ß8{ßE»ßFÉ´x´¢1I´y´ºhß4ßAßA{ßC|¨瓦苏德夫纳加尔¨¨वासुदेव नगर\\Vasudev Nagar¨÷ßDÉßB|ßHß1Jß1KßK÷}}}{ßG¨stn_taAdt34T17¨ß8{ßE»ßFÉ´x´¤K´y´¢9Rß4ßAßA{ßC|¨班西纳加尔¨¨बन्सी नगर\\Bansi Nagar¨÷ßDºdßB|ßHß1Jß1KßK÷}}}{ßG¨stn_kColfr9BrX¨ß8{ßE»ßFÉ´x´¢-K´y´ºJß4ßAßA{ßC|¨洛克马尼亚纳加尔¨¨लोकमान्य नगर\\Lokmanya Nagar¨÷ßDº0ßB|ßHß1Jß1KßK÷}}}÷¨edges¨|¦ß8¦¨diagonal¨¦¨offsetFrom¨¨offsetTo¨¨roundCornerFactor¨¨startFrom¨‡¨reconcileId¨¨single-color¨¦ßB‡¨style¨ß4ßEßF‡ßG¨source¨¨target¨‡ÉÉ¤A¨from¨´´|ßHßIßJßK÷ß2Eß28»É¨line_7tvSAJAXVA¨ßNßQÉÉ¤Aß2I´´|ßHßIßJßK÷ß2Eß28»É¨line_UePhsgKny-¨ßQßTÉÉ¤A´to´´´|ßHßIßJßK÷ß2Eß28»É¨line_ccmJr9Xzrk¨ßTßWÉÉ¤Aß2I´´|ßHßIßJßK÷ß2Eß28»É¨line_p4ymfAE82z¨ßWßZÉÉ¤Aß2I´´|ßHßIßJßK÷ß2Eß28»É¨line_w7SRbIMbQK¨ßZßa—{ßG¨line_o6zWpdYv7o¨ß2Gßaß2Hßkß8{ßE»ßFÉß4¨perpendicular¨ß2P{ß2C´to´ß29Éß2AÉß2B£I.5K}ß2Fß2Eß2E{ßB|ßHßIßJßK÷}ß2D´´}}{ßG¨line_v1YPIrHcAC¨ß2Gßkß2Hßmß8{ßE»ßFÉß4ß2Pß2P{ß2Cß2Iß29Éß2AÉß2BÝ2}ß2Fß2Eß2E{ßB|ßHßIßJßK÷}ß2D´´}}{ßG¨line_1JN7MGsnxv¨ß2Gßmß2Hßpß8{ßE»ßFÉß4ß2Pß2P{ß2C´to´ß29Éß2AÉß2BÝ2}ß2Fß2Eß2E{ßB|ßHßIßJßK÷}ß2D´´}}{ßG¨line_u5nCuhAp0y¨ß2Gßpß2Hßqß8{ßE»ßFÉß4ß2Pß2P{ß2Cß2Iß29Éß2AÉß2BÝ2}ß2Fß2Eß2E{ßB|ßHßIßJßK÷}ß2D´´}}{ßG¨line_ierfQCafjj¨ß2Gßtß2Hßqß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHßIßJßK÷}ß2D´´}}{ßG¨line_WfbnIk7Mon¨ß2Gßtß2Hßwß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHßIßJßK÷}ß2D´´}}{ßG¨line_rmN27R4vGs¨ß2Gßwß2Hßzß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHßIßJßK÷}ß2D´´}}{ßG¨line_tv8_uLtlTY¨ß2Gßzß2Hß12ß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHßIßJßK÷}ß2D´´}}{ßG¨line_yxjAQnQYKV¨ß2Gß12ß2Hß15ß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHßIßJßK÷}ß2D´´}}{ßG¨line_avlBWQ3ykd¨ß2Gß15ß2Hß17ß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHßIßJßK÷}ß2D´´}}{ßG¨line_ojWtgt44pM¨ß2Gß17ß2Hß1Aß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHßIßJßK÷}ß2D´´}}{ßG¨line_KX1qqWHFYA¨ß2Gß1Aß2Hß1Dß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHßIßJßK÷}ß2D´´}}{ßG¨line_pRYznuKVfx¨ß2Gßaß2Hß1Gß8{ßE»ßFÉß4ß2Pß2P{ß2Cß2Iß29Éß2AÉß2BÝ2}ß2Fß2Eß2E{ßB|ßHß1Jß1KßK÷}ß2D´´}}{ßG¨line_gj--HtcXJp¨ß2Gß1Lß2Hß1Gß8{ßE»ßFÉß4ß2Pß2P{ß2Cß2Iß29Éß2AÉß2BÝ2}ß2Fß2Eß2E{ßB|ßHß1Jß1KßK÷}ß2D´´}}{ßG¨line_24ejjzZ9qC¨ß2Gß1Lß2Hß1Oß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHß1Jß1KßK÷}ß2D´´}}{ßG¨line_I2XWHKQ8i3¨ß2Gß1Oß2Hß1Rß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHß1Jß1KßK÷}ß2D´´}}{ßG¨line_Lc7HP7JH1C¨ß2Gß1Rß2Hß1Uß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHß1Jß1KßK÷}ß2D´´}}{ßG¨line_LrXdKKpDwl¨ß2Gß1Uß2Hß1Xß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHß1Jß1KßK÷}ß2D´´}}{ßG¨line_rkEiD_1lfP¨ß2Gß1Xß2Hß1aß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHß1Jß1KßK÷}ß2D´´}}{ßG¨line_r1z8Ii4CUc¨ß2Gß1aß2Hß1dß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHß1Jß1KßK÷}ß2D´´}}{ßG¨line_tofcuATDyt¨ß2Gß1gß2Hßaß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHß1Jß1KßK÷}ß2D´´}}{ßG¨line_6CeAaH5s7o¨ß2Gß1jß2Hß1gß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHß1Jß1KßK÷}ß2D´´}}{ßG¨line_bK8LVahQO1¨ß2Gß1mß2Hß1jß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHß1Jß1KßK÷}ß2D´´}}{ßG¨line_DZwLSAR1iH¨ß2Gß1mß2Hß1pß8{ßE»ßFÉß4ß2Pß2P{ß2Cß2Iß29Éß2AÉß2BÝ2}ß2Fß2Eß2E{ßB|ßHß1Jß1KßK÷}ß2D´´}}{ßG¨line_-VtNGdtmzF¨ß2Gß1sß2Hß1pß8{ßE»ßFÉß4ß2Pß2P{ß2Cß2Iß29Éß2AÉß2BÝ2}ß2Fß2Eß2E{ßB|ßHß1Jß1KßK÷}ß2D´´}}{ßG¨line_ElGPbmyzI_¨ß2Gß1vß2Hß1sß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHß1Jß1KßK÷}ß2D´´}}{ßG¨line_WZO2JxJC4A¨ß2Gß1yß2Hß1vß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHß1Jß1KßK÷}ß2D´´}}{ßG¨line_WzhXA_MeCr¨ß2Gß1yß2Hß21ß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHß1Jß1KßK÷}ß2D´´}}{ßG¨line_KMQ0_dYs20¨ß2Gß21ß2Hß24ß8{ßE»ßFÉß4ß28ß28{ß2Cß2Iß29Éß2AÉß2B¤A}ß2Fß2Eß2E{ßB|ßHß1Jß1KßK÷}ß2D´´}}÷}¨version¨¤Q}</details>

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. However, there are some problems with the work you submitted.

* Missing _Gaddi Godam Square_ between _Kadbi Square_ and _Kasturchand Park _
* Missing _Cotton Market_ between _Nagpur Railway Station_ and _Sitabuldi (EW)_
* _Rachana Ring Road Junction_ instead of _Rachana Ring Road_

Resubmit this work as a new issue after fixing and attach this issue number #1151.
