### ISSUE TITLE
Resources: Update work of beijing

### ISSUE THREAD

**Issue by LYSliuyisi** [railmapgen/rmp-gallery#1163]
Hi RMP team! I would like to contribute to the gallery with the data below.
This update includes new lines and extensions opened on December 2023, including the northern part of Line 17, the extension parts of Line 16, Line 11 and some latest updates on the English name of some stations. Meanwhile, I also changed the scale of the route map to make it more realistic. However, there are a few differences between this route map and the official one.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[beijing.txt](https://github.com/railmapgen/rmp-gallery/files/14034850/beijing.txt)

**Comment by Windows-Taskmgr** [comment]
您好，由于有贡献者已经在 #1117 中提交了，我们遵循“先到先得”原则，所以我们不会汇入您的模板，再此我们深表歉意，感谢您的贡献。
