### ISSUE TITLE
Resources: Update work of toronto

### ISSUE THREAD

**Issue by 52PD** [railmapgen/rmp-gallery#1166]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[toronto.txt](https://github.com/railmapgen/rmp-gallery/files/14074662/toronto.txt)

**Comment by 52PD** [comment]
本issue为#1140 的修正版本。此前提到的3号线永久关闭提示框中的网址错误的问题已经修正。

**Comment by 28yfang** [comment]
您好，您的作品已无问题，并将在稍后进行汇入。感谢您对画廊的贡献！
