### ISSUE TITLE
Resources: Update work of beijing

### ISSUE THREAD

**Issue by Xebalu** [railmapgen/rmp-gallery#1168]
[RMP_1706674773719.json](https://github.com/railmapgen/rmp-gallery/files/14107096/RMP_1706674773719.json)
add Line 17 and fix Line 11 and 16

**Comment by DQB061204** [comment]
**Do not edit lines below, they're meant for bots only!!!**

**Comment by DQB061204** [comment]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

**Comment by Windows-Taskmgr** [comment]
您好，由于已经有贡献者在 #1117 中提交，我们将不会汇入您的作品，感谢您的贡献。
