### ISSUE TITLE
Resources: Update work of nanjing

### ISSUE THREAD

**Issue by Yuqi154** [railmapgen/rmp-gallery#1172]
[nanjing.txt](https://github.com/railmapgen/rmp-gallery/files/14120086/nanjing.txt)
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

**Comment by Windows-Taskmgr** [comment]
您好，我们不支持来自地铁通的数据。
另外，城市介绍并不是让您写更新理由的，请您在更新理由区域写上您的更新（尽显英文）。
请您修改后重新提交，感谢您的贡献。
