### ISSUE TITLE
Resources: Update work of guangzhou

### ISSUE THREAD

**Issue by splovl** [railmapgen/rmp-gallery#1174]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[guangzhou.txt](https://github.com/railmapgen/rmp-gallery/files/14120466/guangzhou.txt)

**Comment by langonginc** [comment]
Hi, 请您认真填写修订理由，感谢您的贡献！
