### ISSUE TITLE
Resources: Update work of hangzhou

### ISSUE THREAD

**Issue by HangzhouMetro09024** [railmapgen/rmp-gallery#1188]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[hangzhou.txt](https://github.com/railmapgen/rmp-gallery/files/14155270/hangzhou.txt)

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板没有问题，请您等待管理员最终汇入，感谢您的贡献。
