### ISSUE TITLE
Resources: Update work of kaohsiung

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#1192]
Hi RMP team! I would like to contribute to the gallery with the data below.
Refer to #1129 @28yfang 
**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1704094274430.txt](https://github.com/railmapgen/rmp-gallery/files/14164826/1704094274430.txt)

**Comment by Windows-Taskmgr** [comment]
您好，在 #1129 中提到的问题均已被修复，请您等待管理员最终汇入，感谢您的贡献。
