### ISSUE TITLE
Resources: Update work of wuxi

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#1194]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1707134542525.txt](https://github.com/railmapgen/rmp-gallery/files/14165298/1707134542525.txt)

**Comment by MajorDucks** [comment]
对方是不是金匮公园搞错了？（不止一张图有这个问题），如下三张图：
![61ABB5DA-ACBE-4583-A1BC-4A240EF1BEFB](https://github.com/railmapgen/rmp-gallery/assets/121087569/9cf38d8f-0bde-482e-8fd1-3288abacd663)
此图是对方的文件截图
![2D90E46A-A0C1-4F8F-A8B2-7FE24475078B](https://github.com/railmapgen/rmp-gallery/assets/121087569/b3ad8080-3d9e-4bc3-9a4d-156ccf4f3879)
此图是Metroman版的线路图截图
![83F97D5B-E0B6-4C0A-A069-8BBF4AFD1BAD](https://github.com/railmapgen/rmp-gallery/assets/121087569/53b3cf6a-c644-4d35-90da-25e701de2b79)
此图是4号线开通后，S1线开通前的线路图截图
两张图均证明对方的线路图有误。

**Comment by thekingofcity** [comment]
嗨，感谢 @MajorDucks 的审核，我们将关闭有错误的画廊作品申请 :)
