### ISSUE TITLE
Resources: Update work of wuxi

### ISSUE THREAD

**Issue by MajorDucks** [railmapgen/rmp-gallery#1198]
Hi RMP team! I would like to contribute to the gallery with the data below.

更新无锡地铁S1线，并使用最贴近的苏州样式，添加了中文描述！强力推荐！

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[wuxi.txt](https://github.com/railmapgen/rmp-gallery/files/14175558/wuxi.txt)

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板没有问题。
以下是一个建议：
我们建议您在南北向线路中的站名竖向偏移为居中，这样能让作品更美观。
（您可选择修改或不修改直接汇入。）
感谢您的贡献。

**Comment by thekingofcity** [comment]
等待作者回复中...

**Comment by MajorDucks** [comment]
先不修改吧，现在没有别的问题，等到明后年4号线2期开通了再统一改吧。

**Comment by thekingofcity** [comment]
嗨，感谢贡献。您的更新已被合入项目，稍后就会上线 :)
