### ISSUE TITLE
Resources: Update work of chengdu

### ISSUE THREAD

**Issue by wzx111111** [railmapgen/rmp-gallery#1200]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[chengdu.txt](https://github.com/railmapgen/rmp-gallery/files/14190812/chengdu.txt)

**Comment by Windows-Taskmgr** [comment]
Edited by @Windows-Taskmgr on the 3rd of Mar.

**Comment by Windows-Taskmgr** [comment]
您好，此issue由于未知原因无法被bots识别，我们正在处理，为此带来的不便深表歉意。

**Comment by Windows-Taskmgr** [comment]
Edited by @Windows-Taskmgr on the 3rd of Mar.

**Comment by Windows-Taskmgr** [comment]
Edited by @Windows-Taskmgr on the 3rd of Mar.

**Comment by thekingofcity** [comment]
Hi, there must not be any simple path with single color to be submitted :)
