### ISSUE TITLE
Donation: New work of jinpu

### ISSUE THREAD

**Issue by JChanty** [railmapgen/rmp-gallery#1221]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

**Comment by JChanty** [comment]
[Uploading jinpu.txt…]()

**Comment by 28yfang** [comment]
您好，请直接在议题正文最下方上传文件，并需等待"uploading"消失后再进行提交。感谢。
