### ISSUE TITLE
Resources: New work of Guangzhou

### ISSUE THREAD

**Issue by 15915996690** [railmapgen/rmp-gallery#1225]
[guangzhou.txt.json](https://github.com/railmapgen/rmp-gallery/files/14277020/guangzhou.txt.json)
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

**Comment by 28yfang** [comment]
您好，画廊中已有广州模版，若想提交新版本请直接对其进行修改。
