### ISSUE TITLE
是否应该支持多个参考网址？（即增加可提交的参考网址个数）

### ISSUE THREAD

**Issue by CatAlan1028** [railmapgen/rmp-gallery#1244]
深圳地铁有点尴尬。它的最新线路图不会做入到标准格式图中。
最新图：https://www.szmc.net/map/
模板图：https://www.szmc.net/shentieyunying/yunyingfuwu/szsgdjtyyxlwlt/
就是你的格式肯定是用模板图格式，但是车站肯定是用最新图。模板图也不是一成不变的。
他们也懒得更换线下图，经常是在原本的图要改的地方拿个贴纸贴上去。

**Comment by 28yfang** [comment]
您好，经查询 https://www.szmc.net/szmc_m/shentieyunying/yunyingfuwu/szsgdjtyyxlwlt/ 已经是最新版本的线路图了，而 https://www.szmc.net/map/ 出现的是票价查询的页面。

**Comment by CatAlan1028** [comment]
但你们的默认参考网址是https://www.szmc.net/map/

**Comment by CatAlan1028** [comment]
而且https://www.szmc.net/szmc_m/shentieyunying/yunyingfuwu/szsgdjtyyxlwlt/不会及时更新，我一月份查过，那个时候并没有更新12月份末上线的8号线2期

**Comment by CatAlan1028** [comment]
https://www.szmc.net/szmc_m/shentieyunying/yunyingfuwu/szsgdjtyyxlwlt/ 不会及时更新，我一月份查过，那个时候并没有更新12月份末上线的8号线2期

**Comment by 28yfang** [comment]
> 最新图：https://www.szmc.net/map/
> 
> 模板图：https://www.szmc.net/shentieyunying/yunyingfuwu/szsgdjtyyxlwlt/

官方似乎已经删除了这两个地址，页面中显示的都是票价查询。

**Comment by CatAlan1028** [comment]
这张图是1月11日才上传到官网的，但是RMP贡献者在这之前就上传了作品到rmp gallery里。我之所以希望允许上传多个参考站点，就是怕这种情况。这样子你们审核也方便一点。

**Comment by CatAlan1028** [comment]
模版图我这边可以浏览啊？

> > 最新图：https://www.szmc.net/map/
> > 模板图：https://www.szmc.net/shentieyunying/yunyingfuwu/szsgdjtyyxlwlt/
> 
> 官方似乎已经删除了这两个地址，页面中显示的都是票价查询。

**Comment by 28yfang** [comment]
> 模版图我这边可以浏览啊？

我这里不管怎么样都会redirect到票价查询

**Comment by 28yfang** [comment]
方便发一个截屏吗？

**Comment by CatAlan1028** [comment]
![image](https://github.com/railmapgen/rmp-gallery/assets/146333201/2d50ee38-9640-43de-ae39-ac0376d8db29)

**Comment by CatAlan1028** [comment]
或者图片地址：https://www.szmc.net/SMARTC/upload/image/20240111/1704956172109061186.jpg

**Comment by 28yfang** [comment]
你发的这张图就是 https://www.szmc.net/szmc_m/shentieyunying/yunyingfuwu/szsgdjtyyxlwlt/ 里面的，你的那两个链接里没有这张图

**Comment by CatAlan1028** [comment]
那真的奇怪了。
我这个是电脑端

**Comment by CatAlan1028** [comment]
你那个是手机端参考网址吧

**Comment by CatAlan1028** [comment]
电脑端点https://www.szmc.net/szmc_m/shentieyunying/yunyingfuwu/szsgdjtyyxlwlt/
给我跳到首页去了

**Comment by 28yfang** [comment]
原来如此。🤦我一直在用移动端

**Comment by CatAlan1028** [comment]
所以使用多个参考网址你觉得有没有必要

**Comment by 28yfang** [comment]
不过 https://www.szmc.net/shentieyunying/yunyingfuwu/szsgdjtyyxlwlt/ 已经是最新版本的线路图了，所以不需要两个链接啊

**Comment by CatAlan1028** [comment]
它现在是新的，但是他会延迟，比如说12月27号开通，它晚了将近半个月才在https://www.szmc.net/shentieyunying/yunyingfuwu/szsgdjtyyxlwlt/ 上传最新图片，但是https://www.szmc.net/map/ 总是最新的

**Comment by CatAlan1028** [comment]
所以现在默认参考网址是https://www.szmc.net/map/

**Comment by CatAlan1028** [comment]
但是这个网址又没有格式参考，就比较麻烦

**Comment by 28yfang** [comment]
我个人认为没什么必要提供两个网址，因为审核员审核的时候一般都会自己找图（至少我会）

**Comment by CatAlan1028** [comment]
那也行，就是你们审核员会辛苦一些

**Comment by CatAlan1028** [comment]
或者你们负责这一部分的可以讨论一下

**Comment by thekingofcity** [comment]
嗨，感谢提出建议。关于额外的参考地址，我想可以在提交更改之后，由于与参考资料不符被驳回时再提供，以供额外参考。除此之外，无需提供额外的参考地址。
