### ISSUE TITLE
Resources: Update work of hangzhou

### ISSUE THREAD

**Issue by HZMetro** [railmapgen/rmp-gallery#1247]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[hangzhou (2).txt](https://github.com/railmapgen/rmp-gallery/files/14318567/hangzhou.2.txt)

**Comment by Windows-Taskmgr** [comment]
您好，我们暂不支持来自百度地图的来源，请您更换来源提交，感谢您的贡献。
