### ISSUE TITLE
Resources: Update work of hefei

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp-gallery#1251]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[Hefei.txt](https://github.com/railmapgen/rmp-gallery/files/14339819/Hefei.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution and your work is merged into the gallery :)
