### ISSUE TITLE
Resources: Update work of hefei

### ISSUE THREAD

**Issue by HarryBreatem** [railmapgen/rmp-gallery#1255]
[hefei.txt](https://github.com/railmapgen/rmp-gallery/files/14343789/hefei.txt)
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

**Comment by 28yfang** [comment]
您好，请在justification中写上您更新的内容，并且希望您能保留各语言的城市名和介绍。
另外，在#1251存在的情况下我们会遵循先来后到的原则，优先汇入#1251。感谢您的贡献。
