### ISSUE TITLE
Resources: New work of shanghaimetrowide

### ISSUE THREAD

**Issue by Fhooth-YG** [railmapgen/rmp-gallery#1259]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[shanghaimetrowide.txt](https://github.com/railmapgen/rmp-gallery/files/14392074/shanghaimetrowide.txt)

**Comment by thekingofcity** [comment]
Hi, wide here only means for another scale with no stations/lines change of the current shanghai work?

**Comment by langonginc** [comment]
Closed as no response.
