### ISSUE TITLE
Resources: Update work of foshan

### ISSUE THREAD

**Issue by zyx19851218** [railmapgen/rmp-gallery#1262]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[foshan.txt](https://github.com/railmapgen/rmp-gallery/files/14393254/foshan.txt)

**Comment by 28yfang** [comment]
您好，经检查您的模版没有问题。感谢您的贡献！
