### ISSUE TITLE
Resources: New work of ZhujiangDeltaRegion (v0.3)

### ISSUE THREAD

**Issue by MizunotoNanami** [railmapgen/rmp-gallery#1263]
[hongkongshenzhen.txt](https://github.com/railmapgen/rmp-gallery/files/14393367/hongkongshenzhen.txt)
[ZDR_Rail.v0.3.json](https://github.com/railmapgen/rmp-gallery/files/14393368/ZDR_Rail.v0.3.json)

**Comment by 28yfang** [comment]
您好，请务必按照画廊中的步骤创建议题，不要删除任何文字，并且无需上传json文件。
