### ISSUE TITLE
Resources: New work of xiongannewarea

### ISSUE THREAD

**Issue by steve372a** [railmapgen/rmp-gallery#1264]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Xiong'an New Area",
        "zh-Hans": "雄安新区"
    },
    "desc": {
        "zh-Hans": "雄安至北京大兴国际机场快线，即雄安轨道交通R1线，是连接雄安新区与北京大兴国际机场的轨道交通线路。该线路途经雄安新区、保定市、廊坊市、霸州市、永清县、固安县境内，终到北京大兴国际机场。\n\nR1线一期工程全长约86公里，设8座车站。车辆采用区域快轨D型车，车辆编组采用8辆编组（7＋1行李车），设计运行速度高架段最高运行时速为200公里、地下段最高运行时速160公里，列车运营时间为24小时全天候。\n\n雄安至北京大兴国际机场快线（R1线）是列入雄安新区“四纵两横”区域轨道交通网的重要干线。\n\n雄安R1线预计将于2024年建成。",
        "en": "The Xiong'an to Beijing Daxing International Airport Express, also known as the Xiong'an Rail Transit R1 Line, is a railway transportation route connecting Xiong'an New Area with Beijing Daxing International Airport. The line passes through Xiong'an New Area, Baoding City, Langfang City, Bazhou City, Yongqing County, and Gu'an County, terminating at Beijing Daxing International Airport.\n\nThe Phase 1 project of the R1 Line has a total length of approximately 86 kilometers and consists of 8 stations. The vehicles used are regional rapid transit D-type trains, with a train formation of 8 cars (7 passenger cars and 1 luggage car). The designed operating speed is up to 200 kilometers per hour on elevated sections and up to 160 kilometers per hour in underground sections, with train operations available 24 hours a day, all year round.\n\nThe Xiong'an to Beijing Daxing International Airport Express (R1 Line) is a crucial mainline included in the \"Four Vertical and Two Horizontal\" regional rail transit network of Xiong'an New Area."
    },
    "reference": "https://zh.wikipedia.org/wiki/雄安轨道交通R1线",
    "justification": "New template of Xiongan New Area"
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="xiongannewarea">{¨svgViewBoxZoom¨¢2k¨svgViewBoxMin¨{´x´£-3f.-2e´y´£A.Fn}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|{¨key¨¨stn_cz6ReI7nTL¨ß8{¨visible¨»¨zIndex¨É´x´¢8s´y´¢1Xß4¨bjsubway-int¨ßE{¨names¨|¨大兴机场¨¨Daxing Jichang\\(Daxing AirPort)¨÷¨nameOffsetX¨¨right¨¨nameOffsetY¨¨middle¨¨outOfStation¨«}}}{ßA¨misc_node_12TZ6KgT-v¨ß8{ßC»ßDÉ´x´¢8T´y´¤jß4¨bjsubway-text-line-badge¨ßO{ßF|¨大兴机场线¨¨Daxing AirPort Express¨÷¨color¨|¨beijing¨¨bj35dj¨¨#004a9f¨¨#fff¨÷}}}{ßA¨stn_ji8-Syibnl¨ß8{ßC»ßDÉ´x´º1´y´¢39ß4¨bjsubway-basic¨ßX{ßF|¨永清临空¨¨Yongqing Linkong¨÷ßIßJßKßL¨open¨»}}}{ßA¨stn_IVJjVjS4j8¨ß8{ßC»ßDÉ´x´¢71´y´¢50ß4ßXßX{ßF|¨霸州开发区¨¨Bazhou Development Zone¨÷ßIßLßK¨bottom¨ßa»}}}{ßA¨misc_node_LYEp3o6fNV¨ß8{ßC»ßDÉ´x´¢8O´y´¢4Mß4¨virtual¨ßg{}}}{ßA¨misc_node_uGrnzdxHbr¨ß8{ßC»ßDÉ´x´¢76´y´¢5yß4¨text¨ßi{¨content¨¨霸州市¨¨fontSize¨¤O¨lineHeight¨¤G¨textAnchor¨ßL¨dominantBaseline¨ßL¨language¨¨jreast_ja¨ßR|¨other¨ßr¨#c0c0c0¨ßV÷¨rotate¨É¨italic¨¨normal¨¨bold¨ßv}}}{ßA¨misc_node_nLTeZ0adGc¨ß8{ßC»ßDÉ´x´¢AK´y´¢3Jß4ßißi{ßj¨永清县¨ßl¤Oßm¤GßnßLßoßLßpßqßR|ßrþßsßV÷ßtÉßußvßwßv}}}{ßA¨misc_node_HVeBVNexYO¨ß8{ßC»ßDÉ´x´º1´y´¢18ß4ßgßg{}}}{ßA¨stn_Zy5S5k1p7o¨ß8{ßC»ßDÉ´x´¢5A´y´¢68ß4ßXßX{ßF|¨雄安站¨¨Xiong'an Railway Station¨÷ßIßJßKßeßa»}}}{ßA¨misc_node_jk7FQIb7dW¨ß8{ßC»ßDÉ´x´º7´y´º2ß4¨facilities¨ß14{ß4¨airport_bj¨}}}{ßA¨stn_CVZ9NFY-CU¨ß8{ßC»ßDÉ´x´¢3O´y´¢6hß4ßXßX{ßF|´雄州´¨Xiongzhou¨÷ßIßLßKßeßa»}}}{ßA¨misc_node_9JAc68ifFa¨ß8{ßC»ßDÉ´x´¢4C´y´¢7zß4ßißi{ßj´雄县´ßl¤Oßm¤GßnßLßoßLßpßqßR|ßrþßsßV÷ßtÉßußvßwßv}}}{ßA¨misc_node_8OvVAsGkkH¨ß8{ßC»ßDÉ´x´¢3d´y´¢7Gß4ßißi{ßj¨雄县汽车站¨ßl¤Cßm¤GßnßLßoßLßpßqßR|ßrþ¨#b70122¨ßV÷ßtÉßußvßwßw}}}{ßA¨misc_node_YSe0ScmPYM¨ß8{ßC»ßDÉ´x´¢7p´y´¢34ß4ßOßO{ßF|¨雄安R1线¨¨Xiong'an R1 Line¨÷ßR|ßSßTßUßV÷}}}{ßA¨misc_node_8w6qyAaK5G¨ß8{ßC»ßDÉ´x´¢63´y´¢ECß4ßißi{ßj¨任丘市¨ßl¤Oßm¤GßnßLßoßLßpßqßR|ßrþßsßV÷ßtÉßußvßwßv}}}{ßA¨stn_o_lrFphCg6¨ß8{ßC»ßDÉ´x´¢2G´y´ºHß4ßXßX{ßF|¨第五组团¨¨Diwuzutuan¨÷ßIßLßKßeßa»}}}{ßA¨stn_YmX0X1E6xm¨ß8{ßC»ßDÉ´x´¢1D´y´ºHß4ßXßX{ßF|¨金融岛¨¨Jinrongdao¨÷ßIßLßKßeßa»}}}{ßA¨stn_07fnD00AvL¨ß8{ßC»ßDÉ´x´Î´y´ºHß4ßXßX{ßF|¨雄安航站楼¨¨Xiong'an Terminal¨÷ßIßLßKßeßa»}}}{ßA¨misc_node_KkWuHZ9jI4¨ß8{ßC»ßDÉ´x´Î´y´¢9Hß4ßißi{ßj¨安新县¨ßl¤Oßm¤GßnßLßoßLßpßqßR|ßrþßsßV÷ßtÉßußvßwßv}}}{ßA¨misc_node_p__75MOJCe¨ß8{ßC»ßDÉ´x´¢-e´y´¢5oß4ßißi{ßj¨容城县¨ßl¤Oßm¤GßnßLßoßLßpßqßR|ßrþßsßV÷ßtÉßußvßwßv}}}{ßA¨misc_node_Ix2uw3o4wA¨ß8{ßC»ßDÉ´x´¢-y´y´¢Egß4ßißi{ßj¨高阳县¨ßl¤Oßm¤GßnßLßoßLßpßqßR|ßrþßsßV÷ßtÉßußvßwßv}}}{ßA¨misc_node_QolWOUXgTL¨ß8{ßC»ßDÉ´x´ºK´y´¢Diß4ßgßg{}}}{ßA¨misc_node_jNUbiZ2-tq¨ß8{ßC»ßDÉ´x´¢4R´y´¢Aoß4ßgßg{}}}{ßA¨misc_node_VwNOcJcHIH¨ß8{ßC»ßDÉ´x´ºI´y´¢AAß4ßgßg{}}}{ßA¨misc_node_W6FRWNdTat¨ß8{ßC»ßDÉ´x´¢3s´y´¢9qß4ßgßg{}}}{ßA¨misc_node_to4socTdYS¨ß8{ßC»ßDÉ´x´¢21´y´¢7fß4ßgßg{}}}{ßA¨misc_node_0ShYz9WZzF¨ß8{ßC»ßDÉ´x´¤t´y´º3ß4ßgßg{}}}{ßA¨misc_node_5VhR_YcLaS¨ß8{ßC»ßDÉ´x´º2´y´¢9bß4ßgßg{}}}{ßA¨misc_node_vsqMMhihYF¨ß8{ßC»ßDÉ´x´¤o´y´¢9vß4ßgßg{}}}{ßA¨misc_node_J7Yv3Ndp5n¨ß8{ßC»ßDÉ´x´¤o´y´¢AZß4ßgßg{}}}{ßA¨misc_node_pR5pt76LJp¨ß8{ßC»ßDÉ´x´¢1r´y´¢Ajß4ßgßg{}}}{ßA¨misc_node_QoSkvvzg-B¨ß8{ßC»ßDÉ´x´¤P´y´¢Bhß4ßgßg{}}}{ßA¨misc_node_DzBpxYt_C1¨ß8{ßC»ßDÉ´x´¢2f´y´ºPß4ßgßg{}}}{ßA¨misc_node_qX2qlPR0BG¨ß8{ßC»ßDÉ´x´¢1w´y´º3ß4ßgßg{}}}{ßA¨misc_node_AFA4e_nJH2¨ß8{ßC»ßDÉ´x´¢1c´y´¢8iß4ßgßg{}}}{ßA¨misc_node_FZOBCA9sVg¨ß8{ßC»ßDÉ´x´¢1S´y´¢A5ß4ßgßg{}}}{ßA¨misc_node_Jb14NKnmQG¨ß8{ßC»ßDÉ´x´¢2z´y´¢9Mß4ßgßg{}}}{ßA¨misc_node_LPiyZo0Skz¨ß8{ßC»ßDÉ´x´¢5F´y´¢APß4ßgßg{}}}{ßA¨misc_node_UXHtOpcAMV¨ß8{ßC»ßDÉ´x´¢2p´y´¢D4ß4ßgßg{}}}{ßA¨misc_node_kt8_56cjbz¨ß8{ßC»ßDÉ´x´ºv´y´¢BIß4ßgßg{}}}{ßA¨misc_node_dV2dZwcf-x¨ß8{ßC»ßDÉ´x´ºQ´y´¢Brß4ßgßg{}}}{ßA¨misc_node_Zxem2fXWtr¨ß8{ßC»ßDÉ´x´ºl´y´¢Ayß4ßißi{ßj¨白洋淀¨ßl¤Oßm¤GßnßLßoßLßpßqßR|ßrþßsßV÷ßtÉßußvßwßv}}}÷¨edges¨|¦ß8¦¨diagonal¨¦¨offsetFrom¨¨offsetTo¨¨roundCornerFactor¨¨startFrom¨‡¨reconcileId¨¨single-color¨¦ßR‡¨style¨ß4ßCßD‡ßA¨source¨¨target¨‡ÉÉ¤A¨from¨´´|ßSßTßUßV÷ß1zß1t»É¨line_kvRnskKp2n¨ßWßBÉÉ¤Aß23´´|ßSßTßUßV÷ß1zß1t»É¨line_1eM_0O-RrM¨ßbßfÉÉ¤Aß23´´|ßSßTßUßV÷ß1zß1t»É¨line_BYEh27Z70K¨ßWßfÉÉ¤Aß23´´|ßSßTßUßV÷ß1zß1t»É¨line_nAPTkm7HFB¨ßBßzÉÉ¤Aß23´´|ßSßTßUßV÷ß1zß1t»É¨line__VzN9ExIxt¨ßbß10ÉÉ¤Aß23´´|ßSßTßUßV÷ß1zß1t»É¨line_VTwDBHeuSh¨ß16ß10ÉÉ¤Aß23´´|ßSßTßUßV÷ß1zß1t»É¨line_jyqxcYG_Yz¨ß16ß1KÉÉ¤Aß23´´|ßSßTßUßV÷ß1zß1t»É¨line_a9EW1bsrpz¨ß1Kß1N—{ßA¨line_NyzQQJTiqJ¨ß21ß1Wß22ß1Xß8{ßC»ßDÄß4ß1tß1t{ß1xß23ß1uÉß1vÉß1wÉ}ß20¨river¨ß1y´´ß2D{ßR|¨shanghai¨ß2D¨#B9E3F9¨ßV÷¨width¨¤e}}}{ßA¨line_EgVkdVPtxO¨ß21ß1Xß22ß1Yß8{ßC»ßDÄß4ß1tß1t{ß1xß23ß1uÉß1vÉß1w¤A}ß20ß2Dß1y´´ß2D{ßR|ß2Eß2Dß2FßV÷ß2G¤K}}}{ßA¨line_QLLKYM3rig¨ß21ß1Yß22ß1Zß8{ßC»ßDÄß4ß1tß1t{ß1xß23ß1uÉß1vÉß1w¤A}ß20ß2Dß1y´´ß2D{ßR|ß2Eß2Dß2FßV÷ß2G¤e}}}{ßA¨line_nMQ79GScmU¨ß21ß1Zß22ß1aß8{ßC»ßDÄß4ß1tß1t{ß1xß23ß1uÉß1vÉß1wÉ}ß20ß2Dß1y´´ß2D{ßR|ß2Eß2Dß2FßV÷ß2G¤e}}}{ßA¨line_q6yd0ioPwL¨ß21ß1aß22ß1bß8{ßC»ßDÄß4ß1tß1t{ß1xß23ß1uÉß1vÉß1w¤A}ß20ß2Dß1y´´ß2D{ßR|ß2Eß2Dß2FßV÷ß2G¤K}}}{ßA¨line_LVQYc3E-Jx¨ß21ß1bß22ß1cß8{ßC»ßDÄß4ß1tß1t{ß1xß23ß1uÉß1vÉß1w¤A}ß20ß2Dß1y´´ß2D{ßR|ß2Eß2Dß2FßV÷ß2G¤K}}}{ßA¨line_N9M2CHK91G¨ß21ß1cß22ß1dß8{ßC»ßDÄß4ß1tß1t{ß1xß23ß1uÉß1vÉß1w¤A}ß20ß2Dß1y´´ß2D{ßR|ß2Eß2Dß2FßV÷ß2G¤K}}}{ßA¨line_0LcsJKgUq9¨ß21ß1dß22ß1eß8{ßC»ßDÄß4ß1tß1t{ß1xß23ß1uÉß1vÉß1w¤A}ß20ß2Dß1y´´ß2D{ßR|ß2Eß2Dß2FßV÷ß2G¤K}}}{ßA¨line_QTpAZoyjQ8¨ß21ß1eß22ß1fß8{ßC»ßDÄß4ß1tß1t{ß1xß23ß1uÉß1vÉß1w¤A}ß20ß2Dß1y´´ß2D{ßR|ß2Eß2Dß2FßV÷ß2G¤K}}}{ßA¨line_5EnpT2vOwn¨ß21ß1fß22ß1gß8{ßC»ßDÄß4ß1tß1t{ß1xß23ß1uÉß1vÉß1w¤A}ß20ß2Dß1y´´ß2D{ßR|ß2Eß2Dß2FßV÷ß2G¤o}}}{ßA¨line_YCbQL2qYBO¨ß21ß1gß22ß1hß8{ßC»ßDÄß4ß1tß1t{ß1xß23ß1uÉß1vÉß1w¤A}ß20ß2Dß1y´´ß2D{ßR|ß2Eß2Dß2FßV÷ß2G¤o}}}{ßA¨line_S9snyMfLAk¨ß21ß1hß22ß1Wß8{ßC»ßDÄß4ß1tß1t{ß1xß23ß1uÉß1vÉß1w¤A}ß20ß2Dß1y´´ß2D{ßR|ß2Eß2Dß2FßV÷ß2G¤y}}}{ßA¨line_ifpa28z3e2¨ß21ß1iß22ß1jß8{ßC»ßDÄß4ß1tß1t{ß1xß23ß1uÉß1vÉß1w¤A}ß20ß2Dß1y´´ß2D{ßR|ß2Eß2Dß2FßV÷ß2Gºp}}}{ßA¨line_7O0zcN5G_i¨ß21ß1kß22ß1lß8{ßC»ßDÄß4ß1tß1t{ß1xß23ß1uÉß1vÉß1w¤A}ß20ß2Dß1y´´ß2D{ßR|ß2Eß2Dß2FßV÷ß2G¤13}}}{ßA¨line_V4B8XzO0Ax¨ß21ß1kß22ß1lß8{ßC»ßDÄß4ß1tß1t{ß1xß23ß1uÉß1vÉß1w¤A}ß20ß2Dß1y´´ß2D{ßR|ß2Eß2Dß2FßV÷ß2G¤13}}}{ßA¨line_B007WEnB9R¨ß21ß1kß22ß1lß8{ßC»ßDÄß4ß1tß1t{ß1xß23ß1uÉß1vÉß1w¤A}ß20ß2Dß1y´´ß2D{ßR|ß2Eß2Dß2FßV÷ß2Gºp}}}{ßA¨line_Cua2xjxVq8¨ß21ß1mß22ß1nß8{ßC»ßDÄß4ß1tß1t{ß1xß23ß1uÉß1vÉß1w¤A}ß20ß2Dß1y´´ß2D{ßR|ß2Eß2Dß2FßV÷ß2G¤1I}}}{ßA¨line_Em7_lwvjs2¨ß21ß1oß22ß1pß8{ßC»ßDÄß4ß1tß1t{ß1xß23ß1uÉß1vÉß1w¤A}ß20ß2Dß1y´´ß2D{ßR|ß2Eß2Dß2FßV÷ß2G¤3E}}}÷}¨version¨¤S}</details>

**Comment by langonginc** [comment]
您好，雄安新区的R1线似乎还未开通，gallery仅接受已开通的线网图，请等待它开通。感谢您的贡献。
