### ISSUE TITLE
Resources: New work of maanshan

### ISSUE THREAD

**Issue by zhuyihao99** [railmapgen/rmp-gallery#1268]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[maanshan.txt](https://github.com/railmapgen/rmp-gallery/files/14409520/maanshan.txt)

[RMP_1708972932297.json](https://github.com/railmapgen/rmp-gallery/files/14409522/RMP_1708972932297.json)

**Comment by langonginc** [comment]
您好，马鞍山地铁似乎并未开通，gallery仅接受已开通的线网图。当然了，欢迎捐赠将作品加入幻想世界哦～感谢您的贡献。
