### ISSUE TITLE
Resources: New template of chengdu

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp-gallery#129]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[chengdu.txt](https://github.com/railmapgen/rmp-gallery/files/11522104/chengdu.txt)

**Comment by langonginc** [comment]
您好，经检查您提交的内容存在如下问题：

1. 3/10号线 `双流西站` 、10号线 `双流机场2航站楼` 、10号线 `双流机场1航站楼` 、10号线 `新津站` 、18号线 `天府机场1号2号航站楼` 应当有相关标识。

<img width="774" alt="image" src="https://github.com/railmapgen/rmp-gallery/assets/59787082/fa7ae270-db01-4869-b25c-dd15049368be">
<img width="798" alt="image" src="https://github.com/railmapgen/rmp-gallery/assets/59787082/01d67e2e-1eb6-4d21-a9a9-25db277a86dc">


2. 5号线 `赛云台` 错写为 `塞云台` 了。

请您修改后重新提交，感谢！

**Comment by 28yfang** [comment]
把 #130 关了吧
