### ISSUE TITLE
Resources: Update work of fuzhou

### ISSUE THREAD

**Issue by Conurs** [railmapgen/rmp-gallery#1294]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[fuzhou.txt](https://github.com/railmapgen/rmp-gallery/files/14481019/fuzhou.txt)

**Comment by thekingofcity** [comment]
Hi, we currently don't accept lines that are not open yet. You may update this work when this segment is open to the public.
