### ISSUE TITLE
Resources: New work of ningbo

### ISSUE THREAD

**Issue by Hsichiene** [railmapgen/rmp-gallery#1296]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**
[ningbo (1).txt](https://github.com/railmapgen/rmp-gallery/files/14493097/ningbo.1.txt)

**Comment by thekingofcity** [comment]
嗨，感谢您的贡献与支持。3号线**南部商务中心**应为**南部商务区**，请修改后附上本议题号 #1296 重新上传，谢谢 :)
