### ISSUE TITLE
Resources: Update work of kyoto

### ISSUE THREAD

**Issue by merakiann** [railmapgen/rmp-gallery#1300]
[kyoto.txt](https://github.com/railmapgen/rmp-gallery/files/14523637/kyoto.txt)
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

**Comment by thekingofcity** [comment]
Hi, station names should be preserved and we currently ask maps to be as much the same as the official maps. This means if Kyoto does not have an official map (official maps means maps from any company or bureaucracy) in this style, we won't accept it :)
