### ISSUE TITLE
Resources: Update work of guangzhou

### ISSUE THREAD

**Issue by fdulezi** [railmapgen/rmp-gallery#1302]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[guangzhou.txt](https://github.com/railmapgen/rmp-gallery/files/14533019/guangzhou.txt)

**Comment by thekingofcity** [comment]
Hi, there must not be any simple path with single color to be submitted to the gallery :)
