### ISSUE TITLE
Resources: Update work of berlin

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp-gallery#1303]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[Berlin.txt](https://github.com/railmapgen/rmp-gallery/files/14538370/Berlin.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution and your updated work is merged into the gallery :)
