### ISSUE TITLE
Resources: Update work of nanjing

### ISSUE THREAD

**Issue by MXSecretStar** [railmapgen/rmp-gallery#1308]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[nanjing (4).txt](https://github.com/railmapgen/rmp-gallery/files/14546593/nanjing.4.txt)

**Comment by thekingofcity** [comment]
Hi, there must not be any simple path with single color to be submitted :)
