### ISSUE TITLE
Resources: Update work of fuzhou

### ISSUE THREAD

**Issue by lingmofengling** [railmapgen/rmp-gallery#1327]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**
[RMP_1710659289718.json](https://github.com/railmapgen/rmp-gallery/files/14626502/RMP_1710659289718.json)

来源于【【福州地铁】福州地铁发展史与未来规划（2016-2035+）-哔哩哔哩】 https://b23.tv/sOPbzWc，本视频参考了福州地铁未来线路

**Comment by lingmofengling** [comment]
> Hi RMP team! I would like to contribute to the gallery with the data below.
> 
> **Paste or Upload below. They are meant for BOTS ONLY!!!** [RMP_1710659289718.json](https://github.com/railmapgen/rmp-gallery/files/14626502/RMP_1710659289718.json)
> 
> 来源于【【福州地铁】福州地铁发展史与未来规划（2016-2035+）-哔哩哔哩】 [https://b23.tv/sOPbzWc 
本视频参考了福州地铁未来线路]

**Comment by lingmofengling** [comment]
[Uploading fuzhou.txt.json…]()

**Comment by thekingofcity** [comment]
嗨，请跟从画廊提示更新作品 :)
