### ISSUE TITLE
Resources: New work of Washington DC

### ISSUE THREAD

**Issue by Hsichiene** [railmapgen/rmp-gallery#1341]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**
[washington.txt](https://github.com/railmapgen/rmp-gallery/files/14667248/washington.txt)

**Comment by 28yfang** [comment]
您好，感谢您的贡献。
经检查，您的作品含有以下问题：
1. 红线 North Bethesda 站站名错写成 White Flint
2. 黄线、绿线 Mt Vernon Sq 站主站名拼写错误 (Sq 不是 Sg
3. 黄线北终点站应为 Mt Vernon Sq 而并非 Greenbelt
4. 绿线 U St 副站名拼写错误 (Civil 不是 Cive，Mem'l 不是 Mem't)
5. 绿线 Hyattsville Crossing 错写成 Prince George's Plaza
6. 黄线、绿线 Archives 站副站名中的 Memorial 应简写成 Mem'l
7. 绿线 Southern Ave 站站名错写成 Southem Ave
8. 黄线、蓝线 National Airport 与 Braddock Rd 之间漏了 Potomac Yard 站，副站名为 VT
9. 蓝线、灰线、橙线 Smithsonian 站漏写了副站名 National Mall
10. 蓝线、灰线、橙线 Eastern Market 站站名错写成 Eastem Market
11. 蓝线、灰线 Downtown Largo 站站名错写成 Largo Town Center
12. 灰线 Tysons 站站名错写成 Tysons Corner
13. 灰线 Wiehle-Reston East 站北面漏了以下站点，如图
![Screenshot 2024-05-24 at 09 49 03](https://github.com/railmapgen/rmp-gallery/assets/123239445/249994d6-e0d7-45b4-8307-047f89724ec1)
14. 橙线 West Falls Church 站、Vienna 站分别漏写了副站名 VT、Fairfax-GMU
15. 橙线 Dunn Loring 站站名中的 Merrifield 应为副站名

请在修正后重新提交，并附上本议题编号（#1341），感谢！
