### ISSUE TITLE
Resources: New work of chongqingbutguangzhoustyle

### ISSUE THREAD

**Issue by tin1us** [railmapgen/rmp-gallery#1345]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[chongqingbutguangzhoustyle.txt](https://github.com/railmapgen/rmp-gallery/files/14729700/chongqingbutguangzhoustyle.txt)

**Comment by tin1us** [comment]
> Hi RMP team! I would like to contribute to the gallery with the data below.
> 
> **Paste or Upload below. They are meant for BOTS ONLY!!!**

[Uploading chongqingbutguangzhoustyle.txt…]()

**Comment by Swiftiecott** [comment]
您好，很抱歉我们不接受重复提交画廊中已存在的城市。

如您想修改某一个画廊中已存在的城市，请直接对其进行修改，如该城市所使用的图标风格已经包含在RMP中，请务必使用对应城市的图标，谢谢。
