### ISSUE TITLE
Resources: Update work of wenzhou

### ISSUE THREAD

**Issue by zzk-zswz** [railmapgen/rmp-gallery#1351]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[wenzhou.txt](https://github.com/railmapgen/rmp-gallery/files/14730611/wenzhou.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. The reference link should be updated with the official link and the detailed station's name should be included in the update reason.

**Comment by zzk-zswz** [comment]
[电台名称]是什么

> 您好，感谢您的贡献。参考链接应使用官方链接进行更新，并且更新原因中应包含详细的电台名称。

**Comment by zzk-zswz** [comment]
#1355 已说明
