### ISSUE TITLE
Resources: Update work of wenzhou

### ISSUE THREAD

**Issue by zzk-zswz** [railmapgen/rmp-gallery#1355]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[wenzhou.txt](https://github.com/railmapgen/rmp-gallery/files/14730965/wenzhou.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your work is merged and will be released soon :)
