### ISSUE TITLE
Filter by author

### ISSUE THREAD

**Issue by Windows-Taskmgr** [railmapgen/rmp-gallery#136]
能不能把不同的人员做的相同的城市的线路图都公开展出？
这样就能将不同的人员的作品都展示出来，更能增加一些趣味

**Comment by 28yfang** [comment]
好主意👍

**Comment by langonginc** [comment]
激发创造活力？

**Comment by Windows-Taskmgr** [comment]
也有这么一个好处吧，主要是因为如果一个城市只有一个作者的作品的话就太单一了

**Comment by langonginc** [comment]
这个要不要先搞出来点赞评分的功能，用它来作为展示顺序？ @thekingofcity

**Comment by thekingofcity** [comment]
> 这个要不要先搞出来点赞评分的功能，用它来作为展示顺序？ @thekingofcity

点赞评分功能又是另一件事了，这需要用户提交数据到仓库中。虽然通过新开issue的方式点赞评分是可行的，但是会不会太麻烦了一些？我认为此功能相对于其的开发成本来说优先级不高，当然如果你愿意帮助一起实现也可以优先推进 :)

**Comment by langonginc** [comment]
@thekingofcity 我记得之前有个东西是给博客加评论的，它的原理是在issue里发comment

**Comment by thekingofcity** [comment]
> @thekingofcity 我记得之前有个东西是给博客加评论的，它的原理是在issue里发comment

你说的是 giscus.app 吧？确实可以提供评论区的效果，但问题是我无法从这些discussion中获得点赞和评分数据啊。

**Comment by Windows-Taskmgr** [comment]
个人觉得先不搞评分功能也可以
