### ISSUE TITLE
Resources: New work of London

### ISSUE THREAD

**Issue by Hsichiene** [railmapgen/rmp-gallery#1362]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**
[london (3).txt](https://github.com/railmapgen/rmp-gallery/files/14734396/london.3.txt)
#1320

**Comment by 28yfang** [comment]
您好，感谢您的贡献。
经检查，您的作品存在以下问题：
1. 此作品中大量线段未使用调色板中的颜色，请将其替换为调色板已有颜色；
2. District与Hammersmith & City线的Bow Road站错写为Bow Church
3. Victoria线与London Overground的Blackhorse Road站错写为Blackhorse
4. DLR遗漏了Pudding Mill Lane站，如图所示：
官方：
![IMG_5614](https://github.com/railmapgen/rmp-gallery/assets/123239445/154b5f86-8d48-44b5-a54f-1097b8d6d8dd)
您的：
![Screenshot 2024-07-02 at 12 09 43](https://github.com/railmapgen/rmp-gallery/assets/123239445/2f434360-733e-4c2b-9ffc-9fb0076c8a53)
5. Elizabeth line的Chadwell Heath错写为Chadwll Heath
6. London Overground的Hackney Wick站错写为Hackey Wick
7. London Overground一个支线分岔口位置错误，如图所示：
官方：
![IMG_5615](https://github.com/railmapgen/rmp-gallery/assets/123239445/69aaba56-412f-4ffa-9c54-3facadbed692)
您的：
![Screenshot 2024-07-02 at 12 19 26](https://github.com/railmapgen/rmp-gallery/assets/123239445/860ee0ff-0d0d-4ee7-8199-aef22b423904)
8. London Overground的Hackney Downs错写为Heckney Downs
9. IFS Cloud Cable Car的所有车站站名前都应加上IFS Cloud二字，如图：
![IMG_5616](https://github.com/railmapgen/rmp-gallery/assets/123239445/e0acb4c9-76ff-476b-be8d-591a6e0951d3)
10. Thameslink北部Towards Welwyn Garden City中的Garden错写为Gaarden
11. Thameslink西南部Beckenham Hill站站名错写为Beckenham
12. Thameslink西南部Towards Sevenoaks错写为Towards Sevenooaks

请在修正后重新提交，并附上本议题编号（#1362），感谢！
