### ISSUE TITLE
Donation: New work of mohaicity

### ISSUE THREAD

**Issue by Wang090204** [railmapgen/rmp-gallery#1365]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**
[mohaicity.txt](https://github.com/railmapgen/rmp-gallery/files/14734455/mohaicity.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your support! Your work is merged and will be released to the gallery soon :)
