### ISSUE TITLE
Donation: New work of kabars

### ISSUE THREAD

**Issue by vicemoter0062** [railmapgen/rmp-gallery#1368]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Kabars",
        "zh-Hant": "喀巴里斯"
    },
    "desc": {
        "en": ""
    },
    "reference": "爱发电,Sun Mar 24 2024 17:03:59 GMT+0800 (中國標準時間)",
    "justification": "",
    "remainingUpdateCount": -1
}</details>

<details repo="rmp-gallery" type="fantasy" compress="zipson" city="kabars">{¨svgViewBoxZoom¨¢2G¨svgViewBoxMin¨{´x´£-D.-9g´y´£-4e.-1c}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨bjsubway-basic¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨¨open¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨right¨¨top¨|¨哈都督李斯特山¨¨Mount Hadudulist¨÷»ßA»¢Ay¢4gÉ¨stn_naziG9cXeR¨ßIßJ|¨卡波裏 ¨¨Kabor¨÷»ßA»¢C1º2É¨stn_JWsmZrAXxa¨ßIßJ|¨多莎¨¨Dosha¨÷»ßA»¢D4º2É¨stn_gZgHSevyuL¨ßIßJ|¨土坷街¨¨Tuk Street¨÷»ßA»¢E2º2É¨stn_qpRjhtnt9t¨ßIßJ|¨喀巴里斯站¨¨Stn¨÷»ßA»¢F5º2É¨stn_FjXhOLqnvX¨ßIßJ|¨激勵蘇克¨¨Jilisuk¨÷»ßA»¢GDº2É¨stn_7r_Ea7VxN6¨ßIßJ|¨博物館¨¨Museum¨÷»ßA»¢HLº2É¨stn_zI1c3Iqmvk¨ßIßJ|¨唐人街¨¨China Twon¨÷»ßA»¢I4¢4CÉ¨stn_0iOdK1yGzi¨ßIßJ|¨購物中心¨¨Shopping Mail¨÷»ßA»º9¢3EÉ¨stn_5eh9Z7S0LY¨ßIßJ|¨哈巴迪¨¨Habadi¨÷»ßA»º9¢26É¨stn_t38R6zTK6p¨ßIßJ|¨國王大街¨¨King street¨÷»ßA»º9¢13É¨stn_loA-XSyUjc¨ßIßJ|¨波利明安¨¨Borik Moan¨÷»ßA»º9¢-AÉ¨stn_0IwiL0wppe¨ßIßJ|¨科美德¨¨Komed¨÷»ßA»¢Is¢-oÉ¨stn_GJSx2cH8X8¨—{ßH¨misc_node_Oo5BvGHZuS¨ß8{ßF»ßGÉ´x´º6´y´¢4Wß4¨facilities¨ßy{ß4¨railway_suzhou¨}}}÷¨edges¨|¦ß8¦¨diagonal¨¦¨offsetFrom¨¨offsetTo¨¨roundCornerFactor¨¨startFrom¨‡¨reconcileId¨¨single-color¨¦¨color¨‡¨style¨ß4ßFßG‡ßH¨source¨¨target¨‡ÉÉ¤A¨from¨´´|¨other¨ß1D¨#ff0000¨¨#fff¨÷ß17ß11»É¨line_7LSe8NNVj7¨ßbßeÉÉ¤Aß1C´´|ß1Dþß1Eß1F÷ß17ß11»É¨line_sCOIaAbDQ8¨ßMßPÉÉ¤Aß1C´´|ß1Dþß1Eß1F÷ß17ß11»É¨line_v1oxPjg942¨ßPßSÉÉ¤Aß1C´´|ß1Dþß1Eß1F÷ß17ß11»É¨line_FNNREGAbNg¨ßSßVÉÉ¤Aß1C´´|ß1Dþß1Eß1F÷ß17ß11»É¨line_Dax4KPYYul¨ßVßYÉÉ¤Aß1C´´|ß1Dþß1Eß1F÷ß17ß11»É¨line_jdrxQOhsDL¨ßYßb—{ßH¨line_qnNnqSsLCw¨ß1Aßeß1Bßhß8{ßF»ßGÉß4¨perpendicular¨ß1N{ß15ß1Cß12Éß13Éß14£I.5K}ß19ß17ß17{ß18|ß1Dþß1Eß1F÷}ß16´´}}{ßH¨line_pbTqPksJdQ¨ß1Aßwß1Bßtß8{ßF»ßGÉß4ß1Nß1N{ß15ß1Cß12Éß13Éß14Ý2}ß19ß17ß17{ß18|ß1Dþß1Eß1F÷}ß16´´}}{ßH¨line_RY2ytZjTq2¨ß1Aßtß1Bßqß8{ßF»ßGÉß4ß11ß11{ß15ß1Cß12Éß13Éß14¤A}ß19ß17ß17{ß18|ß1Dþß1Eß1F÷}ß16´´}}{ßH¨line_ma-1qdmLdA¨ß1Aßhß1Bßkß8{ßF»ßGÉß4ß11ß11{ß15ß1Cß12Éß13Éß14¤A}ß19ß17ß17{ß18|ß1Dþß1Eß1F÷}ß16´´}}{ßH¨line_Lbu7oCt1CB¨ß1Aßkß1Bßnß8{ßF»ßGÉß4ß11ß11{ß15ß1Cß12Éß13Éß14¤A}ß19ß17ß17{ß18|ß1Dþß1Eß1F÷}ß16´´}}{ßH¨line_w0jvTI4iEI¨ß1Aßnß1Bßqß8{ßF»ßGÉß4ß11ß11{ß15ß1Cß12Éß13Éß14¤A}ß19ß17ß17{ß18|ß1Dþß1Eß1F÷}ß16´´}}{ßH¨line_RCCMxN4WRT¨ß1Aßnß1Bßnß8{ßF»ßGÉß4ß11ß11{ß15ß1Cß12Éß13Éß14¤A}ß19ß17ß17{ß18|ß1Dþ¨#2cf22c¨ß1F÷}ß16´´}}÷}¨version¨¤U}</details>

**Comment by thekingofcity** [comment]
Hi, thanks for your support. Your work is merged and will be released soon :)
