### ISSUE TITLE
Resources: Update work of changchun

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp-gallery#1375]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[Changchun.txt](https://github.com/railmapgen/rmp-gallery/files/14787519/Changchun.txt)

**Comment by 28yfang** [comment]
Note: The official map contains a mistake: 长影世纪城 station of lines 3 and 6 should have an English name of Changying Shijicheng, and not Changying Shijiecheng, as shown in this image:
![IMG_5450](https://github.com/railmapgen/rmp-gallery/assets/123239445/625ddc27-1938-4aa2-9861-cdca7659247d)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your work is merged and will be released soon :)
