### ISSUE TITLE
Resources: New work of chengdumetropolitanareahighspeedrailwayroute

### ISSUE THREAD

**Issue by Ryoooh1101** [railmapgen/rmp-gallery#1397]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[chengdumetropolitanareahighspeedrailwayroute (1).txt](https://github.com/railmapgen/rmp-gallery/files/14856278/chengdumetropolitanareahighspeedrailwayroute.1.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. However, we do not accept works that do not follow any existing official maps created by local railway/metro companies.
