### ISSUE TITLE
Resources: New template of chengdu

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp-gallery#141]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[Chengdu Upload File.txt](https://github.com/railmapgen/rmp-gallery/files/11524312/Chengdu.Upload.File.txt)

**Comment by 28yfang** [comment]
由于在官方线路图中，双流西站站、新津站站、和犀浦站并没有任何设施图标，所有我没有加。如果大家强烈建议我加的话，我再上传一次也行。

**Comment by langonginc** [comment]
您好，https://github.com/railmapgen/rmp-gallery/issues/129 中提到的问题已解决。在官方图中并未提及上述设施图标，所以不需添加。等待管理员最终检查并汇入，感谢您的贡献。
