### ISSUE TITLE
Resources: Update work of brussels

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp-gallery#1419]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[Brussels.txt](https://github.com/railmapgen/rmp-gallery/files/14958253/Brussels.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your work is merged and will be available soon :)
