### ISSUE TITLE
Resources: New work of thethirdplanningofnanjingmetro

### ISSUE THREAD

**Issue by DogInTheSpace** [railmapgen/rmp-gallery#1435]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[thethirdplanningofnanjingmetro.txt](https://github.com/railmapgen/rmp-gallery/files/15045168/thethirdplanningofnanjingmetro.txt)

**Comment by DogInTheSpace** [comment]
[thethirdplanningofnanjingmetro.txt](https://github.com/railmapgen/rmp-gallery/files/15047120/thethirdplanningofnanjingmetro.txt)

**Comment by 28yfang** [comment]
Hi, please wait until all lines in this work has opened before submitting it :)

**Comment by DogInTheSpace** [comment]
I'm so sorry. I thought the previous review was not approved due to formatting issues, so I applied for another one.
Thank you very much for clearing the blocked part for me. If possible, please help me delete the duplicate copy submitted later. :)



------------------&nbsp;原始邮件&nbsp;------------------。
发件人:                                                                                                                        "railmapgen/rmp-gallery"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月20日(星期六) 下午2:50
***@***.***&gt;;
抄送:&nbsp;"Vladimir ***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [railmapgen/rmp-gallery] Resources: New work of thethirdplanningofnanjingmetro (Issue #1435)





 
Hi, please wait until all lines in this work has opened before submitting it :)

**Comment by thekingofcity** [comment]
Hi, the previous issue hit a bug in the bot, so no pull request was created. Sorry for the confusion 🥲
