### ISSUE TITLE
Resources: New work of montreal

### ISSUE THREAD

**Issue by chinagi** [railmapgen/rmp-gallery#1469]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[montreal.txt](https://github.com/railmapgen/rmp-gallery/files/15219167/montreal.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your work is merged and will be released soon :)
