### ISSUE TITLE
Resources: Update work of shenzhen

### ISSUE THREAD

**Issue by huikamsum1** [railmapgen/rmp-gallery#1484]
[RMP_1717230257940.json](https://github.com/user-attachments/files/15521183/RMP_1717230257940.json)
Hi RMP team! I would like to contribute to the gallery with the data below.

![深圳地铁运行线路图 新的（2024-6-1）](https://github.com/railmapgen/rmp-gallery/assets/171417133/c7e3b400-504c-4d4c-8d7a-a722d4abe2f8)

**Comment by thekingofcity** [comment]
Hi, upload the generated content from Gallery to have your work being processed:)
