### ISSUE TITLE
New Fantasy Map of Hong Kong

### ISSUE THREAD

**Issue by huikamsum1** [railmapgen/rmp-gallery#1485]
[RMP_1717232063438.json](https://github.com/user-attachments/files/15521186/RMP_1717232063438.json)
![香港铁路运行线路图 新的（2026-6-1）](https://github.com/railmapgen/rmp-gallery/assets/171417133/2c44eb30-7bfc-4726-b3f8-bbd0dbc91354)

**Comment by thekingofcity** [comment]
Hi, to submit a fantasy work, a donation is required. Also, follow the instructions from Gallery and paste/upload the generated content in the issue body :)
