### ISSUE TITLE
New Fantasy Map of Beijing

### ISSUE THREAD

**Issue by huikamsum1** [railmapgen/rmp-gallery#1486]
[RMP_1717232661253.json](https://github.com/user-attachments/files/15521188/RMP_1717232661253.json)
![北京铁路运行线路图 新的](https://github.com/railmapgen/rmp-gallery/assets/171417133/3fa7dfca-9503-48fd-9a43-a2c24e795aed)

**Comment by thekingofcity** [comment]
Hi, to submit a fantasy work, a donation is required. Also, follow the instructions from Gallery and paste/upload the generated content in the issue body :)
