### ISSUE TITLE
New Fantasy of Shanghai

### ISSUE THREAD

**Issue by huikamsum1** [railmapgen/rmp-gallery#1487]
![上海铁路运行线路图 新的](https://github.com/railmapgen/rmp-gallery/assets/171417133/067786b3-867e-4152-b535-4398ef420e2a)
[RMP_1717232964004.json](https://github.com/user-attachments/files/15521189/RMP_1717232964004.json)

**Comment by thekingofcity** [comment]
Hi, to submit a fantasy work, a donation is required. Also, follow the instructions from Gallery and paste/upload the generated content in the issue body :)
