### ISSUE TITLE
Resources: New work of saikong(Fantasy)

### ISSUE THREAD

**Issue by Xevalus** [railmapgen/rmp-gallery#1500]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[saikong.txt](https://github.com/user-attachments/files/15613816/saikong.txt)

**Comment by thekingofcity** [comment]
Hi, to submit a fantasy work, a donation is required. You may switch to the fantasy tab and proceed with the bottom-right love button :)
