### ISSUE TITLE
Resources: Update work of foshan

### ISSUE THREAD

**Issue by BLOCK114514** [railmapgen/rmp-gallery#1518]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**
[foshan2.txt](https://github.com/user-attachments/files/15845551/foshan2.txt)

**Comment by 28yfang** [comment]
您好，请问 #1516 的作者是不是您？如果是，请问是否为旧版本并可以关闭？

**Comment by 28yfang** [comment]
您好，感谢您的贡献。
很抱歉，由于 #1516 比您更早提交并且没有任何问题，我们已优先汇入 #1516。
