### ISSUE TITLE
Resources: Update work of guangzhou

### ISSUE THREAD

**Issue by BLOCK114514** [railmapgen/rmp-gallery#1520]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[newguangzhou.txt](https://github.com/user-attachments/files/15855819/newguangzhou.txt)

**Comment by BLOCK114514** [comment]
@wongchito 什么时候审核？广州地铁画廊图好久没更新了

**Comment by 28yfang** [comment]
您好，感谢您的贡献。
经检查，您的模版含有以下问题：
1. 广州地铁新版换乘车站无法使用反斜杠换行，请用回车键代替。具体车站有：陈家祠、广州南站、珠江新城
2. 此线路图有多处车站站名覆盖的情况，请进行修改
3. 2号线昌岗站车站编号错误，正确的为2|09
4. 3号线燕塘站颜色错误
5. 7号线萝岗至科丰路区间的线段为使用调色板中已有的颜色，请进行替换
6. 黄埔有轨电车1号线北师大实验学校站英文名错误，正确的为Guangzhou Experimental School Affiliated to BNU
7. 黄埔有轨电车1号线峻泰路站英文名错误，正确的为Juntai Lu
8. 佛山地铁3号线佛山大学仙溪校区站中文名错写成佛科院仙溪校区

请在修正后重新提交，并附上本议题编号（#1520），感谢！
