### ISSUE TITLE
Resources: Update work of chengdu

### ISSUE THREAD

**Issue by xsmstl** [railmapgen/rmp-gallery#1533]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[chengdu (4).txt](https://github.com/user-attachments/files/15935647/chengdu.4.txt)

**Comment by 28yfang** [comment]
您好，感谢您的贡献。
经检查，您的作品含有以下错误：
1. 1号线、6号线人民北路站英文站名错误，正确的为Renmin North Road
2. 2号线、6号线犀浦站英文站名错误，正确的为Xipu Railway Station
3. 2号线金科北路站英文名错误，正确的为Jinke North Road
4. 2号线蜀汉路东站英文名错误，正确的为Shuhan Road East
5. 2号线、7号线成都东客站站英文名错误，正确的为Chengdu East Railway Station
6. 3号线、10号线双流西站站英文名错误，正确的为Shuangliu West Railway Station
7. 3号线川藏立交站英文名错误，正确的为Chuanzang Flyover
8. 3号线、7号线驷马桥站英文名错误，正确的为Sima Bridge
9. 3号线昭觉寺南路站英文名错误，正确的为Zhaojuesi South Road
10. 4号线清江西路站英文名错误，正确的为Qingjiang West Road
11. 4号线草堂北路站英文名错误，正确的为Caotang North Road
12. 4号线太升南路站英文名错误，正确的为Taisheng South Road
13. 5号线、7号线北站西二路站英文名错误，正确的为2nd Beizhan West Road
14. 5号线、6号线西北桥站英文名错误，正确的为Xibei Bridge
15. 6号线青岛路站已经开通运营，此站位于沈阳路站与昌公堰站之间
16. 6号线梁家巷站英文名错误，正确的为Liangjiaxiang
17. 10号线儒林路站英文名错误，正确的为Rulin Road
18. 10号线新津站站英文名错误，正确的为Xinjin Railway Station
19. 10号线应天寺站英文名错误，正确的Yingtian Temple
20. 蓉2号线锦城学院站英文名错误，正确的为Chengdu Jincheng College

请在修正后重新提交，并附上本议题编号（#1533），感谢！
