### ISSUE TITLE
Resources: Update work of macao

### ISSUE THREAD

**Issue by ME-786** [railmapgen/rmp-gallery#1540]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Macao"
    },
    "desc": {
        "en": "A route map of Macao Lightrail."
    },
    "reference": "metroman.cn",
    "justification": "A route map of Macao Lightrail."
}</details>

<details repo="rmp-gallery" type="real_world" compress="none" city="macao">{"svgViewBoxZoom":60,"svgViewBoxMin":{"x":239.4371030074692,"y":-32.00906634166313},"graph":{"options":{"type":"directed","multi":true,"allowSelfLoops":true},"attributes":{},"nodes":[{"key":"stn_48ePpDKrBP","attributes":{"visible":true,"zIndex":0,"x":565,"y":190,"type":"mtr","mtr":{"names":["妈阁","Barra"],"nameOffsetX":"right","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"stn_cEaZPWIxv2","attributes":{"visible":true,"zIndex":0,"x":565,"y":305,"type":"mtr","mtr":{"names":["海洋","Ocean"],"nameOffsetX":"right","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"stn_iWXXsvuJ8x","attributes":{"visible":true,"zIndex":0,"x":610,"y":325,"type":"mtr","mtr":{"names":["马会","Jockey Clube"],"nameOffsetX":"right","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"stn_bScaG-6_hD","attributes":{"visible":true,"zIndex":0,"x":660,"y":350,"type":"mtr","mtr":{"names":["运动场","Stadium"],"nameOffsetX":"right","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"stn_cALk-vge6u","attributes":{"visible":true,"zIndex":0,"x":660,"y":405,"type":"mtr","mtr":{"names":["排角","Pai Kok"],"nameOffsetX":"right","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"stn_uvrTGpevPs","attributes":{"visible":true,"zIndex":0,"x":660,"y":455,"type":"mtr","mtr":{"names":["路氹西","Cotai West"],"nameOffsetX":"right","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"stn_PQSfSDcqgc","attributes":{"visible":true,"zIndex":0,"x":690,"y":500,"type":"mtr","mtr":{"names":["莲花","Lotus"],"nameOffsetX":"right","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"stn_yUsW-e1qQz","attributes":{"visible":true,"zIndex":0,"x":795,"y":455,"type":"mtr","mtr":{"names":["东亚运","East Asian Games"],"nameOffsetX":"right","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"stn_HX9b7SrF7F","attributes":{"visible":true,"zIndex":0,"x":795,"y":415,"type":"mtr","mtr":{"names":["路氹东","Cotai East"],"nameOffsetX":"right","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"stn_nj9Ndtb89D","attributes":{"visible":true,"zIndex":0,"x":795,"y":375,"type":"mtr","mtr":{"names":["科大","MUST"],"nameOffsetX":"right","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"stn_q8X_Xvo_sE","attributes":{"visible":true,"zIndex":0,"x":795,"y":330,"type":"mtr","mtr":{"names":["机场","Airport"],"nameOffsetX":"right","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"stn_2Zt_Ybym03","attributes":{"visible":true,"zIndex":0,"x":795,"y":290,"type":"mtr","mtr":{"names":["氹仔码头","Taipa Ferry Terminal"],"nameOffsetX":"right","nameOffsetY":"top","rotate":0,"transfer":[[]]}}}],"edges":[{"key":"line_xsIVoZu0dr","source":"stn_cEaZPWIxv2","target":"stn_48ePpDKrBP","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#45d93a","#fff"]},"reconcileId":""}},{"key":"line_3_P49PEVyq","source":"stn_iWXXsvuJ8x","target":"stn_cEaZPWIxv2","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#45d93a","#fff"]},"reconcileId":""}},{"key":"line_FbB9nd-5BP","source":"stn_iWXXsvuJ8x","target":"stn_bScaG-6_hD","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#45d93a","#fff"]},"reconcileId":""}},{"key":"line_O8HRQ_DzBw","source":"stn_bScaG-6_hD","target":"stn_cALk-vge6u","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#45d93a","#fff"]},"reconcileId":""}},{"key":"line_ofa3BsaJWW","source":"stn_cALk-vge6u","target":"stn_uvrTGpevPs","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#45d93a","#fff"]},"reconcileId":""}},{"key":"line_0QSTB-dUEM","source":"stn_uvrTGpevPs","target":"stn_PQSfSDcqgc","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#45d93a","#fff"]},"reconcileId":""}},{"key":"line_13cxZBAaKa","source":"stn_2Zt_Ybym03","target":"stn_q8X_Xvo_sE","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#45d93a","#fff"]},"reconcileId":""}},{"key":"line_j9_bofcMpT","source":"stn_PQSfSDcqgc","target":"stn_yUsW-e1qQz","attributes":{"visible":true,"zIndex":0,"type":"perpendicular","perpendicular":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":18.33},"style":"single-color","single-color":{"color":["other","other","#45d93a","#fff"]},"reconcileId":""}},{"key":"line_yxGSzAI_p1","source":"stn_q8X_Xvo_sE","target":"stn_nj9Ndtb89D","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#45d93a","#fff"]},"reconcileId":""}},{"key":"line__olaYgq9U5","source":"stn_nj9Ndtb89D","target":"stn_HX9b7SrF7F","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#45d93a","#fff"]},"reconcileId":""}},{"key":"line_pkBcHO7B8w","source":"stn_HX9b7SrF7F","target":"stn_yUsW-e1qQz","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#45d93a","#fff"]},"reconcileId":""}}]},"version":31}</details>

**Comment by 28yfang** [comment]
您好，我未从您提交的作品中看到任何更新。另外，更新作品时请基于已有作品进行修改。
