### ISSUE TITLE
Resources: Update work of ningbo

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#1558]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1719567536241.txt](https://github.com/user-attachments/files/16027580/1719567536241.txt)

**Comment by 28yfang** [comment]
您好，感谢您的贡献。经检查，您的作品含有以下问题：
1. 3号线句章路站英文名应为Gouzhang Road
2. 5号线会展中心站英文名应为International Convention and Exhibition Center

请在修正后重新提交，并附上本议题编号（#1558），感谢！
