### ISSUE TITLE
Resources: Update work of tokyo

### ISSUE THREAD

**Issue by fvsdh** [railmapgen/rmp-gallery#1577]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[tokyo.txt](https://github.com/user-attachments/files/16092140/tokyo.txt)

**Comment by thekingofcity** [comment]
嗨，感谢您的贡献与支持。更新请写明详细更新内容，除此之外，如无必要也请勿更改原图。
