### ISSUE TITLE
Resources: Update work of copenhagen

### ISSUE THREAD

**Issue by axl099** [railmapgen/rmp-gallery#1582]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[copenhagen.txt](https://github.com/user-attachments/files/16119403/copenhagen.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your work is merged and will be available soon :)
