### ISSUE TITLE
Resources: New work of gongqain

### ISSUE THREAD

**Issue by jerry-jerryliu** [railmapgen/rmp-gallery#1584]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**
<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Gongqain",
        "zh-Hant": "公前"
    },
    "desc": {
        "en": ""
    },
    "reference": "github.io",
    "justification": "give it a try"
}</details>

<details repo="rmp-gallery" type="real_world" compress="none" city="gongqain">{"svgViewBoxZoom":120,"svgViewBoxMin":{"x":129.4329971313478,"y":170.3996139526366},"graph":{"options":{"type":"directed","multi":true,"allowSelfLoops":true},"attributes":{},"nodes":[{"key":"stn_KhumwzcvzM","attributes":{"visible":true,"zIndex":0,"x":185,"y":390,"type":"mtr","mtr":{"names":["馬山","Mashan"],"nameOffsetX":"middle","nameOffsetY":"top","rotate":90,"transfer":[[["shanghai","sh1","#e3002b","#fff","",""],["taipei","bl","#0070bd","#fff","",""]]]}}},{"key":"stn_4V8-M3cEGV","attributes":{"visible":true,"zIndex":0,"x":290,"y":390,"type":"mtr","mtr":{"names":["馬山博物館","Mashan Museum"],"nameOffsetX":"middle","nameOffsetY":"top","rotate":90,"transfer":[[["shanghai","sh1","#e3002b","#fff","",""],["taipei","bl","#0070bd","#fff","",""]]]}}},{"key":"stn_lv1wCb6WAr","attributes":{"visible":true,"zIndex":0,"x":455,"y":390,"type":"mtr","mtr":{"names":["前橋","Qainqiao"],"nameOffsetX":"middle","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"stn_HNFgUjE1IJ","attributes":{"visible":true,"zIndex":0,"x":540,"y":390,"type":"mtr","mtr":{"names":["十墘路","Shiqain Rd."],"nameOffsetX":"middle","nameOffsetY":"top","rotate":90,"transfer":[[["shanghai","sh1","#e3002b","#fff","",""],["taipei","bl","#0070bd","#fff","",""]]]}}},{"key":"stn_gQhrEfHk8h","attributes":{"visible":true,"zIndex":0,"x":620,"y":390,"type":"mtr","mtr":{"names":["十墘東路","Shiqain E. Rd."],"nameOffsetX":"middle","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"stn_wYwPUNUVE0","attributes":{"visible":true,"zIndex":0,"x":585,"y":450,"type":"mtr","mtr":{"names":["大壩港口","Daba Port"],"nameOffsetX":"right","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"stn_IGS2BICVYG","attributes":{"visible":true,"zIndex":0,"x":720,"y":380,"type":"mtr","mtr":{"names":["風順醫院","Fungshung\\Hospital"],"nameOffsetX":"left","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"stn_TXh-YzkQ7T","attributes":{"visible":true,"zIndex":0,"x":755,"y":345,"type":"mtr","mtr":{"names":["龜黑赤","Guaheichi"],"nameOffsetX":"left","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"stn_vZDDvvki86","attributes":{"visible":true,"zIndex":0,"x":795,"y":305,"type":"mtr","mtr":{"names":["公前大道","Gongqain\\Avenue"],"nameOffsetX":"right","nameOffsetY":"bottom","rotate":90,"transfer":[[["shanghai","sh1","#e3002b","#fff","",""],["other","other","#82f282","#fff","",""]]]}}},{"key":"stn_wR0hsAH-zb","attributes":{"visible":true,"zIndex":0,"x":855,"y":285,"type":"mtr","mtr":{"names":["公前街","Gongqain\\Street"],"nameOffsetX":"middle","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"stn_Iih793wpwl","attributes":{"visible":true,"zIndex":0,"x":930,"y":285,"type":"mtr","mtr":{"names":["公前高中","Gongqain\\High School"],"nameOffsetX":"middle","nameOffsetY":"top","rotate":0,"transfer":[[["shanghai","sh1","#e3002b","#fff","",""],["taipei","hsr","#db5426","#fff","",""]]]}}},{"key":"stn_1orasjZOkW","attributes":{"visible":true,"zIndex":0,"x":585,"y":510,"type":"mtr","mtr":{"names":["大壩路","Daba Rd."],"nameOffsetX":"right","nameOffsetY":"middle","rotate":0,"transfer":[[]]}}},{"key":"stn_LwnVl06k-K","attributes":{"visible":true,"zIndex":0,"x":630,"y":570,"type":"mtr","mtr":{"names":["大霸機場","Daba Airport"],"nameOffsetX":"middle","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"stn_xiaTCWhijX","attributes":{"visible":true,"zIndex":0,"x":670,"y":620,"type":"mtr","mtr":{"names":["洪光","Honggung"],"nameOffsetX":"right","nameOffsetY":"middle","rotate":0,"transfer":[[["taipei","bl","#0070bd","#fff","",""],["other","other","#82f282","#fff","",""],["taipei","hsr","#db5426","#fff","",""]]]}}},{"key":"stn_GD16iHMj15","attributes":{"visible":true,"zIndex":0,"x":680,"y":695,"type":"mtr","mtr":{"names":["洪光國中","Honggung\\Junior High School"],"nameOffsetX":"left","nameOffsetY":"middle","rotate":0,"transfer":[[]]}}},{"key":"stn_mipecnjq8z","attributes":{"visible":true,"zIndex":0,"x":695,"y":545,"type":"mtr","mtr":{"names":["康莊大道","Kangzhuang\\Aevnue"],"nameOffsetX":"right","nameOffsetY":"bottom","rotate":225,"transfer":[[["taipei","hsr","#db5426","#fff","",""],["other","other","#82f282","#fff","",""]]]}}},{"key":"stn_VcJ0OzpXMy","attributes":{"visible":true,"zIndex":0,"x":770,"y":485,"type":"mtr","mtr":{"names":["市政府","Ctiy Hall"],"nameOffsetX":"left","nameOffsetY":"top","rotate":225,"transfer":[[["other","other","#9900ff","#fff","",""],["taipei","hsr","#db5426","#fff","",""],["other","other","#82f282","#fff","",""]]]}}},{"key":"stn_JnSqJmkRsK","attributes":{"visible":true,"zIndex":0,"x":995,"y":470,"type":"mtr","mtr":{"names":["海口","Haikuo"],"nameOffsetX":"middle","nameOffsetY":"bottom","rotate":0,"transfer":[[]]}}},{"key":"stn_5jDAigTkOQ","attributes":{"visible":true,"zIndex":0,"x":920,"y":470,"type":"mtr","mtr":{"names":["莊園衡","Zhuanyuanhung"],"nameOffsetX":"middle","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"stn_Z9qyvfjv-x","attributes":{"visible":true,"zIndex":0,"x":850,"y":470,"type":"mtr","mtr":{"names":["空村里","Kungzuanli"],"nameOffsetX":"middle","nameOffsetY":"bottom","rotate":0,"transfer":[[]]}}},{"key":"misc_node_Iox071VLuQ","attributes":{"visible":true,"zIndex":0,"x":740,"y":515,"type":"virtual","virtual":{}}},{"key":"misc_node_UMZ-n8idje","attributes":{"visible":true,"zIndex":0,"x":775,"y":540,"type":"virtual","virtual":{}}},{"key":"stn_R6hmBlJsZZ","attributes":{"visible":true,"zIndex":0,"x":800,"y":580,"type":"mtr","mtr":{"names":["洪里","Hongli"],"nameOffsetX":"left","nameOffsetY":"middle","rotate":0,"transfer":[[]]}}},{"key":"stn_Pq0ws_ekkn","attributes":{"visible":true,"zIndex":0,"x":800,"y":620,"type":"mtr","mtr":{"names":["南洪里","South Hongli"],"nameOffsetX":"left","nameOffsetY":"middle","rotate":0,"transfer":[[]]}}},{"key":"stn_kmoucRE5Dz","attributes":{"visible":true,"zIndex":0,"x":800,"y":665,"type":"mtr","mtr":{"names":["下水","Xiashuai"],"nameOffsetX":"left","nameOffsetY":"middle","rotate":0,"transfer":[[]]}}},{"key":"stn_rgHl9bxh5Y","attributes":{"visible":true,"zIndex":0,"x":800,"y":720,"type":"mtr","mtr":{"names":["洪光大學","Honggung\\University"],"nameOffsetX":"left","nameOffsetY":"middle","rotate":0,"transfer":[[]]}}},{"key":"stn_WF7ApHD4XI","attributes":{"visible":true,"zIndex":0,"x":795,"y":395,"type":"mtr","mtr":{"names":["豐山公前","Fungshan\\Gongqain"],"nameOffsetX":"left","nameOffsetY":"middle","rotate":0,"transfer":[[]]}}},{"key":"stn_imyVuueegG","attributes":{"visible":true,"zIndex":0,"x":820,"y":430,"type":"mtr","mtr":{"names":["北遂","Beisuai"],"nameOffsetX":"right","nameOffsetY":"bottom","rotate":0,"transfer":[[]]}}},{"key":"stn_DlZJNWl1s9","attributes":{"visible":true,"zIndex":0,"x":855,"y":395,"type":"mtr","mtr":{"names":["槐鶽","Huaizhung"],"nameOffsetX":"left","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"stn_qaIsekfxmF","attributes":{"visible":true,"zIndex":0,"x":900,"y":350,"type":"mtr","mtr":{"names":["槐鶽國小","Huaizhung\\Elementary School"],"nameOffsetX":"right","nameOffsetY":"bottom","rotate":0,"transfer":[[]]}}},{"key":"stn_zXqI0TZ_C0","attributes":{"visible":true,"zIndex":0,"x":795,"y":255,"type":"mtr","mtr":{"names":["龘宏","Tahong"],"nameOffsetX":"left","nameOffsetY":"middle","rotate":0,"transfer":[[]]}}},{"key":"stn_VY5hxcWwdu","attributes":{"visible":true,"zIndex":0,"x":700,"y":220,"type":"mtr","mtr":{"names":["賊軌囸","Zaiguairui"],"nameOffsetX":"middle","nameOffsetY":"top","rotate":0,"transfer":[[]]}}},{"key":"misc_node_Nh6LRJj2Kq","attributes":{"visible":true,"zIndex":0,"x":300,"y":500,"type":"virtual","virtual":{}}},{"key":"misc_node_btMPlMWpfS","attributes":{"visible":true,"zIndex":0,"x":200,"y":550,"type":"virtual","virtual":{}}},{"key":"misc_node_Ul4c3khPAA","attributes":{"visible":true,"zIndex":0,"x":400,"y":550,"type":"virtual","virtual":{}}},{"key":"misc_node_ENnSkwLU_X","attributes":{"visible":true,"zIndex":0,"x":300,"y":600,"type":"virtual","virtual":{}}},{"key":"misc_node_hUk8S1GIyN","attributes":{"visible":true,"zIndex":0,"x":225,"y":510,"type":"virtual","virtual":{}}},{"key":"misc_node_qFK_xK8RqO","attributes":{"visible":true,"zIndex":0,"x":265,"y":510,"type":"virtual","virtual":{}}},{"key":"misc_node_eWyXbB3UnE","attributes":{"visible":true,"zIndex":0,"x":225,"y":530,"type":"virtual","virtual":{}}},{"key":"misc_node_R2BfiJJc1e","attributes":{"visible":true,"zIndex":0,"x":265,"y":530,"type":"virtual","virtual":{}}},{"key":"misc_node_z7DaNESqAa","attributes":{"visible":true,"zIndex":0,"x":225,"y":550,"type":"virtual","virtual":{}}},{"key":"misc_node_NDA65xaGR4","attributes":{"visible":true,"zIndex":0,"x":265,"y":550,"type":"virtual","virtual":{}}},{"key":"misc_node_AmfS7eIgGy","attributes":{"visible":true,"zIndex":0,"x":225,"y":570,"type":"virtual","virtual":{}}},{"key":"misc_node_G_3Tcozsa3","attributes":{"visible":true,"zIndex":0,"x":265,"y":570,"type":"virtual","virtual":{}}},{"key":"misc_node_5P4joT4Hcy","attributes":{"visible":true,"zIndex":0,"x":225,"y":590,"type":"virtual","virtual":{}}},{"key":"misc_node_xfKh9IShh3","attributes":{"visible":true,"zIndex":0,"x":265,"y":590,"type":"virtual","virtual":{}}},{"key":"misc_node_42yy3Vunsj","attributes":{"visible":true,"zIndex":0,"x":323,"y":509,"type":"text","text":{"content":"馬山公前線 Mashan-Gongqian Line","fontSize":7,"lineHeight":16,"textAnchor":"middle","dominantBaseline":"middle","language":"mtr__zh","color":["shanghai","jsr","#000000","#fff"],"rotate":0,"italic":"normal","bold":"normal"}}},{"key":"misc_node_ojTtRvAgCx","attributes":{"visible":true,"zIndex":0,"x":316,"y":529,"type":"text","text":{"content":"馬山大壩線 Mashan-Daba Line","fontSize":7,"lineHeight":16,"textAnchor":"middle","dominantBaseline":"middle","language":"mtr__zh","color":["shanghai","jsr","#000000","#fff"],"rotate":0,"italic":"normal","bold":"normal"}}},{"key":"misc_node_9wsMQxqFa2","attributes":{"visible":true,"zIndex":0,"x":324,"y":549,"type":"text","text":{"content":"洪光龘宏線 Honggung-Tahong Line","fontSize":7,"lineHeight":16,"textAnchor":"middle","dominantBaseline":"middle","language":"mtr__zh","color":["shanghai","jsr","#000000","#fff"],"rotate":0,"italic":"normal","bold":"normal"}}},{"key":"misc_node_5dAxMqfSpq","attributes":{"visible":true,"zIndex":0,"x":329,"y":569,"type":"text","text":{"content":"洪光槐鶽線 Honggung-Huaizhung Line","fontSize":7,"lineHeight":16,"textAnchor":"middle","dominantBaseline":"middle","language":"mtr__zh","color":["shanghai","jsr","#000000","#fff"],"rotate":0,"italic":"normal","bold":"normal"}}},{"key":"misc_node_JZmkb-ahfd","attributes":{"visible":true,"zIndex":0,"x":320,"y":589,"type":"text","text":{"content":"海口下水線 Haikuo-Xiashuai Line","fontSize":7,"lineHeight":16,"textAnchor":"middle","dominantBaseline":"middle","language":"mtr__zh","color":["shanghai","jsr","#000000","#fff"],"rotate":0,"italic":"normal","bold":"normal"}}}],"edges":[{"key":"line_a3U9K4HP0S","source":"stn_KhumwzcvzM","target":"stn_4V8-M3cEGV","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["shanghai","sh1","#e3002b","#fff"]},"reconcileId":""}},{"key":"line_9Gxt_KdvcK","source":"stn_KhumwzcvzM","target":"stn_4V8-M3cEGV","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":5,"offsetTo":5,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["taipei","bl","#0070bd","#fff"]},"reconcileId":""}},{"key":"line_RSnDUkiMxu","source":"stn_4V8-M3cEGV","target":"stn_lv1wCb6WAr","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["shanghai","sh1","#e3002b","#fff"]},"reconcileId":""}},{"key":"line_UTOYBoNMOT","source":"stn_4V8-M3cEGV","target":"stn_HNFgUjE1IJ","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":5,"offsetTo":5,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["taipei","bl","#0070bd","#fff"]},"reconcileId":""}},{"key":"line_W29YFsMkpJ","source":"stn_lv1wCb6WAr","target":"stn_HNFgUjE1IJ","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["shanghai","sh1","#e3002b","#fff"]},"reconcileId":""}},{"key":"line_i5C4bo3d01","source":"stn_HNFgUjE1IJ","target":"stn_gQhrEfHk8h","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["shanghai","sh1","#e3002b","#fff"]},"reconcileId":""}},{"key":"line_8CNg1B7flv","source":"stn_HNFgUjE1IJ","target":"stn_wYwPUNUVE0","attributes":{"visible":true,"zIndex":0,"type":"perpendicular","perpendicular":{"startFrom":"from","offsetFrom":5,"offsetTo":0,"roundCornerFactor":18.33},"style":"single-color","single-color":{"color":["taipei","bl","#0070bd","#fff"]},"reconcileId":""}},{"key":"line_99eToj6KTV","source":"stn_gQhrEfHk8h","target":"stn_IGS2BICVYG","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["shanghai","sh1","#e3002b","#fff"]},"reconcileId":""}},{"key":"line_rbV8Gy7a45","source":"stn_IGS2BICVYG","target":"stn_TXh-YzkQ7T","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["shanghai","sh1","#e3002b","#fff"]},"reconcileId":""}},{"key":"line_gLD0p_0Ofk","source":"stn_TXh-YzkQ7T","target":"stn_vZDDvvki86","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["shanghai","sh1","#e3002b","#fff"]},"reconcileId":""}},{"key":"line_dzHTsxUIrg","source":"stn_vZDDvvki86","target":"stn_wR0hsAH-zb","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"to","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["shanghai","sh1","#e3002b","#fff"]},"reconcileId":""}},{"key":"line_vpCSWdLprQ","source":"stn_wR0hsAH-zb","target":"stn_Iih793wpwl","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["shanghai","sh1","#e3002b","#fff"]},"reconcileId":""}},{"key":"line_PGOi6K6GZr","source":"stn_wYwPUNUVE0","target":"stn_1orasjZOkW","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["taipei","bl","#0070bd","#fff"]},"reconcileId":""}},{"key":"line_8XzEwIOFNb","source":"stn_1orasjZOkW","target":"stn_LwnVl06k-K","attributes":{"visible":true,"zIndex":0,"type":"perpendicular","perpendicular":{"startFrom":"to","offsetFrom":0,"offsetTo":0,"roundCornerFactor":18.33},"style":"single-color","single-color":{"color":["taipei","bl","#0070bd","#fff"]},"reconcileId":""}},{"key":"line_y1MxlgXetL","source":"stn_xiaTCWhijX","target":"stn_LwnVl06k-K","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["taipei","bl","#0070bd","#fff"]},"reconcileId":""}},{"key":"line_-BpqRD6nx_","source":"stn_xiaTCWhijX","target":"stn_GD16iHMj15","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":10,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["taipei","hsr","#db5426","#fff"]},"reconcileId":""}},{"key":"line_tIvp7o90pO","source":"stn_xiaTCWhijX","target":"stn_mipecnjq8z","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":10,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["taipei","hsr","#db5426","#fff"]},"reconcileId":""}},{"key":"line_uo6Fj7n2tg","source":"stn_xiaTCWhijX","target":"stn_mipecnjq8z","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":5,"offsetTo":-5,"roundCornerFactor":12},"style":"single-color","single-color":{"color":["other","other","#82f282","#fff"]},"reconcileId":""}},{"key":"line_iVYkNGbBjU","source":"stn_mipecnjq8z","target":"stn_VcJ0OzpXMy","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":-5,"offsetTo":-10,"roundCornerFactor":8},"style":"single-color","single-color":{"color":["other","other","#82f282","#fff"]},"reconcileId":""}},{"key":"line_mHm8PDIpfQ","source":"stn_mipecnjq8z","target":"stn_VcJ0OzpXMy","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":-5,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["taipei","hsr","#db5426","#fff"]},"reconcileId":""}},{"key":"line_VsJZ54iifT","source":"stn_JnSqJmkRsK","target":"stn_5jDAigTkOQ","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#9900ff","#fff"]},"reconcileId":""}},{"key":"line_8O-QaGGmh4","source":"stn_5jDAigTkOQ","target":"stn_Z9qyvfjv-x","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#9900ff","#fff"]},"reconcileId":""}},{"key":"line_IsGPDL5wxb","source":"stn_Z9qyvfjv-x","target":"stn_VcJ0OzpXMy","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":9},"style":"single-color","single-color":{"color":["other","other","#9900ff","#fff"]},"reconcileId":""}},{"key":"line_ZCB5pjyJcZ","source":"stn_VcJ0OzpXMy","target":"misc_node_Iox071VLuQ","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#9900ff","#fff"]},"reconcileId":""}},{"key":"line_PqXB-Ls5-D","source":"misc_node_UMZ-n8idje","target":"misc_node_Iox071VLuQ","attributes":{"visible":true,"zIndex":0,"type":"perpendicular","perpendicular":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":18.33},"style":"single-color","single-color":{"color":["other","other","#9900ff","#fff"]},"reconcileId":""}},{"key":"line_-ZWAfgwx6J","source":"misc_node_UMZ-n8idje","target":"stn_R6hmBlJsZZ","attributes":{"visible":true,"zIndex":0,"type":"perpendicular","perpendicular":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":18.33},"style":"single-color","single-color":{"color":["other","other","#9900ff","#fff"]},"reconcileId":""}},{"key":"line_LbaBxCY_E4","source":"stn_R6hmBlJsZZ","target":"stn_Pq0ws_ekkn","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#9900ff","#fff"]},"reconcileId":""}},{"key":"line_sTpm-71gT5","source":"stn_Pq0ws_ekkn","target":"stn_kmoucRE5Dz","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#9900ff","#fff"]},"reconcileId":""}},{"key":"line_J8t5_NS9HB","source":"stn_kmoucRE5Dz","target":"stn_rgHl9bxh5Y","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#9900ff","#fff"]},"reconcileId":""}},{"key":"line_53QZ4heVtT","source":"stn_VcJ0OzpXMy","target":"stn_WF7ApHD4XI","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"to","offsetFrom":-10,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#82f282","#fff"]},"reconcileId":""}},{"key":"line_KzdxLosEoY","source":"stn_imyVuueegG","target":"stn_VcJ0OzpXMy","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":-5.1,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["taipei","hsr","#db5426","#fff"]},"reconcileId":""}},{"key":"line_4pd0b0S0k2","source":"stn_WF7ApHD4XI","target":"stn_vZDDvvki86","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#82f282","#fff"]},"reconcileId":""}},{"key":"line_lFqg8RBCxh","source":"stn_imyVuueegG","target":"stn_DlZJNWl1s9","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["taipei","hsr","#db5426","#fff"]},"reconcileId":""}},{"key":"line__Jt7_GqpdT","source":"stn_DlZJNWl1s9","target":"stn_qaIsekfxmF","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["taipei","hsr","#db5426","#fff"]},"reconcileId":""}},{"key":"line_A2MEznhY90","source":"stn_qaIsekfxmF","target":"stn_qaIsekfxmF","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["taipei","hsr","#db5426","#fff"]},"reconcileId":""}},{"key":"line_cdD8_Mh82c","source":"stn_qaIsekfxmF","target":"stn_Iih793wpwl","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"to","offsetFrom":0,"offsetTo":5,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["taipei","hsr","#db5426","#fff"]},"reconcileId":""}},{"key":"line_ux-0ZMp2yt","source":"stn_vZDDvvki86","target":"stn_zXqI0TZ_C0","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#82f282","#fff"]},"reconcileId":""}},{"key":"line_ZsiK4H8q-s","source":"stn_VY5hxcWwdu","target":"stn_zXqI0TZ_C0","attributes":{"visible":true,"zIndex":0,"type":"perpendicular","perpendicular":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":18.33},"style":"single-color","single-color":{"color":["other","other","#82f282","#fff"]},"reconcileId":""}},{"key":"line_DwO2O5GO1x","source":"misc_node_ENnSkwLU_X","target":"misc_node_btMPlMWpfS","attributes":{"visible":true,"zIndex":0,"type":"perpendicular","perpendicular":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":18.33},"style":"single-color","single-color":{"color":["other","other","#000000","#fff"]},"reconcileId":""}},{"key":"line_jD1nWiZKYc","source":"misc_node_Nh6LRJj2Kq","target":"misc_node_btMPlMWpfS","attributes":{"visible":true,"zIndex":0,"type":"perpendicular","perpendicular":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":18.33},"style":"single-color","single-color":{"color":["other","other","#000000","#fff"]},"reconcileId":""}},{"key":"line_WA7adnKS4h","source":"misc_node_ENnSkwLU_X","target":"misc_node_Ul4c3khPAA","attributes":{"visible":true,"zIndex":0,"type":"perpendicular","perpendicular":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":18.33},"style":"single-color","single-color":{"color":["other","other","#000000","#fff"]},"reconcileId":""}},{"key":"line_9hxlUwZhik","source":"misc_node_Nh6LRJj2Kq","target":"misc_node_Ul4c3khPAA","attributes":{"visible":true,"zIndex":0,"type":"perpendicular","perpendicular":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":18.33},"style":"single-color","single-color":{"color":["other","other","#000000","#fff"]},"reconcileId":""}},{"key":"line_TzlOhnx9Gx","source":"misc_node_hUk8S1GIyN","target":"misc_node_qFK_xK8RqO","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["shanghai","sh1","#e3002b","#fff"]},"reconcileId":""}},{"key":"line_v0TwdFn8B4","source":"misc_node_eWyXbB3UnE","target":"misc_node_R2BfiJJc1e","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["taipei","bl","#0070bd","#fff"]},"reconcileId":""}},{"key":"line_M0jqvnp98-","source":"misc_node_z7DaNESqAa","target":"misc_node_NDA65xaGR4","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#82f282","#fff"]},"reconcileId":""}},{"key":"line_pcsjNw_ooY","source":"misc_node_AmfS7eIgGy","target":"misc_node_G_3Tcozsa3","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["taipei","hsr","#db5426","#fff"]},"reconcileId":""}},{"key":"line_FOZgZCrjbd","source":"misc_node_5P4joT4Hcy","target":"misc_node_xfKh9IShh3","attributes":{"visible":true,"zIndex":0,"type":"diagonal","diagonal":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":10},"style":"single-color","single-color":{"color":["other","other","#9900ff","#fff"]},"reconcileId":""}}]},"version":31}</details>

**Comment by jerry-jerryliu** [comment]
interesting piece

**Comment by thekingofcity** [comment]
Hi, fantasy works requires donations to be available in the Gallery. We're looking forward to your support :)
