### ISSUE TITLE
Update Work of Xiamen BRT

### ISSUE THREAD

**Issue by ChinaExpressA320** [railmapgen/rmp-gallery#1589]
[Hi](url) RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**
[xiamen.txt.json](https://github.com/user-attachments/files/16172173/xiamen.txt.json)

**Comment by 28yfang** [comment]
您好，由于您提交的是两个不同的线网，请您通过点击画廊右下角的"+"按钮创建新作品，而不是替换已有的厦门地铁作品。
