### ISSUE TITLE
Resources: New work of qingyuan

### ISSUE THREAD

**Issue by gebixiaoer** [railmapgen/rmp-gallery#1591]
This is updated
[RMP_1720877645423.json](https://github.com/user-attachments/files/16202309/RMP_1720877645423.json)

**Comment by gebixiaoer** [comment]
This is updated
[RMP_1720877645423.json](https://github.com/user-attachments/files/16202309/RMP_1720877645423.json)

**Comment by 28yfang** [comment]
您好，请按照RMP画廊的提交步骤重新提交议题。
