### ISSUE TITLE
Resources: Update work of lanzhou

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp-gallery#1608]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[Lanzhou.txt](https://github.com/user-attachments/files/16309862/Lanzhou.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your update is merged and will be available soon :)
