### ISSUE TITLE
Donation: New work of guangzhou (simplifiedversion) 

### ISSUE THREAD

**Issue by Qinghai-sys** [railmapgen/rmp-gallery#1614]
Hi RMP team! I would like to contribute to the gallery with the data below.

[广州地铁图（简约版）.json](https://github.com/user-attachments/files/16321238/default.json)

https://ydyc.gzmtr.cn:19090/indexBrowser.html#/index

https://www.metroman.cn/metro.html?city=gz

**Comment by Qinghai-sys** [comment]
https://ydyc.gzmtr.cn:19090/indexBrowser.html#/index

**Comment by thekingofcity** [comment]
Hi, a donation is required to submit a fantasy work :) After donating, open the issue as instructed by the Gallery.
