### ISSUE TITLE
Resources: Update work of luoyang

### ISSUE THREAD

**Issue by BJR114514** [railmapgen/rmp-gallery#1627]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[luoyang.txt](https://github.com/user-attachments/files/16398115/luoyang.txt)

**Comment by thekingofcity** [comment]
Hi, to update a real-world work, a detailed update message is required. This might be _Add newly opened line_ or _fix a name misspellation_. Otherwise, the update request will be closed.

**Comment by BJR114514** [comment]
I have moved the signs of the bus stop and railway station, but I am unable to change the original message. THANK!!!
________________________________
发件人: thekingofcity ***@***.***>
发送时间: 2024年7月27日 13:45
收件人: railmapgen/rmp-gallery ***@***.***>
抄送: BJR114514 ***@***.***>; Author ***@***.***>
主题: Re: [railmapgen/rmp-gallery] Resources: Update work of luoyang (Issue #1627)


Hi, to update a real-world work, a detailed update message is required. This might be Add newly opened line or fix a name misspellation. Otherwise, the update request will be closed.

―

**Comment by thekingofcity** [comment]
![image](https://github.com/user-attachments/assets/63e969e9-a8be-4b1a-ab88-2b09035a38de)

To update, edit the _Justification_ for the update message and do not remove the _Description_ if it is ok.
