### ISSUE TITLE
Resources: New work of Luoyang

### ISSUE THREAD

**Issue by BJR114514** [railmapgen/rmp-gallery#1629]
Hi RMP team! I would like to contribute to the gallery with the data below.

[luoyang.txt](https://github.com/user-attachments/files/16398201/luoyang.txt)
(revised version)

**Comment by thekingofcity** [comment]
Hi, follow the instruction from the Gallery and do not remove line:

> __Paste or Upload below. They are meant for BOTS ONLY!!!__
