### ISSUE TITLE
Resources: New work of kualalumpur

### ISSUE THREAD

**Issue by 289toRefractory** [railmapgen/rmp-gallery#1630]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[kualalumpur.txt](https://github.com/user-attachments/files/16400295/kualalumpur.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Feel free to add _LRT Shah Alam Line_ to the work as it is printed on the official map. But this work still needs to be fixed as the _16 Sierra_ on the _MRT Putrajaya Line_ is misspelled as _Sierra 16_.
