### ISSUE TITLE
Resources: New work of kualalumpur

### ISSUE THREAD

**Issue by 289toRefractory** [railmapgen/rmp-gallery#1632]
Hi RMP team! I would like to contribute to the gallery with the data below.

[kualalumpur.txt](https://github.com/user-attachments/files/16402482/kualalumpur.txt)

**Comment by thekingofcity** [comment]
Hi, follow the instruction from the Gallery and do not remove line:

> __Paste or Upload below. They are meant for BOTS ONLY!!!__
