### ISSUE TITLE
Resources: Update work of chongqing

### ISSUE THREAD

**Issue by Todist2022** [railmapgen/rmp-gallery#1635]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**
[chongqing.txt](https://github.com/user-attachments/files/16468771/chongqing.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your work is merged and will be available soon :)
