### ISSUE TITLE
Donation: Update work of lianshen

### ISSUE THREAD

**Issue by Lian-Shen** [railmapgen/rmp-gallery#1649]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "zh-Hans": "联沈市",
        "en": "Lianshen"
    },
    "desc": {
        "zh-Hans": "线路图包含联沈市市区和郊区，2025+",
        "en": "The route map contains Lianshen city and suburbs, 2025+"
    },
    "reference": ",Thu Aug 08 2024 10:59:20 GMT+0800 (中国标准时间)",
    "remainingUpdateCount": -1,
    "justification": ""
}</details>

<details repo="rmp-gallery" type="fantasy" compress="none" city="a770fe81">{"svgViewBoxZoom":100,"svgViewBoxMin":{"x":0,"y":0},"graph":{"options":{"type":"directed","multi":true,"allowSelfLoops":true},"attributes":{},"nodes":[],"edges":[]},"version":31}</details>

**Comment by thekingofcity** [comment]
Hi, we can't find a record of lianshen in the Gallery. To submit a new fantasy work, donate and open a new issue as the Gallery instructed :)
