### ISSUE TITLE
Resources: Update work of qingdao

### ISSUE THREAD

**Issue by zhenmunse** [railmapgen/rmp-gallery#1664]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[qingdao.txt](https://github.com/user-attachments/files/16574167/qingdao.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your work is merged and will be available soon :)
