### ISSUE TITLE
Resources: New work of Las Vegas

### ISSUE THREAD

**Issue by 289toRefractory** [railmapgen/rmp-gallery#1673]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Las Vegas",
        "es": "Las Vegas",
        "zh-Hans": "拉斯维加斯",
        "zh-Hant": "拉斯維加斯",
        "ja": "ラスベガス"
    },
    "desc": {
        "en": "The Las Vegas Monorail is a 3.9-mile (6.3 km) automated monorail mass transit systemlocated adjacent to the Las Vegas Strip in Clark County, Nevada, United States. It connects several large casinos in the unincorporated communities of Paradise and Winchester, but does not enter the city of Las Vegas proper. Built at a cost of $650 million,it was privately owned and operated by the Las Vegas Monorail Company until their 2020 bankruptcy when it was sold to the Las Vegas Convention and Visitors Authority, a local government agency. In 2022, total annual ridership was roughly 4.3 million, down from a pre-Great Recession peak of 7.9 million in 2007. The monorail is a registered not-for-profit corporation, allowed under Nevada law since the monorail provides a public service. The State of Nevada assisted in bond financing, but no public money was used in construction.",
        "zh-Hans": "拉斯维加斯单轨列车（英语：Las Vegas Monorail）是一条位于美国内华达州克拉克郡内的单轨大众捷运系统，总长3.9英里（6.3公里）。单轨系统连结了天堂市和温彻斯特的非建制地区，而并未真的进入拉斯维加斯市的范围内。系统由拉斯维加斯单轨列车公司（Las Vegas Monorail Company）拥有并负责营运。由于单轨系统属于公众服务，因此该公司在内华达州的法律许可下注册为非营利组织。内华达州政府以债券方式提供资助，除此之外建设过程中并无任何公共财政的支出。"
    },
    "reference": "https://en.m.wikipedia.org/wiki/Las_Vegas_Monorail",
    "justification": "New template of Las Vegas"
}</details>

<details repo="rmp-gallery" type="real_world" compress="none" city="lasvegas">{"svgViewBoxZoom":70,"svgViewBoxMin":{"x":102.28066732974973,"y":-65.7717996352988},"graph":{"options":{"type":"directed","multi":true,"allowSelfLoops":true},"attributes":{},"nodes":[{"key":"stn_tMifPpWKSV","attributes":{"visible":true,"zIndex":0,"x":170,"y":360,"type":"mtr","mtr":{"names":["美高梅大酒店","MGM Grand"],"nameOffsetX":"left","nameOffsetY":"middle","rotate":0,"transfer":[[]]}}},{"key":"stn_s0h8t1Go8j","attributes":{"visible":true,"zIndex":0,"x":170,"y":250,"type":"mtr","mtr":{"names":["馬蹄灣與巴黎","Horseshoe &amp; Paris"],"nameOffsetX":"left","nameOffsetY":"middle","rotate":0,"transfer":[[]]}}},{"key":"stn_CTNLWnuVvd","attributes":{"visible":true,"zIndex":0,"x":170,"y":215,"type":"mtr","mtr":{"names":["火鶴與凱撒宮","Flamingo &amp; Caesars Palace"],"nameOffsetX":"left","nameOffsetY":"middle","rotate":0,"transfer":[[]]}}},{"key":"stn_nVqnl77DvR","attributes":{"visible":true,"zIndex":0,"x":170,"y":180,"type":"mtr","mtr":{"names":["哈拉斯與林尼克","Harrah's &amp; The Linq"],"nameOffsetX":"left","nameOffsetY":"middle","rotate":0,"transfer":[[]]}}},{"key":"misc_node_rFYV2TCo-4","attributes":{"visible":true,"zIndex":0,"x":225,"y":155,"type":"virtual","virtual":{}}},{"key":"stn_Guu2HKstFg","attributes":{"visible":true,"zIndex":0,"x":290,"y":75,"type":"mtr","mtr":{"names":["會展中心","Convention Center"],"nameOffsetX":"right","nameOffsetY":"middle","rotate":0,"transfer":[[]]}}},{"key":"stn_Nens5X4ZGU","attributes":{"visible":true,"zIndex":0,"x":290,"y":10,"type":"mtr","mtr":{"names":["西門","Westgate"],"nameOffsetX":"right","nameOffsetY":"middle","rotate":0,"transfer":[[]]}}},{"key":"stn_27q8-1VDSw","attributes":{"visible":true,"zIndex":0,"x":290,"y":-40,"type":"mtr","mtr":{"names":["撒哈拉","Sahara"],"nameOffsetX":"right","nameOffsetY":"middle","rotate":0,"transfer":[[]]}}}],"edges":[{"key":"line_WJBmffSKyz","source":"stn_tMifPpWKSV","target":"stn_s0h8t1Go8j","attributes":{"visible":true,"zIndex":0,"type":"perpendicular","perpendicular":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":18.33},"style":"single-color","single-color":{"color":["other","other","#133c8c","#fff"]},"reconcileId":""}},{"key":"line_ERNe00TQQq","source":"stn_s0h8t1Go8j","target":"stn_CTNLWnuVvd","attributes":{"visible":true,"zIndex":0,"type":"perpendicular","perpendicular":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":18.33},"style":"single-color","single-color":{"color":["other","other","#133c8c","#fff"]},"reconcileId":""}},{"key":"line_4DCFrPjvWk","source":"stn_CTNLWnuVvd","target":"stn_nVqnl77DvR","attributes":{"visible":true,"zIndex":0,"type":"perpendicular","perpendicular":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":18.33},"style":"single-color","single-color":{"color":["other","other","#133c8c","#fff"]},"reconcileId":""}},{"key":"line_g5qEgcZvVG","source":"misc_node_rFYV2TCo-4","target":"stn_nVqnl77DvR","attributes":{"visible":true,"zIndex":0,"type":"perpendicular","perpendicular":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":18.33},"style":"single-color","single-color":{"color":["other","other","#133c8c","#fff"]},"reconcileId":""}},{"key":"line_cb3VgQ5eeK","source":"misc_node_rFYV2TCo-4","target":"stn_Guu2HKstFg","attributes":{"visible":true,"zIndex":0,"type":"perpendicular","perpendicular":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":18.33},"style":"single-color","single-color":{"color":["other","other","#133c8c","#fff"]},"reconcileId":""}},{"key":"line_Z1DZ0DEwaV","source":"stn_Guu2HKstFg","target":"stn_Nens5X4ZGU","attributes":{"visible":true,"zIndex":0,"type":"perpendicular","perpendicular":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":18.33},"style":"single-color","single-color":{"color":["other","other","#133c8c","#fff"]},"reconcileId":""}},{"key":"line_ArsCMg8rv0","source":"stn_Nens5X4ZGU","target":"stn_27q8-1VDSw","attributes":{"visible":true,"zIndex":0,"type":"perpendicular","perpendicular":{"startFrom":"from","offsetFrom":0,"offsetTo":0,"roundCornerFactor":18.33},"style":"single-color","single-color":{"color":["other","other","#133c8c","#fff"]},"reconcileId":""}}]},"version":31}</details>

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your work is merged and will ba available soon :)
