### ISSUE TITLE
Resources: New work of Kuala Lumpur

### ISSUE THREAD

**Issue by 289toRefractory** [railmapgen/rmp-gallery#1679]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[kualalumpur.txt](https://github.com/user-attachments/files/16640949/kualalumpur.txt)

#1630

**Comment by thekingofcity** [comment]
Thanks for your contribution. Your work is merged and will be available soon :)
