### ISSUE TITLE
Resources: Update work of kualalumpur

### ISSUE THREAD

**Issue by 289toRefractory** [railmapgen/rmp-gallery#1683]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[kualalumpur.txt](https://github.com/user-attachments/files/16644657/kualalumpur.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your work is merged and will be available soon :)
