### ISSUE TITLE
Rongchen Metro

### ISSUE THREAD

**Issue by PJX2024** [railmapgen/rmp-gallery#1692]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**
[rongchen (1).txt](https://github.com/user-attachments/files/16655332/rongchen.1.txt)

**Comment by thekingofcity** [comment]
Hi, do not change the issue title as it will be used internally. Besides, fantasy works require donation before they can be merged. For more information, see https://afdian.com/a/rail-map-toolkit :)
