### ISSUE TITLE
Resources: New work of Guangdong Intercity

### ISSUE THREAD

**Issue by CommandBlocktt** [railmapgen/rmp-gallery#1698]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[guangdongintercity.txt](https://github.com/user-attachments/files/16675554/guangdongintercity.txt)

**Comment by 28yfang** [comment]
您好，感谢您的贡献。
经检查，您的作品含有以下问题：
1. 佛山3号线佛山西站站已经开通运营

请在修正后重新提交，并附上本议题编号（#1698）感谢！
