### ISSUE TITLE
Resources: Update work of chongqing

### ISSUE THREAD

**Issue by Todist2022** [railmapgen/rmp-gallery#1714]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[chongqing (1).txt](https://github.com/user-attachments/files/16797881/chongqing.1.txt)

**Comment by 28yfang** [comment]
您好，由于该线路暂未开通，我们不会接受此作品。请在线路开通后再上传。
