### ISSUE TITLE
Resources: Update work of hefei

### ISSUE THREAD

**Issue by HeiyaZhou** [railmapgen/rmp-gallery#1717]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**
[hefei.txt](https://github.com/user-attachments/files/16814351/hefei.txt)
[RMP_HF2024.json](https://github.com/user-attachments/files/16814356/RMP_HF2024.json)

**Comment by 28yfang** [comment]
您好，由于8号线并未开通，官网中的线路图也并没有画出该线路，因此我们不会接受此作品。请在该线路开通之后重新上传。
