### ISSUE TITLE
Donation: New work of tancheng

### ISSUE THREAD

**Issue by microharddemo** [railmapgen/rmp-gallery#1722]
[tancheng (3).txt](https://github.com/user-attachments/files/16918860/tancheng.3.txt)
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution.

As we’re undergoing a major upgrade to the Gallery over the next few weeks, would you like it to be available by late September? We’ll also add an extra month of validity as compensation. :)

Bests,
thekingofcity

**Comment by thekingofcity** [comment]
Hi, thanks for your support! Your work is merged and will be available soon :)
