### ISSUE TITLE
资源：苏州的更新工作

### ISSUE THREAD

**Issue by huo114** [railmapgen/rmp-gallery#1727]
[RMP_1725969659556.json](https://github.com/user-attachments/files/16944901/RMP_1725969659556.json)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Please follow the instructions in the Gallery and post the generated txt file instead of pure json here. Also, do not translate anything.

**Comment by huo114** [comment]
so sorry,wait for me
