### ISSUE TITLE
Donation page

### ISSUE THREAD

**Issue by thekingofcity** [railmapgen/rmp-gallery#173]
Also add some basic fantasy works.

![image](https://github.com/railmapgen/rmp-gallery/assets/3353040/e4744b41-5971-4431-9b4a-8a62eaacb1ef)
![image](https://github.com/railmapgen/rmp-gallery/assets/3353040/f6842136-543e-439a-a0c5-26ad7a27bc3b)

**Comment by 28yfang** [comment]
期待～
