### ISSUE TITLE
Resources: New work of Shanghai Yan-an Road Medium Capacity Transit [Editor Invited]

### ISSUE THREAD

**Issue by lyy0323** [railmapgen/rmp-gallery#1759]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[shanghaiyananroadmediumcapacitytransit (1).txt](https://github.com/user-attachments/files/17059116/shanghaiyananroadmediumcapacitytransit.1.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your work is merged and will be available soon :)
