### ISSUE TITLE
Resources: New work of kyiv

### ISSUE THREAD

**Issue by Respubika** [railmapgen/rmp-gallery#1761]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[kyiv.txt](https://github.com/user-attachments/files/17088359/kyiv.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Reference should be trustworthy websites such as the official website or at least Wikipedia-like :)
