### ISSUE TITLE
Resources: New work of haikou

### ISSUE THREAD

**Issue by DavidOHTWs** [railmapgen/rmp-gallery#1780]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[haikou.txt](https://github.com/user-attachments/files/17161890/haikou.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution, but only lines currently running and open to the public could be added to the Gallery.
