### ISSUE TITLE
Resources: New work of sendaishi

### ISSUE THREAD

**Issue by fvsdh** [railmapgen/rmp-gallery#1790]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[sendaishi.txt](https://github.com/user-attachments/files/17218534/sendaishi.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. However, the update reason should be complete, instead of _New template of_. Another problem is that if you want to include JR lines, their reference should also be included.
