### ISSUE TITLE
Donation: New work of xinyangcity

### ISSUE THREAD

**Issue by KarChan158** [railmapgen/rmp-gallery#1828]
[xinyangcity.txt](https://github.com/user-attachments/files/17354929/xinyangcity.txt)
[RMP_1728806951569.json](https://github.com/user-attachments/files/17354931/RMP_1728806951569.json)
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

**Comment by thekingofcity** [comment]
Hi, fantasy work requires a donation to be published in the Gallery. We couldn't find a record of the date you specified. Would it be possible to reply with your donation date and screenshot?
