### ISSUE TITLE
Resources: Update work of zhengzhou

### ISSUE THREAD

**Issue by YS-110509** [railmapgen/rmp-gallery#1845]
[zhengzhou (3).txt](https://github.com/user-attachments/files/17450608/zhengzhou.3.txt)
I have added three upcoming routes, 7, 8, and 10, to the Zhengzhou route map

**Comment by thekingofcity** [comment]
Hi, do not remove the lines from the template. Only upload the text file at the end of the content so that the bot will create the required changes for the update :)
