### ISSUE TITLE
Donation: New work of xinyangcity

### ISSUE THREAD

**Issue by KarChan158** [railmapgen/rmp-gallery#1846]
https://ifdian.net/a/rail-map-toolkit
[xinyangcity (2).txt](https://github.com/user-attachments/files/17468989/xinyangcity.2.txt)
[RMP_1728806951569.json](https://github.com/user-attachments/files/17468990/RMP_1728806951569.json)
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

**Comment by thekingofcity** [comment]
Hi, thanks for your support and donation! Your work is merged and will available soon :)
