### ISSUE TITLE
Resources: New work of kobe

### ISSUE THREAD

**Issue by a-sussy-impostor** [railmapgen/rmp-gallery#1851]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**
[kobe.txt.json](https://github.com/user-attachments/files/17490470/kobe.txt.json)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your work is merged and will be available soon :)
