### ISSUE TITLE
Resources: Update work of changzhou

### ISSUE THREAD

**Issue by XXc-QAQ** [railmapgen/rmp-gallery#1872]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[changzhou.txt](https://github.com/user-attachments/files/17616406/changzhou.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for the update. However, the updated content requires detailed explanation. Also, the description should only be updated instead of a new one :)
