### ISSUE TITLE
Resources: Update work of shanghai

### ISSUE THREAD

**Issue by CuteDouya** [railmapgen/rmp-gallery#1902]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[shanghai.txt](https://github.com/user-attachments/files/17760679/shanghai.13.txt)

**Comment by 816R** [comment]
您好 本次模板使用的是版本号Z202408所制作的，其中娄山关路被标注为换乘车站。
Number的拼写问题将会马上修复，谢谢反馈！:)

**Comment by thekingofcity** [comment]
Hi, thanks for your update and contribution. Your work is merged and will be available soon :)

**Comment by thekingofcity** [comment]
以防万一，解释一下，仅有拼写错误被修复，因为娄山关路在不同版本中是不同的车站类型，暂不做调整 :)

**Comment by CuteDouya** [comment]
那上海体育馆站的换乘标识在制作的版本中也不是正圆的？

**Comment by 816R** [comment]
还真没注意到。。Z02408也是正圆的
如果你想更新也可以

**Comment by CuteDouya** [comment]
可以等到下次更新时一起更新
