### ISSUE TITLE
Resources: New work of istanbul

### ISSUE THREAD

**Issue by aaronyz2007** [railmapgen/rmp-gallery#1907]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[istanbul.txt](https://github.com/user-attachments/files/17770139/istanbul.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your work is merged and will be available soon :)
