### ISSUE TITLE
Resources: Update work of tianjin

### ISSUE THREAD

**Issue by SHENJIE15** [railmapgen/rmp-gallery#1926]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[tianjin (1).txt](https://github.com/user-attachments/files/17920893/tianjin.1.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your update. Your work is merged and will be available soon :)
