### ISSUE TITLE
Donation: New work of chenjiangcity

### ISSUE THREAD

**Issue by KarChan158** [railmapgen/rmp-gallery#1973]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[chenjiangcity.txt](https://github.com/user-attachments/files/18004776/chenjiangcity.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your support! Your work is merged and will be available soon :)
