### ISSUE TITLE
Resources: Update work of macao

### ISSUE THREAD

**Issue by zs1322** [railmapgen/rmp-gallery#1985]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Macao",
        "zh-Hans": "澳门",
        "zh-Hant": "澳門",
        "pt": "Macau"
    },
    "desc": {
        "en": "Update for Hospital Union Station, Hengqin Station and Seac Pai Van Station"
    },
    "reference": "https://www.mlm.com.mo/tc/taipa_line.html",
    "justification": "Update new stations"
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="macao">{¨svgViewBoxZoom¨¤y¨svgViewBoxMin¨{´x´£-b.-BT´y´£1z.CN}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨mtr¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨¨rotate¨¨transfer¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨right¨¨middle¨|¨海洋¨¨Oceano\\Ocean¨÷É||÷÷ßA»¢4q¢6IÉ¨stn_mp_yBAKHkx¨ßJ¨top¨|¨馬會¨¨Jockey Clube\\Jockey Club¨÷É||÷÷ßA»¢5K¢6mÉ¨stn_IbmsB2w71o¨ßJßK|¨運動場¨¨Estádio\\Stadium¨÷É||÷÷ßA»¢5o¢7BÉ¨stn_tV507VW6cO¨ßJßK|¨排角¨¨Pai Kok\\Pai Kok¨÷É||÷÷ßA»º4¢7fÉ¨stn_imIAv8KACr¨ßJßK|¨路氹西¨¨Cotai Oeste\\Cotai West¨÷É||÷÷ßA»º4¢89É¨stn__UPrxUpeJc¨ßK¨bottom¨|¨蓮花¨¨Lotus\\Lótus¨÷¢1S|||¨macao¨¨taipa¨¨#A4D65E¨¨#fff¨´´þ÷|¨other¨ßi¨#ff0000¨ßh´´þ÷÷÷ßA»º1¢8nÉ¨stn_Xz3jUnHK-X¨ßJßK|¨東亞運¨¨Jogos da Ásia Oriental\\East Asian Games¨÷É||÷÷ßA»¢7Q¢8EÉ¨stn_RRhXuGEzSe¨ßJßK|¨路氹東¨¨Cotai Leste\\Cotai East¨÷É||÷÷ßA»ºA¢7kÉ¨stn_cQPSeFsDuL¨ßJßK|¨科大¨¨UCTM\\MUST¨÷É||÷÷ßA»ºA¢7GÉ¨stn_VaRXP9CAf9¨ßJßK|¨機場¨¨Aeroporto \\Airport¨÷É||÷÷ßA»º7¢6cÉ¨stn_Wbc-0BtGIT¨ßJßK|¨氹仔碼頭¨¨Terminal Marítimo da Taipa\\Taipa Ferry Terminal¨÷É||÷÷ßA»º7¢68É¨stn_jRG7al2w_Q¨—{ßI¨misc_node_fMJcjAWGY0¨ß8{ßG»ßHÉ´x´¢7p´y´¢6wß4¨virtual¨ß11{}}}{ßI¨misc_node_RgUeol94UY¨ß8{ßG»ßHÉ´x´¢4M´y´¢5eß4ß11ß11{}}}{ßI¨stn_gi4FgU8wm8¨ß8{ßG»ßHÉ´x´¢3s´y´¢55ß4ßAßA{ßD|´媽閣´¨Barra\\Barra¨÷ßBßJßCßKßEÉßF||÷÷}}}{ßI¨stn_WEIsa_x9vs¨ß8{ßG»ßHÉ´x´ºH´y´º9ß4ßAßA{ßD|¨協和醫院¨¨Hospital Union\\Union Hospital¨÷ßBßKßCßbßEº8ßF|||ßeßfßgßh´´þ÷|ßiþ¨#af67e0¨ßh´´þ÷÷÷}}}{ßI¨stn_F90nit0b6U¨ß8{ßG»ßHÉ´x´ºA´y´¢9gß4ßAßA{ßD|¨石排灣¨¨Seac Pai Van\\Seac Pai Van¨÷ßBßJßCßKßEÉßF||÷÷}}}{ßI¨stn_nfGNVxBb9_¨ß8{ßG»ßHÉ´x´º2´y´¢8sß4ßAßA{ßD|´橫琴´¨Hengqin\\Hengqin¨÷ßBßKßCßbßEÉßF||÷÷}}}÷¨edges¨|¦ß8¦¨perpendicular¨¦¨offsetFrom¨¨offsetTo¨¨roundCornerFactor¨¨startFrom¨‡¨reconcileId¨¨single-color¨¦¨color¨‡¨style¨ß4ßGßH‡ßI¨source¨¨target¨‡ÉÉ£I.5K´to´´´|ßeßfßgßh÷ß1Lß1F»É¨line_dfQo7_bBTE¨ßNßRÉÉÝ2¨from¨´´|ßeßfßgßh÷ß1Lß1F»É¨line_NoCdP3Uw-P¨ßRßUÉÉÝ2ß1R´´|ßeßfßgßh÷ß1Lß1F»É¨line_SksJ8-BCYa¨ßUßXÉÉÝ2ß1R´´|ßeßfßgßh÷ß1Lß1F»É¨line_ESVWubVMuJ¨ßXßaÉÉÝ2ß1R´´|ßeßfßgßh÷ß1Lß1F»É¨line_kSvBrTEtxM¨ßkßaÉÉÝ2ß1R´´|ßeßfßgßh÷ß1Lß1F»É¨line_m9XP_4V-Rl¨ßnßqÉÉÝ2ß1R´´|ßeßfßgßh÷ß1Lß1F»É¨line_CxvDHte5LE¨ßqßtÉÉÝ2ß1R´´|ßeßfßgßh÷ß1Lß1F»É¨line_-4e57VMzZm¨ß10ßtÉÉÝ2ß1R´´|ßeßfßgßh÷ß1Lß1F»É¨line_NnYDnXWAwO¨ß10ßwÉÉÝ2ß1R´´|ßeßfßgßh÷ß1Lß1F»É¨line_hA_hrsMPeC¨ßwßzÉÉÝ2ß1R´´|ßeßfßgßh÷ß1Lß1F»É¨line_m1q3sW2xr-¨ß12ßNÉÉÝ2´to´´´|ßeßfßgßh÷ß1Lß1F»É¨line_U3bWI2kGf4¨ß13ß12—{ßI¨line_feKZUMT7NW¨ß1Oßkß1Pß15ß8{ßG»ßHÉß4¨diagonal¨ß1e{ß1Jß1Rß1GÉß1HÉß1I¤A}ß1Nß1Lß1L{ß1M|ßeßfßgßh÷}ß1K´´}}{ßI¨line_gjGkdgwbvs¨ß1Oß15ß1Pßnß8{ßG»ßHÉß4ß1Fß1F{ß1Jß1Rß1GÉß1HÉß1IÝ2}ß1Nß1Lß1L{ß1M|ßeßfßgßh÷}ß1K´´}}{ßI¨line_Gm4y-DzyBT¨ß1Oß15ß1Pß19ß8{ßG»ßHÉß4ß1Fß1F{ß1Jß1Rß1GÎß1HÉß1IÝ2}ß1Nß1Lß1L{ß1M|ßiþß18ßh÷}ß1K´´}}{ßI¨line_h986_o6A6l¨ß1Oß1Cß1Pßkß8{ßG»ßHÉß4ß1eß1e{ß1Jß1Rß1GÉß1HÎß1I¤A}ß1Nß1Lß1L{ß1M|ßiþßjßh÷}ß1K´´}}÷}¨version¨¤S}</details>

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. However the update reason should be written in the Justification field.

> Update for Hospital Union Station, Hengqin Station and Seac Pai Van Station
