### ISSUE TITLE
Donation:+New+work+of+rongchen

### ISSUE THREAD

**Issue by PJX2024** [railmapgen/rmp-gallery#1987]
Hi+RMP+team!+I+would+like+to+contribute+to+the+gallery+with+the+data+below.

**Paste+or+Upload+below.+They+are+meant+for+BOTS+ONLY!!!**

**Comment by thekingofcity** [comment]
Hi, upload the text file generated by the Gallery. Also, copy and paste the following lines instead of every space replaced with +.

> Hi RMP team! I would like to contribute to the gallery with the data below.
>
> **Paste or Upload below. They are meant for BOTS ONLY!!!**
