### ISSUE TITLE
Resources: Update work of shanghai

### ISSUE THREAD

**Issue by CuteDouya** [railmapgen/rmp-gallery#2022]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**
[shanghai-2.txt](https://github.com/user-attachments/files/18191288/shanghai-2.txt)

**Comment by CuteDouya** [comment]
要真等下去都不知道下次更新是什么时候了，还是赶紧发出来吧:)

**Comment by thekingofcity** [comment]
嗨，感谢您的贡献。您的作品已被合并并即将在所有平台可用 :)
