### ISSUE TITLE
Resources: Update work of qingdao

### ISSUE THREAD

**Issue by Zongyu1007** [railmapgen/rmp-gallery#2030]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[qingdao (1).txt](https://github.com/user-attachments/files/18210970/qingdao.1.txt)
[RMP_1734531778809.json](https://github.com/user-attachments/files/18210973/RMP_1734531778809.json)

**Comment by thekingofcity** [comment]
Hi, what exactly did you update?

**Comment by Zongyu1007** [comment]
Qingdao Metro Line 2 International Cruise Port Station to Sichuan Road Ferry Station temporarily open sign

**Comment by thekingofcity** [comment]
Hi, as the update details are not correctly stated in the reason field, we're closing and merging #2038
