### ISSUE TITLE
Resources: New template of tianjin

### ISSUE THREAD

**Issue by LittleLing03** [railmapgen/rmp-gallery#205]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[tianjin.txt](https://github.com/railmapgen/rmp-gallery/files/11619610/tianjin.txt)

**Comment by 52PD** [comment]
您好，经检查我们发现以下问题：

- 4号线和平路站到徐州道站这里的斜线坡度明显不是45°啊
![Screenshot 2023-06-06 at 11 24 01 PM](https://github.com/railmapgen/rmp-gallery/assets/98044618/1b50dd9d-5277-49ad-9935-46f3ed1f2a23)
- 5号线直沽站到津塘路这段经典对不齐🌝
![Screenshot 2023-06-06 at 11 17 14 PM](https://github.com/railmapgen/rmp-gallery/assets/98044618/55f97338-b477-441d-b65b-40773b683a8e)

请在修正上述问题后重新开启一个新的Issue，并在新Issue中附上本Issue的编号（#205 ），感谢您的支持。

然后以下是一个建议：在检查时我注意到您的部分站间距出现了过大或过小的问题，虽然这并不是必须修改的问题，但在考虑到美观性上还是希望以后的投稿中多注意一下这个问题，谢谢。
