### ISSUE TITLE
Resources: New work of shaogan

### ISSUE THREAD

**Issue by TZYloui** [railmapgen/rmp-gallery#2051]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[shaogan.txt](https://github.com/user-attachments/files/18245710/shaogan.txt)

**Comment by thekingofcity** [comment]
嗨，幻想作品欢迎捐赠后提交在幻想世界下 :)
