### ISSUE TITLE
Resources: New template of wuhan

### ISSUE THREAD

**Issue by nmwdzs** [railmapgen/rmp-gallery#213]
[Hi]() RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

**Comment by 52PD** [comment]
您好，非常抱歉由于您并未通过https://railmapgen.github.io/?app=rmp-gallery 将您所制作的线路图源代码文件进行上传，因此很抱歉我们没办法将您的线路图汇入到项目中。
