### ISSUE TITLE
Resources: New template of shenzhen

### ISSUE THREAD

**Issue by wwj2006** [railmapgen/rmp-gallery#214]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

![RMP_1685770640996](https://github.com/railmapgen/rmp-gallery/assets/135408518/8c225fa2-f1de-4b49-a0c9-ff7e13528767)

**Comment by wwj2006** [comment]
![Shenzhen Subway](https://github.com/railmapgen/rmp-gallery/assets/135408518/358c1c05-60a4-4b99-8b56-f55cca94c4b0)
Hi, I am a Chinese and a beginner of Github, I made a self-made map of the Shenzhen subway by Github with reference to the attached picture. Hope you like it. (I'm sorry that Line 13 is not put in the map since it is not open yet)

**Comment by 52PD** [comment]
您好，非常抱歉由于您并未通过https://railmapgen.github.io/?app=rmp-gallery 将您所制作的线路图源代码文件进行上传，因此很抱歉我们没办法将您的线路图汇入到项目中。
