### ISSUE TITLE
Resources: New template of taipei

### ISSUE THREAD

**Issue by LittleLing03** [railmapgen/rmp-gallery#231]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[taipei.txt](https://github.com/railmapgen/rmp-gallery/files/11651200/taipei.txt)

**Comment by Windows-Taskmgr** [comment]
您好，您提交的模板包括但不限于以下问题：
- 建议调整“双连”站站名位置
您的：
<img width="159" alt="截屏2023-06-06 20 23 51" src="https://github.com/railmapgen/rmp-gallery/assets/99594702/6c133b6d-e576-46a1-bff8-e581b0423d56">

- “台北车站”站应放置火车站标识
您的：
<img width="307" alt="截屏2023-06-06 20 24 55" src="https://github.com/railmapgen/rmp-gallery/assets/99594702/da77d205-a0d1-4585-8656-6736da64f013">

正确的：
<img width="133" alt="截屏2023-06-06 20 25 18" src="https://github.com/railmapgen/rmp-gallery/assets/99594702/f0d897cb-a971-4ed2-8667-e8b93be060ed">

- 线路标识建议使用“广州地铁线路标识”
您的：
<img width="114" alt="截屏2023-06-06 21 49 03" src="https://github.com/railmapgen/rmp-gallery/assets/99594702/ca197b5a-8809-42cf-8719-c82b41e00197">

- 建议调整“昆阳”站至“永春”站的线段
您的：
<img width="460" alt="截屏2023-06-06 21 50 08" src="https://github.com/railmapgen/rmp-gallery/assets/99594702/e103b294-bb02-4a82-bbaf-49eb17cd6895">

- 建议调整“大桥头”站站名位置
您的：
<img width="179" alt="截屏2023-06-06 21 57 29" src="https://github.com/railmapgen/rmp-gallery/assets/99594702/2fe24b4a-909b-4574-830c-30fe741e7435">

- 建议加入河流（官方图上有）
- “To Huanbei”的“H”应大写
您的：
<img width="357" alt="截屏2023-06-06 22 03 26" src="https://github.com/railmapgen/rmp-gallery/assets/99594702/d3cde14a-6b3c-43bc-9885-01d2511f31f7">

正确的：
<img width="86" alt="截屏2023-06-06 22 04 11" src="https://github.com/railmapgen/rmp-gallery/assets/99594702/c8ddca10-04fd-45a9-9dd4-4156bbbbcb49">

- “猫空站”站后应有线路标识
您的：
<img width="304" alt="截屏2023-06-06 22 07 08" src="https://github.com/railmapgen/rmp-gallery/assets/99594702/2cead69c-e948-48c2-bb30-526f446aa469">

正确的：
<img width="308" alt="截屏2023-06-06 22 07 14" src="https://github.com/railmapgen/rmp-gallery/assets/99594702/a4d7a08e-4e06-4c00-a118-38a443fe2321">

_（如您有异议，请留下您的证明来源）_
请修正后重新提交，感谢您的贡献。

**Comment by 28yfang** [comment]
请关闭#232
