### ISSUE TITLE
Resources: New template of guiyang

### ISSUE THREAD

**Issue by LittleLing03** [railmapgen/rmp-gallery#233]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[guiyang.txt](https://github.com/railmapgen/rmp-gallery/files/11652434/guiyang.txt)

**Comment by 28yfang** [comment]
您好，您的模版包含但不限于以下问题：
1. 贵阳北站英文名错误
您的：
![image](https://github.com/railmapgen/rmp-gallery/assets/123239445/330e1c2f-c2bb-44cf-9a7d-d57889c7dfe8)
正确的：
![image](https://github.com/railmapgen/rmp-gallery/assets/123239445/23fbc24a-0518-4f39-b221-9f432712592f)

2. 龙洞堡机场站应有相关火车站标识：
![image](https://github.com/railmapgen/rmp-gallery/assets/123239445/e923be4d-23bb-45e8-b22f-f97d5faa557c)

3. 图中含有河流，非常建议您加入！
![image](https://github.com/railmapgen/rmp-gallery/assets/123239445/ac0199fe-7758-4d26-ba13-d113134bc1f8)

请您修改后重新提交，感谢！
审核来源：维基百科（https://upload.wikimedia.org/wikipedia/commons/e/e1/Guiyang_Urban_Rail_Transit_Map.png）
![image](https://github.com/railmapgen/rmp-gallery/assets/123239445/d36cec40-e738-442a-bc72-417fa2a2e6c7)

**Comment by 52PD** [comment]
Closed issue as the fixed version updated in #237 .
