### ISSUE TITLE
Resources: New template of guiyang

### ISSUE THREAD

**Issue by LittleLing03** [railmapgen/rmp-gallery#237]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[guiyang (1).txt](https://github.com/railmapgen/rmp-gallery/files/11663254/guiyang.1.txt)

**Comment by 28yfang** [comment]
您好，在此感谢您的贡献。
在此有一处建议：
由于线路图中有河流，建议您添加河流样式，并标注河流的中英文名。
![image](https://github.com/railmapgen/rmp-gallery/assets/123239445/eb1fc377-dd48-467f-8d86-b9e35bbdf3a6)
由于您已经修复了#233中所提出的问题，并且线路图已达到汇入标准，您可以选择不采纳此建议直接汇入。
感谢您对RMT项目的支持！
PS. 请管理者关闭#233 #234.
