### ISSUE TITLE
Resources: New template of taipei

### ISSUE THREAD

**Issue by LittleLing03** [railmapgen/rmp-gallery#243]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[taipei (1).txt](https://github.com/railmapgen/rmp-gallery/files/11675308/taipei.1.txt)

**Comment by langonginc** [comment]
您好，感谢你的贡献，但仍存在如下问题：

**大量线段未使用 45/135 度或未对齐**

<img width="344" alt="image" src="https://github.com/railmapgen/rmp-gallery/assets/59787082/6ff821e6-aff0-4d93-b040-bcc282857231">

<img width="385" alt="image" src="https://github.com/railmapgen/rmp-gallery/assets/59787082/24f7204d-a007-4014-826a-027ae36afec5">
<img width="247" alt="image" src="https://github.com/railmapgen/rmp-gallery/assets/59787082/f20cf74a-61af-427f-b4f3-008ebf5914d9">

<img width="260" alt="image" src="https://github.com/railmapgen/rmp-gallery/assets/59787082/547f6273-992b-4b0f-8dfa-9695689af146">

我们同时建议您修改站距维持其美观性。

请您修改后重新提交并附上本issue的编号 `#243` 感谢。
