### ISSUE TITLE
Resources: New template of pyeongyang

### ISSUE THREAD

**Issue by aaronyz2007** [railmapgen/rmp-gallery#255]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Pyeongyang",
        "zh-CN": "平壤",
        "zh-Hant": "平壤",
        "ko": "평양"
    },
    "desc": {
        "en": ""
    },
    "reference": "wikipedia.com",
    "justification": "pyeongyang metro template"
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="pyeongyang">{¨svgViewBoxZoom¨¤y¨svgViewBoxMin¨{´x´£-29.-3B´y´£-1k.-8n}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨shmetro-basic¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨right¨¨middle¨|¨红星¨¨붉은별¨÷ßA»¢4v¢-yÉ¨stn_8L4W5FMSwY¨ßI¨top¨|¨三兴¨¨삼흥¨÷ßA»¢6I¤UÉ¨stn_JipoH5J3r_¨ßIßM|¨革新¨¨혁신¨÷ßA»¢3O¤UÉ¨stn_Oka6hwsncY¨ßIßM|¨复兴¨¨부흥¨÷ßA»¢1r¢7kÉ¨stn_VcpDfuxF96¨ßIßM|¨荣光¨¨영광¨÷ßA»¢3Eº5É¨stn_rJDA6LnC6d¨ßHßI|¨烽火¨¨봉화¨÷ßA»º0º2É¨stn_L8onX7-YUv¨ßHßI|¨胜利¨ßK÷ßA»º0¢4qÉ¨stn_zUycY7w4qa¨ßHßI|¨统一¨¨통일¨÷ßA»º0º3É¨stn_9DXa2D8aNt¨ßHßI|¨凯旋¨¨개선¨÷ßA»º0¢1wÉ¨stn_VVt8lEQUOP¨—{ßG¨stn_jinr3F7I0Z¨ß8{ßE»ßFÉ´x´º0´y´¤Uß4¨shmetro-int¨ßl{ßD|¨战友/战胜¨¨전우 / 전승¨÷ßBßIßCßM¨rotate¨É¨height¨¤A¨width¨¤D}}}{ßG¨misc_node_lVrb2jhPRb¨ß8{ßE»ßFÉ´x´¢9g´y´¤Fß4¨bjsubway-text-line-badge¨ßs{ßD|¨革新线¨¨혁신선¨÷¨color¨|¨other¨ßw¨#008000¨¨#fff¨÷}}}{ßG¨misc_node_wQ7GFfXam3¨ß8{ßE»ßFÉ´x´¤j´y´¢7Vß4ßsßs{ßD|¨千里马线¨¨천리마선¨÷ßv|¨beijing¨¨bj1¨¨#c23a30¨ßy÷}}}{ßG¨stn_B-aUhfYoVN¨ß8{ßE»ßFÉ´x´º5´y´¤Uß4ßAßA{ßD|¨光明（停运）¨¨광명（폐쇄）¨÷ßBßIßCßM}}}{ßG¨stn_ZGohEUf4vK¨ß8{ßE»ßFÉ´x´¢9C´y´¤Uß4ßAßA{ßD|´乐园´´락원´÷ßBßIßCßM}}}{ßG¨stn_Q2RW4GXbcV¨ß8{ßE»ßFÉ´x´¢2f´y´º8ß4ßAßA{ßD|´建设´´건설´÷ßBßHßCßI}}}{ßG¨stn_fgWiOXBBDu¨ß8{ßE»ßFÉ´x´º1´y´º3ß4ßAßA{ßD|´光复´´광복´÷ßBßIßCßM}}}{ßG¨stn_X_-AxAxtkT¨ß8{ßE»ßFÉ´x´¤U´y´º3ß4ßAßA{ßD|´建国´¨Kŏnguk¨÷ßBßIßCßM}}}{ßG¨stn_UWYdKDyHAD¨ß8{ßE»ßFÉ´x´º8´y´º3ß4ßAßA{ßD|¨黄金谷¨¨황금벌¨÷ßBßIßCßM}}}{ßG¨misc_node_vJt5kgb0sd¨ß8{ßE»ßFÉ´x´¢4U´y´¢-1cß4ßsßs{ßD|ß10ß11÷ßv|ß12ß13ß14ßy÷}}}{ßG¨misc_node_RNCNO2GtoU¨ß8{ßE»ßFÉ´x´¢-1w´y´¢39ß4ßsßs{ßD|ßtßu÷ßv|ßwþßxßy÷}}}{ßG¨misc_node_Swz5UFKicq¨ß8{ßE»ßFÉ´x´¢-1I´y´¢8Yß4¨virtual¨ß1J{}}}{ßG¨misc_node_ZeB5pNkYpw¨ß8{ßE»ßFÉ´x´¢6m´y´ºIß4ß1Jß1J{}}}{ßG¨misc_node_by4CLGTYdo¨ß8{ßE»ßFÉ´x´ºJ´y´¢1Sß4ß1Jß1J{}}}{ßG¨misc_node_N9-KkVVioh¨ß8{ßE»ßFÉ´x´¢Bc´y´ºKß4ß1Jß1J{}}}{ßG¨misc_node_MYNcWFKkqM¨ß8{ßE»ßFÉ´x´ºK´y´ºIß4¨text¨ß1O{¨content¨¨大同江¨¨fontSize¨¤W¨lineHeight¨¤G¨textAnchor¨ßI¨dominantBaseline¨ßI¨language¨´zh´ßv|¨shanghai¨¨jsr¨¨#000000¨ßy÷}}}{ßG¨misc_node__J_l7MojlL¨ß8{ßE»ßFÉ´x´ºJ´y´º3ß4ß1Oß1O{ß1P¨大
同
江
  

대
동
강¨ß1R¤Wß1S¤Wß1TßIß1UßIß1V´zh´ßv|ß1Wß1Xß1Yßy÷}}}{ßG¨misc_node_G9k_MeKzsI¨ß8{ßE»ßFÉ´x´¢3s´y´ºIß4ß1Oß1O{ß1P¨대동강¨ß1R¤Wß1S¤Gß1TßIß1UßIß1V´zh´ßv|ß1Wß1Xß1Yßy÷}}}{ßG¨misc_node_mnEDospcNi¨ß8{ßE»ßFÉ´x´¢8E´y´ºKß4ß1Oß1O{ß1Pß1Qß1R¤Wß1S¤Gß1TßIß1UßIß1V´zh´ßv|ß1Wß1Xß1Yßy÷}}}{ßG¨misc_node_oyfI-ixP6T¨ß8{ßE»ßFÉ´x´¢AA´y´ºKß4ß1Oß1O{ß1Pß1cß1R¤Wß1S¤Gß1TßIß1UßIß1V´zh´ßv|ß1Wß1Xß1Yßy÷}}}÷¨edges¨|¦ß8¦¨reconcileId¨¨simple¨¦¨offset¨‡¨single-color¨¦ßv‡¨style¨ß4ßEßF‡ßG¨source¨¨target¨‡´´É|ß1W¨sh1¨¨#E3002B¨ßy÷ß1jß1h»É¨line_6TJLuCdcPc¨ßLßL´´É|ß1Wß1nß1oßy÷ß1jß1h»É¨line_7popSNbfpe¨ßLßb—{ßG¨line__bhF_t4ZZT¨ß1lßVß1mßYß8{ßE»ßFÉß4¨perpendicular¨ß1s{¨startFrom¨¨from¨¨offsetFrom¨É¨offsetTo¨É¨roundCornerFactor¨£I.5K}ß1kß1jß1j{ßv|ß1Wß1nß1oßy÷}ß1g´´}}{ßG¨line_dw-Er4BbQo¨ß1lßYß1mßbß8{ßE»ßFÉß4ß1sß1s{ß1tß1uß1vÉß1wÉß1xÝ2}ß1kß1jß1j{ßv|ß1Wß1nß1oßy÷}ß1g´´}}{ßG¨line_BNKNHGbtXj¨ß1lß1Aß1mß1Dß8{ßE»ßFÉß4ß1hß1h{ß1iÉ}ß1kß1jß1j{ßv|ßwþßxßy÷}ß1g´´}}{ßG¨line_RrPsyg9lfw¨ß1lß1Dß1mß19ß8{ßE»ßFÉß4ß1sß1s{ß1tß1uß1vÉß1wÉß1xÝ2}ß1kß1jß1j{ßv|ßwþßxßy÷}ß1g´´}}{ßG¨line_5jB3ix4Yal¨ß1lßSß1mß19ß8{ßE»ßFÉß4ß1sß1s{ß1tß1uß1vÉß1wÉß1xÝ2}ß1kß1jß1j{ßv|ßwþßxßy÷}ß1g´´}}{ßG¨line_0fIzRV4Rce¨ß1lßSß1mß18ß8{ßE»ßFÉß4ß1hß1h{ß1iÉ}ß1kß1jß1j{ßv|ßwþßxßy÷}ß1g´´}}{ßG¨line_M3WMHE_sbF¨ß1lß1Mß1mß1Mß8{ßE»ßFÉß4ß1hß1h{ß1iÉ}ß1kß1jß1j{ßv|ß1Wß1nß1oßy÷}ß1g´´}}{ßG¨line_Mv3LtNgVYt¨ß1lß1Mß1mß1Lß8{ßE»ßFÄß4ß1hß1h{ß1iÉ}ß1k¨river¨ß1g´´ß25{ßv|ß1Wß25¨#9EE3F9¨ßy÷ßq¤e}}}{ßG¨line_iGPGs9WBle¨ß1lß1Lß1mß1Kß8{ßE»ßFÄß4ß1hß1h{ß1iÉ}ß1kß25ß1g´´ß25{ßv|ß1Wß25ß26ßy÷ßq¤e}}}{ßG¨line_HzoJewaRXd¨ß1lß1Iß1mß1Kß8{ßE»ßFÄß4ß1hß1h{ß1iÉ}ß1kß25ß1g´´ß25{ßv|ß1Wß25ß26ßy÷ßq¤e}}}÷}¨version¨¤B}</details>

**Comment by langonginc** [comment]
您好，经检查，您提交的内容存在如下问题：

1. 请使用对应的颜色，建议您提交palette调色板，您在千里马线使用了上海1号线的颜色，而且标签使用的是北京地铁1号线/八通线的颜色；革新线的颜色也并不正确。

请您修改后重新提交并附上本issue的编号 `#255` ，感谢您的贡献。
