### ISSUE TITLE
Resources: New template of pyongyang

### ISSUE THREAD

**Issue by coxine** [railmapgen/rmp-gallery#257]
Hi RMP team! I would like to contribute to the gallery with the data below.

注：根据开发者在 https://github.com/railmapgen/rmp-gallery/issues/255 中的建议，做出了相应的改进

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Pyongyang",
        "zh-CN": "平壤",
        "ko": "평양"
    },
    "desc": {
        "en": ""
    },
    "reference": "https://zh.wikipedia.org/wiki/%E5%B9%B3%E5%A3%A4%E5%9C%B0%E9%90%B5",
    "justification": "Pyongyang metro template"
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="pyongyang">{¨svgViewBoxZoom¨¢2N¨svgViewBoxMin¨{´x´£-Bh.-3N´y´£-6P.-9f}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨shmetro-basic¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨right¨¨middle¨|¨红星¨¨붉은별¨÷ßA»¢4v¢-yÉ¨stn_8L4W5FMSwY¨ßI¨top¨|¨三兴¨¨삼흥¨÷ßA»¢6I¤UÉ¨stn_JipoH5J3r_¨ßIßM|¨革新¨¨혁신¨÷ßA»¢3O¤UÉ¨stn_Oka6hwsncY¨ßIßM|¨复兴¨¨부흥¨÷ßA»¢1r¢7kÉ¨stn_VcpDfuxF96¨ßIßM|¨荣光¨¨영광¨÷ßA»¢3Eº6É¨stn_rJDA6LnC6d¨ßHßI|¨烽火¨¨봉화¨÷ßA»º1º3É¨stn_L8onX7-YUv¨ßHßI|¨胜利¨ßK÷ßA»º1¢4qÉ¨stn_zUycY7w4qa¨ßHßI|¨统一¨¨통일¨÷ßA»º1º4É¨stn_9DXa2D8aNt¨ßHßI|¨凯旋¨¨개선¨÷ßA»º1¢1wÉ¨stn_VVt8lEQUOP¨—{ßG¨stn_jinr3F7I0Z¨ß8{ßE»ßFÉ´x´º1´y´¤Uß4¨shmetro-int¨ßl{ßD|¨战友/战胜¨¨전우 / 전승¨÷ßBßIßCßM¨rotate¨É¨height¨¤A¨width¨¤D}}}{ßG¨misc_node_lVrb2jhPRb¨ß8{ßE»ßFÉ´x´¢9g´y´¤Fß4¨bjsubway-text-line-badge¨ßs{ßD|¨革新线¨¨혁신선¨÷¨color¨|¨pyongyang¨¨hyeoksin¨¨#00ff00¨¨#fff¨÷}}}{ßG¨misc_node_wQ7GFfXam3¨ß8{ßE»ßFÉ´x´¤j´y´¢7Vß4ßsßs{ßD|¨千里马线¨¨천리마선¨÷ßv|ßw¨chollima¨¨#ff0000¨ßz÷}}}{ßG¨stn_B-aUhfYoVN¨ß8{ßE»ßFÉ´x´º6´y´¤Uß4ßAßA{ßD|¨光明（停运）¨¨광명（폐쇄）¨÷ßBßIßCßM}}}{ßG¨stn_ZGohEUf4vK¨ß8{ßE»ßFÉ´x´¢9C´y´¤Uß4ßAßA{ßD|´乐园´´락원´÷ßBßIßCßM}}}{ßG¨stn_Q2RW4GXbcV¨ß8{ßE»ßFÉ´x´¢2f´y´º9ß4ßAßA{ßD|´建设´´건설´÷ßBßHßCßI}}}{ßG¨stn_fgWiOXBBDu¨ß8{ßE»ßFÉ´x´º2´y´º4ß4ßAßA{ßD|´光复´´광복´÷ßBßIßCßM}}}{ßG¨stn_X_-AxAxtkT¨ß8{ßE»ßFÉ´x´¤U´y´º4ß4ßAßA{ßD|´建国´´건국´÷ßBßIßCßM}}}{ßG¨stn_UWYdKDyHAD¨ß8{ßE»ßFÉ´x´º9´y´º4ß4ßAßA{ßD|¨黄金谷¨¨황금벌¨÷ßBßIßCßM}}}{ßG¨misc_node_vJt5kgb0sd¨ß8{ßE»ßFÉ´x´¢4U´y´¢-1cß4ßsßs{ßD|ß11ß12÷ßv|ßwß13ß14ßz÷}}}{ßG¨misc_node_RNCNO2GtoU¨ß8{ßE»ßFÉ´x´¢-1w´y´¢39ß4ßsßs{ßD|ßtßu÷ßv|ßwßxßyßz÷}}}{ßG¨misc_node_Swz5UFKicq¨ß8{ßE»ßFÉ´x´¢-1I´y´¢8Yß4¨virtual¨ß1I{}}}{ßG¨misc_node_ZeB5pNkYpw¨ß8{ßE»ßFÉ´x´¢6m´y´ºJß4ß1Iß1I{}}}{ßG¨misc_node_by4CLGTYdo¨ß8{ßE»ßFÉ´x´ºK´y´¢1Sß4ß1Iß1I{}}}{ßG¨misc_node_N9-KkVVioh¨ß8{ßE»ßFÉ´x´¢Bc´y´ºLß4ß1Iß1I{}}}{ßG¨misc_node_MYNcWFKkqM¨ß8{ßE»ßFÉ´x´ºL´y´ºJß4¨text¨ß1N{¨content¨¨大同江¨¨fontSize¨¤W¨lineHeight¨¤G¨textAnchor¨ßI¨dominantBaseline¨ßI¨language¨´zh´ßv|¨shanghai¨¨jsr¨¨#000000¨ßz÷}}}{ßG¨misc_node__J_l7MojlL¨ß8{ßE»ßFÉ´x´ºK´y´º4ß4ß1Nß1N{ß1O¨大
同
江
  

대
동
강¨ß1Q¤Wß1R¤Wß1SßIß1TßIß1U´zh´ßv|ß1Vß1Wß1Xßz÷}}}{ßG¨misc_node_G9k_MeKzsI¨ß8{ßE»ßFÉ´x´¢3s´y´ºJß4ß1Nß1N{ß1O¨대동강¨ß1Q¤Wß1R¤Gß1SßIß1TßIß1U´zh´ßv|ß1Vß1Wß1Xßz÷}}}{ßG¨misc_node_mnEDospcNi¨ß8{ßE»ßFÉ´x´¢8E´y´ºLß4ß1Nß1N{ß1Oß1Pß1Q¤Wß1R¤Gß1SßIß1TßIß1U´zh´ßv|ß1Vß1Wß1Xßz÷}}}{ßG¨misc_node_oyfI-ixP6T¨ß8{ßE»ßFÉ´x´¢AA´y´ºLß4ß1Nß1N{ß1Oß1bß1Q¤Wß1R¤Gß1SßIß1TßIß1U´zh´ßv|ß1Vß1Wß1Xßz÷}}}÷¨edges¨|¦ß8¦¨reconcileId¨¨simple¨¦¨offset¨‡¨single-color¨¦ßv‡¨style¨ß4ßEßF‡ßG¨source¨¨target¨‡´´É|ß1V¨sh1¨¨#E3002B¨ßz÷ß1iß1g»É¨line_6TJLuCdcPc¨ßLßL´´É|ßwß13ß14ßz÷ß1iß1g»É¨line_7popSNbfpe¨ßLßb—{ßG¨line__bhF_t4ZZT¨ß1kßVß1lßYß8{ßE»ßFÉß4¨perpendicular¨ß1r{¨startFrom¨¨from¨¨offsetFrom¨É¨offsetTo¨É¨roundCornerFactor¨£I.5K}ß1jß1iß1i{ßv|ßwß13ß14ßz÷}ß1f´´}}{ßG¨line_dw-Er4BbQo¨ß1kßYß1lßbß8{ßE»ßFÉß4ß1rß1r{ß1sß1tß1uÉß1vÉß1wÝ2}ß1jß1iß1i{ßv|ßwß13ß14ßz÷}ß1f´´}}{ßG¨line_BNKNHGbtXj¨ß1kß1Aß1lß1Cß8{ßE»ßFÉß4ß1gß1g{ß1hÉ}ß1jß1iß1i{ßv|ßwßxßyßz÷}ß1f´´}}{ßG¨line_RrPsyg9lfw¨ß1kß1Cß1lß19ß8{ßE»ßFÉß4ß1rß1r{ß1sß1tß1uÉß1vÉß1wÝ2}ß1jß1iß1i{ßv|ßwßxßyßz÷}ß1f´´}}{ßG¨line_5jB3ix4Yal¨ß1kßSß1lß19ß8{ßE»ßFÉß4ß1rß1r{ß1sß1tß1uÉß1vÉß1wÝ2}ß1jß1iß1i{ßv|ßwßxßyßz÷}ß1f´´}}{ßG¨line_0fIzRV4Rce¨ß1kßSß1lß18ß8{ßE»ßFÉß4ß1gß1g{ß1hÉ}ß1jß1iß1i{ßv|ßwßxßyßz÷}ß1f´´}}{ßG¨line_M3WMHE_sbF¨ß1kß1Lß1lß1Lß8{ßE»ßFÉß4ß1gß1g{ß1hÉ}ß1jß1iß1i{ßv|ß1Vß1mß1nßz÷}ß1f´´}}{ßG¨line_Mv3LtNgVYt¨ß1kß1Lß1lß1Kß8{ßE»ßFÄß4ß1gß1g{ß1hÉ}ß1j¨river¨ß1f´´ß24{ßv|ß1Vß24¨#9EE3F9¨ßz÷ßq¤e}}}{ßG¨line_iGPGs9WBle¨ß1kß1Kß1lß1Jß8{ßE»ßFÄß4ß1gß1g{ß1hÉ}ß1jß24ß1f´´ß24{ßv|ß1Vß24ß25ßz÷ßq¤e}}}{ßG¨line_HzoJewaRXd¨ß1kß1Hß1lß1Jß8{ßE»ßFÄß4ß1gß1g{ß1hÉ}ß1jß24ß1f´´ß24{ßv|ß1Vß24ß25ßz÷ßq¤e}}}÷}¨version¨¤B}</details>

**Comment by langonginc** [comment]
您好，经检查，您提交的内容存在如下问题：

1. 千里马线的胜利站，朝鲜语不恰当

<img width="345" alt="image" src="https://github.com/railmapgen/rmp-gallery/assets/59787082/9fb222df-8e97-4e53-9885-60b3594149d7">
<img width="168" alt="image" src="https://github.com/railmapgen/rmp-gallery/assets/59787082/031439a5-e53a-4deb-be7a-ecb3f061c3e5">

以上内容摘自维基百科，（因为我看不懂朝鲜语）如有疑议，您可以在评论区发送您的来源。

请您在修改后通过 https://railmapgen.github.io/rmp-gallery/new 重新上传新issue，感谢您的贡献！

**Comment by coxine** [comment]
好的，谢谢
新issue：https://github.com/railmapgen/rmp-gallery/issues/259

**Comment by langonginc** [comment]
管理员：需关闭 #257 #258

**Comment by coxine** [comment]
@langonginc 
这个我关了，#258 关不掉
