### ISSUE TITLE
Resources: New template of wuhan

### ISSUE THREAD

**Issue by LittleLing03** [railmapgen/rmp-gallery#261]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[wuhan.txt](https://github.com/railmapgen/rmp-gallery/files/11714767/wuhan.txt)

**Comment by langonginc** [comment]
您好，您提交的内容存在如下问题：

以下若干区间均出现部分线条不直

<img width="341" alt="image" src="https://github.com/railmapgen/rmp-gallery/assets/59787082/1a7ad0b5-ca4c-4d48-b7dd-64985ceb5708">
<img width="240" alt="image" src="https://github.com/railmapgen/rmp-gallery/assets/59787082/a008e2c8-679c-435f-a46b-563827f82e2d">

另外，5号线未使用 调色板/Palette 的颜色，请您调整。

感谢您的贡献，请您修改后重新提交并附上本issue编号 `#261`。
