### ISSUE TITLE
Resources: New template of shenzhenapprovedphase5planning

### ISSUE THREAD

**Issue by masterplasma** [railmapgen/rmp-gallery#263]
Hi RMP team! I would like to contribute to the gallery with the data below.
[shenzhenapprovedphase5planning.txt](https://github.com/railmapgen/rmp-gallery/files/11732479/shenzhenapprovedphase5planning.txt)

**Do not edit lines below, they are meant for bots only!!!**

**Comment by masterplasma** [comment]
目前的版本是在参考的链接基础上做了以下的变化：

①尽量参照Wiki给出的潘通色号调整了各条线路的配色（2号线和13号线给出的颜色差距太小，所以没改）；
②修正了一些既有规划图中的错误站名，并尽量采用了已经存在的英文地名（南山智园-Nanshan I Park）；
③相对参照实际地图修改了线路的走向；
④补充了出站换乘信息（红树湾-红树湾南；通过地铁商业街等换乘的没有计入；）

目前的版本是五期规划的批复版，后续应该会在这张图的基础上做一个运营版的出来，以及尝试结合东莞、惠州乃至广州的数据做个更大的版本吧（望天

**Comment by masterplasma** [comment]
另外在作图的过程中发现了一些编辑器用着不太顺手的地方，这里也提一下建议：

①北京地铁数字线路标识在显示两位数的编号时会过宽，实际上北京地铁的数字标识宽度是一致的；
②港铁的赛马日线路等特殊线路只能通过135°和90°转角选中，且切换时会清空既有的颜色数据，用起来比较麻烦；

总之以上就是用着感觉不太顺手的问题，感谢诸位开发者制作的工具，希望诸位生活顺心！

**Comment by LittleLing03** [comment]
嗨，这应该归类为幻想，并继续关注幻想分类的开放。

**Comment by langonginc** [comment]
> 另外在作图的过程中发现了一些编辑器用着不太顺手的地方，这里也提一下建议：
> 
> ①北京地铁数字线路标识在显示两位数的编号时会过宽，实际上北京地铁的数字标识宽度是一致的；
> ②港铁的赛马日线路等特殊线路只能通过135°和90°转角选中，且切换时会清空既有的颜色数据，用起来比较麻烦；
> 
> 总之以上就是用着感觉不太顺手的问题，感谢诸位开发者制作的工具，希望诸位生活顺心！

嗨，感谢您对项目的支持。

对于您的第一个问题，已经在 https://github.com/railmapgen/rmp/issues/238 中提到过。

第二个问题，切换清空颜色，我这边看稍后是可以修改代码解决的，但可能需要一些时间。

cc @thekingofcity
