### ISSUE TITLE
Resources: New template of nanjing

### ISSUE THREAD

**Issue by YeeHOMO** [railmapgen/rmp-gallery#271]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[nanjing.txt](https://github.com/railmapgen/rmp-gallery/files/11753477/nanjing.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Nanjing is merged and released :)
