### ISSUE TITLE
Resources: New template of macao

### ISSUE THREAD

**Issue by langonginc** [railmapgen/rmp-gallery#275]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Macao",
        "zh-Hans": "澳门",
        "zh-Hant": "澳門"
    },
    "desc": {
        "en": ""
    },
    "reference": "https://www.mlm.com.mo/tc/taipa_line.html",
    "justification": "Add Macao Light Rapid Transit"
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="macao">{¨svgViewBoxZoom¨¤e¨svgViewBoxMin¨{´x´£2p.3E´y´£4B.Cu}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨mtr¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨¨rotate¨¨transfer¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨right¨¨middle¨|¨海洋¨¨Ocean¨÷É||÷÷ßA»¢4q¢6IÉ¨stn_mp_yBAKHkx¨ßJ¨top¨|¨馬會¨¨Jockey Club¨÷É||÷÷ßA»¢5K¢6mÉ¨stn_IbmsB2w71o¨ßJßK|¨運動場¨¨Stadium¨÷É||÷÷ßA»¢5o¢7BÉ¨stn_tV507VW6cO¨ßJßK|¨排角¨¨Pai Kok¨÷É||÷÷ßA»º4¢7fÉ¨stn_imIAv8KACr¨ßJßK|¨路氹西¨¨Cotai West¨÷É||÷÷ßA»º4¢89É¨stn__UPrxUpeJc¨ßK¨bottom¨|¨蓮花口岸¨¨Lotus Checkpoint¨÷É||÷÷ßA»¢6S¢8YÉ¨stn_Xz3jUnHK-X¨ßJßK|¨東亞運¨¨East Asian Games¨÷É||÷÷ßA»¢76º7É¨stn_RRhXuGEzSe¨ßJßK|¨路氹東¨¨Cotai East¨÷É||÷÷ßA»ºAº6É¨stn_cQPSeFsDuL¨ßJßK|¨科大¨¨MUST¨÷É||÷÷ßA»ºAº5É¨stn_VaRXP9CAf9¨ßJßK|¨機場¨¨Airport¨÷É||÷÷ßA»¢7uº8É¨stn_Wbc-0BtGIT¨ßJßK|¨氹仔碼頭¨¨Taipa Ferry Terminal¨÷É||÷÷ßA»ºB¢5yÉ¨stn_jRG7al2w_Q¨—{ßI¨misc_node_fMJcjAWGY0¨ß8{ßG»ßHÉ´x´¢7V´y´º3ß4¨virtual¨ßv{}}}÷¨edges¨|¦ß8¦¨perpendicular¨¦¨offsetFrom¨¨offsetTo¨¨roundCornerFactor¨¨startFrom¨‡¨reconcileId¨¨single-color¨¦¨color¨‡¨style¨ß4ßGßH‡ßI¨source¨¨target¨‡ÉÉ£I.5K´to´´´|¨macao¨¨taipa¨¨#A4D65E¨¨#fff¨÷ß13ßx»É¨line_dfQo7_bBTE¨ßNßRÉÉÝ2¨from¨´´|ß18ß19ß1Aß1B÷ß13ßx»É¨line_NoCdP3Uw-P¨ßRßUÉÉÝ2ß1D´´|ß18ß19ß1Aß1B÷ß13ßx»É¨line_SksJ8-BCYa¨ßUßXÉÉÝ2ß1D´´|ß18ß19ß1Aß1B÷ß13ßx»É¨line_ESVWubVMuJ¨ßXßaÉÉÝ2ß1D´´|ß18ß19ß1Aß1B÷ß13ßx»É¨line_kSvBrTEtxM¨ßeßaÉÉÝ2ß1D´´|ß18ß19ß1Aß1B÷ß13ßx»É¨line_Ym6QJs4CP1¨ßeßhÉÉÝ2ß1D´´|ß18ß19ß1Aß1B÷ß13ßx»É¨line_m9XP_4V-Rl¨ßhßkÉÉÝ2ß1D´´|ß18ß19ß1Aß1B÷ß13ßx»É¨line_CxvDHte5LE¨ßkßnÉÉÝ2ß1D´´|ß18ß19ß1Aß1B÷ß13ßx»É¨line_-4e57VMzZm¨ßußnÉÉÝ2ß1D´´|ß18ß19ß1Aß1B÷ß13ßx»É¨line_NnYDnXWAwO¨ßußqÉÉÝ2ß1D´´|ß18ß19ß1Aß1B÷ß13ßx»É¨line_hA_hrsMPeC¨ßqßt—÷}¨version¨¤B}</details>

**Comment by 28yfang** [comment]
您好，感谢您对画廊的贡献。
您的模版没有任何问题，以下为一些建议：
官方线路图中有葡萄牙语站名，建议加上。
![image](https://github.com/railmapgen/rmp-gallery/assets/123239445/ab99e286-bf2a-4259-ab65-1b0edd507799)
