### ISSUE TITLE
Resources: New template of tianjin

### ISSUE THREAD

**Issue by 123aaazz** [railmapgen/rmp-gallery#279]
[tianjin (1).txt](https://github.com/railmapgen/rmp-gallery/files/11846040/tianjin.1.txt)
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

**Comment by langonginc** [comment]
您好，经检查发现您提交的图与天津官方的图在布局等方面有较大出入，而且我们已经发现更为合适的图加入到了画廊，感谢您的贡献与支持。
