### ISSUE TITLE
Resources: New template of nanjing

### ISSUE THREAD

**Issue by 123aaazz** [railmapgen/rmp-gallery#281]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[nanjing.txt](https://github.com/railmapgen/rmp-gallery/files/11846217/nanjing.txt)

**Comment by 28yfang** [comment]
您好，在此感谢您对画廊的贡献。
经检查，您的模版含有但不限于以下问题：
1. 南京地铁所有车站英文名**均为全大写拼音。**
2. 南京站、南京南站应有相关火车站标识。
3. 禄口机场站应有相关机场标识。
3. 卡子门站错误地使用了换乘车站，请改成单线车站。
![image](https://github.com/railmapgen/rmp-gallery/assets/123239445/a04387b8-96bc-4ddf-85f0-49e4286b37f6)

4. 2号线标识距离线路过远，请调整：
![image](https://github.com/railmapgen/rmp-gallery/assets/123239445/3970ff38-78be-4602-be9f-6f31504d5842)

5. S1线翠屏山站站名位置不美观，请调整至左中位置
![image](https://github.com/railmapgen/rmp-gallery/assets/123239445/32c69daf-0bef-4ad2-8a8b-555609d1b8a2)
