### ISSUE TITLE
Use RmgDebouncedTextbox for description

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp-gallery#283]
<img width="520" alt="Screenshot 2023-06-23 at 17 54 27" src="https://github.com/railmapgen/rmp-gallery/assets/123239445/42e33bc9-0bca-412d-808c-193c5b92407b">

**Comment by Windows-Taskmgr** [comment]
嗨，描述部分可能确实需要较大的框，要不然可能不够
cc @thekingofcity
