### ISSUE TITLE
Resources: New template of suzhou

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp-gallery#288]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[Suzhou.txt](https://github.com/railmapgen/rmp-gallery/files/11856489/Suzhou.txt)

**Comment by thekingofcity** [comment]
您好，经检查我们发现以下问题：

- 11号线正仪站（Zhengyi）错写成了"正义"站（Zhengyi）；
- 无法打开的参考链接，建议改为 http://www.sz-mtr.com/service/guide/map/index_zh.html；
- 使用香港普通车站和换乘车站的理由，苏州换乘站在官网上看为北京样式，普通站亦可用上海普通车站，字体与官网图相符的黑体；

请在修正上述问题后重新开启一个新的Issue，并在新Issue中附上本Issue的编号 #288，感谢您的支持。

**Comment by 28yfang** [comment]
1. OK
2. 这个链接似乎打不开
3. 列车中似乎使用类似于港铁车站样式的车站。另外，若换乘站使用北京样式，单线车站使用上海样式，会出现文字大小不一的问题。
