### ISSUE TITLE
Resources: New template of suzhou

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp-gallery#298]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[Suzhou.txt](https://github.com/railmapgen/rmp-gallery/files/11915521/Suzhou.txt)

**Comment by 28yfang** [comment]
备注：
1. 站名已修复，11号线走向已更改，河流已加全
2. 由于苏州轨道交通列车中使用类型于港铁的车站样式，并且若更改样式需要花费大量时间和精力，因此不对其做出任何改变

**Comment by thekingofcity** [comment]
嗨，感谢您对项目的支持与贡献。此内容已合入并更新于版本 1.3.10 中 :)
