### ISSUE TITLE
Resources: Update template of tianjin

### ISSUE THREAD

**Issue by LittlePpa** [railmapgen/rmp-gallery#302]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[tianjin.txt](https://github.com/railmapgen/rmp-gallery/files/11929676/tianjin.txt)

**Comment by Windows-Taskmgr** [comment]
Hello, there is no problem with the template you submitted, please wait for the administrator to finally import it, thank you for your contribution.
