### ISSUE TITLE
Cannot open upload view in RMT

### ISSUE THREAD

**Issue by wongchito** [railmapgen/rmp-gallery#31]
Pressing '+' button in 'RMP Gallery' hosting in RMT will open 'RMG Templates Upload' incorrectly. 

If the upload view is expected to be opened in the same tab, `runtime.openApp()` should not be used. Instead, `navigate` hook of `react-router-dom` can handle this case properly. 

If the upload view is expected to be opened in another tab (like 'RMG Templates Upload'), the upload view should be registered as a separated app and the `appId` passed to `runtime.openApp()` should be updated. One thing worth noticing is that the upload view must be able to use independently.

**Comment by thekingofcity** [comment]
Hi, thanks for reporting. It is fixed in 1.0.21
