### ISSUE TITLE
Enable duplicate galleries to submit to RMP

### ISSUE THREAD

**Issue by Windows-Taskmgr** [railmapgen/rmp-gallery#310]
RMP Gallery has a very big drawback: if someone else has done a real-world gallery, others can't do it anymore. So I want to make a point: collect the real world that everyone does, so that the gallery that does not let others finish submit it and find that it has been done by others, and the gallery has multiple styles, what a double win!

**Comment by thekingofcity** [comment]
Hi, thanks for this suggestion. I believe maintaining a work that is widely accepted by the majority of people in the real world, while submitting the remaining works in the realm of fantasy, would be appropriate. The work that is widely accepted can be the earliest submission, the most aesthetically pleasing, or the one that best aligns with the official implementation. If the subsequent works do not significantly improve any aspect, then the previous work should be considered. This also follows the convention of determining whether a template update is a major one or not.
