### ISSUE TITLE
Resources: New template of jinan

### ISSUE THREAD

**Issue by YeeHOMO** [railmapgen/rmp-gallery#311]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[jinan.txt](https://github.com/railmapgen/rmp-gallery/files/11954765/jinan.txt)

**Comment by thekingofcity** [comment]
您好，感谢您对画廊的支持与贡献。
经检查，您的模版含有但不限于以下问题：

- 济南西站英文名为JINANXI RAILWAY STATION。
- 济南东站英文名为JINANDONG RAILWAY STATION。
- 济南地铁车站无车站编号，请提供车站的编号来源。

请您修改后通过画廊指引重新打开一个issue并附上本issue号 #311，谢谢！
