### ISSUE TITLE
Resources: New template of hangzhoushaoxinghaining

### ISSUE THREAD

**Issue by HangzhouMetro09024** [railmapgen/rmp-gallery#321]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[hangzhoushaoxinghaining.txt](https://github.com/railmapgen/rmp-gallery/files/11974827/hangzhoushaoxinghaining.txt)

**Comment by thekingofcity** [comment]
您好，感谢您对画廊的支持与贡献。
经检查，您的模版含有但不限于以下问题：

- 5号线博奥路站英文错写为Boao Road，正确为Bo'ao Road。
- 4号线笕桥老街站英文错写为Jianqiao old Street，正确为Jianqiao Old Street。
- 3号线汤家村站尚未开通。
- 9号线红普南路站英文错写为Liubao，正确为South Hongpu Road。

请您修改后通过画廊指引重新打开一个issue并附上本issue号 #321，谢谢！
