### ISSUE TITLE
Resources: New template of qingdao

### ISSUE THREAD

**Issue by Zhengyang-Rd** [railmapgen/rmp-gallery#326]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[qingdao.txt](https://github.com/railmapgen/rmp-gallery/files/11990649/qingdao.txt)

**Comment by thekingofcity** [comment]
嗨，感谢对项目的支持与贡献。经检查您所提交的线路图模版有以下问题：

- 4号线缺少车站海泊河公园。
- 13号线朝阳山站错写为朝阳路站。
- 我们不再接收线段为纯色样式且线段路径为基本线段的作品，请将作品中的所有基本线段路径更新为90°或135°线段。

在您对上述问题进行修改后，请重新通过https://railmapgen.github.io/?app=rmp-gallery 进行上传，并在Issue内回复本Issue的编号（格式为井号“#”加上Issue编号），谢谢。

**Comment by Zhengyang-Rd** [comment]
感谢您花费精力对此模版的纠错，这使我深刻意识到了错误，并对它们进行了修改，希望您能再次对#350进行审查，谢谢。

祝RMP与RMG发展顺利。
