### ISSUE TITLE
Resources: New template of shenzhen

### ISSUE THREAD

**Issue by masterplasma** [railmapgen/rmp-gallery#328]
Hi RMP team! I would like to contribute to the gallery with the data below.

这次上传的版本是（基本）严格遵循深铁官网的运营图版本，以上海地铁的模板绘制的；

按照深铁官方的版本，加上了龙华有轨的略图，并且删去了所有需要通过地下商业街实现的虚拟换乘，仅保留了官方运营图上4号线和10号线的出站换乘提示；
另外根据深铁的版本，保留了尚未开通的13号线，也保留了港铁东铁线的样貌。
之后是尽量把拐角的地方做的好看了一些

最后感谢各位管理的对社区的维护！

**Do not edit lines below, they are meant for bots only!!!**

[shenzhen.txt](https://github.com/railmapgen/rmp-gallery/files/11990910/shenzhen.txt)

**Comment by langonginc** [comment]
非常感谢您的贡献，但是由于深圳模版已经有比您更先一步的贡献者提交并汇入了（详见 #300 ），如果深圳模版存在问题或未更新，您可通过修改该作品继续贡献，再次感谢您的贡献。
