### ISSUE TITLE
Resources: New template of taiyuan

### ISSUE THREAD

**Issue by polygon827** [railmapgen/rmp-gallery#332]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Taiyuan",
        "zh": "太原"
    },
    "desc": {
        "zh-Hans": "太原地铁（Taiyuan Metro），是服务于中国山西省太原市及太原都市圈各地区的城市轨道交通系统，其第一条线路（2号线）于2020年12月26日开通运营，使太原成为中国大陆第39座开通地铁的城市，也是华北地区第5座开通地铁的城市，山西省第1座开通地铁的城市。",
        "en": "Taiyuan Metro is an urban rail transit system serving Taiyuan City in Shanxi Province of China and various regions of Taiyuan Metropolitan Circle. Its first line (Line 2) was put into operation on December 26, 2020, making Taiyuan the 39th city in Chinese Mainland to open a subway, the fifth city in North China and the first city in Shanxi Province to open a subway.",
        "zh-Hant": "太原捷運（Taiyuan Metro），是服務於中國山西省太原市及太原都市圈各地區的城市軌道交通系統，其第一條線路（2號線）於2020年12月26日開通運營，使太原成為中國大陸第39座開通捷運的都市，也是華北地區第5座開通捷運的都市，山西省第1座開通捷運的都市。"
    },
    "reference": "https://www.tymetro.ltd/service/map",
    "justification": "Taiyuan Metro"
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="taiyuan">{¨svgViewBoxZoom¨¢4M¨svgViewBoxMin¨{´x´£-PH.-8T´y´£e.1y}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨bjsubway-basic¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨¨open¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨right¨¨middle¨|¨尖草坪¨¨Jiancaoping¨÷»ßA»¢5K¢1cÉ¨stn_G0ewNfZtKz¨¨left¨ßJ|¨涧河¨¨Jianhe¨÷»ßA»º1¢2aÉ¨stn_T64XarKOMP¨ßIßJ|¨胜利街¨¨ShengliStreet¨÷»ßA»º1¢3TÉ¨stn_vIHUV0-Jyz¨ßNßJ|¨大北门¨¨Dabeimen¨÷»ßA»º1º0É¨stn_xMY2pXFQMf¨ßIßJ|¨缉虎营¨¨Jihuying¨÷»ßA»º1º1É¨stn_3omkAUhdBq¨ßNßJ|¨府西街¨¨FuxiStreet¨÷»ßA»º1¢6IÉ¨stn_fP42Z4CKuO¨ßIßJ|¨开化寺街¨¨KaihuasiStreet¨÷»ßA»º1¢7BÉ¨stn_N8uxRdNAd8¨ßNßJ|¨大南门¨¨Dananmen¨÷»ßA»º1¢89É¨stn_Uu71MB78yG¨ßIßJ|¨体育馆¨¨Tiyuguan¨÷»ßA»º1¢9CÉ¨stn_IrnPVnqa2M¨ßNßJ|¨南内环¨¨Nanneihuan¨÷»ßA»º1¢AAÉ¨stn_oXZrTKbKhd¨ßIßJ|¨王村南街¨¨WangcunSouthStreet¨÷»ßA»º1¢BIÉ¨stn_WhUt-h8bh5¨ßNßJ|¨长风街¨¨ChangfengStreet¨÷»ßA»º1¢CQÉ¨stn_jm5E943b09¨ßIßJ|¨学府街¨¨XuefuStreet¨÷»ßA»º1¢DOÉ¨stn_jROp9BZZ0a¨ßNßJ|¨南中环¨¨Nanzhuonghuan¨÷»ßA»º1¢EMÉ¨stn_nUzGk4KCrO¨ßIßJ|¨晋阳街¨¨JinyangStreet¨÷»ßA»º1¢FFÉ¨stn_RHp5npwG4c¨ßNßJ|¨龙兴街¨¨LongxingStreet¨÷»ßA»º1¢GDÉ¨stn_0HBq_x3g5s¨ßIßJ|¨龙城公园¨¨Longchenggongyuan¨÷»ßA»º1¢H6É¨stn_yJsaZBu8zo¨ßNßJ|´嘉节´¨Jiajie¨÷»ßA»º1¢I4É¨stn_lMInq7Ndor¨ßIßJ|¨电子西街¨¨DianzixiStreet¨÷»ßA»º1¢IxÉ¨stn_Ayie4WZWz2¨ßNßJ|¨康宁街¨¨KangningStreet¨÷»ßA»º1¢JqÉ¨stn_83NgTk_FM4¨ßIßJ|¨通达街¨¨TongdaStreet¨÷»ßA»º1¢KoÉ¨stn_WjvVaIvWy6¨ßNßJ|¨化章西街¨¨HuazhangWestStreet¨÷«ßA»º1¢LmÉ¨stn_ql9301bUyA¨ßIßJ|´西桥´¨Xiqiao¨÷»ßA»º1¢MkÉ¨stn_GVk_gz5UPL¨—{ßH¨misc_node_O6z8gcQQYK¨ß8{ßF»ßGÉ´x´¢50´y´¢NEß4¨bjsubway-num-line-badge¨ß1R{¨num¨Ë¨color¨|¨taiyuan¨´2´¨#b31c21¨¨#fff¨÷}}}{ßH¨misc_node_j6lN774zyh¨ß8{ßF»ßGÉ´x´ºN´y´¤jß4ß1Rß1R{ß1SËß1T|ß1U´2´ß1Vß1W÷}}}{ßH¨misc_node_4EFJGt6J14¨ß8{ßF»ßGÉ´x´¢18´y´Éß4¨virtual¨ß1Z{}}}{ßH¨misc_node_LIumLv5GDa¨ß8{ßF»ßGÉ´x´¢3E´y´º0ß4ß1Zß1Z{}}}{ßH¨misc_node_CX0dP1HhGX¨ß8{ßF»ßGÉ´x´º3´y´º9ß4ß1Zß1Z{}}}{ßH¨misc_node_HDYjvGWbx9¨ß8{ßF»ßGÉ´x´¢34´y´¢DEß4ß1Zß1Z{}}}{ßH¨misc_node_YHLrlwJXyu¨ß8{ßF»ßGÉ´x´¢2k´y´ºHß4ß1Zß1Z{}}}{ßH¨misc_node_jlPxOf63vI¨ß8{ßF»ßGÉ´x´¢1m´y´¢KAß4ß1Zß1Z{}}}{ßH¨misc_node_TqSISRMIqB¨ß8{ßF»ßGÉ´x´¢2Q´y´ºOß4ß1Zß1Z{}}}{ßH¨misc_node_L2v7xp0xbN¨ß8{ßF»ßGÉ´x´¢39´y´¢55ß4¨text¨ß1h{¨content¨¨汾
河¨¨fontSize¨¤P¨lineHeight¨¤U¨textAnchor¨ßJ¨dominantBaseline¨ßJ¨language¨´zh´ß1T|¨shanghai¨¨jsr¨¨#000000¨ß1W÷}}}{ßH¨misc_node_zFCL2_PNo-¨ß8{ßF»ßGÉ´x´¢2p´y´¢Bcß4ß1hß1h{ß1iß1jß1k¤Pß1l¤Uß1mßJß1nßJß1o´zh´ß1T|ß1pß1qß1rß1W÷}}}{ßH¨misc_node_RbnT3kBmrH¨ß8{ßF»ßGÉ´x´¢26´y´¢LXß4ß1hß1h{ß1iß1jß1k¤Pß1l¤Uß1mßJß1nßJß1o´zh´ß1T|ß1pß1qß1rß1W÷}}}{ßH¨misc_node_kN8KcB64aW¨ß8{ßF»ßGÉ´x´¢-Cp´y´¢HVß4ß1Zß1Z{}}}{ßH¨misc_node_JkvpN8WSxH¨ß8{ßF»ßGÉ´x´¢-BD´y´¢Ftß4ß1Zß1Z{}}}{ßH¨misc_node_x7R8Yv9mcw¨ß8{ßF»ßGÉ´x´¢-8s´y´ºeß4ß1Zß1Z{}}}{ßH¨misc_node_c8b8chj6N4¨ß8{ßF»ßGÉ´x´¢-C1´y´¢Grß4ß1Zß1Z{}}}{ßH¨misc_node_Of1j1bO-RA¨ß8{ßF»ßGÉ´x´¢-A0´y´¢GXß4ß1Zß1Z{}}}{ßH¨misc_node_OE3MqonQps¨ß8{ßF»ßGÉ´x´¢-8i´y´ºVß4ß1Zß1Z{}}}{ßH¨misc_node_VHjH76rLyp¨ß8{ßF»ßGÉ´x´¢-Cu´y´¢Keß4ß1Zß1Z{}}}{ßH¨misc_node_FXiz9V16N4¨ß8{ßF»ßGÉ´x´¢-Ck´y´¢MGß4ß1Zß1Z{}}}{ßH¨misc_node_QTtf4ACnAS¨ß8{ßF»ßGÉ´x´¢-8Y´y´¢Lwß4ß1Zß1Z{}}}{ßH¨misc_node_KjXAfK9ZIr¨ß8{ßF»ßGÉ´x´¢-CG´y´¢LIß4ß1Zß1Z{}}}{ßH¨misc_node_vGW7B3gwvK¨ß8{ßF»ßGÉ´x´¢-9C´y´¢L3ß4ß1Zß1Z{}}}{ßH¨misc_node_sl6rbNXl0c¨ß8{ßF»ßGÉ´x´¢-BI´y´ºIß4ß1hß1h{ß1i¨晋阳湖¨ß1k¤Uß1l¤eß1mßJß1nßJß1o¨mtr__en¨ß1T|¨other¨ß28¨#39d7fe¨ß1W÷}}}÷¨edges¨|¦ß8¦¨reconcileId¨¨simple¨¦¨offset¨‡¨single-color¨¦ß1T‡¨style¨ß4ßFßG‡ßH¨source¨¨target¨‡´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_B9VYaJUUWg¨ßMßQ´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_UX53LHAred¨ßQßT´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_MR2A6Rn3z4¨ßTßW´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_FhSr3l3sr4¨ßWßZ´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_7Xlg5xeOHe¨ßZßc´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_Bgnh7-Xj9b¨ßcßf´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_CzFQgg9Qw8¨ßfßi´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_8zvrPDcaRK¨ßißl´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_OCnYcmgVCR¨ßlßo´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_ID8yuwq7Gu¨ßoßr´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_9XhNcLKZST¨ßrßu´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_xu083E_cOY¨ßußx´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_ua2HaABvci¨ßxß10´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_AeYVWdfmNH¨ß10ß13´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_d3a03g5ZtK¨ß13ß16´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_RgOG97PMdR¨ß16ß19´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_WBy_P99dNC¨ß19ß1B´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_BXdMU8LP00¨ß1Bß1E´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line__LXnFLAzdn¨ß1Eß1H´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_zU3x5if1bj¨ß1Hß1K´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_9jxkAq_oST¨ß1Kß1N´´É|ß1U´2´ß1Vß1W÷ß2Eß2C»É¨line_MmJnYaJ8m-¨ß1Nß1P—{ßH¨line_CTWgX2cGvQ¨ß2Gß1Yß2Hß1aß8{ßF»ßGÄß4ß2Cß2C{ß2DÉ}ß2F¨river¨ß2B´´ß2f{ß1T|ß1pß2f¨#9EE3F9¨ß1W÷¨width¨¤U}}}{ßH¨line_1kc8zicP8G¨ß2Gß1aß2Hß1bß8{ßF»ßGÄß4ß2Cß2C{ß2DÉ}ß2Fß2fß2B´´ß2f{ß1T|ß1pß2fß2gß1W÷ß2h¤U}}}{ßH¨line_bXfrwUBduR¨ß2Gß1bß2Hß1cß8{ßF»ßGÄß4ß2Cß2C{ß2DÉ}ß2Fß2fß2B´´ß2f{ß1T|ß1pß2fß2gß1W÷ß2h¤U}}}{ßH¨line_Sq4ydPpM3p¨ß2Gß1cß2Hß1dß8{ßF»ßGÄß4ß2Cß2C{ß2DÉ}ß2Fß2fß2B´´ß2f{ß1T|ß1pß2fß2gß1W÷ß2h¤U}}}{ßH¨line_ToqH-HeI4d¨ß2Gß1dß2Hß1eß8{ßF»ßGÄß4ß2Cß2C{ß2DÉ}ß2Fß2fß2B´´ß2f{ß1T|ß1pß2fß2gß1W÷ß2h¤U}}}{ßH¨line_7beTPbOXTj¨ß2Gß1eß2Hß1fß8{ßF»ßGÄß4ß2Cß2C{ß2DÉ}ß2Fß2fß2B´´ß2f{ß1T|ß1pß2fß2gß1W÷ß2h¤U}}}{ßH¨line_eZCODDM9aR¨ß2Gß1vß2Hß1uß8{ßF»ßGÄß4¨diagonal¨ß2o{¨startFrom¨¨from¨¨offsetFrom¨É¨offsetTo¨É¨roundCornerFactor¨¤A}ß2Fß2fß2B´´ß2f{ß1T|ß1pß2fß2gß1W÷ß2h¤o}}}{ßH¨line_KxOD8KWzL4¨ß2Gß1vß2Hß1wß8{ßF»ßGÄß4ß2oß2o{ß2pß2qß2rÉß2sÉß2t¤A}ß2Fß2fß2B´´ß2f{ß1T|ß1pß2fß2gß1W÷ß2h¤o}}}{ßH¨line_-PCuV-BH0h¨ß2Gß1uß2Hß1wß8{ßF»ßGÄß4ß2Cß2C{ß2DÉ}ß2Fß2fß2B´´ß2f{ß1T|ß1pß2fß2gß1W÷ß2h¤o}}}{ßH¨line_8W3MsiSmYD¨ß2Gß1xß2Hß1yß8{ßF»ßGÄß4ß2Cß2C{ß2DÉ}ß2Fß2fß2B´´ß2f{ß1T|ß1pß2fß2gß1W÷ß2hºP}}}{ßH¨line_kRYhyikVNA¨ß2Gß1wß2Hß1zß8{ßF»ßGÄß4ß2Cß2C{ß2DÉ}ß2Fß2fß2B´´ß2f{ß1T|ß1pß2fß2gß1W÷ß2h¤o}}}{ßH¨line_lcnWoj3xbY¨ß2Gß20ß2Hß1zß8{ßF»ßGÄß4ß2Cß2C{ß2DÉ}ß2Fß2fß2B´´ß2f{ß1T|ß1pß2fß2gß1W÷ß2h¤o}}}{ßH¨line_d_FCwXmJyW¨ß2Gß20ß2Hß21ß8{ßF»ßGÄß4ß2Cß2C{ß2DÉ}ß2Fß2fß2B´´ß2f{ß1T|ß1pß2fß2gß1W÷ß2h¤o}}}{ßH¨line_tUl4exbZQr¨ß2Gß21ß2Hß22ß8{ßF»ßGÄß4ß2Cß2C{ß2DÉ}ß2Fß2fß2B´´ß2f{ß1T|ß1pß2fß2gß1W÷ß2h¤o}}}{ßH¨line_VtkKZHqgh4¨ß2Gß1zß2Hß22ß8{ßF»ßGÄß4ß2Cß2C{ß2DÉ}ß2Fß2fß2B´´ß2f{ß1T|ß1pß2fß2gß1W÷ß2h¤o}}}{ßH¨line_y2qfAsiCU4¨ß2Gß23ß2Hß24ß8{ßF»ßGÄß4ß2Cß2C{ß2DÉ}ß2Fß2fß2B´´ß2f{ß1T|ß1pß2fß2gß1W÷ß2hºP}}}÷}¨version¨¤B}</details>

**Comment by langonginc** [comment]
您好，您的作品稍后将会汇入项目，感谢您的贡献。
