### ISSUE TITLE
Resources: New template of hangzhou

### ISSUE THREAD

**Issue by HangzhouMetro09024** [railmapgen/rmp-gallery#336]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**
[hangzhou.txt](https://github.com/railmapgen/rmp-gallery/files/11997422/hangzhou.txt)

**Comment by thekingofcity** [comment]
Update from #321

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. The data you submitted is now merged and will be displayed in the Gallery soon :)
