### ISSUE TITLE
Resources: New template of jinhua

### ISSUE THREAD

**Issue by HangzhouMetro09024** [railmapgen/rmp-gallery#339]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "zh": "金华",
        "en": "Jinhua"
    },
    "desc": {
        "zh": "金华轨道交通是服务于中国浙江省金华市的城市轨道交通系统，其首条线路金华轨道交通金义东线分别于2022年8月30日及2022年12月28日开通金义段和义东段（首通段）试运营",
        "en": "Jinhua Rail Transit is an urban rail transit system serving Jinhua City, Zhejiang Province, China, and its first line, Jinyi East Rail Transit, opened for trial operation on August 30, 2022 and December 28, 2022 respectively"
    },
    "reference": "https://www.metroman.cn/metro.html?city=jh",
    "justification": "This is the first version"
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="jinhua">{¨svgViewBoxZoom¨¢1w¨svgViewBoxMin¨{´x´£-1Y.-BI´y´£-1j.-6S}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|{¨key¨¨stn_Yo17Zg5UTM¨ß8{¨visible¨»¨zIndex¨É´x´¢8O´y´¢9Cß4¨bjsubway-basic¨ßE{¨names¨|¨金华站¨¨Jinhua Railway Station¨÷¨nameOffsetX¨¨left¨¨nameOffsetY¨¨bottom¨¨open¨»}}}{ßA¨misc_node_u6rjcmoIAb¨ß8{ßC»ßDÉ´x´¢6m´y´¢9Rß4¨text¨ßO{¨content¨¨快车¨¨fontSize¨¤G¨lineHeight¨¤G¨textAnchor¨¨middle¨¨dominantBaseline¨ßU¨language¨¨en¨¨color¨|¨other¨ßZ¨#e53333¨¨#fff¨÷}}}{ßA¨stn_V5ImmIcNIX¨ß8{ßC»ßDÉ´x´¢97´y´¢9vß4ßEßE{ßF|¨双溪西路¨¨West Shuangxi Road¨÷ßIßJßKßLßM»}}}{ßA¨misc_node_Ya1W54rVuf¨ß8{ßC»ßDÉ´x´¢8n´y´¢8xß4¨facilities¨ßg{ß4¨railway¨}}}{ßA¨misc_node_RaObkbSWNe¨ß8{ßC»ßDÉ´x´¢9H´y´º5ß4ßOßO{ßP¨金华¨ßR¤EßS¤GßTßUßVßUßWßXßY|ßZþ¨#ff0000¨ßb÷}}}{ßA¨stn_XLEx_9WZU2¨ß8{ßC»ßDÉ´x´¢AK´y´¢APß4ßEßE{ßF|¨八一南街¨¨South Bayi Street¨÷ßIßUßKßLßM»}}}{ßA¨misc_node_KesqB-Bf22¨ß8{ßC»ßDÉ´x´ºA´y´¢B8ß4ßOßO{ßPßQßR¤GßS¤GßTßUßVßUßWßXßY|ßZþßaßb÷}}}{ßA¨stn_QaKJxC2hF1¨ß8{ßC»ßDÉ´x´¢BI´y´ºBß4ßEßE{ßF|¨万达广场¨¨Wanda Plaza¨÷ßIßUßK¨top¨ßM»}}}{ßA¨misc_node_-rPRPl0Ehx¨ß8{ßC»ßDÉ´x´¢8i´y´¢Bmß4ßOßO{ßP¨婺城
Wucheng¨ßR¤GßS¤GßTßUßVßUßWßXßY|¨shanghai¨¨jsr¨¨#000000¨ßb÷}}}{ßA¨stn_cG9QVQOtKC¨ß8{ßC»ßDÉ´x´¢CG´y´ºBß4ßEßE{ßF|¨大堰河街¨¨Dayanhe Street¨÷ßIßUßKßLßM»}}}{ßA¨stn_JrhrvH_-8v¨ß8{ßC»ßDÉ´x´¢DE´y´ºBß4ßEßE{ßF|¨轨道大厦¨¨Railway Building¨÷ßIßUßKßsßM»}}}{ßA¨stn_Zkwm1kpVaM¨ß8{ßC»ßDÉ´x´¢EC´y´ºBß4ßEßE{ßF|¨金华南站¨¨Jinhuanan Railway Station¨÷ßIßUßKßLßM»}}}{ßA¨misc_node_Q7ZK7N6Gkb¨ß8{ßC»ßDÉ´x´ºI´y´¢9gß4ßgßg{ß4ßh}}}{ßA¨misc_node_W5J_Amk6KV¨ß8{ßC»ßDÉ´x´ºI´y´¢AAß4ßOßO{ßP¨金华南¨ßR¤CßS¤GßTßUßVßUßWßXßY|ßZþßkßb÷}}}{ßA¨stn_8iFH5o7iLf¨ß8{ßC»ßDÉ´x´¢FF´y´¢9qß4ßEßE{ßF|´塘雅´¨Tangya¨÷ßI¨right¨ßKßLßM»}}}{ßA¨stn_nOMwXAawJc¨ß8{ßC»ßDÉ´x´¢Ft´y´º2ß4ßEßE{ßF|¨车辆段¨¨Depot¨÷ßIß1CßKßLßM«}}}{ßA¨stn_ivy884YZj6¨ß8{ßC»ßDÉ´x´¢GX´y´¢8Yß4ßEßE{ßF|¨综保区¨¨Comprehensive Bonded Zone¨÷ßIß1CßKßLßM»}}}{ßA¨stn_ofLC1iXsaA¨ß8{ßC»ßDÉ´x´¢HB´y´¢7uß4ßEßE{ßF|´新区´¨Xinqu¨÷ßIß1CßKßLßM»}}}{ßA¨misc_node_hRv1tc0Etu¨ß8{ßC»ßDÉ´x´¢IJ´y´¢89ß4ßOßO{ßPßQßR¤GßS¤GßTßUßVßUßWßXßY|ßZþßaßb÷}}}{ßA¨stn_r2CUPSL0Ab¨ß8{ßC»ßDÉ´x´¢Hp´y´¢7Gß4ßEßE{ßF|¨东华街¨¨Donghua Street¨÷ßIß1CßKßLßM»}}}{ßA¨stn_OZf__iaaAH¨ß8{ßC»ßDÉ´x´¢IT´y´¢6cß4ßEßE{ßF|´义亭´¨Yiting¨÷ßIß1CßKßLßM»}}}{ßA¨stn_tROMO9cd65¨ß8{ßC»ßDÉ´x´¢J7´y´¢5yß4ßEßE{ßF|´官塘´¨Guantang¨÷ßIß1CßKßLßM»}}}{ßA¨stn_d1E9BAKfbn¨ß8{ßC»ßDÉ´x´¢Jl´y´¢5Kß4ßEßE{ßF|´稠江´¨Choujiang¨÷ßIß1CßKßLßM»}}}{ßA¨stn_SiMYpwgmU4¨ß8{ßC»ßDÉ´x´¢KP´y´¢4gß4ßEßE{ßF|´绣湖´¨Xiuhu¨÷ßIß1CßKßLßM»}}}{ßA¨stn_SvXoLzbum7¨ß8{ßC»ßDÉ´x´¢LX´y´¢4Cß4ßEßE{ßF|´秦塘´¨Qintang¨÷ßIßUßKßsßM»}}}{ßA¨misc_node_Mrx-Z-gK8T¨ß8{ßC»ßDÉ´x´ºe´y´¢3Tß4ßOßO{ßPßQßR¤GßS¤GßTßUßVßUßWßXßY|ßZþßaßb÷}}}{ßA¨stn_5MZ4LOoCVg¨ß8{ßC»ßDÉ´x´ºc´y´¢3iß4ßEßE{ßF|´春晗´¨Chunhan¨÷ßIßJßKßLßM»}}}{ßA¨stn__kwGAemdj8¨ß8{ßC»ßDÉ´x´ºa´y´¢34ß4ßEßE{ßF|´凌云´¨Lingyun¨÷ßIßJßKßLßM»}}}{ßA¨stn_dehDLa2Bjx¨ß8{ßC»ßDÉ´x´ºY´y´¢2Qß4ßEßE{ßF|¨义乌高铁站¨¨Yiwu Railway Station¨÷ßIßJßKßLßM«}}}{ßA¨misc_node_YwZ0ex1AW7¨ß8{ßC»ßDÉ´x´¢Is´y´¢21ß4ßgßg{ß4ßh}}}{ßA¨misc_node_82ir_6uufx¨ß8{ßC»ßDÉ´x´¢IR´y´¢2Dß4ßOßO{ßP´义乌´ßR¤EßS¤GßTßUßVßUßWßXßY|ßZþßkßb÷}}}{ßA¨stn_JkVm1rQ9-3¨ß8{ßC»ßDÉ´x´¢MV´y´ºfß4ßEßE{ßF|¨国际商贸城¨¨International Trade Center¨÷ßIßUßKßLßM»}}}{ßA¨misc_node_QeucAhtb0E¨ß8{ßC»ßDÉ´x´¢Lh´y´¢5Uß4ßOßO{ßP¨义乌
Yiwu¨ßR¤GßS¤GßTßUßVßUßWßXßY|ßvßwßxßb÷}}}{ßA¨stn_TNHG6XAoRX¨ß8{ßC»ßDÉ´x´¢NT´y´ºfß4ßEßE{ßF|¨浙医四院¨¨The Fourth Affiliated Hospital\\Zhejiang University School of Medicine¨÷ßIßUßKßsßM»}}}{ßA¨stn_Qr6TdnP2pz¨ß8{ßC»ßDÉ´x´¢OW´y´¢4bß4ßEßE{ßF|´江东´¨Jiangdong¨÷ßIß1CßKßsßM»}}}{ßA¨stn_SPs2-aKym_¨ß8{ßC»ßDÉ´x´¢PA´y´¢5Fß4ßEßE{ßF|¨木雕城¨¨Woodcarving City¨÷ßIß1CßKßsßM»}}}{ßA¨stn_bXRrlo_2Uq¨ß8{ßC»ßDÉ´x´¢Po´y´¢5tß4ßEßE{ßF|¨歌山路¨¨Geshan Road¨÷ßIß1CßKßsßM»}}}{ßA¨stn_2G2LGVL7UC¨ß8{ßC»ßDÉ´x´¢QS´y´¢6Xß4ßEßE{ßF|¨人民路¨¨Renmin Road¨÷ßIß1CßKßsßM»}}}{ßA¨misc_node_bTvN7fV0dl¨ß8{ßC»ßDÉ´x´¤Ru´y´¤68ß4ßOßO{ßPßQßR¤GßS¤GßTßUßVßUßWßXßY|ßZþßaßb÷}}}{ßA¨stn_hvKbQJITQc¨ß8{ßC»ßDÉ´x´¤R6´y´¤7Bß4ßEßE{ßF|¨会展中心¨¨Conference &amp; Exhibition Center¨÷ßIß1CßKßsßM»}}}{ßA¨stn_2Yh0q-W3ts¨ß8{ßC»ßDÉ´x´¤Rk´y´¤7pß4ßEßE{ßF|¨体育馆¨¨Sports Center¨÷ßIß1CßKßsßM»}}}{ßA¨stn_8DZV8yeGrJ¨ß8{ßC»ßDÉ´x´¤SO´y´¤8Tß4ßEßE{ßF|¨横店高铁站¨¨Hengdian Railway Station¨÷ßIß1CßKßsßM«}}}{ßA¨misc_node_SkGI2J4vN1¨ß8{ßC»ßDÉ´x´¤Rz´y´¤8Jß4ßgßg{ß4ßh}}}{ßA¨misc_node_GKBYLCXUNI¨ß8{ßC»ßDÉ´x´¤RO´y´¤8Vß4ßOßO{ßP¨东阳横店¨ßR¤CßS¤GßTßUßVßUßWßXßY|ßZþ¨#808080¨ßb÷}}}{ßA¨stn_A_qlpuuEKl¨ß8{ßC»ßDÉ´x´¤T2´y´º5ß4ßEßE{ßF|¨明清宫¨¨Ming &amp; Qing Dynasty Palaces¨÷ßIß1CßKßsßM»}}}{ßA¨misc_node_wCFz_Treg5¨ß8{ßC»ßDÉ´x´¤UU´y´ºEß4ßOßO{ßPßQßR¤GßS¤GßTßUßVßUßWßXßY|ßZþßaßb÷}}}{ßA¨misc_node_1KttwyE4cb¨ß8{ßC»ßDÉ´x´¤TC´y´º9ß4¨bjsubway-text-line-badge¨ß2L{ßF|¨金义东线¨¨Jinyidong Line¨÷ßY|ßZþßaßb÷}}}{ßA¨misc_node_-65NbqpyaM¨ß8{ßC»ßDÉ´x´¤JC´y´ºtß4ß2Lß2L{ßF|ß2Mß2N÷ßY|ßZþßaßb÷}}}{ßA¨misc_node_5eK23RsfM8¨ß8{ßC»ßDÉ´x´¤JW´y´º0ß4ß2Lß2L{ßF|ß2Mß2N÷ßY|ßZþßaßb÷}}}{ßA¨misc_node_K8o7WotPrk¨ß8{ßC»ßDÉ´x´¤7L´y´º7ß4ß2Lß2L{ßF|ß2Mß2N÷ßY|ßZþßaßb÷}}}{ßA¨misc_node_fjzQadW3YR¨ß8{ßC»ßDÉ´x´¤QX´y´¤7kß4ßOßO{ßP¨东阳
Dongyang¨ßR¤GßS¤GßTßUßVßUßWßXßY|ßvßwßxßb÷}}}÷¨edges¨|¦ß8¦¨diagonal¨¦¨offsetFrom¨¨offsetTo¨¨roundCornerFactor¨¨startFrom¨‡¨reconcileId¨¨single-color¨¦ßY‡¨style¨ß4ßCßD‡ßA¨source¨¨target¨‡ÉÉ¤A¨from¨´´|ßZþßaßb÷ß2aß2U»É¨line_qN1iz71MwK¨ßBßcÉÉ¤Aß2e´´|ßZþßaßb÷ß2aß2U»É¨line_zcFkv7OaZo¨ßlßcÉÉ¤Aß2e´´|ßZþßaßb÷ß2aß2U»É¨line_qQ8uifrcd7¨ßlßpÉÉ¤Aß2e´´|ßZþßaßb÷ß2aß2U»É¨line_FdBkHSggKz¨ßpßyÉÉ¤Aß2e´´|ßZþßaßb÷ß2aß2U»É¨line_Na2j980_y6¨ßyß11ÉÉ¤Aß2e´´|ßZþßaßb÷ß2aß2U»É¨line_2X81EGOzMQ¨ß11ß14ÉÉ¤Aß2e´´|ßZþßaßb÷ß2aß2U»É¨line_JejlYGBiMa¨ß14ß1AÉÉ¤Aß2e´´|ßZþßaßb÷ß2aß2U»É¨line_AzzUt0sl5_¨ß1Aß1DÉÉ¤Aß2e´´|ßZþßaßb÷ß2aß2U»É¨line_nU0bEdp7yU¨ß1Dß1GÉÉ¤Aß2e´´|ßZþßaßb÷ß2aß2U»É¨line_2xhOUl-dGp¨ß1Gß1JÉÉ¤Aß2e´´|ßZþßaßb÷ß2aß2U»É¨line_Z_40Eg-0sQ¨ß1Jß1MÉÉ¤Aß2e´´|ßZþßaßb÷ß2aß2U»É¨line_fUxsURy3Gh¨ß1Mß1PÉÉ¤Aß2e´´|ßZþßaßb÷ß2aß2U»É¨line_pd7wXygUQ7¨ß1Pß1RÉÉ¤Aß2e´´|ßZþßaßb÷ß2aß2U»É¨line_mRJi9Ha7eM¨ß1Rß1TÉÉ¤Aß2e´´|ßZþßaßb÷ß2aß2U»É¨line_XLF-Wd1GQg¨ß1Tß1VÉÉ¤Aß2e´´|ßZþßaßb÷ß2aß2U»É¨line_d5j2n1sm_P¨ß1Xß1VÉÉ¤Aß2e´´|ßZþßaßb÷ß2aß2U»É¨line_rDIeRdZatn¨ß1Xß1aÉÉ¤Aß2e´´|ßZþßaßb÷ß2aß2U»É¨line_CgmP2Wvaa-¨ß1cß1a—{ßA¨line_PckGhpjHZ9¨ß2cß1eß2dß1cß8{ßC»ßDÉß4ß2Uß2U{ß2Yß2eß2VÉß2WÉß2X¤A}ß2b¨mtr-race-days¨ß2Z´´ß2y{ßY|ßZþßaßb÷}}}{ßA¨line_63KqnlGons¨ß2cß1Xß2dß1jß8{ßC»ßDÉß4ß2Uß2U{ß2Yß2eß2VÉß2WÉß2X¤A}ß2bß2aß2a{ßY|ßZþßaßb÷}ß2Z´´}}{ßA¨line_3pT3y-XdqU¨ß2cß1jß2dß1oß8{ßC»ßDÉß4ß2Uß2U{ß2Yß2eß2VÉß2WÉß2X¤A}ß2bß2aß2a{ßY|ßZþßaßb÷}ß2Z´´}}{ßA¨line_fviOSFfLXd¨ß2cß1oß2dß1rß8{ßC»ßDÉß4ß2Uß2U{ß2Yß2eß2VÉß2WÉß2X¤A}ß2bß2aß2a{ßY|ßZþßaßb÷}ß2Z´´}}{ßA¨line_cit5QmmApu¨ß2cß1rß2dß1tß8{ßC»ßDÉß4ß2Uß2U{ß2Yß2eß2VÉß2WÉß2X¤A}ß2bß2aß2a{ßY|ßZþßaßb÷}ß2Z´´}}{ßA¨line_iflWy_mekp¨ß2cß1tß2dß1wß8{ßC»ßDÉß4ß2Uß2U{ß2Yß2eß2VÉß2WÉß2X¤A}ß2bß2aß2a{ßY|ßZþßaßb÷}ß2Z´´}}{ßA¨line_LIJXGj-i95¨ß2cß1wß2dß1zß8{ßC»ßDÉß4ß2Uß2U{ß2Yß2eß2VÉß2WÉß2X¤A}ß2bß2aß2a{ßY|ßZþßaßb÷}ß2Z´´}}{ßA¨line_ZcPXAYI9Ic¨ß2cß1zß2dß23ß8{ßC»ßDÉß4ß2Uß2U{ß2Yß2eß2VÉß2WÉß2X¤A}ß2bß2aß2a{ßY|ßZþßaßb÷}ß2Z´´}}{ßA¨line_b9tAbasQg_¨ß2cß23ß2dß26ß8{ßC»ßDÉß4ß2Uß2U{ß2Yß2eß2VÉß2WÉß2X¤A}ß2bß2aß2a{ßY|ßZþßaßb÷}ß2Z´´}}{ßA¨line_GHbh312uE_¨ß2cß26ß2dß29ß8{ßC»ßDÉß4ß2Uß2U{ß2Yß2eß2VÉß2WÉß2X¤A}ß2bß2aß2a{ßY|ßZþßaßb÷}ß2Z´´}}{ßA¨line_zeuCAbDHZ9¨ß2cß29ß2dß2Gß8{ßC»ßDÉß4ß2Uß2U{ß2Yß2eß2VÉß2WÉß2X¤A}ß2bß2aß2a{ßY|ßZþßaßb÷}ß2Z´´}}÷}¨version¨¤B}</details>

**Comment by langonginc** [comment]
您好，您所提供的来源并非官方或维基百科，我们无法确认其是否可靠，请您寻找官方来源，感谢您的贡献。
