### ISSUE TITLE
Resources: New template of xiamen

### ISSUE THREAD

**Issue by Xiaoleng233** [railmapgen/rmp-gallery#347]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[xiamen.txt](https://github.com/railmapgen/rmp-gallery/files/12028290/xiamen.txt)

**Comment by langonginc** [comment]
您好，模版上方存在一个多余的车站，请您将它移除，感谢您的贡献！
