### ISSUE TITLE
Resources: New template of qingdao

### ISSUE THREAD

**Issue by Zhengyang-Rd** [railmapgen/rmp-gallery#350]
Hi RMP team! I would like to contribute to the gallery with the data below.
#326 
**Do not edit lines below, they are meant for bots only!!!**

[qingdao.txt](https://github.com/railmapgen/rmp-gallery/files/12063165/qingdao.txt)

**Comment by thekingofcity** [comment]
嗨，感谢对项目的支持与贡献。此作品已被添加到画廊中 :)

**Comment by Zhengyang-Rd** [comment]
您好，感谢RMP团队对此模版的认可。

请问，如果我想更新此模版，是否是将新模板上传到Issues中？

**Comment by thekingofcity** [comment]
> 请问，如果我想更新此模版，是否是将新模板上传到Issues中？

请根据画廊中的提示，修改作品后重新开新问题 :)
