### ISSUE TITLE
Resources: Update template of chongqing

### ISSUE THREAD

**Issue by mrliyu-a11y** [railmapgen/rmp-gallery#358]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[chongqing.txt](https://github.com/railmapgen/rmp-gallery/files/12084157/chongqing.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for the contribution. However, you need to describe your changes in detail other than _Add Chongqing Rail Transit Template_ :)
