### ISSUE TITLE
Resources: New template of wuhan

### ISSUE THREAD

**Issue by HangzhouMetro09024** [railmapgen/rmp-gallery#364]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[wuhan.txt](https://github.com/railmapgen/rmp-gallery/files/12101457/wuhan.txt)

**Comment by langonginc** [comment]
您好，您所提供的来源并非官方或维基百科，我们无法确认其是否可靠，请您寻找官方来源，感谢您的贡献。
