### ISSUE TITLE
Resources: New template of hohhot

### ISSUE THREAD

**Issue by Jax-axl099** [railmapgen/rmp-gallery#366]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[hohhot.txt](https://github.com/railmapgen/rmp-gallery/files/12101869/hohhot.txt)

**Comment by 28yfang** [comment]
您好，感谢您对画廊的贡献。
经检查，您的模版包含但不限于以下问题：
1. 1号线内蒙古博物院站中文名称错误，请修正（您写的是内蒙古博物馆）
2. 我们发现1号线部分站名下加了回车，导致站名距离车站过远，建议删去。

请您在修改后重新上传并附上本issue号（#366），感谢！

**Comment by Jax-axl099** [comment]
好的

**Comment by 28yfang** [comment]
请管理员关闭本issue和#367
