### ISSUE TITLE
Resources: New template of luoyang

### ISSUE THREAD

**Issue by Jax-axl099** [railmapgen/rmp-gallery#368]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Luoyang"
    },
    "desc": {
        "en": "Luoyang is an industrial city in central China’s Henan province, in what is widely recognized as the region where Chinese civilization originated. Luoyang, ancient China’s capital during multiple dynasties, is home to Baima Si (White Horse Temple), among China’s first Buddhist temples, founded in the 1st century. Nearby, the Longmen Grottoes contain thousands of Buddhist rock carvings dating to the 5th century. "
    },
    "reference": "https://www.lysubway.com.cn/service.html#home2",
    "justification": "Added template of the Luoyang metro system"
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="luoyang">{¨svgViewBoxZoom¨¤h¨svgViewBoxMin¨{´x´£Ad.9C´y´£4q.2G}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨bjsubway-basic¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨¨open¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨right¨¨middle¨|¨红山¨¨Hongshan¨÷»ßA»¢8Y¢1wÉ¨stn_lQOmh8WM8q¨ßJ¨bottom¨|¨谷水¨¨Gushui¨÷»ßA»¢9C¢2VÉ¨stn_KlBin9HAjt¨ßJ¨top¨|¨秦岭路¨¨Qinling Road¨÷»ßA»¢AAº3É¨stn_aF_YgvbfVe¨¨left¨ßN|¨武汉路¨¨Wuhan Road¨÷»ßA»¢Ae¢2uÉ¨stn_Xegc4SuUiF¨ßJßR|¨长安路¨¨Chang'an Road¨÷»ßA»¢Bh¢3EÉ¨stn_4rc5zA51IQ¨ßJßN|¨上海市场¨¨Shanghai Market¨÷»ßA»¢Caº8É¨stn_V8RBc-J-sE¨ßJßR|¨牡丹广场¨¨Peony Square¨÷»ßA»¢DYº8É¨stn_4kzMuSZyvC¨ßJßN|¨七里河¨¨Qilihe¨÷»ßA»¢EWº8É¨stn_QVIZyKAkRw¨ßJßR|¨王城公园¨¨Wangcheng Park¨÷»ßA»¢FPº8É¨stn_XQNs3ycqyF¨—{ßH¨stn_rbR3BsAB5o¨ß8{ßF»ßGÉ´x´¢GN´y´º8ß4¨bjsubway-int¨ßp{ßD|¨解放路¨¨Jiefang Road¨÷ßBßIßCßN¨outOfStation¨«}}}{ßH¨stn_7ZoDlhlBEz¨ß8{ßF»ßGÉ´x´¢HQ´y´º8ß4ßAßA{ßD|¨周王城广场¨¨Zhouwangcheng Square¨÷ßBßJßCßRßE»}}}{ßH¨stn__cws5JHVG2¨ß8{ßF»ßGÉ´x´¢IJ´y´º8ß4ßAßA{ßD|¨应天门¨¨Yingtianmen¨÷ßBßJßCßNßE»}}}{ßH¨stn_vMLCwmZJmu¨ß8{ßF»ßGÉ´x´¢JH´y´º8ß4ßAßA{ßD|¨丽景门¨¨Lijingmen¨÷ßBßJßCßRßE»}}}{ßH¨stn_lcW13iMlyC¨ß8{ßF»ßGÉ´x´¢KF´y´º8ß4ßAßA{ßD|¨青年宫¨¨Qingniangong¨÷ßBßJßCßNßE»}}}{ßH¨stn_sNKEbpqt1A¨ß8{ßF»ßGÉ´x´¢L8´y´º8ß4ßAßA{ßD|¨夹马营¨¨Jiamaying¨÷ßBßJßCßRßE»}}}{ßH¨stn_7OSUYnpayM¨ß8{ßF»ßGÉ´x´¢M1´y´º8ß4ßAßA{ßD|¨启明南路¨¨South Qiming Road¨÷ßBßJßCßNßE»}}}{ßH¨stn_eYfDcEvGen¨ß8{ßF»ßGÉ´x´¢Mz´y´º8ß4ßAßA{ßD|´塔湾´¨Tawan¨÷ßBßJßCßRßE»}}}{ßH¨stn_8h_CD3Rrmn¨ß8{ßF»ßGÉ´x´¢O2´y´º8ß4ßAßA{ßD|¨史家湾¨¨Shijiawan¨÷ßBßJßCßNßE»}}}{ßH¨stn_DXAzu3Zp01¨ß8{ßF»ßGÉ´x´¢P0´y´º8ß4ßAßA{ßD|´杨湾´¨Yangwan¨÷ßBßJßCßRßE»}}}{ßH¨misc_node_XltWZBKind¨ß8{ßF»ßGÉ´x´¢PU´y´¢2zß4¨shmetro-num-line-badge¨ß1J{¨num¨Ê¨color¨|¨luoyang¨¨ly1¨¨#c4608c¨¨#fff¨÷}}}{ßH¨misc_node_DEzvhULfPv¨ß8{ßF»ßGÉ´x´¢7a´y´¢1mß4ß1Jß1J{ß1KÊß1L|ß1Mß1Nß1Oß1P÷}}}{ßH¨misc_node_clnycjkEz_¨ß8{ßF»ßGÉ´x´¢ER´y´¢-Zß4ß1Jß1J{ß1KËß1L|ß1M¨ly2¨¨#6fba2c¨ß1P÷}}}{ßH¨stn_JCTp75Eu31¨ß8{ßF»ßGÉ´x´¢Ev´y´¢-jß4ßAßA{ßD|¨二乔路¨¨Erqiao Road¨÷ßBßJßCßRßE»}}}{ßH¨stn_XXvM2rxXhg¨ß8{ßF»ßGÉ´x´¢Fo´y´ºUß4ßAßA{ßD|´邙岭´¨Mangling¨÷ßBßJßCßNßE»}}}{ßH¨misc_node_Up8FzaZP2n¨ß8{ßF»ßGÉ´x´¢HB´y´¢9vß4ß1Jß1J{ß1KËß1L|ß1Mß1Sß1Tß1P÷}}}{ßH¨stn_N9ZfJN5ou3¨ß8{ßF»ßGÉ´x´ºD´y´¤Fß4ßAßA{ßD|¨国花路¨¨Guohua Road¨÷ßBßIßCßJßE»}}}{ßH¨stn_TcSKkpBbeS¨ß8{ßF»ßGÉ´x´ºD´y´¢18ß4ßAßA{ßD|¨洛阳火车站¨¨Luoyang Railway Station¨÷ßBßIßCßJßE»}}}{ßH¨misc_node_awSUs_gF59¨ß8{ßF»ßGÉ´x´¢IY´y´¤tß4¨facilities¨ß1h{ß4¨railway¨}}}{ßH¨misc_node_xLk7JYmq_q¨ß8{ßF»ßGÉ´x´¢G8´y´¤yß4¨virtual¨ß1k{}}}{ßH¨misc_node_oyG7NUStUC¨ß8{ßF»ßGÉ´x´¢Gm´y´¤eß4ß1kß1k{}}}{ßH¨stn_Eey6Q5I3zF¨ß8{ßF»ßGÉ´x´ºD´y´¢21ß4ßAßA{ßD|¨纱厂路¨¨Shachang Road¨÷ßBßIßCßJßE»}}}{ßH¨stn_RWVnIpB3yh¨ß8{ßF»ßGÉ´x´ºD´y´¢47ß4ßAßA{ßD|¨牡丹桥¨¨Mudan Bridge¨÷ßBßIßCßJßE»}}}{ßH¨stn_TCf7QFvwjT¨ß8{ßF»ßGÉ´x´¢G3´y´¢55ß4ßAßA{ßD|¨文博园¨¨Wenbo Park¨÷ßBßIßCßNßE»}}}{ßH¨stn_Sh0aXLmA8Y¨ß8{ßF»ßGÉ´x´¢FU´y´¢5eß4ßAßA{ßD|¨隋唐园¨¨Sui-Tang Botanical Garden¨÷ßBßVßCßRßE»}}}{ßH¨stn_fqiCoNq2qO¨ß8{ßF»ßGÉ´x´¢F5´y´¢6cß4ßAßA{ßD|¨体育中心¨¨Sports Center¨÷ßBßIßCßJßE»}}}{ßH¨stn_prMMZBOP5l¨ß8{ßF»ßGÉ´x´ºi´y´¢7Vß4ßAßA{ßD|¨市民之家¨¨Citizens’ Home¨÷ßBßIßCßJßE»}}}{ßH¨stn_u29qLHDUdA¨ß8{ßF»ßGÉ´x´ºi´y´¢8Jß4ßAßA{ßD|¨开元湖¨¨Kaiyuan Lake¨÷ßBßVßCßJßE»}}}{ßH¨misc_node_YewwaXaxAY¨ß8{ßF»ßGÉ´x´¢FK´y´¢8iß4ß1kß1k{}}}{ßH¨misc_node_gjeF7vFhY1¨ß8{ßF»ßGÉ´x´ºm´y´º2ß4ß1kß1k{}}}{ßH¨misc_node_3X0d1YLVGM¨ß8{ßF»ßGÉ´x´ºm´y´¢9Wß4ß1kß1k{}}}{ßH¨misc_node_ZCg-r99jkT¨ß8{ßF»ßGÉ´x´ºm´y´¢9qß4ß1kß1k{}}}{ßH¨stn_bwGwrS_xrh¨ß8{ßF»ßGÉ´x´ºi´y´ºoß4ßAßA{ßD|¨兴洛湖¨¨Xingluo Lake¨÷ßBßVßCßJßE»}}}{ßH¨stn_9IQsbRTnzx¨ß8{ßF»ßGÉ´x´¢Ft´y´º4ß4ßAßA{ßD|¨龙门高铁站¨¨Longmen High-Speed Railway Station¨÷ßBßJßCßNßE»}}}{ßH¨misc_node_-9lXbaJlU1¨ß8{ßF»ßGÉ´x´¢Gw´y´¢AFß4ß1hß1h{ß4ß1i}}}{ßH¨stn_URPDIqfUnw¨ß8{ßF»ßGÉ´x´¢Gh´y´º4ß4ßAßA{ßD|¨八里堂¨¨Balitang¨÷ßBßJßCßRßE»}}}{ßH¨misc_node_hetA9IX-uC¨ß8{ßF»ßGÉ´x´¢Eb´y´º4ß4ß1kß1k{}}}{ßH¨misc_node_gZldKL1tyK¨ß8{ßF»ßGÉ´x´ºV´y´¢9lß4ß1kß1k{}}}{ßH¨misc_node_NwiyuZxcPU¨ß8{ßF»ßGÉ´x´¢7B´y´¢4bß4ß1kß1k{}}}{ßH¨misc_node_QyDo91F_83¨ß8{ßF»ßGÉ´x´¢QN´y´ºxß4ß1kß1k{}}}{ßH¨misc_node_gJziZYHmoX¨ß8{ßF»ßGÉ´x´¢Id´y´ºxß4¨text¨ß2Q{¨content¨¨洛河 Luo River¨¨fontSize¨¤G¨lineHeight¨¤G¨textAnchor¨ßJ¨dominantBaseline¨ßJ¨language¨´en´ß1L|¨shanghai¨¨jsr¨¨#000000¨ß1P÷¨rotate¨É¨italic¨«}}}÷¨edges¨|¦ß8¦¨reconcileId¨¨simple¨¦¨offset¨‡¨single-color¨¦ß1L‡¨style¨ß4ßFßG‡ßH¨source¨¨target¨‡´´É|ß1Mß1Nß1Oß1P÷ß2hß2f»É¨line_DYPiLuRBVZ¨ßQßU´´É|ß1Mß1Nß1Oß1P÷ß2hß2f»É¨line_QjKjKkNPWy¨ßbße´´É|ß1Mß1Nß1Oß1P÷ß2hß2f»É¨line_eIYLcT2K8k¨ßeßh´´É|ß1Mß1Nß1Oß1P÷ß2hß2f»É¨line_7j3ol-bXJ2¨ßhßk´´É|ß1Mß1Nß1Oß1P÷ß2hß2f»É¨line_xAx0QnUrAr¨ßkßn´´É|ß1Mß1Nß1Oß1P÷ß2hß2f»É¨line_FfX2dHYpmS¨ßnßo´´É|ß1Mß1Nß1Oß1P÷ß2hß2f»É¨line_GCWbeDeD73¨ßoßt´´É|ß1Mß1Nß1Oß1P÷ß2hß2f»É¨line_PEmQpYKuEA¨ßtßw´´É|ß1Mß1Nß1Oß1P÷ß2hß2f»É¨line_CwHELSznkP¨ßwßz´´É|ß1Mß1Nß1Oß1P÷ß2hß2f»É¨line_BS_d7fTqsD¨ßzß12´´É|ß1Mß1Nß1Oß1P÷ß2hß2f»É¨line_mxDlOTAgrE¨ß12ß15—{ßH¨line_w8ZpfljYFP¨ß2jßQß2kßMß8{ßF»ßGÉß4¨perpendicular¨ß2x{¨startFrom¨¨from¨¨offsetFrom¨É¨offsetTo¨É¨roundCornerFactor¨£I.5K}ß2iß2hß2h{ß1L|ß1Mß1Nß1Oß1P÷}ß2e´´}}{ßH¨line_7c_1cNDlIN¨ß2jßUß2kßYß8{ßF»ßGÉß4ß2xß2x{ß2yß2zß30Éß31Éß32Ý2}ß2iß2hß2h{ß1L|ß1Mß1Nß1Oß1P÷}ß2e´´}}{ßH¨line_TApqStG7Pi¨ß2jßbß2kßYß8{ßF»ßGÉß4ß2xß2x{ß2yß2zß30Éß31Éß32Ý2}ß2iß2hß2h{ß1L|ß1Mß1Nß1Oß1P÷}ß2e´´}}{ßH¨line_9vGZuZgxmj¨ß2jß15ß2kß18ß8{ßF»ßGÉß4ß2fß2f{ß2gÉ}ß2iß2hß2h{ß1L|ß1Mß1Nß1Oß1P÷}ß2e´´}}{ßH¨line_JyWfIBkr_q¨ß2jß18ß2kß1Bß8{ßF»ßGÉß4ß2fß2f{ß2gÉ}ß2iß2hß2h{ß1L|ß1Mß1Nß1Oß1P÷}ß2e´´}}{ßH¨line_E8vQUUucQH¨ß2jß1Bß2kß1Dß8{ßF»ßGÉß4ß2fß2f{ß2gÉ}ß2iß2hß2h{ß1L|ß1Mß1Nß1Oß1P÷}ß2e´´}}{ßH¨line_qGqcqZMhkZ¨ß2jß1Dß2kß1Gß8{ßF»ßGÉß4ß2fß2f{ß2gÉ}ß2iß2hß2h{ß1L|ß1Mß1Nß1Oß1P÷}ß2e´´}}{ßH¨line_XdDooadtGQ¨ß2jß1Uß2kß1Xß8{ßF»ßGÉß4ß2fß2f{ß2gÉ}ß2iß2hß2h{ß1L|ß1Mß1Sß1Tß1P÷}ß2e´´}}{ßH¨line_j-GELbFFaB¨ß2jß1Xß2kß1aß8{ßF»ßGÉß4ß2xß2x{ß2yß2zß30Éß31Éß32Ý2}ß2iß2hß2h{ß1L|ß1Mß1Sß1Tß1P÷}ß2e´´}}{ßH¨line_qrvWyY02nS¨ß2jß1aß2kß1dß8{ßF»ßGÊß4ß2fß2f{ß2gÉ}ß2iß2hß2h{ß1L|ß1Mß1Sß1Tß1P÷}ß2e´´}}{ßH¨line_EX74x4ccsL¨ß2jß1jß2kß1lß8{ßF»ßGÉß4¨diagonal¨ß2i¨china-railway¨ß2e´´ß3D{ß2yß2zß30Éß31Éß32¤A}ß3E{}}}{ßH¨line_Ptf4k-qmty¨ß2jß1dß2kß1mß8{ßF»ßGÉß4ß2fß2f{ß2gÉ}ß2iß2hß2h{ß1L|ß1Mß1Sß1Tß1P÷}ß2e´´}}{ßH¨line_ZD_rQ0JTZt¨ß2jß1mß2kßoß8{ßF»ßGÉß4ß2fß2f{ß2gÉ}ß2iß2hß2h{ß1L|ß1Mß1Sß1Tß1P÷}ß2e´´}}{ßH¨line_cRn4eyDXO_¨ß2jßoß2kß1pß8{ßF»ßGÉß4ß2fß2f{ß2gÉ}ß2iß2hß2h{ß1L|ß1Mß1Sß1Tß1P÷}ß2e´´}}{ßH¨line_6-PN2i4qyM¨ß2jß1pß2kß1sß8{ßF»ßGÉß4ß3Dß3D{ß2yß2zß30Éß31Éß32¤A}ß2iß2hß2h{ß1L|ß1Mß1Sß1Tß1P÷}ß2e´´}}{ßH¨line_qet8P7-n0t¨ß2jß1vß2kß1sß8{ßF»ßGÉß4ß2fß2f{ß2gÉ}ß2iß2hß2h{ß1L|ß1Mß1Sß1Tß1P÷}ß2e´´}}{ßH¨line_YCfNaiOIgB¨ß2jß1yß2kß1vß8{ßF»ßGÉß4ß3Dß3D{ß2yß2zß30Éß31Éß32¤A}ß2iß2hß2h{ß1L|ß1Mß1Sß1Tß1P÷}ß2e´´}}{ßH¨line_dOQ0IXHydD¨ß2jß1yß2kß21ß8{ßF»ßGÉß4ß2fß2f{ß2gÉ}ß2iß2hß2h{ß1L|ß1Mß1Sß1Tß1P÷}ß2e´´}}{ßH¨line_NliVB453bX¨ß2jß21ß2kß24ß8{ßF»ßGÉß4ß2fß2f{ß2gÉ}ß2iß2hß2h{ß1L|ß1Mß1Sß1Tß1P÷}ß2e´´}}{ßH¨line_lxPx92q2s7¨ß2jß29ß2kß2Aß8{ßF»ßGÄß4ß2fß2f{ß2gÉ}ß2i¨river¨ß2e´´ß3O{ß1L|ß2Yß3O¨#9EE3F9¨ß1P÷¨width¨¤K}}}{ßH¨line_nNljkkL3fK¨ß2jß27ß2kß28ß8{ßF»ßGÄß4ß2fß2f{ß2gÉ}ß2iß3Oß2e´´ß3O{ß1L|ß2Yß3Oß3Pß1P÷ß3Q¤K}}}{ßH¨line_6JajvFsgaV¨ß2jß24ß2kß2Bß8{ßF»ßGÉß4ß2fß2f{ß2gÉ}ß2iß2hß2h{ß1L|ß1Mß1Sß1Tß1P÷}ß2e´´}}{ßH¨line_f0qJiPoJJD¨ß2jß2Eß2kß2Bß8{ßF»ßGÊß4ß2xß2x{ß2yß2zß30Éß31Éß32Ý2}ß2iß2hß2h{ß1L|ß1Mß1Sß1Tß1P÷}ß2e´´}}{ßH¨line_6XQSkQpP-0¨ß2jß2Eß2kß2Iß8{ßF»ßGÉß4ß2fß2f{ß2gÉ}ß2iß2hß2h{ß1L|ß1Mß1Sß1Tß1P÷}ß2e´´}}{ßH¨line_Ni3tVDweu3¨ß2jß2Lß2kß2Mß8{ßF»ßGÉß4ß3Dß2iß3Eß2e´´ß3D{ß2yß2zß30Éß31Éß32¤A}ß3E{}}}{ßH¨line_wusNgGcvqQ¨ß2jß2Nß2kß2Oß8{ßF»ßGÄß4ß2fß2f{ß2gÉ}ß2iß3Oß2e´´ß3O{ß1L|ß2Yß3Oß3Pß1P÷ß3Q¤Q}}}÷}¨version¨¤D}</details>

#341

**Comment by thekingofcity** [comment]
嗨，感谢对画廊的支持与贡献，作品已被合入项目并上线 :)

**Comment by Jax-axl099** [comment]
谢谢
