### ISSUE TITLE
Resources: Update template of beijing

### ISSUE THREAD

**Issue by wsqtiger** [railmapgen/rmp-gallery#370]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[beijing.txt](https://github.com/railmapgen/rmp-gallery/files/12103293/beijing.txt)

**Comment by thekingofcity** [comment]
嗨，感谢对画廊中作品的纠错，更新已被合入项目并上线 :)
