### ISSUE TITLE
Resources: New template of hohhot

### ISSUE THREAD

**Issue by Jax-axl099** [railmapgen/rmp-gallery#374]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[hohhot.txt](https://github.com/railmapgen/rmp-gallery/files/12115444/hohhot.txt)

**Comment by Jax-axl099** [comment]
#366

**Comment by 28yfang** [comment]
您好，问题均已修复，请等待管理员最终确认并汇入。感谢您对画廊的贡献！

**Comment by thekingofcity** [comment]
嗨，感谢对画廊的支持与贡献，作品已被合入项目并上线 :)

**Comment by Jax-axl099** [comment]
谢谢
