### ISSUE TITLE
Resources: New template of nanchang

### ISSUE THREAD

**Issue by axl099** [railmapgen/rmp-gallery#376]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[nanchang.txt](https://github.com/railmapgen/rmp-gallery/files/12117368/nanchang.txt)

**Comment by 28yfang** [comment]
您好，Slack群链接如下：
Join me on Slack -- it’s a faster, simpler way to work. Sign up here, from any device: https://join.slack.com/t/railmapgenerator/shared_invite/zt-1yogpxr2o-sfEc~mVlLCQ1YbffcAc5GA

**Comment by Jax-axl099** [comment]
谢谢

**Comment by langonginc** [comment]
检查无误，感谢您的贡献，您的作品即将上线！
