### ISSUE TITLE
Resources: Update template of hangzhou

### ISSUE THREAD

**Issue by HangzhouMetroXianingBridge** [railmapgen/rmp-gallery#378]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[hangzhou (1).txt](https://github.com/railmapgen/rmp-gallery/files/12122649/hangzhou.1.txt)

**Comment by thekingofcity** [comment]
Hi, you need a sufficient reason to update a template. Also, do not remove its description without a valid reason.
