### ISSUE TITLE
Resources: New template of shijiazhuang

### ISSUE THREAD

**Issue by YeeHOMO** [railmapgen/rmp-gallery#387]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[shijiazhuang.txt](https://github.com/railmapgen/rmp-gallery/files/12140970/shijiazhuang.txt)
我想问一下如果这个通过之后需要等多久才能展出在画廊上，之前发的一个南京的已经等了好久了

**Comment by thekingofcity** [comment]
嗨，请不要将可以复制的文本内容粘贴到文本文件中再上传，直接粘贴到议题中即可。

关于审核和合入进度，由于审核画廊作品的工作量较大且社区审核贡献者精力有限，无法即时处理，敬请谅解。欢迎加入slack群组了解审核要求后处理其他申请并帮助画廊作品的审核，谢谢 :)
