### ISSUE TITLE
Resources: Update template of nanning

### ISSUE THREAD

**Issue by LittleLing03** [railmapgen/rmp-gallery#388]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[nanning (3).txt](https://github.com/railmapgen/rmp-gallery/files/12140997/nanning.3.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for the contribution. What did you update?

**Comment by LittleLing03** [comment]
更新线路标识位置及3号线的走向

**Comment by thekingofcity** [comment]
嗨，请将此内容填写在证明处 :)
