### ISSUE TITLE
Resources: Update template of beijing

### ISSUE THREAD

**Issue by HuQiUaN** [railmapgen/rmp-gallery#394]
[2tnJ3x491q%n.txt](https://github.com/railmapgen/rmp-gallery/files/12145549/2tnJ3x491q.n.txt)
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

**Comment by langonginc** [comment]
您好，您能否具体描述一下修改了哪些车站的名称或位置？我无法获知您对哪部分进行了修改，谢谢。

**Comment by HuQiUaN** [comment]
由于已有新版北京模板，此贴已完结。
