### ISSUE TITLE
Resources: New template of zhengzhou

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp-gallery#396]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[Zhengzhou.txt](https://github.com/railmapgen/rmp-gallery/files/12157156/Zhengzhou.txt)

**Comment by 28yfang** [comment]
Note: English station names from https://upload.wikimedia.org/wikipedia/commons/4/4b/System_Map_of_Zhengzhou_Metro_%28with_realistic_scale%29.png

**Comment by langonginc** [comment]
感谢您的贡献！
