### ISSUE TITLE
Resources: New template of nanning

### ISSUE THREAD

**Issue by WaterLeee** [railmapgen/rmp-gallery#404]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**
[nanning.txt](https://github.com/railmapgen/rmp-gallery/files/12191780/nanning.txt)
[nanning.txt](https://github.com/railmapgen/rmp-gallery/files/12191790/nanning.txt)

**Comment by 28yfang** [comment]
您好，RMP画廊已经有南宁地铁的模版。若您提供的是更新版本的南宁地铁（如加了最近开通的线路等），请您直接编辑南宁模版即可。感谢您对贡献！

**Comment by WaterLeee** [comment]
您好，我并未在画廊看到南宁地铁的模板

**Comment by WaterLeee** [comment]
您好，我并未在画廊看到南宁地铁的模板

**Comment by 28yfang** [comment]
您好，南宁地铁模版位于澳门与平壤模版之间。![image](https://github.com/railmapgen/rmp-gallery/assets/123239445/4486956f-ce81-4c26-bc87-b6de2f1e8a58)

**Comment by WaterLeee** [comment]
该更新没有在Windows端应用软件内显示，请问如何解决
