### ISSUE TITLE
Resources: New template of glasgow

### ISSUE THREAD

**Issue by polygon827** [railmapgen/rmp-gallery#419]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Glasgow",
        "zh-Hans": "格拉斯哥"
    },
    "desc": {
        "zh-Hans": "格拉斯哥地铁（Glasgow Subway）位于苏格兰格拉斯哥，始于1896年12月，由一条闭环地铁线构成，分成内外环运营。全长10.4公里，共有15个车站（全部是地下站）。",
        "en": "The Glasgow Subway, located in Glasgow, Scotland, began in December 1896. It consists of a closed loop subway line and is divided into inner and outer rings for operation. The total length is 10.4 kilometers, with a total of 15 stations (all underground)."
    },
    "reference": "https://www.spt.co.uk/travel-with-spt/subway/maps-stations/",
    "justification": "Glasgow"
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="glasgow">{¨svgViewBoxZoom¨¢1S¨svgViewBoxMin¨{´x´£-1O.-Be´y´£1W.DF}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨mtr¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨¨rotate¨¨transfer¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨middle¨¨top¨|¨开尔文布里奇¨¨Kelvinbridge¨÷¢4M|||¨glasgow¨¨inner¨¨#4f4c4d¨¨#fff¨´´þ÷|ßN¨outer¨¨#f57c14¨ßQ´´þ÷÷÷ßA»¢4q¢5UÉ¨stn_56RWjYAybF¨ßJßK|¨圣乔治十字¨¨St. George's Cross¨÷º1|||ßNßOßPßQ´´þ÷|ßNßRßSßQ´´þ÷÷÷ßA»¢6cº3É¨stn_UNg1G6fe6J¨¨right¨ßK|¨考卡登斯¨¨Cowcaddens¨÷º1|||ßNßOßPßQ´´þ÷|ßNßRßSßQ´´þ÷÷÷ßA»¢8Jº3É¨stn_TcdQ8ouDKE¨ßXßK|¨布坎南街¨¨Buchanan Street¨÷¢55|||ßNßOßPßQ´´þ÷|ßNßRßSßQ´´þ÷÷÷ßA»¢9q¢63É¨stn_RC2_0J3lU2¨ßX¨bottom¨|¨桥街¨¨Bridge Street¨÷É|||ßNßOßPßQ´´þ÷|ßNßRßSßQ´´þ÷÷÷ßA»¢AP¢8OÉ¨stn_nbnMeFs91h¨ßXße|¨西街¨¨West Street¨÷¤j|||ßNßOßPßQ´´þ÷|ßNßRßSßQ´´þ÷÷÷ßA»º7¢97É¨stn_2Fk9TWLHn-¨ßJße|¨希尔兹路¨¨Shields Road¨÷º0|||ßNßOßPßQ´´þ÷|ßNßRßSßQ´´þ÷÷÷ßA»¢84º7É¨stn_0xJOFGjrM0¨ßJße|¨金宁公园¨¨Kining Park¨÷º0|||ßNßOßPßQ´´þ÷|ßNßRßSßQ´´þ÷÷÷ßA»¢6Iº7É¨stn_Nr5aBiYgxN¨ßJße|¨赛斯诺克¨¨Cessnock¨÷º0|||ßNßOßPßQ´´þ÷|ßNßRßSßQ´´þ÷÷÷ßA»¢4Wº7É¨stn_c6R9qtmyeV¨¨left¨ße|¨伊布罗克斯¨¨Ibrox¨÷¢2B|||ßNßOßPßQ´´þ÷|ßNßRßSßQ´´þ÷÷÷ßA»¢2VºBÉ¨stn_sa_o9PHGMl¨ßuße|¨戈文¨¨Govan¨÷¢2u|||ßNßOßPßQ´´þ÷|ßNßRßSßQ´´þ÷÷÷ßA»¢1rºAÉ¨stn_R_dvRUgbDC¨ßußK|¨帕特里克¨¨Patrick¨÷ºH|||ßNßOßPßQ´´þ÷|ßNßRßSßQ´´þ÷÷÷ßA»ºI¢71É¨stn_orKYh0_wY2¨ßußK|¨开尔文霍尔¨¨Kelvinhall¨÷¢3d|||ßNßOßPßQ´´þ÷|ßNßRßSßQ´´þ÷÷÷ßA»ºGº8É¨stn_NW5kDIrhqd¨ßußK|´山头´¨Hillhead¨÷º1|||ßNßOßPßQ´´þ÷|ßNßRßSßQ´´þ÷÷÷ßA»ºKº3É¨stn_z1iXNm4qyh¨ßXßK|¨圣以诺¨¨St. Enoch¨÷É|||ßNßOßPßQ´´þ÷|ßNßRßSßQ´´þ÷÷÷ßA»º9ºJÉ¨stn_vvDK1sxBkx¨—{ßI¨misc_node_P-zyukhsjf¨ß8{ßG»ßHÉ´x´¢18´y´¢7kß4¨virtual¨ß1D{}}}{ßI¨misc_node_N5U1wRmdHu¨ß8{ßG»ßHÉ´x´¢B3´y´ºMß4ß1Dß1D{}}}{ßI¨misc_node_rk3kcr77D3¨ß8{ßG»ßHÉ´x´¢4R´y´ºMß4¨text¨ß1G{¨content¨¨克莱德河¨¨fontSize¨¤G¨lineHeight¨¤G¨textAnchor¨ßJ¨dominantBaseline¨ßJ¨language¨¨mtr__zh¨¨color¨|¨shanghai¨¨jsr¨¨#000000¨ßQ÷ßEÉ¨italic¨«}}}{ßI¨misc_node_a2ghGW4xbU¨ß8{ßG»ßHÉ´x´¢7B´y´ºMß4ß1Gß1G{ß1H¨River Clyde¨ß1J¤Gß1K¤Gß1LßJß1MßJß1N¨mtr__en¨ß1P|ß1Qß1Rß1SßQ÷ßEÉß1T«}}}{ßI¨misc_node_nYGKg97jos¨ß8{ßG»ßHÉ´x´¢5F´y´¢9Rß4¨bjsubway-text-line-badge¨ß1Y{ßD|¨内环线¨¨Inner Circle¨÷ß1P|ßNßOßPßQ÷}}}{ßI¨misc_node_bqzSN3djAE¨ß8{ßG»ßHÉ´x´ºQ´y´¢A0ß4ß1Yß1Y{ßD|¨外环线¨¨Outer Circle¨÷ß1P|ßNßRßSßQ÷}}}÷¨edges¨|¦ß8¦¨diagonal¨¦¨offsetFrom¨¨offsetTo¨¨roundCornerFactor¨¨startFrom¨‡¨reconcileId¨¨single-color¨¦ß1P‡¨style¨ß4ßGßH‡ßI¨source¨¨target¨‡ÉÉ¤A¨from¨´´|ßNßOßPßQ÷ß1lß1f»É¨line_ZwgYfeCEnd¨ß18ßTÉÉ¤Aß1p´´|ßNßOßPßQ÷ß1lß1f»É¨line_ptUDucjPU7¨ßTßWÉÉ¤Aß1p´´|ßNßOßPßQ÷ß1lß1f»É¨line_5ymssBJHwT¨ßWßaÉÉ¤oß1p´´|ßNßOßPßQ÷ß1lß1f»É¨line_SL7OA7HfUm¨ßaßdÉÉ¤oß1p´´|ßNßOßPßQ÷ß1lß1f»É¨line_2yaLdqvwS9¨ßhßkÉÉ¤oß1p´´|ßNßOßPßQ÷ß1lß1f»É¨line_EsEOwgh52M¨ßnßkÉÉ¤Aß1p´´|ßNßOßPßQ÷ß1lß1f»É¨line_HoUl6Szo1x¨ßqßnÉÉ¤Aß1p´´|ßNßOßPßQ÷ß1lß1f»É¨line_GgsSfrpWBz¨ßtßqÉÉ¤oß1p´´|ßNßOßPßQ÷ß1lß1f»É¨line_aogI6ZrvD6¨ß18ß16ÉÉ¤oß1p´´|ßNßOßPßQ÷ß1lß1f»É¨line__rXi9yqFsO¨ß13ß16ÉÉ¤oß1p´´|ßNßOßPßQ÷ß1lß1f»É¨line_GmcuWoTbMF¨ß10ß13ÉÉ¤oß1p´´|ßNßOßPßQ÷ß1lß1f»É¨line_yQ3VPIKutO¨ß10ßxÉÉ¤oß1p´´|ßNßOßPßQ÷ß1lß1f»É¨line_QVC0bus_Jk¨ßtßxÄÂ¤rß1p´´|ßNßRßSßQ÷ß1lß1f»É¨line_tHNNZS6KvL¨ß10ß13ÄÄ¤rß1p´´|ßNßRßSßQ÷ß1lß1f»É¨line_t1F73qaoMT¨ß13ß16ÄÄ¤rß1p´´|ßNßRßSßQ÷ß1lß1f»É¨line_jY3swdjfJz¨ß18ß16ÄÎ¤Aß1p´´|ßNßRßSßQ÷ß1lß1f»É¨line_4CWvy4QT3j¨ß18ßTÄÎ¤Aß1p´´|ßNßRßSßQ÷ß1lß1f»É¨line_KacxDDeoM9¨ßTßWÄÎ¤Aß1p´´|ßNßRßSßQ÷ß1lß1f»É¨line_PxHnAslf3h¨ßWßaÄÎ¤rß1p´´|ßNßRßSßQ÷ß1lß1f»É¨line_XPL7vePaMw¨ßaßdÎÎ¤rß1p´´|ßNßRßSßQ÷ß1lß1f»É¨line_0Hu6Jtl_eH¨ßhßkÎÎ¤rß1p´´|ßNßRßSßQ÷ß1lß1f»É¨line_814LAZrb_8¨ßnßkÎÂ¤Aß1p´´|ßNßRßSßQ÷ß1lß1f»É¨line_j6izapYxHE¨ßqßnÎÂ¤Aß1p´´|ßNßRßSßQ÷ß1lß1f»É¨line_9JgbdLRQxm¨ßtßqÎÄ¤rß1p´´|ßNßRßSßQ÷ß1lß1f»É¨line_4C91vgqlJ6¨ßtßxÄÄ¤rß1p´´|ßNßRßSßQ÷ß1lß1f»É¨line_l2Louv1YwG¨ß10ßxÉÉ¤oß1p´´|ßNßOßPßQ÷ß1lß1f»É¨line_wytdXr5K47¨ß1BßdÉÉ¤Aß1p´´|ßNßOßPßQ÷ß1lß1f»É¨line_3kXxFQAwun¨ß1BßhÎÎ¤rß1p´´|ßNßRßSßQ÷ß1lß1f»É¨line_5Ov6f4aJOS¨ß1BßdÎÐ¤Aß1p´´|ßNßRßSßQ÷ß1lß1f»É¨line_cP15Y2CSCK¨ß1Bßh—{ßI¨line_IgdyyxCr1R¨ß1nß1Cß1oß1Eß8{ßG»ßHÄß4ß1fß1f{ß1jß1pß1gÉß1hÉß1i¤A}ß1m¨river¨ß1k´´ß2L{ß1P|ß1Qß2L¨#B9E3F9¨ßQ÷¨width¨¤y}}}÷}¨version¨¤D}</details>

**Comment by langonginc** [comment]
感谢您的贡献，您的作品即将上线！
