### ISSUE TITLE
Resources: New template of urumqi

### ISSUE THREAD

**Issue by polygon827** [railmapgen/rmp-gallery#436]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Urumqi",
        "zh-Hans": "乌鲁木齐"
    },
    "desc": {
        "en": "Urumqi Metro is an urban rail transit system serving Ürümqi City, Xinjiang, China. Its first line was opened for trial operation on October 25, 2018, making Urumqi the second city in northwest China to open and operate a subway",
        "zh-Hans": "乌鲁木齐地铁（Urumqi Metro）是服务于中国新疆维吾尔自治区乌鲁木齐市的城市轨道交通系统，其首条线路于2018年10月25日开通试运营，使乌鲁木齐成为西北地区第二个开通运营地铁的城市"
    },
    "reference": "https://www.urumqimtr.com/DTXLT/5402.aspx",
    "justification": "Urumqi"
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="urumqi">{¨svgViewBoxZoom¨¢26¨svgViewBoxMin¨{´x´£-1m.-BA´y´£-4j.-DX}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨shmetro-basic¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨left¨¨top¨|¨国际机场¨¨International Airport\\خەلقئارا ئايرودروم¨÷ßA»¢34¢1wÉ¨stn_xsI4TweYSO¨¨middle¨ßI|¨大地窝堡¨¨Dadiwopu\\دادىۋوپۇ¨÷ßA»¢42¢2VÉ¨stn_cLppjoG5xx¨¨right¨ßI|¨宣仁墩¨¨Xuanrendun\\شۈەنرېندۈن¨÷ßA»¢50¢21É¨stn_XF8sFeY8EN¨ßHßM|¨三工¨¨Sangong\\سەنگۇڭ¨÷ßA»¢5y¢2QÉ¨stn_LGJdxWisWc¨ßH¨bottom¨|¨迎宾路口¨¨Yingbin Road Crossing\\مەرھابا يول ئېغىزى¨÷ßA»¢6X¢2zÉ¨stn_obzGDUE2m5¨ßHßX|¨植物园¨¨Botanical Garden\\ئۆسۈملۈك باغچىسى¨÷ßA»¢7B¢3iÉ¨stn_z9obM7DYH7¨ßHßX|¨体育中心¨¨Sports Center\\تەنتەربىيە مەركىزى¨÷ßA»¢7p¢4RÉ¨stn_rcxQuSmGIj¨—{ßG¨misc_node_P3NP7aDQGi¨ß8{ßE»ßFÉ´x´¢1m´y´¤tß4¨bjsubway-num-line-badge¨ßi{¨num¨Ê¨color¨|¨urumqi¨¨urumqi1¨¨#10069f¨¨#fff¨÷}}}{ßG¨stn_c2xEshpdrg¨ß8{ßE»ßFÉ´x´¢8T´y´¢55ß4ßAßA{ßD|¨铁路局¨¨Tieluju\\تۆمۈر يول ئىدارىسى¨÷ßBßHßCßX}}}{ßG¨stn_KbP6DL4Vmo¨ß8{ßE»ßFÉ´x´¢9C´y´¢5oß4ßAßA{ßD|¨小西沟¨¨Xiaoxigou\\شياۋشىگۇ¨÷ßBßHßCßM}}}{ßG¨stn_xxCU-Nwxzq¨ß8{ßE»ßFÉ´x´¢9b´y´¢6cß4ßAßA{ßD|¨中营工¨¨Zhongyinggong\\جۇڭيىڭگۇڭ¨÷ßBßHßCßM}}}{ßG¨stn_RqmLjjCVSp¨ß8{ßE»ßFÉ´x´¢9l´y´¢7Vß4ßAßA{ßD|¨新疆图书馆¨¨Xinjiang Library\\شىنجاڭ كۇتۇپخانىسى¨÷ßBßHßCßM}}}{ßG¨stn_0Weoask3D4¨ß8{ßE»ßFÉ´x´¢AZ´y´¢84ß4ßAßA{ßD|´八楼´¨Balou\\سەككىزىنچى قەۋەت¨÷ßBßMßCßX}}}{ßG¨stn_s2YRYdNNFP¨ß8{ßE»ßFÉ´x´¢Bm´y´ºPß4ßAßA{ßD|¨王家梁¨¨Wangjialiang\\ۋاڭ جيالياڭ¨÷ßBßMßCßI}}}{ßG¨stn_OgIYjjsyEp¨ß8{ßE»ßFÉ´x´¢CQ´y´¢8iß4ßAßA{ßD|¨南湖北路¨¨Nanhu North Road\\جەنۇبىي خۇبېي يولى¨÷ßBßQßCßM}}}{ßG¨stn_QQwpw-ZZZI¨ß8{ßE»ßFÉ´x´¢CV´y´¢9gß4ßAßA{ßD|¨南湖广场¨¨Nanhu Square\\نەنخۇ مەيدانى¨÷ßBßQßCßM}}}{ßG¨stn_PL386p69D4¨ß8{ßE»ßFÉ´x´¢Ca´y´¢Aeß4ßAßA{ßD|¨新兴街¨¨Xinxing Street\\شىنشىڭ كوچىسى¨÷ßBßQßCßM}}}{ßG¨stn_veZVV0-n5v¨ß8{ßE»ßFÉ´x´¢Cf´y´¢BSß4ßAßA{ßD|´北门´¨Beimen\\شىمالىي قوۋۇق¨÷ßBßQßCßM}}}{ßG¨stn_eLIKGjEZl4¨ß8{ßE»ßFÉ´x´¢Cu´y´¢CGß4ßAßA{ßD|´南门´¨Nanmen\\جەنۇبىي قوۋۇق¨÷ßBßQßCßM}}}{ßG¨stn_g9v7nL0Ubo¨ß8{ßE»ßFÉ´x´ºV´y´¢D4ß4ßAßA{ßD|¨二道桥¨¨Erdaoqiao\\ئېرداۋچياۋ كۆۋرۈكى¨÷ßBßQßCßM}}}{ßG¨stn_Vppa66827S¨ß8{ßE»ßFÉ´x´¢C6´y´¢Dsß4ßAßA{ßD|¨新疆大学¨¨Xinjiang University\\شىنجاڭ ئۇنىۋېرسىتېتى\\¨÷ßBßQßCßM}}}{ßG¨stn_1Thtn9Hk10¨ß8{ßE»ßFÉ´x´¢Bc´y´¢Egß4ßAßA{ßD|¨三屯碑¨¨Santunbei\\سەنتۇن ئابىدىسى¨÷ßBßQßCßM}}}{ßG¨misc_node_H_uFu9rIPg¨ß8{ßE»ßFÉ´x´¢B8´y´¢FAß4ßißi{ßjÊßk|ßlßmßnßo÷}}}÷¨edges¨|{ßG¨line_-cnhxvVvT8¨¨source¨ßP¨target¨ßLß8{ßE»ßFÉß4¨diagonal¨ß1X{¨startFrom¨¨from¨¨offsetFrom¨É¨offsetTo¨É¨roundCornerFactor¨¤A}¨style¨¨single-color¨ß1e{ßk|ßlßmßnßo÷}¨reconcileId¨´´}}{ßG¨line_o8ofT3akmB¨ß1VßPß1WßTß8{ßE»ßFÉß4¨simple¨ß1h{¨offset¨É}ß1dß1eß1e{ßk|ßlßmßnßo÷}ß1f´´}}{ßG¨line_EbTOGHlVmz¨ß1VßTß1WßWß8{ßE»ßFÉß4ß1Xß1X{ß1Yß1Zß1aÉß1bÉß1c¤A}ß1dß1eß1e{ßk|ßlßmßnßo÷}ß1f´´}}{ßG¨line_DABUFXZT6O¨ß1VßWß1Wßaß8{ßE»ßFÉß4ß1hß1h{ß1iÉ}ß1dß1eß1e{ßk|ßlßmßnßo÷}ß1f´´}}{ßG¨line_236hQ-cd7l¨ß1Vßaß1Wßdß8{ßE»ßFÉß4ß1hß1h{ß1iÉ}ß1dß1eß1e{ßk|ßlßmßnßo÷}ß1f´´}}{ßG¨line_rhH3ZfT56C¨ß1Vßdß1Wßgß8{ßE»ßFÉß4ß1hß1h{ß1iÉ}ß1dß1eß1e{ßk|ßlßmßnßo÷}ß1f´´}}{ßG¨line_uOnxoexrMH¨ß1Vßgß1Wßpß8{ßE»ßFÉß4ß1hß1h{ß1iÉ}ß1dß1eß1e{ßk|ßlßmßnßo÷}ß1f´´}}{ßG¨line_SWnVU1_rTi¨ß1Vßpß1Wßsß8{ßE»ßFÉß4ß1hß1h{ß1iÉ}ß1dß1eß1e{ßk|ßlßmßnßo÷}ß1f´´}}{ßG¨line_TYuYnsxN4T¨ß1Vßsß1Wßvß8{ßE»ßFÉß4ß1hß1h{ß1iÉ}ß1dß1eß1e{ßk|ßlßmßnßo÷}ß1f´´}}{ßG¨line_VDEWg9wGKd¨ß1Vßvß1Wßyß8{ßE»ßFÉß4ß1hß1h{ß1iÉ}ß1dß1eß1e{ßk|ßlßmßnßo÷}ß1f´´}}{ßG¨line_cx7eSwcaQT¨ß1Vß11ß1Wßyß8{ßE»ßFÉß4¨perpendicular¨ß1s{ß1Yß1Zß1aÉß1bÉß1c£I.5K}ß1dß1eß1e{ßk|ßlßmßnßo÷}ß1f´´}}{ßG¨line_1vfVQLZaRs¨ß1Vß11ß1Wß13ß8{ßE»ßFÉß4ß1hß1h{ß1iÉ}ß1dß1eß1e{ßk|ßlßmßnßo÷}ß1f´´}}{ßG¨line_CIjIa352Im¨ß1Vß16ß1Wß19ß8{ßE»ßFÉß4ß1hß1h{ß1iÉ}ß1dß1eß1e{ßk|ßlßmßnßo÷}ß1f´´}}{ßG¨line_-sK6pn1oBG¨ß1Vß19ß1Wß1Cß8{ßE»ßFÉß4ß1hß1h{ß1iÉ}ß1dß1eß1e{ßk|ßlßmßnßo÷}ß1f´´}}{ßG¨line_4r1EEmKKTV¨ß1Vß1Cß1Wß1Fß8{ßE»ßFÉß4ß1hß1h{ß1iÉ}ß1dß1eß1e{ßk|ßlßmßnßo÷}ß1f´´}}{ßG¨line_w-vJwslq_t¨ß1Vß1Fß1Wß1Hß8{ßE»ßFÉß4ß1hß1h{ß1iÉ}ß1dß1eß1e{ßk|ßlßmßnßo÷}ß1f´´}}{ßG¨line_T3HfP9nip-¨ß1Vß1Hß1Wß1Jß8{ßE»ßFÉß4ß1hß1h{ß1iÉ}ß1dß1eß1e{ßk|ßlßmßnßo÷}ß1f´´}}{ßG¨line__CWHlkmrpj¨ß1Vß1Jß1Wß1Mß8{ßE»ßFÉß4ß1hß1h{ß1iÉ}ß1dß1eß1e{ßk|ßlßmßnßo÷}ß1f´´}}{ßG¨line_e4XCxt_jdt¨ß1Vß1Mß1Wß1Pß8{ßE»ßFÉß4ß1hß1h{ß1iÉ}ß1dß1eß1e{ßk|ßlßmßnßo÷}ß1f´´}}{ßG¨line_QdAMsCCB33¨ß1Vß13ß1Wß16ß8{ßE»ßFÉß4ß1sß1s{ß1Yß1Zß1aÉß1bÉß1cÝ2}ß1dß1eß1e{ßk|ßlßmßnßo÷}ß1f´´}}÷}¨version¨¤E}</details>

**Comment by langonginc** [comment]
https://github.com/railmapgen/rmp-gallery/issues/191

**Comment by langonginc** [comment]
#191 中提到的问题已经解决，即将汇入，感谢您的贡献。
