### ISSUE TITLE
Resources: Update template of dalian

### ISSUE THREAD

**Issue by LittleLing03** [railmapgen/rmp-gallery#440]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[dalian.txt](https://github.com/railmapgen/rmp-gallery/files/12271526/dalian.txt)

**Comment by thekingofcity** [comment]
嗨，感谢对画廊的支持与共享，更新已被合入并即将上线 :)
