### ISSUE TITLE
Resources: New template of wuhu

### ISSUE THREAD

**Issue by Egneriess** [railmapgen/rmp-gallery#449]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Wuhu",
        "zh-CN": "芜湖"
    },
    "desc": {
        "zh-CN": "芜湖轨道交通（Wuhu Rail Transit）是服务于中国安徽省芜湖市的城市轨道交通系统，其首条线路于2021年11月3日开通运营，使芜湖成为中国内地第49座  、安徽省第二座开通城市轨道交通的城市 。截至2021年12月，芜湖轨道交通运营线路共有2条，为芜湖轨道交通1号线、芜湖轨道交通2号线，共设置车站35座，其中高架站34座，地下站1座；芜湖轨道交通运营里程为46.2千米 。2021年，芜湖轨道交通累计客流294.4万人次，日均客流5.1万人次；2022年，芜湖轨道交通累计客流2278.3万人次；最高日客运量为2022年2月5日的19.36万人次  。",
        "en": "Wuhu Rail Transit is an urban rail transit system serving Wuhu City, Anhui Province, China. Its first line was put into operation on November 3, 2021, making Wuhu the 49th city in mainland China and the second city in Anhui Province to open urban rail transit. As of December 2021, there are a total of 2 operating lines of Wuhu Rail Transit, including Wuhu Rail Transit Line 1 and Wuhu Rail Transit Line 2, with a total of 35 stations, including 34 elevated stations and 1 underground station; The operating mileage of Wuhu Rail Transit is 46.2 kilometers. In 2021, the cumulative passenger flow of Wuhu Rail Transit was 2.944 million, with an average daily passenger flow of 51000; In 2022, the cumulative passenger flow of Wuhu Rail Transit was 22.783 million; The maximum daily passenger volume is 193600 people on February 5, 2022."
    },
    "reference": "http://www.wuhurailtransit.com/Home/Index/news/id/60.html",
    "justification": "Creating a Subway Route Map for Wuhu City."
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="wuhu">{¨svgViewBoxZoom¨¢1c¨svgViewBoxMin¨{´x´£W.6S´y´£-5h.-EW}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨shmetro-basic¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨right¨¨middle¨|¨白马山¨¨BAIMASHAN¨÷ßA»¢2u¢A5É¨stn_A8XIc2hHsH¨ßH¨bottom¨|¨芜湖南站¨¨Wuhunan Railway Station¨÷ßA»¢3Y¢9RÉ¨stn_26ZVoWSBWM¨—{ßG¨misc_node_rPoi140z6j¨ß8{ßE»ßFÉ´x´¢3E´y´¢97ß4¨facilities¨ßR{ß4¨railway¨}}}{ßG¨stn_MYuol5lAdp¨ß8{ßE»ßFÉ´x´¢42´y´¢8Yß4ßAßA{ßD|¨珩琅山路¨¨HENGLANGSHANLU¨÷ßB¨left¨ßCßI}}}{ßG¨misc_node_gV1_iQKcnX¨ß8{ßE»ßFÉ´x´¢2L´y´¢APß4¨gzmtr-line-badge¨ßY{ßD|¨1号线¨¨Line 1¨÷¨color¨|¨other¨ßc¨#c01723¨¨#fff¨÷}}}{ßG¨stn_Xhj7lLGUzt¨ß8{ßE»ßFÉ´x´º7´y´¢7pß4ßAßA{ßD|¨文津东路¨¨WENJINDONGLU¨÷ßBßWßCßI}}}{ßG¨stn_1jHlyWgy7F¨ß8{ßE»ßFÉ´x´º7´y´¢76ß4ßAßA{ßD|¨博览中心¨¨BOLANZHONGXIN¨÷ßBßWßCßI}}}{ßG¨stn_uJrzo2qA7P¨ß8{ßE»ßFÉ´x´º7´y´¢6Nß4ßAßA{ßD|¨红花山路¨¨HONGHUASHANLU¨÷ßBßWßCßI}}}{ßG¨stn_dLkSbFt_zj¨ß8{ßE»ßFÉ´x´º7´y´¢5eß4ßAßA{ßD|¨奥体中心¨¨AOTIZHONGXIN¨÷ßBßWßCßI}}}{ßG¨stn__vRIiYICow¨ß8{ßE»ßFÉ´x´º7´y´¢50ß4ßAßA{ßD|¨环城北路¨¨HUANCHENGBEILU¨÷ßBßWßCßI}}}{ßG¨stn_8AdX3de8Gf¨ß8{ßE»ßFÉ´x´¢3d´y´¢4bß4¨shmetro-int¨ßv{ßD|¨鸠兹广场¨¨JIUZIGUANGCHANG¨÷ßBßWßCßI¨rotate¨¤j¨height¨¤A¨width¨¤D}}}{ßG¨stn_ZS1pjgcoyh¨ß8{ßE»ßFÉ´x´º5´y´¢4Cß4ßAßA{ßD|¨中山北路¨¨ZHONGSHANBEILU¨÷ßBßWßCßI}}}{ßG¨stn_haQny_zPOu¨ß8{ßE»ßFÉ´x´º5´y´º3ß4ßAßA{ßD|¨赭山公园¨¨ZHESHANGONGYUAN¨÷ßBßWßCßI}}}{ßG¨stn_IoG4gdjsvW¨ß8{ßE»ßFÉ´x´º5´y´º1ß4ßAßA{ßD|¨赭山路¨¨ZHESHANLU¨÷ßBßWßCßI}}}{ßG¨stn_tCsg0S2dNu¨ß8{ßE»ßFÉ´x´º5´y´¢2Gß4ßAßA{ßD|¨赤铸山路¨¨CHIZHUSHANLU¨÷ßBßWßCßI}}}{ßG¨stn_s9HE3MH_1K¨ß8{ßE»ßFÉ´x´º5´y´¢1Xß4ßAßA{ßD|¨天门山路¨¨TIANMENSHANLU¨÷ßBßWßCßI}}}{ßG¨stn_tvjqZXmbLj¨ß8{ßE»ßFÉ´x´º5´y´¤tß4ßAßA{ßD|¨天柱山路¨¨TIANZHUSHANLU¨÷ßBßWßCßI}}}{ßG¨stn_gH754Htk7m¨ß8{ßE»ßFÉ´x´º5´y´¤Fß4ßAßA{ßD|¨港一路¨¨GANGYILU¨÷ßBßWßCßI}}}{ßG¨stn_RgbQoGb8c0¨ß8{ßE»ßFÉ´x´º5´y´¢-Pß4ßAßA{ßD|¨武夷山路¨¨WUYISHANLU¨÷ßBßWßCßI}}}{ßG¨stn_ETDGDQkK2V¨ß8{ßE»ßFÉ´x´º5´y´¢-13ß4ßAßA{ßD|¨裕安路¨¨YU'ANLU¨÷ßBßWßCßI}}}{ßG¨stn_Ylo1KOM5NL¨ß8{ßE»ßFÉ´x´º5´y´¢-1hß4ßAßA{ßD|¨港湾路¨¨GANGWANLU¨÷ßBßWßCßI}}}{ßG¨stn_0ynpUadlvJ¨ß8{ßE»ßFÉ´x´º5´y´¢-2Lß4ßAßA{ßD|¨鞍山路¨¨ANSHANLU¨÷ßBßWßCßI}}}{ßG¨stn_JNuv280fmK¨ß8{ßE»ßFÉ´x´º5´y´¢-2zß4ßAßA{ßD|¨龙山路¨¨LONGSHANLU¨÷ßBßWßCßI}}}{ßG¨stn_pRGJxs7P-f¨ß8{ßE»ßFÉ´x´¢3i´y´¢-3sß4ßAßA{ßD|¨衡山路¨¨HENGSHANLU¨÷ßBßHßCßI}}}{ßG¨stn_na8-eRKObb¨ß8{ßE»ßFÉ´x´¢4W´y´¢-4gß4ßAßA{ßD|¨华山路¨¨HUASHANLU¨÷ßBßHßCßI}}}{ßG¨stn_csIhQ8mFqE¨ß8{ßE»ßFÉ´x´¢47´y´¢-4Hß4ßAßA{ßD|¨泰山路¨¨TAISHANLU¨÷ßBßHßCßI}}}{ßG¨stn__jhYc7sOOI¨ß8{ßE»ßFÉ´x´ºF´y´¢-5Aß4ßAßA{ßD|¨保顺路¨¨BAOSHUNLU¨÷ßBßHßCßI}}}{ßG¨misc_node_Z6dDo64fDQ¨ß8{ßE»ßFÉ´x´¢5U´y´¢-5yß4ßYßY{ßD|ßZßa÷ßb|ßcþßdße÷}}}{ßG¨stn_HO7pHqatoK¨ß8{ßE»ßFÉ´x´ºH´y´ºHß4ßAßA{ßD|¨文化路¨¨WENHUALU¨÷ßBßIßCßM}}}{ßG¨stn_Ka_dNHfcCN¨ß8{ßE»ßFÉ´x´¢4v´y´ºUß4ßAßA{ßD|¨神山口¨¨SHENSHANKOU¨÷ßBßHßCßI}}}{ßG¨stn_Q-I4THue4o¨ß8{ßE»ßFÉ´x´ºZ´y´º3ß4ßAßA{ßD|¨芜湖火车站¨¨Wuhu Railway Station¨÷ßBßHßCßI}}}{ßG¨misc_node_BI5fq6gxOW¨ß8{ßE»ßFÉ´x´ºS´y´¢3Jß4ßRßR{ß4ßS}}}{ßG¨stn_X1WPW5lbHT¨ß8{ßE»ßFÉ´x´¢5F´y´¢2Qß4ßAßA{ßD|¨神山公园¨¨SHENSHANGONGYUAN¨÷ßBßIßC¨top¨}}}{ßG¨stn_otrejeEYB0¨ß8{ßE»ßFÉ´x´¢5y´y´ºcß4ßAßA{ßD|¨云从路¨¨YUNCONGLU¨÷ßBßIßCßM}}}{ßG¨stn_lDJ2-k8Dok¨ß8{ßE»ßFÉ´x´¢6h´y´ºcß4ßAßA{ßD|¨政务中心¨¨ZHENGWUZHONGXIN¨÷ßBßIßCß21}}}{ßG¨stn_w93Btc4d7W¨ß8{ßE»ßFÉ´x´¢7V´y´ºcß4ßAßA{ßD|¨海晏路¨¨HAIYANLU¨÷ßBßIßCßM}}}{ßG¨stn_uDnB7RO0hi¨ß8{ßE»ßFÉ´x´¢8E´y´ºcß4ßAßA{ßD|¨徽州路¨¨HUIZHOULU¨÷ßBßIßCß21}}}{ßG¨stn_axrxk27UDC¨ß8{ßE»ßFÉ´x´¢8x´y´ºcß4ßAßA{ßD|¨梦溪路¨¨MENGXILU¨÷ßBßIßCßM}}}{ßG¨stn_7jgUOSQ1EC¨ß8{ßE»ßFÉ´x´º4´y´¤Zß4ßAßA{ßD|¨万春湖路¨¨WANCHUNHULU¨÷ßBßIßCßM}}}{ßG¨misc_node_-38MDpo_Lq¨ß8{ßE»ßFÉ´x´ºh´y´¢13ß4¨virtual¨ß2L{}}}{ßG¨misc_node_For7_G8rbM¨ß8{ßE»ßFÉ´x´º6´y´ºcß4ß2Lß2L{}}}{ßG¨misc_node_-JL0PGHrUy¨ß8{ßE»ßFÉ´x´¢AA´y´¤Kß4ßYßY{ßD|¨2号线¨¨Line 2¨÷ßb|ßcþ¨#006db2¨ße÷}}}÷¨edges¨|¦ß8¦¨diagonal¨¦¨offsetFrom¨¨offsetTo¨¨roundCornerFactor¨¨startFrom¨‡¨reconcileId¨¨single-color¨¦ßb‡¨style¨ß4ßEßF‡ßG¨source¨¨target¨‡ÉÉ¤A´to´´´|ßcþ¨#c0172c¨ße÷ß2Yß2S»É¨line_d1MCwq8yUS¨ßPßTÉÉ¤A¨from¨´´|ßcþß2cße÷ß2Yß2S»É¨line_wOwWgrcwUC¨ßPßLÉÉ¤Aß2e´´|ßcþß2cße÷ß2Yß2S»É¨line_XOsd27ykZX¨ßfßTÉÉ¤Aß2e´´|ßcþß2cße÷ß2Yß2S»É¨line_YXiep6O8nL¨ßfßi—{ßG¨line_ablNXoil_Q¨ß2aßlß2bßiß8{ßE»ßFÉß4¨perpendicular¨ß2j{ß2Wß2eß2TÉß2UÉß2V£I.5K}ß2Zß2Yß2Y{ßb|ßcþß2cße÷}ß2X´´}}{ßG¨line_TA9roY5n_c¨ß2aßoß2bßlß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2cße÷}ß2X´´}}{ßG¨line_F5563EMexr¨ß2aßrß2bßoß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2cße÷}ß2X´´}}{ßG¨line_0N6F06ACdS¨ß2aßrß2bßuß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2cße÷}ß2X´´}}{ßG¨line_S5UMDhnFjx¨ß2aß11ß2bßuß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2cße÷}ß2X´´}}{ßG¨line_euzb8fOi18¨ß2aß14ß2bß11ß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2cße÷}ß2X´´}}{ßG¨line_asRxmjgIaG¨ß2aß17ß2bß14ß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2cße÷}ß2X´´}}{ßG¨line_pOG_fwISSl¨ß2aß1Aß2bß17ß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2cße÷}ß2X´´}}{ßG¨line_oHHn66iqGl¨ß2aß1Dß2bß1Aß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2cße÷}ß2X´´}}{ßG¨line_YeNXXgOdE6¨ß2aß1Dß2bß1Gß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2cße÷}ß2X´´}}{ßG¨line_BAHesIfzyb¨ß2aß1Gß2bß1Jß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2cße÷}ß2X´´}}{ßG¨line_zbA5z0SduP¨ß2aß1Mß2bß1Jß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2cße÷}ß2X´´}}{ßG¨line_rDMnuBL_wG¨ß2aß1Pß2bß1Mß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2cße÷}ß2X´´}}{ßG¨line_W4JeNZ2Bwl¨ß2aß1Sß2bß1Pß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2cße÷}ß2X´´}}{ßG¨line_wJPVM6l0Fl¨ß2aß1Yß2bß1Vß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2cße÷}ß2X´´}}{ßG¨line_zXJFgwUcTc¨ß2aß1Vß2bß1Sß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2cße÷}ß2X´´}}{ßG¨line_yitsDCcnPp¨ß2aß1bß2bß1Yß8{ßE»ßFÉß4ß2Sß2S{ß2W´to´ß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2cße÷}ß2X´´}}{ßG¨line_NSHAVcavfi¨ß2aß1hß2bß1bß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2cße÷}ß2X´´}}{ßG¨line_89QamyFfDV¨ß2aß1eß2bß1hß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2cße÷}ß2X´´}}{ßG¨line_4TI0MM1AoG¨ß2aß1eß2bß1kß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2cße÷}ß2X´´}}{ßG¨line_USKGbTiTnM¨ß2aßuß2bß1oß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2Qße÷}ß2X´´}}{ßG¨line_x2XwBkmIJP¨ß2aß1oß2bß1rß8{ßE»ßFÉß4ß2jß2j{ß2Wß2eß2TÉß2UÉß2VÝ2}ß2Zß2Yß2Y{ßb|ßcþß2Qße÷}ß2X´´}}{ßG¨line_ExxiLWzbJl¨ß2aß1uß2bß1rß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2Qße÷}ß2X´´}}{ßG¨line_id2WboxpOH¨ß2aß1yß2bß1uß8{ßE»ßFÉß4ß2jß2j{ß2Wß2eß2TÉß2UÉß2VÝ2}ß2Zß2Yß2Y{ßb|ßcþß2Qße÷}ß2X´´}}{ßG¨line_JcIHxTB51y¨ß2aß1yß2bß22ß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2Qße÷}ß2X´´}}{ßG¨line_ZYk6ddcOgk¨ß2aß22ß2bß25ß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2Qße÷}ß2X´´}}{ßG¨line_Vh7eMGPLxp¨ß2aß25ß2bß28ß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2Qße÷}ß2X´´}}{ßG¨line_uFy_wSRNZD¨ß2aß28ß2bß2Bß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2Qße÷}ß2X´´}}{ßG¨line_EG3mGgEppG¨ß2aß2Bß2bß2Eß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2V¤A}ß2Zß2Yß2Y{ßb|ßcþß2Qße÷}ß2X´´}}{ßG¨line_YCaa64gMms¨ß2aß2Hß2bß2Kß8{ßE»ßFÉß4ß2jß2j{ß2Wß2eß2TÉß2UÉß2VÝ2}ß2Zß2Yß2Y{ßb|ßcþß2Qße÷}ß2X´´}}{ßG¨line_W99qduT2oN¨ß2aß2Mß2bß2Eß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2Vº0}ß2Zß2Yß2Y{ßb|ßcþß2Qße÷}ß2X´´}}{ßG¨line_S1aYjOqkBm¨ß2aß2Mß2bß2Kß8{ßE»ßFÉß4ß2Sß2S{ß2Wß2eß2TÉß2UÉß2Vº0}ß2Zß2Yß2Y{ßb|ßcþß2Qße÷}ß2X´´}}÷}¨version¨¤E}</details>

**Comment by thekingofcity** [comment]
See #451
