### ISSUE TITLE
Resources: New template of osaka

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp-gallery#474]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[Osaka.txt](https://github.com/railmapgen/rmp-gallery/files/12299848/Osaka.txt)

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板没有问题，请您等待管理员最终汇入，感谢您的贡献。
