### ISSUE TITLE
Resources: New template of liuzhou

### ISSUE THREAD

**Issue by WaterLeee** [railmapgen/rmp-gallery#486]
[liuzhou.txt](https://github.com/railmapgen/rmp-gallery/files/12304843/liuzhou.txt)
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

**Comment by LittleLing03** [comment]
您好，我们暂不支持百度百科的来源，且柳州轨道交通尚未开通，我们暂不会汇入您的模板，感谢您的贡献。
