### ISSUE TITLE
Resources: Update template of hangzhou

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#495]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[1691650717383.txt](https://github.com/railmapgen/rmp-gallery/files/12309774/1691650717383.txt)

**Comment by thekingofcity** [comment]
Hi, we won't accept a reference from metroman. If you intend to update this due to problems, you need to provide creditworthy sources.
