### ISSUE TITLE
Resources: Update template of suzhou

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#504]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[1691772215755.txt](https://github.com/railmapgen/rmp-gallery/files/12323586/1691772215755.txt)

**Comment by 28yfang** [comment]
您好，您的模版无问题，请等待管理员最终确认并汇入。感谢您的贡献！
