### ISSUE TITLE
Resources: Update template of chengdu

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#509]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Note:** With effect from 13 August 2023.

**Do not edit lines below, they are meant for bots only!!!**

[1691838434863.txt](https://github.com/railmapgen/rmp-gallery/files/12327213/1691838434863.txt)

**Comment by langonginc** [comment]
感谢您的贡献，将稍后汇入。
