### ISSUE TITLE
Resources: Update template of hongkong

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#511]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[1691858023605.txt](https://github.com/railmapgen/rmp-gallery/files/12327825/1691858023605.txt)

**Comment by 28yfang** [comment]
您好，感谢您的贡献。
经检查，您的模版包含但不限于以下问题：
大水坑站英文名称错误，正确的因为Tai Shui Hang。
请您在修改后重新提交，并附上本issue号（#511），感谢！
