### ISSUE TITLE
Resources: New template of beijing

### ISSUE THREAD

**Issue by langonginc** [railmapgen/rmp-gallery#54]
<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Hong Kong",
        "zh-Hans": "香港",
        "zh-Hant": "香港",
        "ko": "홍콩"
    },
    "desc": {
        "en": "The Mass Transit Railway (MTR) is a major public transport network serving Hong Kong. Operated by the MTR Corporation Limited (MTRCL), it consists of heavy rail, light rail, and feeder bus service centred on a 10-line rapid transit network serving the urbanised areas of Hong Kong Island, Kowloon, and the New Territories. The system included 240.6 km (149.5 mi) of rail as of 2022 with 167 stations, including 98 heavy rail stations, 68 light rail stops and one high-speed rail terminus. https://en.m.wikipedia.org/wiki/MTR"
    },
    "reference": "https://www.mtr.com.hk/en/customer/services/system_map.html",
    "justification": "Add English Description"
}</details>

**Comment by 28yfang** [comment]
？你咋抄了我的

**Comment by thekingofcity** [comment]
🌚是上传一下北京的metadata，发给你的hk是参照用的
