### ISSUE TITLE
Resources: New template of daegu

### ISSUE THREAD

**Issue by axl099** [railmapgen/rmp-gallery#543]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**
[daegu.txt](https://github.com/railmapgen/rmp-gallery/files/12354585/daegu.txt)

**Comment by 28yfang** [comment]
Hello, you need to write what you added instead of "daegu". (_Add template of daegu_ will do)
