### ISSUE TITLE
Resources: New template of stpetersburg

### ISSUE THREAD

**Issue by YIYO1** [railmapgen/rmp-gallery#547]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "St. Petersburg"
    },
    "desc": {
        "en": "The Saint Petersburg Metro (Russian: Петербургский метрополитен, romanized: Peterburgskiy metropoliten) is a rapid transit system in Saint Petersburg, Russia. Construction began in early 1941, but was put on hold due to World War II and the subsequent Siege of Leningrad, during which the constructed stations were used as bomb shelters. It was finally opened on 15 November 1955.\n\nFormerly known as the Order of Lenin Leningrad Metro named after V. I. Lenin (Ленинградский Ордена Ленина Метрополитен имени В. И. Ленина), the system exhibits many typical Soviet designs and features exquisite decorations and artwork making it one of the most attractive and elegant metros in the world. Due to the city's unique geology, the Saint Petersburg Metro is also one of the deepest metro systems in the world and the deepest by the average depth of all the stations. The system's deepest station, Admiralteyskaya, is 86 metres (282 ft) below ground.\n\nThe network consists of 5 lines with a total length of 124 kilometres (77 mi). It has 72 stations including 7 transfer points. Serving about 2 million passengers daily, it is the 26th busiest metro system in the world."
    },
    "reference": "http://www.metro.spb.ru/",
    "justification": "Newly created St. Petersburg Metro map"
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="stpetersburg">{¨svgViewBoxZoom¨¢2a¨svgViewBoxMin¨{´x´£-Bu.-G8´y´£-58.-3E}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨shmetro-basic¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨right¨¨top¨|´´þ÷ßA»¢A0¢5KÉ¨stn_Cwy0lZCrbH¨ßH¨middle¨|¨亚历山大·涅夫斯基广场-1¨¨Площадь Александра Невского-1¨÷ßA»¢DE¢6hÉ¨stn_3zZoG-U_v-¨ßHßK|¨圈楼¨¨Гостиный двор¨÷ßA»¢7pº2É¨stn_4KVG1Gl1-q¨ßKßI|¨利戈夫斯基大道¨¨Лиговский проспкт¨÷ßA»¢Bm¢7BÉ¨stn_36UqdOTurg¨—{ßG¨stn_dIXsG9m62T¨ß8{ßE»ßFÉ´x´º3´y´¢6wß4¨shmetro-int¨ßV{ßD|´´þ÷ßBßHßCßI¨rotate¨¢1S¨height¨¤E¨width¨¤i}}}{ßG¨stn_PrvGV_kDZ8¨ß8{ßE»ßFÉ´x´º3´y´º4ß4ßAßA{ßD|´´þ÷ßBßHßCßK}}}{ßG¨stn_KnVDFjy04S¨ß8{ßE»ßFÉ´x´º3´y´º7ß4ßAßA{ßD|¨亚历山大·涅夫斯基广场-2¨¨Плщадь Алексндра Нвского-2¨÷ßBßHßC¨bottom¨}}}{ßG¨stn_MGNKdj_cp3¨ß8{ßE»ßFÉ´x´º1´y´º7ß4ßAßA{ßD|´´þ÷ßBßKßCßI}}}{ßG¨stn_KDjqQIhaCJ¨ß8{ßE»ßFÉ´x´º5´y´¢7Qß4ßVßV{ßD|´´þ÷ßBßHßCßIßWº9ßX¤EßY¤i}}}{ßG¨stn_xVmEEMV7Fo¨ß8{ßE»ßFÉ´x´º5´y´¢7fß4ßAßA{ßD|¨花园¨¨Садовая¨÷ßB¨left¨ßCßK}}}{ßG¨stn_2Ajsho-xBz¨ß8{ßE»ßFÉ´x´¢84´y´º7ß4ßVßV{ßD|´´þ÷ßBßHßCßIßWÉßX¤EßY¤i}}}{ßG¨stn_02Temb0D7d¨ß8{ßE»ßFÉ´x´º5´y´º7ß4ßAßA{ßD|¨干草广场¨¨Сення плщадь¨÷ßBßKßCßI}}}{ßG¨stn_yJsK3ADh0r¨ß8{ßE»ßFÉ´x´¢8J´y´º7ß4ßAßA{ßD|¨救世主¨¨Спсская¨÷ßBßHßCßK}}}{ßG¨stn_bM2oZoHnhs¨ß8{ßE»ßFÉ´x´¢4C´y´º2ß4ßAßA{ßD|¨瓦西里岛¨¨Василеостровская¨÷ßBßHßCßI}}}{ßG¨stn_BcKZSBW4xV¨ß8{ßE»ßFÉ´x´¢34´y´¢4Hß4ßAßA{ßD|¨海滨¨¨Приморская¨÷ßBßHßCßK}}}{ßG¨stn_5okfQRqTFV¨ß8{ßE»ßFÉ´x´ºF´y´¢39ß4ßAßA{ßD|¨泽尼特¨¨Зенит¨÷ßBßHßCßK}}}{ßG¨stn_PM2OXUDlrp¨ß8{ßE»ßFÉ´x´ºF´y´¢1wß4ßAßA{ßD|¨贝戈瓦亚¨¨Беговая¨÷ßBßHßCßK}}}{ßG¨stn_axkE7EiW9P¨ß8{ßE»ßFÉ´x´º3´y´¢92ß4ßAßA{ßD|¨耶利扎罗夫¨¨Елизаровская¨÷ßBßHßCßK}}}{ßG¨stn_KYzosruLnP¨ß8{ßE»ßFÉ´x´º3´y´º1ß4ßAßA{ßD|¨罗曼诺索夫¨¨Ломоносовская¨÷ßBßHßCßK}}}{ßG¨stn_QDO8zp_0yP¨ß8{ßE»ßFÉ´x´º3´y´¢Ayß4ßAßA{ßD|¨无产阶级¨¨Пролетарская¨÷ßBßHßCßK}}}{ßG¨stn_cDjteqw5i3¨ß8{ßE»ßFÉ´x´º3´y´¢Bwß4ßAßA{ßD|¨奥布霍沃¨¨Обухово¨÷ßBßHßCßK}}}{ßG¨stn_kgyJ_x5UdF¨ß8{ßE»ßFÉ´x´º3´y´¢Cuß4ßAßA{ßD|¨里巴茨科耶¨¨Рыбацкое¨÷ßBßHßCßK}}}{ßG¨stn_eIEx8n6LGF¨ß8{ßE»ßFÉ´x´¢GI´y´ºCß4ßAßA{ßD|¨新切尔卡瑟¨¨Новочеркасская¨÷ßBßHßCßK}}}{ßG¨stn_vU8lbdADT_¨ß8{ßE»ßFÉ´x´ºN´y´ºJß4ßAßA{ßD|¨拉多加¨¨Ладожская¨÷ßBßHßCßK}}}{ßG¨stn_XOzxqVowbv¨ß8{ßE»ßFÉ´x´ºN´y´º1ß4ßAßA{ßD|¨布尔什维克大道¨¨Проспект Большевиков¨÷ßBßHßCßK}}}{ßG¨stn_6qaO583fh9¨ß8{ßE»ßFÉ´x´ºN´y´ºKß4ßAßA{ßD|¨德宾科街¨¨Улица Дыбéнко¨÷ßBßHßCßK}}}{ßG¨stn_qTANYWOCrS¨ß8{ßE»ßFÉ´x´º5´y´¢9Mß4ßAßA{ßD|´´þ÷ßBßjßCßI}}}{ßG¨stn_u3-J6-k7Jg¨ß8{ßE»ßFÉ´x´ºB´y´¢9Wß4ßVßV{ßD|´´þ÷ßBßHßCßIßW¢2BßX¤EßY¤i}}}{ßG¨stn_qlONI4Jj_J¨ß8{ßE»ßFÉ´x´º5´y´ºOß4ßAßA{ßD|¨科技学院-2¨¨Технологический институт-2¨÷ßBßjßCßI}}}{ßG¨stn_dzLNAgU0fu¨ß8{ßE»ßFÉ´x´¢7V´y´¢9gß4ßAßA{ßD|¨科技学院-1¨¨Технологический институт-1¨÷ßBßjßCßK}}}{ßG¨stn_AzdlrFtGSV¨ß8{ßE»ßFÉ´x´¢97´y´ºCß4ßAßA{ßD|´´þ÷ßBßHßCßI}}}{ßG¨stn_S__Oo2DFd7¨ß8{ßE»ßFÉ´x´¢8x´y´¢8Eß4ßVßV{ßD|´´þ÷ßBßHßCßIßWºQßX¤EßY¤i}}}{ßG¨stn_Py4PMBpusD¨ß8{ßE»ßFÉ´x´ºT´y´ºCß4ßAßA{ßD|¨兹韦尼哥罗德¨¨Звенигородская¨÷ßBßHßCßK}}}{ßG¨stn_Sf0oeUMjIe¨ß8{ßE»ßFÉ´x´¢8n´y´¢8Oß4ßAßA{ßD|¨普希金¨¨Пушкинская¨÷ßBßjßCßK}}}{ßG¨stn_e78tlH46AA¨ß8{ßE»ßFÉ´x´¢6N´y´¢Aoß4ßAßA{ßD|¨波罗的海¨¨Балтийская¨÷ßBßjßCßK}}}{ßG¨stn_ENWxpn_oD9¨ß8{ßE»ßFÉ´x´¢5U´y´¢Bhß4ßAßA{ßD|¨纳尔瓦¨¨Нарвская¨÷ßBßjßCßK}}}{ßG¨stn_KUYLq9oMei¨ß8{ßE»ßFÉ´x´¢50´y´¢D4ß4ßAßA{ßD|¨基洛夫工厂¨¨Кировский заво́д¨÷ßBßjßCßK}}}{ßG¨stn_4FrmMi4dj2¨ß8{ßE»ßFÉ´x´ºc´y´¢E2ß4ßAßA{ßD|¨阿夫托沃¨¨Автово¨÷ßBßjßCßK}}}{ßG¨stn_ttQBJxm7Km¨ß8{ßE»ßFÉ´x´ºc´y´¢F0ß4ßAßA{ßD|¨列宁大道¨¨Ленинский проспект¨÷ßBßjßCßK}}}{ßG¨stn_bo26Y3hMS9¨ß8{ßE»ßFÉ´x´ºc´y´¢Fyß4ßAßA{ßD|¨老将大道¨¨Проспект Ветеранов¨÷ßBßjßCßK}}}{ßG¨stn_KTCcSZOWgv¨ß8{ßE»ßFÉ´x´º5´y´ºZß4ßAßA{ßD|¨伏龙芝¨¨Фрунзенская¨÷ßBßHßCßK}}}{ßG¨stn_cLenuXfVaY¨ß8{ßE»ßFÉ´x´º5´y´º6ß4ßAßA{ßD|¨莫斯科门¨¨Москвские ворта¨÷ßBßHßCßK}}}{ßG¨stn_Cm8XFXxUPn¨ß8{ßE»ßFÉ´x´º5´y´¢Ckß4ßAßA{ßD|¨电气力量¨¨Электросила¨÷ßBßHßCßK}}}{ßG¨stn_t45brDW4ZW¨ß8{ßE»ßFÉ´x´º5´y´¢Diß4ßAßA{ßD|¨胜利公园¨¨Парк Победы¨÷ßBßHßCßK}}}{ßG¨stn_qFA65X519I¨ß8{ßE»ßFÉ´x´º5´y´¢Egß4ßAßA{ßD|¨莫斯科¨¨Московская¨÷ßBßHßCßK}}}{ßG¨stn_EJgBN2tRip¨ß8{ßE»ßFÉ´x´º5´y´¢Feß4ßAßA{ßD|´明星´¨Звёздная¨÷ßBßHßCßK}}}{ßG¨stn_bzzsVL255n¨ß8{ßE»ßFÉ´x´º5´y´¢Gcß4ßAßA{ßD|¨库普辛诺¨¨Купчино¨÷ßBßHßCßK}}}{ßG¨stn_UZ2BbVPTfX¨ß8{ßE»ßFÉ´x´º5´y´¢55ß4ßVßV{ßD|´´þ÷ßBßHßCßIßWº9ßX¤EßY¤i}}}{ßG¨stn_Nn51CPLGIA¨ß8{ßE»ßFÉ´x´º5´y´º2ß4ßAßA{ßD|´´þ÷ßBßHßCßI}}}{ßG¨stn_AaEaDdOr-P¨ß8{ßE»ßFÉ´x´º5´y´¢4qß4ßAßA{ßD|¨涅瓦大街¨¨Невский проспе́кт¨÷ßBßHßCßI}}}{ßG¨stn_BvPh5lNThn¨ß8{ßE»ßFÉ´x´º5´y´¢3Yß4ßAßA{ßD|¨高尔基¨¨Горьковская¨÷ßBßHßCßK}}}{ßG¨stn_kirRciRC1I¨ß8{ßE»ßFÉ´x´º5´y´º0ß4ßAßA{ßD|¨彼得格勒¨¨Петроградская¨÷ßBßHßCßK}}}{ßG¨stn_VFyweInoyn¨ß8{ßE»ßFÉ´x´º5´y´¢1cß4ßAßA{ßD|´黑犀´¨Чёрная речка¨÷ßBßHßCßK}}}{ßG¨stn_gA4rc229GT¨ß8{ßE»ßFÉ´x´º5´y´¤eß4ßAßA{ßD|¨少先队¨¨Пионерская¨÷ßBßHßCßK}}}{ßG¨stn_qroaYYI424¨ß8{ßE»ßFÉ´x´º5´y´¢-Kß4ßAßA{ßD|´封邑´¨Удельная¨÷ßBßHßCßK}}}{ßG¨stn_ii_mrmrWha¨ß8{ßE»ßFÉ´x´º5´y´¢-1Iß4ßAßA{ßD|´湖区´¨Озерки¨÷ßBßHßCßK}}}{ßG¨stn_451DE1-cnD¨ß8{ßE»ßFÉ´x´º5´y´¢-2Gß4ßAßA{ßD|¨启蒙大道¨¨Проспéкт Просвещéния¨÷ßBßHßCßK}}}{ßG¨stn_Q4S-5XUBR5¨ß8{ßE»ßFÉ´x´º5´y´¢-3Oß4ßAßA{ßD|¨帕尔纳斯¨¨Парнас¨÷ßBßHßCßK}}}{ßG¨stn_sx5lObXCOG¨ß8{ßE»ßFÉ´x´º1´y´º7ß4ßAßA{ßD|´´þ÷ßBßKßCßI}}}{ßG¨stn_E5ih8cMV4x¨ß8{ßE»ßFÉ´x´¢9q´y´¢7Lß4ßVßV{ßD|´´þ÷ßBßHßCßKßWºQßX¤EßY¤i}}}{ßG¨stn_FmNuTzOxyX¨ß8{ßE»ßFÉ´x´º1´y´º7ß4ßAßA{ßD|¨陀思妥耶夫斯基¨¨Достовская¨÷ßBßKßCßI}}}{ßG¨stn_BrblQOxXMP¨ß8{ßE»ßFÉ´x´ºS´y´ºRß4ßAßA{ßD|¨弗拉基米尔¨¨Влади́мирская¨÷ßBßHßCßK}}}{ßG¨stn_iL3QEnwla9¨ß8{ßE»ßFÉ´x´¢AF´y´º2ß4ßVßV{ßD|´´þ÷ßBßHßCßIßWÉßX¤EßY¤i}}}{ßG¨stn_c8sqGJzpyW¨ß8{ßE»ßFÉ´x´º1´y´º2ß4ßAßA{ßD|¨起义广场¨¨Плóщадь Восстáния¨÷ßBßKßCßI}}}{ßG¨stn_mEJgYKo31y¨ß8{ßE»ßFÉ´x´¢AU´y´º2ß4ßAßA{ßD|¨马雅科夫斯基¨¨Маяковская¨÷ßBßHßCßd}}}{ßG¨stn_dU7EJzZpEN¨ß8{ßE»ßFÉ´x´º1´y´¢4Mß4ßAßA{ßD|¨切尔尼舍夫斯基¨¨Черныше́вская¨÷ßBßHßCßK}}}{ßG¨stn_ogqe3eWHgw¨ß8{ßE»ßFÉ´x´º1´y´¢3Oß4ßAßA{ßD|¨列宁广场¨¨Пло́щадь Ле́нина¨÷ßBßHßCßK}}}{ßG¨stn_vHW6te_r_n¨ß8{ßE»ßFÉ´x´º1´y´¤2Qß4ßAßA{ßD|´维堡´¨Вы́боргская¨÷ßBßHßCßK}}}{ßG¨stn_eI_rbzQ7q3¨ß8{ßE»ßFÉ´x´º1´y´º9ß4ßAßA{ßD|´森林´¨Лесна́я¨÷ßBßHßCßK}}}{ßG¨stn_EK4I3cvrJf¨ß8{ßE»ßFÉ´x´º1´y´¤Uß4ßAßA{ßD|¨奋勇广场¨¨Пло́щадь Му́жества¨÷ßBßHßCßK}}}{ßG¨stn_-SOPmWS2um¨ß8{ßE»ßFÉ´x´º1´y´¤-Uß4ßAßA{ßD|¨综合技术¨¨Политехни́ческая¨÷ßBßHßCßK}}}{ßG¨stn_hDNu8Y3dSi¨ß8{ßE»ßFÉ´x´º1´y´¢-1Sß4ßAßA{ßD|¨科学院¨¨Академи́ческая¨÷ßBßHßCßK}}}{ßG¨stn_9nM-gJoM2U¨ß8{ßE»ßFÉ´x´º1´y´¢-2Qß4ßAßA{ßD|¨公民大道¨¨Гражда́нский проспе́кт¨÷ßBßHßCßK}}}{ßG¨stn_bHptX1GTlY¨ß8{ßE»ßFÉ´x´º1´y´ºtß4ßAßA{ßD|¨杰维亚特金诺¨¨Девя́ткино¨÷ßBßHßCßK}}}{ßG¨stn_6BNEPeQaNv¨ß8{ßE»ßFÉ´x´¤AA´y´ºTß4ßAßA{ßD|¨支流运河¨¨Обводный канал¨÷ßBßHßCßI}}}{ßG¨stn_tbYTiXm9Sd¨ß8{ßE»ßFÉ´x´¤AZ´y´ºZß4ßAßA{ßD|¨沃尔科沃¨¨Волковская¨÷ßBßHßCßK}}}{ßG¨stn_Q9aKcobEvX¨ß8{ßE»ßFÉ´x´¤AZ´y´º6ß4ßAßA{ßD|¨布加勒斯特¨¨Бухарестская¨÷ßBßHßCßK}}}{ßG¨stn_DK4NwYwXCx¨ß8{ßE»ßFÉ´x´¤AZ´y´ºhß4ßAßA{ßD|´国际´¨Международная¨÷ßBßHßCßK}}}{ßG¨stn_8n7J2QKXXK¨ß8{ßE»ßFÉ´x´¤AZ´y´ºiß4ßAßA{ßD|¨荣耀大道¨¨Проспект Славы¨÷ßBßHßCßK}}}{ßG¨stn_-VBQOMX4Zy¨ß8{ßE»ßFÉ´x´¤AZ´y´ºjß4ßAßA{ßD|´多瑙´¨Дунайская¨÷ßBßHßCßK}}}{ßG¨stn_tlc1Dvyblw¨ß8{ßE»ßFÉ´x´¤AZ´y´ºkß4ßAßA{ßD|¨舒沙雷¨¨Шушары¨÷ßBßHßCßK}}}{ßG¨stn_NuBWJGMeVt¨ß8{ßE»ßFÉ´x´¤6D´y´¤63ß4ßAßA{ßD|¨海军总部¨¨Адмиралтейская¨÷ßBßHßCßK}}}{ßG¨stn_dBm8ZyHoz1¨ß8{ßE»ßFÉ´x´ºn´y´¤3sß4ßAßA{ßD|¨运动场¨¨Спорти́вная¨÷ßBßHßCßK}}}{ßG¨stn_a5Tra_6Iyn¨ß8{ßE»ßFÉ´x´ºn´y´¤2uß4ßAßA{ßD|¨契卡洛夫¨¨Чка́ловская¨÷ßBßHßCßK}}}{ßG¨stn_qSQ-P8neTk¨ß8{ßE»ßFÉ´x´ºn´y´ºIß4ßAßA{ßD|¨十字架岛¨¨Крестовский остров¨÷ßBßHßCßK}}}{ßG¨stn_kkMlnPzNig¨ß8{ßE»ßFÉ´x´ºn´y´¤yß4ßAßA{ßD|´旧村´¨Старая Деревня¨÷ßBßHßCßK}}}{ßG¨stn__HL77zYhJC¨ß8{ßE»ßFÉ´x´ºn´y´Éß4ßAßA{ßD|¨总督大道¨¨Комендантский проспект¨÷ßBßHßCßK}}}{ßG¨misc_node_i7jRBM9jIq¨ß8{ßE»ßFÉ´x´¤AK´y´¤5Zß4¨facilities¨ß41{ß4¨railway¨}}}{ßG¨misc_node_6JeFxc3wcg¨ß8{ßE»ßFÉ´x´ºu´y´ºTß4ß41ß41{ß4ß42}}}{ßG¨misc_node_suod7TvNZH¨ß8{ßE»ßFÉ´x´¤9C´y´ºXß4ß41ß41{ß4ß42}}}{ßG¨misc_node_w_na0SIFva¨ß8{ßE»ßFÉ´x´¤6X´y´ºKß4ß41ß41{ß4ß42}}}{ßG¨misc_node_EN0yCsF-r4¨ß8{ßE»ßFÉ´x´ºA´y´¢-3Yß4ß41ß41{ß4ß42}}}{ßG¨misc_node_G7BpgmNp-M¨ß8{ßE»ßFÉ´x´¤9b´y´¢-3dß4ß41ß41{ß4ß42}}}{ßG¨misc_node_1idfG6ljiE¨ß8{ßE»ßFÉ´x´¤9b´y´ºHß4ß41ß41{ß4ß42}}}{ßG¨misc_node_K-swQyKzlq¨ß8{ßE»ßFÉ´x´¤Ft´y´¤8sß4ß41ß41{ß4ß42}}}{ßG¨misc_node_ZjQp1yXown¨ß8{ßE»ßFÉ´x´¤68´y´¤Grß4ß41ß41{ß4¨airport¨}}}{ßG¨misc_node___kqVYkyYP¨ß8{ßE»ßFÉ´x´º4´y´¤H6ß4¨text¨ß4D{¨content¨¨LED¨¨fontSize¨¤G¨lineHeight¨¤G¨textAnchor¨ßK¨dominantBaseline¨ßK¨language¨´en´¨color¨|¨shanghai¨¨jsr¨¨#000000¨¨#fff¨÷ßWÉ¨italic¨«}}}{ßG¨misc_node_Fn5mgx1DHo¨ß8{ßE»ßFÉ´x´ºc´y´¤GNß4¨gzmtr-line-badge¨ß4S{ßD|¨1号线¨¨Line 1¨÷ß4L|¨other¨ß4V¨#ff0000¨ß4P÷}}}{ßG¨misc_node_peEKN73QCG¨ß8{ßE»ßFÉ´x´º5´y´¤Gwß4ß4Sß4S{ßD|¨2号线¨¨Line 2¨÷ß4L|ß4Vþ¨#365299¨ß4P÷}}}{ßG¨misc_node_9bYmx0A4nl¨ß8{ßE»ßFÉ´x´¤AZ´y´¤Ftß4ß4Sß4S{ßD|¨5号线¨¨Line 5¨÷ß4L|ß4Vþ¨#461D84¨ß4P÷}}}{ßG¨misc_node_XaOZxHDE9d¨ß8{ßE»ßFÉ´x´º3´y´¤D9ß4ß4Sß4S{ßD|¨3号线¨¨Line 3¨÷ß4L|ß4M¨sh19¨¨#48864D¨ß4P÷}}}{ßG¨misc_node_OThuQkWo_E¨ß8{ßE»ßFÉ´x´ºN´y´¤BDß4ß4Sß4S{ßD|¨4号线¨¨Line 4¨÷ß4L|ß4Vþ¨#ED6F00¨ß4P÷}}}{ßG¨misc_node_17q_roS8vV¨ß8{ßE»ßFÉ´x´ºF´y´¤1Iß4ß4Sß4S{ßD|ß4gß4h÷ß4L|ß4Mß4iß4jß4P÷}}}{ßG¨misc_node_dfSqn7QFji¨ß8{ßE»ßFÉ´x´ºn´y´¤-jß4ß4Sß4S{ßD|ß4cß4d÷ß4L|ß4Vþß4eß4P÷}}}{ßG¨misc_node_PyrYMpR5M7¨ß8{ßE»ßFÉ´x´º5´y´¢-47ß4ß4Sß4S{ßD|ß4Yß4Z÷ß4L|ß4Vþß4aß4P÷}}}{ßG¨misc_node_5QLMNXZrtm¨ß8{ßE»ßFÉ´x´º1´y´º14ß4ß4Sß4S{ßD|ß4Tß4U÷ß4L|ß4Vþß4Wß4P÷}}}{ßG¨misc_node_Datu8vuN2N¨ß8{ßE»ßFÉ´x´ºu´y´¢-50ß4ß4Dß4D{ß4E¨圣彼得堡地铁中文路线（2023.08.16）¨ß4G¤Zß4H¤Gß4IßKß4JßKß4K´en´ß4L|ß4Mß4Nß4Oß4P÷ßWÉß4Q«}}}{ßG¨misc_node_YiP9s_n9D3¨ß8{ßE»ßFÉ´x´¤2k´y´¤-yß4ß4Dß4D{ß4E´´ß4G¤Kß4H¤Gß4IßKß4JßKß4K´en´ß4L|ß4Mß4Nß4Oß4P÷ßWÉß4Q«}}}÷¨edges¨|¦ß8¦¨perpendicular¨¦¨offsetFrom¨¨offsetTo¨¨roundCornerFactor¨¨startFrom¨‡¨reconcileId¨¨single-color¨¦ß4L‡¨style¨ß4ßEßF‡ßG¨source¨¨target¨‡ÉÉ£I.5K¨from¨´´|ß4Mß4iß4jß4P÷ß52ß4w»É¨line_Cw8FMxuyde¨ßJßNÉÉÝ2ß56´´|ß4Mß4iß4jß4P÷ß52ß4w»É¨line_QmC7E7WRsQ¨ßQßJÉÉÝ2ß56´´|ß4Mß4iß4jß4P÷ß52ß4w»É¨line_-RfHwyKbus¨ß10ßuÉÉÝ2ß56´´|ß4Mß4iß4jß4P÷ß52ß4w»É¨line_LICAJNt6V1¨ßrßuÉÉÝ2ß56´´|ß4Mß4iß4jß4P÷ß52ß4w»É¨line_B9q3ouNFOT¨ßrßQÉÉÝ2ß56´´|ß4Mß4iß4jß4P÷ß52ß4w»É¨line_WSBfx3qlwc¨ßaß1FÉÉÝ2ß56´´|ß4M¨sh7¨ß4n¨#000¨÷ß52ß4w»É¨line_xvIdIz8RzY¨ßoßeÉÉÝ2ß56´´|ß4Mß5Dß4nß5E÷ß52ß4w»É¨line_XVarjFrpE1¨ßeßaÉÉÝ2ß56´´|ß4Mß5Dß4nß5E÷ß52ß4w»É¨line_5cP0SqHB5V¨ßaß1IÉÉÝ2ß56´´|ß4Mß5Dß4nß5E÷ß52ß4w»É¨line_BbGk38c8EW¨ß1Iß1RÉÉÝ2ß56´´|ß4M¨sh20¨ß4aß4P÷ß52ß4w»É¨line_Sfk-NA8oD2¨ßQßl—{ßG¨line_cAo67kS8iP¨ß54ß1Uß55ßeß8{ßE»ßFÉß4¨diagonal¨ß5M{ß50ß56ß4xÉß4yÉß4z¤A}ß53ß52ß52{ß4L|ß4M¨sh1¨¨#E3002B¨ß4P÷}ß51´´}}{ßG¨line_zsCwXh8d2l¨ß54ßgß55ß1Wß8{ßE»ßFÉß4ß4wß4w{ß50ß56ß4xÉß4yÉß4zÝ2}ß53ß52ß52{ß4L|ß4Mß5Jß4aß4P÷}ß51´´}}{ßG¨line_j9m06xSAQX¨ß54ßgß55ß1cß8{ßE»ßFÉß4ß5Mß5M{ß50ß56ß4xÉß4yÉß4z¤A}ß53ß52ß52{ß4L|ß4M¨sh4¨ß4eß4P÷}ß51´´}}{ßG¨line_DBAM21c0qa¨ß54ß1Zß55ß1kß8{ßE»ßFÉß4ß5Mß5M{ß50ß56ß4xÉß4yÉß4z¤A}ß53ß52ß52{ß4L|ß4Mß5Nß5Oß4P÷}ß51´´}}{ßG¨line_9rCj4YqPmS¨ß54ß1kß55ß1nß8{ßE»ßFÉß4ß5Mß5M{ß50ß56ß4xÉß4yÉß4z¤A}ß53ß52ß52{ß4L|ß4Mß5Nß5Oß4P÷}ß51´´}}{ßG¨line_KBFlqlJYL2¨ß54ß1qß55ß1nß8{ßE»ßFÉß4ß5Mß5M{ß50ß56ß4xÉß4yÉß4z¤A}ß53ß52ß52{ß4L|ß4Mß5Nß5Oß4P÷}ß51´´}}{ßG¨line_PbwMyibzM-¨ß54ß1qß55ß1zß8{ßE»ßFÉß4ß5Mß5M{ß50ß56ß4xÉß4yÉß4z¤A}ß53ß52ß52{ß4L|ß4Mß5Nß5Oß4P÷}ß51´´}}{ßG¨line_1eAuEiuvMj¨ß54ß1Wß55ß2Jß8{ßE»ßFÉß4ß4wß4w{ß50ß56ß4xÉß4yÉß4zÝ2}ß53ß52ß52{ß4L|ß4Mß5Jß4aß4P÷}ß51´´}}{ßG¨line_hGt3sneQ5l¨ß54ß2eß55ß2Oß8{ßE»ßFÉß4ß4wß4w{ß50ß56ß4xÉß4yÉß4zÝ2}ß53ß52ß52{ß4L|ß4Mß5Jß4aß4P÷}ß51´´}}{ßG¨line_J8_hVgncd-¨ß54ß2jß55ß2eß8{ßE»ßFÉß4ß4wß4w{ß50ß56ß4xÉß4yÉß4zÝ2}ß53ß52ß52{ß4L|ß4Mß5Jß4aß4P÷}ß51´´}}{ßG¨line_pu4RvRaUaO¨ß54ßJß55ß2oß8{ßE»ßFÉß4ß4wß4w{ß50ß56ß4xÉß4yÉß4zÝ2}ß53ß52ß52{ß4L|ß4Mß5Nß5Oß4P÷}ß51´´}}{ßG¨line_JRZWYRoRh0¨ß54ß3Kß55ß2vß8{ßE»ßFÉß4ß4wß4w{ß50ß56ß4xÉß4yÉß4zÝ2}ß53ß52ß52{ß4L|ß4Mß5Nß5Oß4P÷}ß51´´}}{ßG¨line_yc2ecn18db¨ß54ß3Nß55ß3Kß8{ßE»ßFÉß4ß4wß4w{ß50ß56ß4xÉß4yÉß4zÝ2}ß53ß52ß52{ß4L|ß4Mß5Nß5Oß4P÷}ß51´´}}{ßG¨line_NRCOmYwmfY¨ß54ß1eß55ß3Qß8{ßE»ßFÉß4ß5Mß5M{ß50ß56ß4xÉß4yÉß4z¤A}ß53ß52ß52{ß4L|ß4Mß5Rß4eß4P÷}ß51´´}}{ßG¨line_OBsWWms00P¨ß54ß3Tß55ß3Qß8{ßE»ßFÉß4ß5Mß5M{ß50ß56ß4xÉß4yÉß4z¤A}ß53ß52ß52{ß4L|ß4Mß5Rß4eß4P÷}ß51´´}}{ßG¨line_jBqV5lzpb9¨ß54ß3gß55ß3Tß8{ßE»ßFÉß4ß4wß4w{ß50ß56ß4xÉß4yÉß4zÝ2}ß53ß52ß52{ß4L|ß4Mß5Rß4eß4P÷}ß51´´}}{ßG¨line_T0wjGspgFE¨ß54ß3jß55ßgß8{ßE»ßFÉß4ß5Mß5M{ß50ß56ß4xÉß4yÉß4z¤A}ß53ß52ß52{ß4L|ß4Mß5Rß4eß4P÷}ß51´´}}{ßG¨line_Y54QpvBJrq¨ß54ß3mß55ß3jß8{ßE»ßFÉß4ß5Mß5M{ß50ß56ß4xÉß4yÉß4z¤A}ß53ß52ß52{ß4L|ß4Mß5Rß4eß4P÷}ß51´´}}{ßG¨line_IhK_osO1za¨ß54ß3xß55ß3mß8{ßE»ßFÉß4ß4wß4w{ß50ß56ß4xÉß4yÉß4zÝ2}ß53ß52ß52{ß4L|ß4Mß5Rß4eß4P÷}ß51´´}}÷}¨version¨¤F}</details>

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. St. Petersburg is merged and released :)
