### ISSUE TITLE
Resources: New template of amsterdam

### ISSUE THREAD

**Issue by axl099** [railmapgen/rmp-gallery#549]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[amsterdam.txt](https://github.com/railmapgen/rmp-gallery/files/12357591/amsterdam.txt)

**Comment by langonginc** [comment]
您好，这里似乎存在一些问题：

- 50/51线的 `Sloterdijk` , `Lelylaan` 和 `RAI` 车站分别被您标记为 `Station Sloterdijk` , `Station Lelylaan` 和 `Station RAI`.
- 53线的 `Venserpolder` 和 `Diemen Zuid` 车站顺序颠倒
- 51/53/54线的 `Amstel` 站被您标记为 `Amstelstation`

如上问题如有异议，可在下方评论您的依据。

请您修改后重新提交并补上本 issue 编号 `#549` ，感谢您的贡献！
