### ISSUE TITLE
Resources: New template of nantong

### ISSUE THREAD

**Issue by 203IhzElttil** [railmapgen/rmp-gallery#552]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "zh-CN": "南通",
        "en": "Nantong"
    },
    "desc": {
        "zh-CN": "南通轨道交通是中华人民共和国江苏省南通市的城市轨道交通系统，于2022年11月10日正式开通运行。\n\n南通轨道交通规划始于2011年，2014年8月获得国务院审批通过。规划由4条线路构成，全长170.8公里，此外还有153.2公里的市域线路。南通轨道交通一号线于2017年12月18日开工，2022年11月10日开通运营。目前的线路有已开通的1号线（南通西站 - 振兴路站）和建设中的2号线（幸福镇站 - 先锋镇站），共计59.55km。",
        "en": "Nantong Rail Transit is an urban rail transit system in Nantong City, Jiangsu Province, People's Republic of China (PRC), which was officially put into operation on November 10th, 2022.\n\nNantong rail transit planning began in 2011 and was approved by the State Council in August 2014. The plan consists of four lines, with a total length of 170.8 kilometers, in addition to 153.2 kilometers of municipal lines. Nantong Rail Transit Line 1 started on December 18, 2017 and opened for operation on November 10, 2022. At present, there are Line 1 which has been opened (Nantong West Railway Station-Zhenxing Road Station) and Line 2 which is under construction (Xingfu Town Station-Xianfeng Town Station), with a total length of 59.55km.\nhttps://zh.wikipedia.org/zh-cn/%E5%8D%97%E9%80%9A%E8%BD%A8%E9%81%93%E4%BA%A4%E9%80%9A"
    },
    "reference": "https://service.ntrailway.com/#/Siteguides",
    "justification": "1"
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="nantong">{¨svgViewBoxZoom¨¢1w¨svgViewBoxMin¨{´x´£-CA.-7R´y´£-7j.-3E}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|{¨key¨¨stn_bWSWOqN9HA¨ß8{¨visible¨»¨zIndex¨É´x´É´y´Éß4¨shmetro-basic¨ßE{¨names¨|¨和平桥¨¨Hepingqiao¨÷¨nameOffsetX¨¨middle¨¨nameOffsetY¨¨top¨}}}{ßA¨misc_node_2wrruBYB_p¨ß8{ßC»ßDÉ´x´¢-6N´y´¢-6hß4¨bjsubway-num-line-badge¨ßN{¨num¨Ê¨color¨|¨nantong¨¨nt1¨¨#e60012¨¨#fff¨÷}}}{ßA¨stn_NIl68GvkL5¨ß8{ßC»ßDÉ´x´¤o´y´Éß4ßEßE{ßF|¨友谊桥¨¨Youyiqiao ¨÷ßIßJßKßL}}}{ßA¨stn_hy-pWU-S_1¨ß8{ßC»ßDÉ´x´¢1c´y´Éß4ßEßE{ßF|¨学田¨¨Xuetian¨÷ßI¨right¨ßKßJ}}}{ßA¨stn_iLj1aYShJZ¨ß8{ßC»ßDÉ´x´¢-o´y´Éß4ßEßE{ßF|¨孩儿巷¨¨Hai'er Xiang¨÷ßIßJßK¨bottom¨}}}{ßA¨stn_caKJLDCc1F¨ß8{ßC»ßDÉ´x´¢-1S´y´Éß4ßEßE{ßF|¨茶庵殿¨¨Cha'an Dian¨÷ßIßJßKße}}}{ßA¨stn_qYgtN1yDq-¨ß8{ßC»ßDÉ´x´¢-2Q´y´¢-Pß4ßEßE{ßF|¨曙光¨¨Shuguang¨÷ßI¨left¨ßKßJ}}}{ßA¨stn_lnQsPQ73xq¨ß8{ßC»ßDÉ´x´¢-2p´y´¢-1Dß4ßEßE{ßF|¨城港路¨¨Chenggang Lu¨÷ßIßlßKßJ}}}{ßA¨stn_WusEcSb3bx¨ß8{ßC»ßDÉ´x´º6´y´¢-1cß4ßEßE{ßF|¨十里坊¨¨Shilifang¨÷ßIßlßKßJ}}}{ßA¨stn_nEB8Vq0l-c¨ß8{ßC»ßDÉ´x´¢-21´y´ºBß4ßEßE{ßF|¨普贤路¨¨Puxian Lu¨÷ßIßaßKßJ}}}{ßA¨stn_GsARS1-Kh_¨ß8{ßC»ßDÉ´x´º8´y´º8ß4ßEßE{ßF|¨唐闸公园¨¨Tangzha Park¨÷ßIßaßKßJ}}}{ßA¨stn_ml8cVPknOB¨ß8{ßC»ßDÉ´x´¢-5F´y´ºCß4ßEßE{ßF|¨南通西站¨¨Nantongxi Railway Station¨÷ßIßaßKßJ}}}{ßA¨stn_s9_tQgNYpX¨ß8{ßC»ßDÉ´x´¢-4R´y´ºDß4ßEßE{ßF|¨集成村¨¨Jichengcun¨÷ßIßaßKßJ}}}{ßA¨stn_LemQCbwx5h¨ß8{ßC»ßDÉ´x´¢-3d´y´ºEß4ßEßE{ßF|´河口´¨Hekou¨÷ßIßaßKßJ}}}{ßA¨stn_Gk1UAr3of4¨ß8{ßC»ßDÉ´x´¢-63´y´ºFß4ßEßE{ßF|´平潮´¨Pingchao¨÷ßIßaßKßJ}}}{ßA¨misc_node_nIe9coWto8¨ß8{ßC»ßDÉ´x´¢-5Z´y´¢-5Aß4¨facilities¨ß19{ß4¨railway¨}}}{ßA¨stn_boN-sHACtt¨ß8{ßC»ßDÉ´x´º3´y´¤oß4ßEßE{ßF|´文峰´¨Wenfeng¨÷ßIßaßKßJ}}}{ßA¨stn_-Gh-ecoPoW¨ß8{ßC»ßDÉ´x´º3´y´º3ß4ßEßE{ßF|¨慈善博物馆¨¨Charity Museum¨÷ßIßaßKßJ}}}{ßA¨stn_2ZZRtNgCee¨ß8{ßC»ßDÉ´x´º3´y´¢2Qß4ßEßE{ßF|¨政务中心¨¨Government Affairs Center¨÷ßIßlßKßJ}}}{ßA¨stn_9e5djJfhvo¨ß8{ßC»ßDÉ´x´º3´y´¢3Eß4ßEßE{ßF|¨世纪大道¨¨Shiji Dadao¨÷ßIßlßKßJ}}}{ßA¨stn_2SSzSvt7lh¨ß8{ßC»ßDÉ´x´ºI´y´ºJß4ßEßE{ßF|¨图书馆¨¨Nantong Library¨÷ßIßJßKße}}}{ßA¨stn_rtCzo7Fcy7¨ß8{ßC»ßDÉ´x´ºJ´y´ºJß4ßEßE{ßF|¨南通大学¨¨Nantong University¨÷ßIßJßKßL}}}{ßA¨stn_biW0IrEtQD¨ß8{ßC»ßDÉ´x´¢42´y´ºJß4ßEßE{ßF|¨盘香路¨¨Panxiang Lu¨÷ßIßJßKße}}}{ßA¨stn_ceo_-316cS¨ß8{ßC»ßDÉ´x´¢4q´y´ºJß4ßEßE{ßF|¨崇州大道¨¨Chongzhou Dadao¨÷ßIßJßKßL}}}{ßA¨stn_HRno-7o3bt¨ß8{ßC»ßDÉ´x´¢5e´y´¢3dß4ßEßE{ßF|¨静海大道¨¨Jinhai Dadao¨÷ßIßaßKßJ}}}{ßA¨stn_3UQWbg1STs¨ß8{ßC»ßDÉ´x´ºM´y´¢4Rß4ßEßE{ßF|¨大剧院¨¨Grand Theatre¨÷ßIßaßKßJ}}}{ßA¨stn_6_s3sGrKG0¨ß8{ßC»ßDÉ´x´ºM´y´¢5Fß4ßEßE{ßF|¨紫琅湖¨¨Zilang Lake¨÷ßIßaßKßJ}}}{ßA¨stn_H3zM6BeoEQ¨ß8{ßC»ßDÉ´x´ºM´y´¢63ß4ßEßE{ßF|¨能达商务区¨¨NETDA Businesses District¨÷ßIßaßKßJ}}}{ßA¨stn__uxtUvBHFK¨ß8{ßC»ßDÉ´x´ºM´y´¢6rß4ßEßE{ßF|¨航运学院¨¨Shipping College¨÷ßIßaßKßJ}}}{ßA¨stn_9uDPmmbbr_¨ß8{ßC»ßDÉ´x´ºM´y´¢7fß4ßEßE{ßF|¨振兴路¨¨Zhengxin Lu¨÷ßIßaßKßJ}}}{ßA¨misc_node_NLb6elpqFK¨ß8{ßC»ßDÉ´x´¢5P´y´¢7zß4ßNßN{ßOÊßP|ßQßRßSßT÷}}}{ßA¨misc_node_hKP1XI7nwa¨ß8{ßC»ßDÉ´x´¢84´y´ºMß4¨virtual¨ß1s{}}}{ßA¨misc_node_2yRkxj26JC¨ß8{ßC»ßDÉ´x´º3´y´¢7Gß4ß1sß1s{}}}{ßA¨misc_node_AZBCrrX_Oj¨ß8{ßC»ßDÉ´x´¢-42´y´º3ß4ß1sß1s{}}}{ßA¨misc_node_PUBjIUaK8V¨ß8{ßC»ßDÉ´x´ºV´y´º9ß4ß1sß1s{}}}{ßA¨misc_node_5zECrH-mvl¨ß8{ßC»ßDÉ´x´¢-7f´y´ºBß4ß1sß1s{}}}{ßA¨misc_node_92dFMj7Mu7¨ß8{ßC»ßDÉ´x´º6´y´¢-7Gß4ß1sß1s{}}}{ßA¨misc_node_WEjR3pkoCl¨ß8{ßC»ßDÉ´x´º7´y´º9ß4ß1sß1s{}}}{ßA¨misc_node_Q0-rQEiaxH¨ß8{ßC»ßDÉ´x´ºD´y´ºEß4ß1sß1s{}}}{ßA¨misc_node_NUyiWSyX23¨ß8{ßC»ßDÉ´x´ºC´y´ºEß4ß1sß1s{}}}{ßA¨misc_node_1LWqiQdSok¨ß8{ßC»ßDÉ´x´ºE´y´¢-3Eß4ß1sß1s{}}}{ßA¨misc_node_avD_B6X8IK¨ß8{ßC»ßDÉ´x´ºF´y´ºEß4ß1sß1s{}}}{ßA¨misc_node_IqGwaJx94Z¨ß8{ßC»ßDÉ´x´¢-6r´y´¢-84ß4ß1sß1s{}}}{ßA¨misc_node_UB8jDkFJwu¨ß8{ßC»ßDÉ´x´º6´y´ºLß4ß1sß1s{}}}{ßA¨misc_node_Ry0VMdiK0O¨ß8{ßC»ßDÉ´x´ºZ´y´ºAß4ß1sß1s{}}}{ßA¨misc_node_GgY4GdGumR¨ß8{ßC»ßDÉ´x´¢-6S´y´ºaß4ß1sß1s{}}}{ßA¨misc_node_Zm3d_dZTvC¨ß8{ßC»ßDÉ´x´¢-C6´y´º6ß4ß1sß1s{}}}{ßA¨misc_node_Z3wVp0Fn_Z¨ß8{ßC»ßDÉ´x´ºc´y´º4ß4¨text¨ß29{¨content¨´长´¨fontSize¨º3¨lineHeight¨¤G¨textAnchor¨ßJ¨dominantBaseline¨ßJ¨language¨´zh´ßP|¨other¨ß2G¨#e1ffff¨ßT÷¨rotate¨É¨italic¨«}}}{ßA¨misc_node_rBb9d9xCA-¨ß8{ßC»ßDÉ´x´º9´y´ºQß4ß29ß29{ß2A´江´ß2Bº3ß2C¤Gß2DßJß2EßJß2F´zh´ßP|ß2Gþß2HßT÷ß2IÉß2J«}}}{ßA¨misc_node_Ula7qfH8XM¨ß8{ßC»ßDÉ´x´º3´y´¢AUß4ß1sß1s{}}}÷¨edges¨|¦ß8¦¨diagonal¨¦¨offsetFrom¨¨offsetTo¨¨roundCornerFactor¨¨startFrom¨‡¨reconcileId¨¨single-color¨¦ßP‡¨style¨ß4ßCßD‡ßA¨source¨¨target¨‡ÉÉ¤A¨from¨´´|ßQßRßSßT÷ß2Tß2N»É¨line_pIyU1xwvI6¨ßBßUÉÉ¤Aß2X´´|ßQßRßSßT÷ß2Tß2N»É¨line_4Ou_UhkJf4¨ßUßXÉÉ¤Aß2X´´|ßQßRßSßT÷ß2Tß2N»É¨line_JRsFX-kGXT¨ßbßBÉÉ¤Aß2X´´|ßQßRßSßT÷ß2Tß2N»É¨line_dFE3wTFItc¨ßfßbÉÉ¤Aß2X´´|ßQßRßSßT÷ß2Tß2N»É¨line_JiKozChy_b¨ßfßi—{ßA¨line_PnbXwYL_u-¨ß2Vßiß2Wßmß8{ßC»ßDÉß4¨ro-perp¨ß2e{ß2Rß2Xß2OÉß2PÉß2Q£I.5K}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_CC-V3f0f_q¨ß2Vßpß2Wßmß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_IoQ2T-t0F0¨ß2Vßpß2Wßsß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_8U76__3tzO¨ß2Vßsß2Wßvß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_66QmjA85lP¨ß2Vßvß2Wß14ß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_E0M_JEwQto¨ß2Vß11ß2Wß14ß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_8HrQpwv35P¨ß2Vßyß2Wß11ß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_S8hsC4R8n0¨ß2Vßyß2Wßyß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line__oCLxbqWRU¨ß2Vßyß2Wß16ß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_fPMP7-3F_n¨ß2VßXß2Wß1Bß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_yLPBckzmyu¨ß2Vß1Bß2Wß1Dß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_4u4D6UKFa0¨ß2Vß1Dß2Wß1Gß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_9LXYI51aXB¨ß2Vß1Gß2Wß1Jß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_aEOMNGji1S¨ß2Vß1Jß2Wß1Mß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_Eh7TizimnY¨ß2Vß1Mß2Wß1Pß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_Qo_B2jPPxm¨ß2Vß1Pß2Wß1Sß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_QxDP_NWgtc¨ß2Vß1Sß2Wß1Vß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_F9X_7Ah2Bf¨ß2Vß1Vß2Wß1Yß8{ßC»ßDÉß4¨perpendicular¨ß2w{ß2Rß2Xß2OÉß2PÉß2QÎ}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_3WA-yBGSJz¨ß2Vß1Yß2Wß1bß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_wkblIjNtU0¨ß2Vß1bß2Wß1eß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_UO90THeXg0¨ß2Vß1eß2Wß1hß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_S7N2-hG3w2¨ß2Vß1hß2Wß1kß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_lKSorUhI-5¨ß2Vß1kß2Wß1nß8{ßC»ßDÉß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß2Tß2T{ßP|ßQßRßSßT÷}ß2S´´}}{ßA¨line_JciNO7Feff¨ß2Vß1rß2Wß1tß8{ßC»ßDÄß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2U¨river¨ß2S´´ß33{ßP|¨shanghai¨ß33¨#B9E3F9¨ßT÷¨width¨¤A}}}{ßA¨line_9yBFFmkXTP¨ß2Vß1vß2Wß1uß8{ßC»ßDÄß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß33ß2S´´ß33{ßP|ß34ß33ß35ßT÷ß36¤F}}}{ßA¨line_wU3MtrY8ty¨ß2Vß1xß2Wß1wß8{ßC»ßDÄß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß33ß2S´´ß33{ßP|ß34ß33ß35ßT÷ß36¤A}}}{ßA¨line_gZNa6fQfTq¨ß2Vß1yß2Wß21ß8{ßC»ßDÄß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß33ß2S´´ß33{ßP|ß34ß33ß35ßT÷ß36Î}}}{ßA¨line_UsMoU0F-p1¨ß2Vß21ß2Wß1zß8{ßC»ßDÄß4ß2eß2e{ß2Rß2Xß2OÉß2PÉß2QÝ2}ß2Uß33ß2S´´ß33{ßP|ß34ß33ß35ßT÷ß36Î}}}{ßA¨line_LUHdJdRYQO¨ß2Vß20ß2Wß1zß8{ßC»ßDÄß4ß2eß2e{ß2Rß2Xß2OÉß2PÉß2QÝ2}ß2Uß33ß2S´´ß33{ßP|ß34ß33ß35ßT÷ß36Î}}}{ßA¨line_O2o5aKJdGH¨ß2Vß23ß2Wß22ß8{ßC»ßDÄß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß33ß2S´´ß33{ßP|ß34ß33ß35ßT÷ß36Î}}}{ßA¨line_gTCMfBkiTv¨ß2Vß26ß2Wß25ß8{ßC»ßDÄß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß33ß2S´´ß33{ßP|ß34ß33ß35ßT÷ß36Î}}}{ßA¨line_OSa402mV1L¨ß2Vß27ß2Wß24ß8{ßC»ßDÄß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß33ß2S´´ß33{ßP|ß34ß33ß35ßT÷ß36ºJ}}}{ßA¨line_Fmj1yw_ny1¨ß2Vß2Lß2Wß24ß8{ßC»ßDÄß4ß2Nß2N{ß2Rß2Xß2OÉß2PÉß2Q¤A}ß2Uß33ß2S´´ß33{ßP|ß34ß33ß35ßT÷ß36ºJ}}}{ßA¨line_Bw8WYM7FT1¨ß2Vß20ß2Wß22ß8{ßC»ßDÄß4ß2eß2e{ß2Rß2Xß2OÉß2PÉß2QÝ2}ß2Uß33ß2S´´ß33{ßP|ß34ß33ß35ßT÷ß36Î}}}÷}¨version¨¤F}</details>

**Comment by 203IhzElttil** [comment]
南通竟然没人做 我随便做一个看看

**Comment by thekingofcity** [comment]
嗨，证明需要被填写诸如New template for nantong之类的内容，单纯的数字不被允许 :)
