### ISSUE TITLE
Resources: Update template of qingdao

### ISSUE THREAD

**Issue by Minwtraft** [railmapgen/rmp-gallery#558]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[qingdao_6.txt](https://github.com/railmapgen/rmp-gallery/files/12368610/qingdao_6.txt)

**Comment by thekingofcity** [comment]
嗨，感谢贡献，由于青岛在审核期间有在您前的更新 #556 ，请您基于现在版本的青岛重新修改，否则上一个版本的变化将消失，带来的不便敬请谅解 :)
