### ISSUE TITLE
Resources: Update template of shijiazhuang

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#567]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[1692378488505.txt](https://github.com/railmapgen/rmp-gallery/files/12381558/1692378488505.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for the contribution. The update is merged and released :)
