### ISSUE TITLE
Author order

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#573]
There are more than 1 authors in some projects.
It is recommended to place the authors in order by their contributions.

**Comment by thekingofcity** [comment]
Hi, the contributors are sorted by their contribution time instead of the total contribution numbers for this single work :)

**Comment by Zhengyang-Rd** [comment]
I think this can encourage people to contribute positively :)

**Comment by thekingofcity** [comment]
> The initial author is not placed at front.

The work may look different after several updates. So there is no reason to put the initial author in the front.
