### ISSUE TITLE
Resources: Update template of chengdu

### ISSUE THREAD

**Issue by LiuYiLin-CA** [railmapgen/rmp-gallery#576]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[chengdu.txt](https://github.com/railmapgen/rmp-gallery/files/12387974/chengdu.txt)

**Comment by 28yfang** [comment]
您好，8号线二期与19号线未开通，请在开通后重新上传，感谢。
