### ISSUE TITLE
Resources: Update template of suzhou

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp-gallery#578]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[Suzhou.txt](https://github.com/railmapgen/rmp-gallery/files/12388050/Suzhou.txt)

**Comment by 28yfang** [comment]
火车站和汽车站标识将在上线后添加。

**Comment by langonginc** [comment]
感谢您的贡献！
