### ISSUE TITLE
Resources: New template of melbourne

### ISSUE THREAD

**Issue by Jimmilily** [railmapgen/rmp-gallery#584]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[melbourne.txt](https://github.com/railmapgen/rmp-gallery/files/12394103/melbourne.txt)

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板没有问题，请您等待管理员最终汇入，感谢您的贡献。
