### ISSUE TITLE
Resources: New template of nanjing

### ISSUE THREAD

**Issue by ulanbayar** [railmapgen/rmp-gallery#586]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[nanjing.txt](https://github.com/railmapgen/rmp-gallery/files/12394858/nanjing.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Nanjing is created with the first submission, see #271 for more details :) If there is something changed after that, please update that work :)
