### ISSUE TITLE
Resources: New template of jiwotuosi

### ISSUE THREAD

**Issue by 114514191981015** [railmapgen/rmp-gallery#603]

**Comment by thekingofcity** [comment]
Hi, you need to follow the instructions at https://railmapgen.github.io/?app=rmp-gallery to submit a new template :)

**Comment by 28yfang** [comment]
我怀疑这根本不是一个真实的城市……

**Comment by 114514191981015** [comment]
确实

**Comment by 114514191981015** [comment]
我是新手

**Comment by 114514191981015** [comment]
基沃托斯是一个来源于蔚蓝档案的游戏

**Comment by 114514191981015** [comment]
参考资料
https://mzh.moegirl.org.cn/%E8%94%9A%E8%93%9D%E6%A1%A3%E6%A1%88

**Comment by 114514191981015** [comment]
就是这个游戏
https://bluearchive-cn.com/

**Comment by 28yfang** [comment]
您好，很抱歉我们不会收录非现实世界的线路颜色。

**Comment by thekingofcity** [comment]
嗨，欢迎关注即将上线的幻想世界分区，在那里通过捐赠您可以上传任何任何符合条款的作品 :)
