### ISSUE TITLE
Resources: New template of Edinburgh

### ISSUE THREAD

**Issue by Tiger-Qiao** [railmapgen/rmp-gallery#622]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Edinburgh",
        "zh-CN": "爱丁堡",
        "zh-TW": "愛丁堡"
    },
    "desc": {
        "zh": "这两天在爱丁堡 录完展望视频就顺手做了一个 中文站名是自己翻译的（参考了wiki）",
        "en": "Edinburgh Tram Map of Chinese"
    },
    "reference": "https://zh.wikipedia.org/zh-hans/%E6%84%9B%E4%B8%81%E5%A0%A1%E9%9B%BB%E8%BB%8A",
    "justification": "TramMap"
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="edinburgh">{¨svgViewBoxZoom¨¢1I¨svgViewBoxMin¨{´x´£p.ET´y´£21.8H}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨shmetro-basic¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨right¨¨bottom¨|¨圣安德鲁广场¨¨St Andrew Square¨÷ßA»¢Br¢71É¨stn_h8rOHJSO8s¨ßH¨middle¨|¨皮卡第广场¨¨Picardy Place¨÷ßA»¢Ck¢6NÉ¨stn__TupoczUrV¨¨left¨¨top¨|¨麦当劳路¨¨McDonald Road¨÷ßA»¢Cz¢5ZÉ¨stn_kegF7S16W_¨ßQßR|¨贝尔福街¨¨Balfour Street¨÷ßA»¢DY¢50É¨stn_jaE8Erb6O1¨ßQßR|¨临海¨¨The Shore¨÷ßA»¢Eg¢3sÉ¨stn_8jB9RqWPGw¨ßHßM|¨利斯港¨¨Port of Leith¨÷ßA»¢Ev¢2kÉ¨stn_5ifFKm3f5N¨ßMßR|¨海运大厦¨¨Ocean Terminal¨÷ßA»¢E2¢2BÉ¨stn_E5X9gokkwx¨ßMßR|¨纽黑文¨¨Newhaven¨÷ßA»¢CuºEÉ¨stn_85DbqA_Vso¨ßMßR|¨王子街¨¨Princes Street¨÷ßA»¢Ajº2É¨stn_oAJCn1Lzz_¨ßMßR|¨西区¨¨West End¨÷ßA»¢9bº2É¨stn_fIzWyIZBRf¨ßQßR|¨干草市场¨¨Haymarket¨÷ßA»¢8O¢7LÉ¨stn_VPNDCLwRNE¨ßQßR|¨默里菲尔德体育中心¨¨Murrayfield Stadium¨÷ßA»¢7f¢84É¨stn_UM8uYR1_ic¨ßQßR|¨巴尔格林¨¨Balgreen¨÷ßA»¢6r¢8sÉ¨stn_4DBikckIq3¨ßQßR|¨萨顿¨¨Sauthton¨÷ßA»¢63¢9gÉ¨stn_DhSYj4r5Rr¨ßQßR|¨班克黑德¨¨Bankhead¨÷ßA»¢5K¢APÉ¨stn_WRD8KSywBf¨ßMßI|¨爱丁堡公园¨¨Edinburgh Park¨÷ßA»¢4H¢AtÉ¨stn_dmE0nbZjMg¨ßQßM|¨公园中心¨¨Edinburgh Park Central¨÷ßA»¢3T¢AKÉ¨stn_jSdq4G2p1V¨ßHßM|¨盖尔购物中心¨¨Gyle Centre¨÷ßA»ºU¢9RÉ¨stn_TN7pzTF0h6¨ßHßR|¨爱丁堡之门¨¨Edinburgh Gateway¨÷ßA»¢2p¢8nÉ¨stn_rfRD93k7rR¨ßMßR|¨戈加尔伯恩¨¨Gogarburn¨÷ßA»¢1wºYÉ¨stn_QIdKgvHTuY¨ßMßI|¨英格里斯顿停车场¨¨Ingliston Park &amp; Ride¨÷ßA»¢13ºYÉ¨stn_rE9Zo1l-pa¨ßQßM|¨爱丁堡机场¨¨Edinburgh Airport¨÷ßA»¤e¢7zÉ¨stn_kxbYcGmDil¨—{ßG¨misc_node_En-M3-sbPH¨ß8{ßE»ßFÉ´x´¢-o´y´¢7kß4¨facilities¨ß1R{ß4¨airport¨}}}{ßG¨misc_node_kSvRlDNC17¨ß8{ßE»ßFÉ´x´º1´y´¢76ß4ß1Rß1R{ß4¨railway¨}}}{ßG¨misc_node_Bcc7zOX3uI¨ß8{ßE»ßFÉ´x´ºe´y´ºMß4ß1Rß1R{ß4ß1U}}}{ßG¨misc_node_uGHVWIfQw9¨ß8{ßE»ßFÉ´x´ºX´y´¢8Jß4ß1Rß1R{ß4ß1U}}}{ßG¨misc_node_4lIvTMSdcX¨ß8{ßE»ßFÉ´x´¢-K´y´¢8Eß4¨shmetro-text-line-badge¨ß1Y{ßD|¨有轨电车¨¨Edinburgh Tram¨÷¨color¨|¨other¨ß1c¨#8d181b¨¨#fff¨÷}}}{ßG¨misc_node_iezbOn4O7N¨ß8{ßE»ßFÉ´x´¢CV´y´¢2Qß4ß1Yß1Y{ßD|ß1Zß1a÷ß1b|ß1cþß1dß1e÷}}}{ßG¨stn_H8ZHYEwnGc¨ß8{ßE»ßFÉ´x´¢E7´y´¢4Rß4ßAßA{ßD|¨步行街¨¨Foot of the Walk¨÷ßBßQßCßR}}}÷¨edges¨|{ßG¨line_9RwG9wlLdQ¨¨source¨ßL¨target¨ßPß8{ßE»ßFÉß4¨perpendicular¨ß1n{¨startFrom¨¨from¨¨offsetFrom¨É¨offsetTo¨É¨roundCornerFactor¨£I.5K}¨style¨¨single-color¨ß1u{ß1b|¨edinburgh¨¨tram¨ß1dß1e÷}¨reconcileId¨´´}}{ßG¨line_LfgBFHOspv¨ß1lßPß1mßaß8{ßE»ßFÉß4¨diagonal¨ß1z{ß1oß1pß1qÉß1rÉß1s¤A}ß1tß1uß1u{ß1b|ß1vß1wß1dß1e÷}ß1x´´}}{ßG¨line_idQTUqg6Tu¨ß1lßdß1mßaß8{ßE»ßFÉß4ß1zß1z{ß1oß1pß1qÉß1rÉß1s¤A}ß1tß1uß1u{ß1b|ß1vß1wß1dß1e÷}ß1x´´}}{ßG¨line_K9P-zzy0Zr¨ß1lßgß1mßdß8{ßE»ßFÉß4ß1nß1n{ß1oß1pß1qÉß1rÉß1sÝ2}ß1tß1uß1u{ß1b|ß1vß1wß1dß1e÷}ß1x´´}}{ßG¨line_Y4DDvxJLuo¨ß1lßjß1mßgß8{ßE»ßFÉß4ß1zß1z{ß1oß1pß1qÉß1rÉß1s¤A}ß1tß1uß1u{ß1b|ß1vß1wß1dß1e÷}ß1x´´}}{ßG¨line_yxl6eH7b-s¨ß1lßLß1mßpß8{ßE»ßFÉß4ß1zß1z{ß1oß1pß1qÉß1rÉß1s¤A}ß1tß1uß1u{ß1b|ß1vß1wß1dß1e÷}ß1x´´}}{ßG¨line_EBOls6Qq4R¨ß1lßpß1mßvß8{ßE»ßFÉß4ß1zß1z{ß1oß1pß1qÉß1rÉß1s¤A}ß1tß1uß1u{ß1b|ß1vß1wß1dß1e÷}ß1x´´}}{ßG¨line_KA2-KdD_pX¨ß1lß17ß1mßvß8{ßE»ßFÉß4ß1zß1z{ß1oß1pß1qÉß1rÉß1s¤A}ß1tß1uß1u{ß1b|ß1vß1wß1dß1e÷}ß1x´´}}{ßG¨line_Chye5zcZ5R¨ß1lß17ß1mß1Aß8{ßE»ßFÉß4ß1nß1n{ß1oß1pß1qÉß1rÉß1sÝ2}ß1tß1uß1u{ß1b|ß1vß1wß1dß1e÷}ß1x´´}}{ßG¨line_IpzXvY3UAG¨ß1lß1Gß1mß1Aß8{ßE»ßFÉß4ß1nß1n{ß1oß1pß1qÉß1rÉß1sÝ2}ß1tß1uß1u{ß1b|ß1vß1wß1dß1e÷}ß1x´´}}{ßG¨line_D9los9e_Q6¨ß1lß1Gß1mß1Pß8{ßE»ßFÉß4ß1nß1n{ß1oß1pß1qÉß1rÉß1sÝ2}ß1tß1uß1u{ß1b|ß1vß1wß1dß1e÷}ß1x´´}}÷}¨version¨¤G}</details>

**Comment by Windows-Taskmgr** [comment]
您好，我们建议中文站名与维基百科上的内容一致，所以我们建议把中文站名换成维基百科官方标准后重新提交，感谢您的贡献。
