### ISSUE TITLE
Resources: Update template of wuhu

### ISSUE THREAD

**Issue by TPCpp** [railmapgen/rmp-gallery#633]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "zh-Hans": "芜湖",
        "en": "Wuhu"
    },
    "desc": {
        "en": ""
    },
    "reference": "http://www.wuhurailtransit.com/Home/Index/news/id/60.html",
    "justification": "There was no map of Wuhu before."
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="wuhu">{¨svgViewBoxZoom¨¢1F¨svgViewBoxMin¨{´x´£-7X.-EN´y´£-IL.-Ei}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨shmetro-basic¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨right¨¨middle¨|¨白马山¨¨BAIMASHAN¨÷ßA»ÉÉÉ¨stn_Xmc5Mf5Qx8¨ßH¨bottom¨|¨芜湖南站¨¨Wuhunan Railway Station¨÷ßA»¤o¢-oÉ¨stn_8AphHtP3Ix¨¨left¨ßI|¨珩琅山路¨¨HENGLANGSHANLU¨÷ßA»¢1c¢-2QÉ¨stn_zyeHPjDi_P¨ßQßI|¨文津东路¨¨WENJINDONGLU¨÷ßA»º2¢-3EÉ¨stn_pMcYW-W3Cx¨—{ßG¨misc_node_dsmAj77OiF¨ß8{ßE»ßFÉ´x´¢-K´y´¤Kß4¨shmetro-num-line-badge¨ßY{¨num¨Ê¨color¨|¨shanghai¨¨sh1¨¨#E4002B¨¨#fff¨÷}}}{ßG¨stn_lASP0TPH5M¨ß8{ßE»ßFÉ´x´º2´y´¢-42ß4ßAßA{ßD|¨博览中心¨¨BOLANZHONGXIN¨÷ßBßQßCßI}}}{ßG¨stn_EgPiu5Iqje¨ß8{ßE»ßFÉ´x´º2´y´¢-4qß4ßAßA{ßD|¨红花山路¨¨HONGHUASHANLU¨÷ßBßQßCßI}}}{ßG¨stn_6-yydVuKl8¨ß8{ßE»ßFÉ´x´É´y´¢-AUß4ßAßA{ßD|¨赤铸山路¨¨CHIZHUSHANLE¨÷ßBßQßCßI}}}{ßG¨stn_VsJ4eMjfe4¨ß8{ßE»ßFÉ´x´É´y´¢-9gß4ßAßA{ßD|¨赭山路¨¨ZHESHANLU¨÷ßBßQßCßI}}}{ßG¨stn_GwPMRUUd-4¨ß8{ßE»ßFÉ´x´É´y´¢-8sß4ßAßA{ßD|¨赭山公园¨¨ZHESHANGONGYUAN¨÷ßBßQßCßI}}}{ßG¨stn_2dIyo_4AIc¨ß8{ßE»ßFÉ´x´É´y´¢-84ß4ßAßA{ßD|¨中山北路¨¨ZHONGSHANBEILU¨÷ßBßQßCßI}}}{ßG¨stn_TMwLKjVxof¨ß8{ßE»ßFÉ´x´¤o´y´¢-7Gß4¨shmetro-int¨ßy{ßD|¨鸠兹广场¨¨JIUZIGUANGCHANG¨÷ßBßQßCßI¨rotate¨É¨height¨¤A¨width¨¤D}}}{ßG¨stn_LBfCePaL4o¨ß8{ßE»ßFÉ´x´º2´y´¢-6Sß4ßAßA{ßD|¨环城北路¨¨HUANCHENGBEILU¨÷ßBßQßCßI}}}{ßG¨stn_CUp6-S23db¨ß8{ßE»ßFÉ´x´º2´y´¢-5eß4ßAßA{ßD|¨奥体中心¨¨AOTIZHONGXIN¨÷ßBßQßCßI}}}{ßG¨stn_9ds-7sChph¨ß8{ßE»ßFÉ´x´É´y´¢-Gwß4ßAßA{ßD|¨龙山路¨¨LONGSHANLU¨÷ßBßQßCßI}}}{ßG¨stn_p2_TUb_cTu¨ß8{ßE»ßFÉ´x´É´y´¢-G8ß4ßAßA{ßD|¨鞍山路¨¨ANSHANLU¨÷ßBßQßCßI}}}{ßG¨stn_hqN-8Xu6HC¨ß8{ßE»ßFÉ´x´É´y´¢-FKß4ßAßA{ßD|¨港湾路¨¨GANGWANLU¨÷ßBßQßCßI}}}{ßG¨stn_wi7PLj9NHx¨ß8{ßE»ßFÉ´x´É´y´¢-EWß4ßAßA{ßD|¨裕安路¨¨YU'ANLU¨÷ßBßQßCßI}}}{ßG¨stn_p2zCWqqJIT¨ß8{ßE»ßFÉ´x´É´y´¢-Diß4ßAßA{ßD|¨武夷山路¨¨WUYISHANLU¨÷ßBßQßCßI}}}{ßG¨stn_cty8nWsc_e¨ß8{ßE»ßFÉ´x´É´y´¢-Cuß4ßAßA{ßD|¨港一路¨¨GANGYILU¨÷ßBßQßCßI}}}{ßG¨stn_qnWS99OL0-¨ß8{ßE»ßFÉ´x´É´y´¢-C6ß4ßAßA{ßD|¨天柱山路¨¨TIANZHUSHANLU¨÷ßBßQßCßI}}}{ßG¨stn_p4Yz4YrRwY¨ß8{ßE»ßFÉ´x´É´y´¢-BIß4ßAßA{ßD|¨天门山路¨¨TIANMENSHANLU¨÷ßBßQßCßI}}}{ßG¨stn_3Fwd8aI4Xl¨ß8{ßE»ßFÉ´x´¢3E´y´¢-Kyß4ßAßA{ßD|¨保顺路¨¨BAOSHUNLU¨÷ßBßQßCßI}}}{ßG¨stn_4_TCzoJslI¨ß8{ßE»ßFÉ´x´¢2V´y´¢-KAß4ßAßA{ßD|¨华山路¨¨HUASHANLU¨÷ßBßQßCßI}}}{ßG¨stn_WOM53Kb1Pd¨ß8{ßE»ßFÉ´x´º2´y´¢-JMß4ßAßA{ßD|¨泰山路¨¨TAISHANLU¨÷ßBßQßCßI}}}{ßG¨stn_yDxTSjRiLi¨ß8{ßE»ßFÉ´x´¤o´y´¢-IYß4ßAßA{ßD|¨衡山路¨¨HENGSHANLU¨÷ßBßQßCßI}}}{ßG¨stn_IU95Yx_2Sf¨ß8{ßE»ßFÉ´x´¢76´y´ºLß4ßAßA{ßD|¨万春湖路¨¨WANCHUNHULU\\¨÷ßBßQßCßI}}}{ßG¨stn_a7MnDv272P¨ß8{ßE»ßFÉ´x´¢6m´y´º8ß4ßAßA{ßD|¨徽州路¨¨HUIZHOULU¨÷ßBßIßCßM}}}{ßG¨stn_UuRFSHxsGu¨ß8{ßE»ßFÉ´x´¢5y´y´º8ß4ßAßA{ßD|ßjßk÷ßBßIßC¨top¨}}}{ßG¨stn_567zv3FLxN¨ß8{ßE»ßFÉ´x´¢5A´y´º8ß4ßAßA{ßD|¨海晏路¨¨HAIYANLU¨÷ßBßIßCßM}}}{ßG¨stn_U8N_6Xru-9¨ß8{ßE»ßFÉ´x´¢4M´y´º8ß4ßAßA{ßD|¨政务中心¨¨ZHENGWUZHONGXIN¨÷ßBßIßCß1r}}}{ßG¨stn_QZjMiavyIw¨ß8{ßE»ßFÉ´x´¢3Y´y´º8ß4ßAßA{ßD|¨云从路¨¨YUNCONGLU1¨÷ßBßIßCßM}}}{ßG¨stn_sMv7zDCgzL¨ß8{ßE»ßFÉ´x´¢2k´y´º8ß4ßAßA{ßD|¨神山公园¨¨SHENSHANGONGYUAN¨÷ßBßIßCß1r}}}{ßG¨stn_YAKtr3Cky0¨ß8{ßE»ßFÉ´x´¢2Q´y´ºAß4ßAßA{ßD|¨芜湖火车站¨¨Wuhu Railway Station¨÷ßBßHßCßI}}}{ßG¨stn_ZS72cPe4R6¨ß8{ßE»ßFÉ´x´ºa´y´ºBß4ßAßA{ßD|¨神山口¨¨SHENSHANKOU¨÷ßBßHßCßI}}}{ßG¨stn_-sFXhVt84v¨ß8{ßE»ßFÉ´x´¢26´y´ºCß4ßAßA{ßD|¨文化路¨¨WENHUALU¨÷ßBßHßCßM}}}{ßG¨misc_node_ZdAlPNOeB7¨ß8{ßE»ßFÉ´x´¢2p´y´¢-Lhß4ßYßY{ßZÊßa|ßbßcßdße÷}}}{ßG¨misc_node_uQ1JAVIHLQ¨ß8{ßE»ßFÉ´x´¢7L´y´¢-CLß4ßYßY{ßZËßa|¨other¨ß2F¨#4a86e8¨ße÷}}}÷¨edges¨|¦ß8¦¨diagonal¨¦¨offsetFrom¨¨offsetTo¨¨roundCornerFactor¨¨startFrom¨‡¨reconcileId¨¨single-color¨¦ßa‡¨style¨ß4ßEßF‡ßG¨source¨¨target¨‡ÉÉ¤A¨from¨´´|ßbßc¨#E3002B¨ße÷ß2Oß2I»É¨line_dMym6wrSty¨ßLßPÉÉ¤Aß2S´´|ß2Fþ¨#e3002b¨ße÷ß2Oß2I»É¨line_KptP3PBlda¨ßTßPÉÉ¤Aß2S´´|ß2Fþß2Vße÷ß2Oß2I»É¨line_PmdP7arghY¨ßTßWÉÉ¤Aß2S´´|ß2Fþß2Vße÷ß2Oß2I»É¨line_aaUNhOqKOO¨ßWßfÉÉ¤Aß2S´´|ß2Fþß2Vße÷ß2Oß2I»É¨line_5-7QQ7ri3M¨ßfßiÉÉ¤Aß2S´´|ß2Fþß2Vße÷ß2Oß2I»É¨line_RsgzIKTQfg¨ßiß17ÉÉ¤Aß2S´´|ß2Fþß2Vße÷ß2Oß2I»É¨line_aJJGOI5W2k¨ß17ß14ÉÉ¤Aß2S´´|ß2Fþß2Vße÷ß2Oß2I»É¨line_DYhJPicqhB¨ßlßoÉÉ¤Aß2S´´|ß2Fþß2Vße÷ß2Oß2I»É¨line_Nmz9Icjk1Q¨ßoßrÉÉ¤Aß2S´´|ß2Fþß2Vße÷ß2Oß2I»É¨line_Wa5-Pgezhc¨ßrßuÉÉ¤Aß2S´´|ß2Fþß2Vße÷ß2Oß2I»É¨line__vL7JKW1-G¨ßußxÉÉ¤Aß2S´´|ß2Fþß2Vße÷ß2Oß2I»É¨line_6dgV1-GzsT¨ßxß14ÉÉ¤Aß2S´´|ß2Fþß2Vße÷ß2Oß2I»É¨line_pxgkp8jnhv¨ß1Aß1DÉÉ¤Aß2S´´|ß2Fþß2Vße÷ß2Oß2I»É¨line_Y7ipEO3TOo¨ß1Aß1YÉÉ¤Aß2S´´|ß2Fþß2Gße÷ß2Oß2I»É¨line_F61BIB5ntP¨ß27ß2AÉÉ¤Aß2S´´|ß2Fþß2Gße÷ß2Oß2I»É¨line_xBSHI2iCuJ¨ßxß2AÉÉ¤Aß2S´´|ß2Fþß2Gße÷ß2Oß2I»É¨line_8pPeAaoGRy¨ß27ß24ÉÉ¤Aß2S´´|ß2Fþß2Gße÷ß2Oß2I»É¨line_imnUrYqbAV¨ß24ß21ÉÉ¤Aß2S´´|ß2Fþß2Gße÷ß2Oß2I»É¨line_1Nw4qQymAf¨ß1kß1kÉÉ¤Aß2S´´|ß2Fþß2Gße÷ß2Oß2I»É¨line_FXZ0LXp2A8¨ß21ß21ÉÉ¤Aß2S´´|ß2Fþß2Gße÷ß2Oß2I»É¨line_qf9qOZk1g5¨ß1nß1kÉÉ¤Aß2S´´|ßbßcß2Tße÷ß2Oß2I»É¨line_yvj8-jV4MN¨ß21ß21ÉÉ¤Aß2S´´|ß2Fþß2Gße÷ß2Oß2I»É¨line_Gwwn0nF4_H¨ß21ß1yÉÉ¤Aß2S´´|ß2Fþß2Gße÷ß2Oß2I»É¨line_Qy5Fp6Bn25¨ß1yß1vÉÉ¤Aß2S´´|ß2Fþß2Gße÷ß2Oß2I»É¨line_9lZZIX0vRo¨ß1vß1sÉÉ¤Aß2S´´|ß2Fþß2Gße÷ß2Oß2I»É¨line_LyUUGqp7aA¨ß1sß1qÉÉ¤Aß2S´´|ß2Fþß2Gße÷ß2Oß2I»É¨line__2YviEBkYo¨ß1qß1nÉÉ¤Aß2S´´|ß2Fþß2Vße÷ß2Oß2I»É¨line_zeuabz9Pyf¨ß1Vß1SÉÉ¤Aß2S´´|ß2Fþß2Vße÷ß2Oß2I»É¨line_lHj4TAor1P¨ßlß1VÉÉ¤Aß2S´´|ß2Fþß2Vße÷ß2Oß2I»É¨line_Y4P48MorUN¨ß1Sß1PÉÉ¤Aß2S´´|ß2Fþß2Vße÷ß2Oß2I»É¨line__SPjbb-dsm¨ß1Pß1MÉÉ¤Aß2S´´|ß2Fþß2Vße÷ß2Oß2I»É¨line_mwfwhBFxWu¨ß1Jß1GÉÉ¤Aß2S´´|ß2Fþß2Vße÷ß2Oß2I»É¨line_c6q6h97fYM¨ß1Mß1JÉÉ¤Aß2S´´|ß2Fþß2Vße÷ß2Oß2I»É¨line_jKIfY9Qo9o¨ß1Gß1D—÷}¨version¨¤H}</details>

**Comment by thekingofcity** [comment]
Hi, what did you changed? There is already Wuhu in Gallery :(
