### ISSUE TITLE
Resources: Update template of chongqing

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#637]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

[1693369346939.txt](https://github.com/railmapgen/rmp-gallery/files/12471652/1693369346939.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your work is merged and will be released soon :)
