### ISSUE TITLE
Resources: New template of changzhou

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmp-gallery#66]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Changzhou",
        "ko": "창저우",
        "zh-Hans": "常州",
        "zh-Hant": "常州"
    },
    "desc": {
        "en": "The Changzhou Metro is a rapid transit system in Changzhou, Jiangsu province, China. The system started operation on 21 September 2019, with the opening of its first line, Line 1 becoming the 35th city in China with a subway in Mainland China. https://en.wikipedia.org/wiki/Changzhou_Metro",
        "ko": "창저우 지하철은 중화인민공화국 장쑤성 창저우시의 도시 철도이다. https://ko.wikipedia.org/wiki/%EC%B0%BD%EC%A0%80%EC%9A%B0_%EC%A7%80%ED%95%98%EC%B2%A0",
        "zh-Hans": "常州地铁是中华人民共和国江苏省常州市的城市轨道交通系统，于2019年9月21日随1号线开通正式投入运营。至2021年，有运营2条线路。https://zh.wikipedia.org/wiki/%E5%B8%B8%E5%B7%9E%E5%9C%B0%E9%93%81",
        "zh-Hant": "常州地鐵是中華人民共和國江蘇省常州市的城市軌道交通系統，於2019年9月21日隨1號線開通正式投入運營。至2021年，有運營2條線路。https://zh.wikipedia.org/wiki/%E5%B8%B8%E5%B7%9E%E5%9C%B0%E9%93%81"
    },
    "reference": "https://en.wikipedia.org/wiki/Changzhou_Metro",
    "justification": "Add Changzhou Metro Template"
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="changzhou">{¨svgViewBoxZoom¨¤h¨svgViewBoxMin¨{´x´£-I.-2I´y´£8T.ES}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨bjsubway-basic¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨¨open¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨left¨¨middle¨|¨森林公园¨¨Forest Park¨÷»ßA»¢3E¢4CÉ¨stn_E93vgqHFOu¨ßIßJ|¨新龙¨¨Xinlong¨÷»ßA»º0¢4lÉ¨stn_A6BcYcmLZA¨ßIßJ|¨旅游学校¨¨Tourism and Commerce Institute¨÷»ßA»º0¢5KÉ¨stn_bOxQmL1UY9¨ßIßJ|¨新桥¨¨Xinqiao¨÷»ßA»º0¢5tÉ¨stn_9CtgvIY2Cl¨ßJ¨bottom¨|¨常州北站¨¨Changzhou North\\Railway Station¨÷»ßA»¢3n¢6SÉ¨stn_Kp5jtLKkIg¨ßJ¨top¨|¨北郊中学¨¨Beijiao High School¨÷»ßA»¢4gº6É¨stn_8U_cdRox4B¨ßJßW|¨外国语学校¨¨Foreign Language\\School¨÷»ßA»¢5Zº6É¨stn_BG9k_Q3a7d¨¨right¨ßJ|¨环球港¨¨Global Harbor¨÷»ßA»¢6I¢76É¨stn_HcA5L-IPLL¨ßhßJ|¨新区公园¨¨Xinqu Park¨÷»ßA»º9¢7fÉ¨stn_RjKwmwSZso¨ßhßJ|¨河海¨¨Hehai¨÷»ßA»º9¢8EÉ¨stn_uXpfQJgN2h¨ßhßJ|¨奥体中心¨¨Olympic Sports Center¨÷»ßA»º9¢8nÉ¨stn_Vr1epKBSlI¨ßhßJ|¨市民广场¨¨Citizens' Square¨÷»ßA»º9¢9MÉ¨stn_pLLNaDgmDY¨ßhßJ|¨翠竹¨¨Cuizhu¨÷»ßA»º9¢9vÉ¨stn_36KITYg9yg¨ßIßJ|¨常州火车站¨¨Changzhou Railway Station¨÷»ßA»º9¢AUÉ¨stn_OrjifBnCca¨ßhßJ|¨博爱路¨¨Boai Lu¨÷»ßA»º9¢B3É¨stn_pOt-m673zg¨—{ßH¨stn_pGzXY4ECsR¨ß8{ßF»ßGÉ´x´º9´y´¢Brß4¨bjsubway-int¨ß17{ßD|¨文化宫¨¨Cultural Palace¨÷ßBßhßCßa¨outOfStation¨«}}}{ßH¨stn_ZpoclZINdE¨ß8{ßF»ßGÉ´x´º9´y´¢CQß4ßAßA{ßD|¨同济桥¨¨Tongjiqiao¨÷ßBßIßCßJßE»}}}{ßH¨stn_amMP_VfMLV¨ß8{ßF»ßGÉ´x´º9´y´¢Czß4ßAßA{ßD|¨清凉寺¨¨Qingliang Temple¨÷ßBßIßCßJßE»}}}{ßH¨stn_FeKKsHWajt¨ß8{ßF»ßGÉ´x´º9´y´¢DYß4ßAßA{ßD|´茶山´¨Chashan¨÷ßBßIßCßJßE»}}}{ßH¨stn_8-F2OtBGUZ¨ß8{ßF»ßGÉ´x´º9´y´¢E7ß4ßAßA{ßD|¨聚湖路¨¨Juhu Lu¨÷ßBßIßCßJßE»}}}{ßH¨stn_kp9LbGRJXg¨ß8{ßF»ßGÉ´x´º9´y´¢Egß4ßAßA{ßD|´湖塘´¨Hutang¨÷ßBßIßCßJßE»}}}{ßH¨stn_tbpaZnMSK0¨ß8{ßF»ßGÉ´x´º9´y´¢FFß4ßAßA{ßD|¨新天地公园¨¨Xintiandi Park¨÷ßBßIßCßJßE»}}}{ßH¨stn_lrL3fsS1nz¨ß8{ßF»ßGÉ´x´º9´y´¢Foß4ßAßA{ßD|¨长虹路¨¨Changhong Lu¨÷ßBßIßCßJßE»}}}{ßH¨stn_6fiAxPrguz¨ß8{ßF»ßGÉ´x´º9´y´¢GNß4ßAßA{ßD|¨延政大道¨¨Yanzheng Dadao¨÷ßBßIßCßJßE»}}}{ßH¨stn_3wXLoQyscu¨ß8{ßF»ßGÉ´x´º9´y´¢Gwß4ßAßA{ßD|¨科教城北¨¨Kejiaocheng Bei¨÷ßBßIßCßJßE»}}}{ßH¨stn_3fay_si5_X¨ß8{ßF»ßGÉ´x´º9´y´¢HVß4ßAßA{ßD|¨科教城南¨¨Kejiaocheng Nan¨÷ßBßIßCßJßE»}}}{ßH¨stn_FkPpJpfmzP¨ß8{ßF»ßGÉ´x´º9´y´¢I4ß4ßAßA{ßD|¨武进沿江城际¨¨Wujin Yanjiang Railway Station¨÷ßBßIßCßJßE»}}}{ßH¨stn_3xx-nJCnSP¨ß8{ßF»ßGÉ´x´º9´y´¢Idß4ßAßA{ßD|¨阳湖路¨¨Yanghu Lu¨÷ßBßIßCßJßE»}}}{ßH¨stn_QWNsrz35jL¨ß8{ßF»ßGÉ´x´º9´y´¢JCß4ßAßA{ßD|¨南夏墅¨¨Nanxiashu¨÷ßBßIßCßJßE»}}}{ßH¨stn_Mq-7KxqL-4¨ß8{ßF»ßGÉ´x´¢5U´y´ºIß4ßAßA{ßD|¨南大街¨¨Nandajie¨÷ßBßJßCßaßE»}}}{ßH¨stn_5KBTnSI2Ss¨ß8{ßF»ßGÉ´x´º7´y´ºIß4ßAßA{ßD|´怀德´¨Huaide¨÷ßBßJßCßWßE»}}}{ßH¨stn_9lPog_RyDO¨ß8{ßF»ßGÉ´x´¢3s´y´¢BXß4ßAßA{ßD|´勤业´¨Qinye¨÷ßBßhßCßaßE»}}}{ßH¨stn_syYqHUS3Rd¨ß8{ßF»ßGÉ´x´¢3O´y´ºHß4ßAßA{ßD|´五星´¨Wuxing¨÷ßBßIßCßWßE»}}}{ßH¨stn_t3TBwtp00_¨ß8{ßF»ßGÉ´x´¢2u´y´¢AZß4ßAßA{ßD|¨海棠路¨¨Haitang Lu¨÷ßBßhßCßaßE»}}}{ßH¨stn_KAd-ZRWFM5¨ß8{ßF»ßGÉ´x´¢2Q´y´¢A5ß4ßAßA{ßD|¨青枫公园¨¨Qingfeng Park¨÷ßBßIßCßJßE»}}}{ßH¨stn_rxJIlEbd3E¨ß8{ßF»ßGÉ´x´ºA´y´ºIß4ßAßA{ßD|¨红梅公园¨¨Hongmei Park¨÷ßBßJßCßWßE»}}}{ßH¨stn_5AORC4l7yI¨ß8{ßF»ßGÉ´x´¢7k´y´¢BIß4ßAßA{ßD|¨五角场¨¨Wujiaochang¨÷ßBßhßCßJßE»}}}{ßH¨stn_Y3y94NzDck¨ß8{ßF»ßGÉ´x´¢8O´y´¢Aeß4ßAßA{ßD|¨三角场¨¨Sanjiaochang¨÷ßBßJßCßaßE»}}}{ßH¨stn_veNEqu7fG-¨ß8{ßF»ßGÉ´x´¢9C´y´¢Ayß4ßAßA{ßD|´紫云´¨Ziyun¨÷ßBßhßCßaßE»}}}{ßH¨stn_bgxQVeH-uR¨ß8{ßF»ßGÉ´x´¢9g´y´¢BSß4ßAßA{ßD|¨青洋路¨¨Qingyang Lu¨÷ßBßhßCßaßE»}}}{ßH¨stn_YXFOQNpT-i¨ß8{ßF»ßGÉ´x´ºG´y´¢Bmß4ßAßA{ßD|´丁堰´¨Dingyan¨÷ßBßJßCßWßE»}}}{ßH¨stn_RxikifsDYk¨ß8{ßF»ßGÉ´x´¢BN´y´ºmß4ßAßA{ßD|´潞城´¨Lucheng¨÷ßBßJßCßWßE»}}}{ßH¨stn_9SsDytZ2Ih¨ß8{ßF»ßGÉ´x´¢CG´y´ºmß4ßAßA{ßD|¨五一路¨¨Wuyi Lu¨÷ßBßJßCßaßE»}}}{ßH¨misc_node_u2kKituN_s¨ß8{ßF»ßGÉ´x´¢3J´y´¢4Hß4¨bjsubway-num-line-badge¨ß2N{¨num¨Ê¨color¨|¨changzhou¨¨cz1¨¨#cd5c5c¨¨#fff¨÷}}}{ßH¨misc_node_nBB6A7SpUq¨ß8{ßF»ßGÉ´x´¢1w´y´ºGß4ß2Nß2N{ß2OËß2P|ß2Q¨cz2¨¨#529fc9¨ß2T÷}}}÷¨edges¨|¦ß8¦¨reconcileId¨¨simple¨¦¨offset¨‡¨single-color¨¦ß2P‡¨style¨ß4ßFßG‡ßH¨source¨¨target¨‡´´É|ß2Qß2Rß2Sß2T÷ß2bß2Z»É¨line_f25nJXmo97¨ßMßP´´É|ß2Qß2Rß2Sß2T÷ß2bß2Z»É¨line_OfupQdzZ76¨ßPßS´´É|ß2Qß2Rß2Sß2T÷ß2bß2Z»É¨line_ztxwgm8q5B¨ßSßV—{ßH¨line_juvmgb6Jdu¨ß2dßZß2eßVß8{ßF»ßGÉß4¨perpendicular¨ß2j{¨startFrom¨¨from¨¨offsetFrom¨É¨offsetTo¨É¨roundCornerFactor¨¤A}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_6yO0Rj5BSo¨ß2dßZß2eßdß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_6KBxwuPTR2¨ß2dßdß2eßgß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_-yxK8Fi5C9¨ß2dßgß2eßkß8{ßF»ßGÉß4ß2jß2j{ß2kß2lß2mÉß2nÉß2o¤A}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_pQQ4FwBDnq¨ß2dßkß2eßnß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_otFVvwzObn¨ß2dßnß2eßqß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_bd6iqEZF1i¨ß2dßqß2eßtß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_i1o9tGaknN¨ß2dßtß2eßwß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_jkX8JhcSD3¨ß2dßwß2eßzß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_vkLR8PMafG¨ß2dßzß2eß12ß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_6Q2HeqMKJf¨ß2dß12ß2eß15ß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_sn_-ECACk6¨ß2dß15ß2eß16ß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_dYeye0lH5S¨ß2dß16ß2eß1Bß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_c1s1114PlQ¨ß2dß1Bß2eß1Eß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_tBS_fT6_Xg¨ß2dß1Eß2eß1Hß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_rc4rtdbpav¨ß2dß1Hß2eß1Jß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_R9P4m6SARL¨ß2dß1Jß2eß1Mß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_6Fjffqo3p4¨ß2dß1Mß2eß1Oß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_sNK5tRSN1O¨ß2dß1Oß2eß1Rß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_e-dymfhkYu¨ß2dß1Rß2eß1Uß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_9FDwsvxQV1¨ß2dß1Uß2eß1Xß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_xK9MSDDQPW¨ß2dß1Xß2eß1aß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_HDFawuASuJ¨ß2dß1aß2eß1dß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_Sw54Rc16ke¨ß2dß1dß2eß1gß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_JZ-tcEVgFq¨ß2dß1gß2eß1jß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Rß2Sß2T÷}ß2Y´´}}{ßH¨line_7CJSSptNRL¨ß2dß1mß2eß16ß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Vß2Wß2T÷}ß2Y´´}}{ßH¨line_PIbE57VmWs¨ß2dß1mß2eß1pß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Vß2Wß2T÷}ß2Y´´}}{ßH¨line_zgonKDXCcZ¨ß2dß1pß2eß1rß8{ßF»ßGÉß4¨diagonal¨ß3G{ß2kß2lß2mÉß2nÉß2oÎ}ß2cß2bß2b{ß2P|ß2Qß2Vß2Wß2T÷}ß2Y´´}}{ßH¨line_nHOI7hEuwW¨ß2dß1rß2eß1tß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Vß2Wß2T÷}ß2Y´´}}{ßH¨line_-3QziShkkm¨ß2dß1tß2eß1vß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Vß2Wß2T÷}ß2Y´´}}{ßH¨line_4_9xkijNJV¨ß2dß1vß2eß1yß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Vß2Wß2T÷}ß2Y´´}}{ßH¨line_2cZpXoBJVn¨ß2dß16ß2eß21ß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Vß2Wß2T÷}ß2Y´´}}{ßH¨line_VH8NgAoGHu¨ß2dß21ß2eß24ß8{ßF»ßGÉß4ß2jß2j{ß2kß2lß2mÉß2nÉß2o¤A}ß2cß2bß2b{ß2P|ß2Qß2Vß2Wß2T÷}ß2Y´´}}{ßH¨line_ilT-i9clZG¨ß2dß27ß2eß24ß8{ßF»ßGÉß4ß2jß2j{ß2kß2lß2mÉß2nÉß2o¤A}ß2cß2bß2b{ß2P|ß2Qß2Vß2Wß2T÷}ß2Y´´}}{ßH¨line_XvDbg-J8Ct¨ß2dß27ß2eß2Aß8{ßF»ßGÉß4ß3Gß3G{ß2kß2lß2mÉß2nÉß2oÎ}ß2cß2bß2b{ß2P|ß2Qß2Vß2Wß2T÷}ß2Y´´}}{ßH¨line_M2BJJjcCej¨ß2dß2Aß2eß2Cß8{ßF»ßGÉß4ß2Zß2cß2bß2b{ß2P|ß2Qß2Vß2Wß2T÷}ß2Y´´ß2Z{ß2aÉ}}}{ßH¨line_LO1FhwUkpM¨ß2dß2Fß2eß2Cß8{ßF»ßGÉß4ß3Gß3G{ß2kß2lß2mÉß2nÉß2oÎ}ß2cß2bß2b{ß2P|ß2Qß2Vß2Wß2T÷}ß2Y´´}}{ßH¨line_Tk2F123Jpb¨ß2dß2Fß2eß2Hß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Vß2Wß2T÷}ß2Y´´}}{ßH¨line_Zr_Ty7WZeR¨ß2dß2Hß2eß2Jß8{ßF»ßGÉß4ß2Zß2Z{ß2aÉ}ß2cß2bß2b{ß2P|ß2Qß2Vß2Wß2T÷}ß2Y´´}}÷}¨version¨¤B}</details>

**Comment by langonginc** [comment]
您好，我这边检查没什么问题，感谢您的贡献，等待管理员审核并汇入。
