### ISSUE TITLE
Donation: New work of 114514

### ISSUE THREAD

**Issue by LittleLing03** [railmapgen/rmp-gallery#678]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[114514.txt](https://github.com/railmapgen/rmp-gallery/files/12504098/114514.txt)

**Comment by thekingofcity** [comment]
Hi, there is a bug preventing this work from being merged. See #683 :)
