### ISSUE TITLE
Resources: New work of amsterdam

### ISSUE THREAD

**Issue by axl099** [railmapgen/rmp-gallery#690]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[amsterdam.txt](https://github.com/railmapgen/rmp-gallery/files/12512656/amsterdam.txt)

**Comment by axl099** [comment]
#666

**Comment by langonginc** [comment]
#549 

感谢您的贡献，请等候汇入。
