### ISSUE TITLE
Resources: Update work of beijing

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#704]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1693987911411.txt](https://github.com/railmapgen/rmp-gallery/files/12535115/1693987911411.txt)

**Comment by langonginc** [comment]
我注意到了您的更新，您将全部纯色线更换为北京纯色，但是这带来了相关问题，例如首都机场线由于存在多个虚拟车站，造成线路中出现了一些多余的白边，以及6号线北海北-南锣鼓巷区间，建议您进行修改。感谢您的贡献。

<img width="338" alt="image" src="https://github.com/railmapgen/rmp-gallery/assets/59787082/d4241b55-56dd-4f70-a2ce-f6581af5ea65">
