### ISSUE TITLE
Resources: New work of boston

### ISSUE THREAD

**Issue by axl099** [railmapgen/rmp-gallery#706]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**
[boston.txt](https://github.com/railmapgen/rmp-gallery/files/12537018/boston.txt)

**Comment by axl099** [comment]
number line badge improvement

**Comment by axl099** [comment]
#593

**Comment by axl099** [comment]
？

**Comment by axl099** [comment]
这不是新的吗？

**Comment by langonginc** [comment]
感谢您的贡献，请等候汇入！
