### ISSUE TITLE
Resources: New work of jinan

### ISSUE THREAD

**Issue by Zhengyang-Rd** [railmapgen/rmp-gallery#714]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**
[jinan.txt](https://github.com/railmapgen/rmp-gallery/files/12559619/jinan.txt)

**Comment by langonginc** [comment]
根据您提交的来源链接，车站英文名称均为大写拼音，而您图中的为大小写混搭拼音，请您检查修改。

如有异议，可在下方提出，感谢您的贡献。
