### ISSUE TITLE
Reources: New templates of seoul

### ISSUE THREAD

**Issue by LittleLing03** [railmapgen/rmp-gallery#721]
Hi RMP team! I would like to contribute to the gallery with the data below.

Paste or Upload below. They are meant for BOTS ONLY!

[seoul (2).txt](https://github.com/railmapgen/rmp-gallery/files/12564309/seoul.2.txt)

**Comment by thekingofcity** [comment]
Hi, you need to follow the instructions at Gallery and do not modify anything :)
