### ISSUE TITLE
Resources: Update work of nanjing

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#731]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1694332965185.txt](https://github.com/railmapgen/rmp-gallery/files/12567758/1694332965185.txt)

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板没有问题，请您等待管理员最终汇入，感谢您的贡献。
Hello, there is no problem with the template you submitted, please wait for the administrator to finally import it, thank you for your contribution.
