### ISSUE TITLE
Donation: New work of lemoetown

### ISSUE THREAD

**Issue by lyy0323** [railmapgen/rmp-gallery#754]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[lemoetown (1).txt](https://github.com/railmapgen/rmp-gallery/files/12619758/lemoetown.1.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your support! Your work has been merged and released :)
