### ISSUE TITLE
Donation: New work of songling

### ISSUE THREAD

**Issue by AnNamelessAlmond** [railmapgen/rmp-gallery#762]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[songling.txt](https://github.com/railmapgen/rmp-gallery/files/12640416/songling.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your support. Your work is merged and will publicly available very soon. To access your personalized link, click or share this link: https://railmapgen.github.io/rmp/s/XiuerSongling
