### ISSUE TITLE
Resources: Update work of nanjing

### ISSUE THREAD

**Issue by WIWO-ZHANG** [railmapgen/rmp-gallery#773]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[nanjing.txt](https://github.com/railmapgen/rmp-gallery/files/12642274/nanjing.txt)

**Comment by 28yfang** [comment]
Hi, please explain what you updated in the justification. Also, you have removed multiple languages of the city name and description. Please explain why if you don't mind.
