### ISSUE TITLE
Resources: Update work of beijing

### ISSUE THREAD

**Issue by Windows-Taskmgr** [railmapgen/rmp-gallery#777]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[beijing.txt](https://github.com/railmapgen/rmp-gallery/files/12642699/beijing.txt)

**Comment by langonginc** [comment]
很抱歉，您更新的内容已经在 #775 中完成了，非常感谢您的贡献！
