### ISSUE TITLE
Resources: Update work of hongkonglightrail

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#779]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1694968481431.txt](https://github.com/railmapgen/rmp-gallery/files/12643277/1694968481431.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. The trailing spaces in 屯門泳池 need to be removed :)
