### ISSUE TITLE
Resources: Update work of tokyo

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#786]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1694975051183.txt](https://github.com/railmapgen/rmp-gallery/files/12643456/1694975051183.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your work is merged and will be released soon :)
