### ISSUE TITLE
Donation: New work of rainynightcity

### ISSUE THREAD

**Issue by lyy0323** [railmapgen/rmp-gallery#793]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[rainynightcity.txt](https://github.com/railmapgen/rmp-gallery/files/12665191/rainynightcity.txt)

**Comment by thekingofcity** [comment]
Hi, we couldn't find a donation record on Sep 20 in 爱发电. Would you like to share your record or screenshot from your side?

**Comment by lyy0323** [comment]
Hi, I've supposed that one donation can cover multiple works of fantasy, and there was a donation at Sep 15, see attachment to the email.


----- 原始邮件 -----
发件人: "thekingofcity" ***@***.***>
收件人: "railmapgen/rmp-gallery" ***@***.***>
抄送: "lyy0323" ***@***.***>, "Author" ***@***.***>
发送时间: 星期三, 2023年 9 月 20日 下午 2:22:02
主题: Re: [railmapgen/rmp-gallery] Donation: New work of rainynightcity (Issue #793)

Hi, we couldn't find a donation record on Sep 20 in 爱发电. Would you like to share your record or screenshot from your side?

**Comment by thekingofcity** [comment]
Hi,

We want to clarify any confusion and extend our apologies for any misunderstandings. To make it crystal clear, each donation of either ￥18 or ￥28 is valid for a single fantasy work for one year. Furthermore, the total number of fantasy works you can select, multiplied by the corresponding donation amount, must not exceed your total donation.

Please rest assured that we acknowledge your work as a reward for helping us clarify this ambiguity. Thank you, and have a wonderful day! 😊
