### ISSUE TITLE
Resources: Update work of fuzhou

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#804]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1695205960186.txt](https://github.com/railmapgen/rmp-gallery/files/12672059/1695205960186.txt)

**Comment by 28yfang** [comment]
您好，感谢您对画廊的贡献。
经检查，我发现您混用了上海风格的普通车站和北京风格的换乘车站。这会导致车站字体大小不统一，作品的整体美观性下降。希望您可以做出调整。（在此建议全部换为北京风格的车站）
再次感谢您的贡献！
