### ISSUE TITLE
Resources: Update work of jinan

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#806]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Jinan",
        "zh-Hans": "济南",
        "zh-Hant": "濟南",
        "ja": "済南",
        "ko": "지난"
    },
    "desc": {
        "en": "Jinan Metro, also known as Jinan Rail Transit is a rapid transit system serving Jinan, the capital of Shandong province, China.",
        "zh-Hans": "济南地铁，又称为济南轨道交通，是服务于中国山东省济南市的城市轨道交通系统，由济南轨道交通集团有限公司运营。截至2021年3月26日，济南轨道交通已开通运营3条线路、42座车站，运营里程84.25千米。",
        "zh-Hant": "濟南地鐵，又稱為濟南軌道交通，是服務於中國山東省濟南市的城市軌道交通系統，由濟南軌道交通集團有限公司營運。截至2021年3月26日，濟南軌道交通已開通營運3條路線（1號綫、2號綫、3號綫）、42座車站，營運距離84.25公里。",
        "ja": "済南地下鉄は、中華人民共和国山東省済南市において営業中の地下鉄である。",
        "ko": "지난 지하철은 중화인민공화국 산둥성 지난시의 도시 철도이다."
    },
    "reference": "http://www.jngdjt.cn/",
    "justification": "Fix station name of Jinan West Railway Station. Also unifying station styles and improving alignment near WANGFUZHUANG and YUANBOYUAN."
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="jinan">{¨svgViewBoxZoom¨¢2G¨svgViewBoxMin¨{´x´£-8n.-5N´y´£-1F.-8x}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨bjsubway-basic¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨¨open¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨right¨¨middle¨|¨方特¨¨FANGTE¨÷»ßA»¢4v¢2VÉ¨stn_4-ycRMFHig¨¨left¨ßJ|¨济南西站¨¨JINAN WEST RAILWAY STATION¨÷»ßA»º1¢2zÉ¨stn_suaOWBwDvi¨ßNßJ|¨大杨¨¨DAYANG¨÷»ßA»º1¢3TÉ¨stn_d4hRMy1tqo¨—{ßH¨stn_tVlCMLVjVo¨ß8{ßF»ßGÉ´x´¢4W´y´¢4Cß4¨bjsubway-int¨ßV{ßD|¨王府庄¨¨WANGFUZHUANG¨÷ßBßNßC¨top¨¨outOfStation¨«}}}{ßH¨stn_Vy7lEa90Sq¨ß8{ßF»ßGÉ´x´¢3x´y´¢4bß4ßAßA{ßD|¨玉符河¨¨YUFUHE¨÷ßBßIßC¨bottom¨ßE»}}}{ßH¨misc_node_fd8IuqB1mz¨ß8{ßF»ßGÉ´x´¢4g´y´¢21ß4¨bjsubway-num-line-badge¨ßf{¨num¨Ê¨color¨|¨jinan¨¨jn1¨¨#BE1FA1¨¨#fff¨÷}}}{ßH¨stn_rCo9PvvHqq¨ß8{ßF»ßGÉ´x´¢3Y´y´¢50ß4ßAßA{ßD|¨赵营¨¨ZHAOYING¨÷ßBßIßCßdßE»}}}{ßH¨stn_8LmyLfSipa¨ß8{ßF»ßGÉ´x´¢39´y´¢5Pß4ßAßA{ßD|¨紫薇路¨¨ZIWEILU¨÷ßBßIßCßdßE»}}}{ßH¨stn_x-X1jB5NU2¨ß8{ßF»ßGÉ´x´¢2k´y´¢5oß4ßAßA{ßD|¨大学城¨¨DAXUECHENG¨÷ßBßIßCßdßE»}}}{ßH¨stn_TRoMw9CT5C¨ß8{ßF»ßGÉ´x´¢2L´y´¢6Sß4ßAßA{ßD|¨园博园¨¨YUANBOYUAN¨÷ßBßIßCßJßE»}}}{ßH¨stn_Izm0M-sYs6¨ß8{ßF»ßGÉ´x´ºH´y´¢6wß4ßAßA{ßD|¨创新谷¨¨CHUANGXINGU¨÷ßBßIßCßJßE»}}}{ßH¨stn_9tCJwapYgs¨ß8{ßF»ßGÉ´x´¢1m´y´¢7aß4ßAßA{ßD|¨工研院¨¨GONGYANYUAN¨÷ßBßJßCßdßE»}}}{ßH¨stn_n8Eme1BHRP¨ß8{ßF»ßGÉ´x´¢5F´y´¢3sß4ßAßA{ßD|¨腊山南¨¨LASHANNAN¨÷ßBßIßCßdßE»}}}{ßH¨stn_710SF9vA4t¨ß8{ßF»ßGÉ´x´¢5e´y´º4ß4ßAßA{ßD|´腊山´¨LASHAN¨÷ßBßIßCßdßE»}}}{ßH¨misc_node_QAmHh_aNeK¨ß8{ßF»ßGÉ´x´¢Hf´y´º2ß4ßfßf{ßgËßh|ßi¨jn2¨¨#FFB620¨ßl÷}}}{ßH¨stn_K2wJbhIVUm¨ß8{ßF»ßGÉ´x´¢63´y´¢34ß4ßAßA{ßD|¨二环西路¨¨ERHUANXILU¨÷ßBßIßCßdßE»}}}{ßH¨stn_4rt88cm6CM¨ß8{ßF»ßGÉ´x´¢7B´y´¢2uß4ßAßA{ßD|´老屯´¨LAOTUN¨÷ßBßJßCßYßE»}}}{ßH¨stn_0e5RfEW8IX¨ß8{ßF»ßGÉ´x´¢7p´y´ºTß4ßAßA{ßD|¨八里桥¨¨BALIQIAO¨÷ßBßJßCßdßE»}}}{ßH¨stn_aEZdmZUWhk¨ß8{ßF»ßGÉ´x´¢8T´y´ºTß4ßAßA{ßD|¨益康路¨¨YIKANGLU¨÷ßBßJßCßYßE»}}}{ßH¨stn_JWeuaXe8DR¨ß8{ßF»ßGÉ´x´¢Eb´y´ºTß4ßVßV{ßD|¨八涧堡¨¨BAJIANPU¨÷ßBßNßCßYßZ«}}}{ßH¨stn_bdpXA2FMjY¨ß8{ßF»ßGÉ´x´¢9H´y´ºTß4ßAßA{ßD|¨济南站北¨¨JINAN RAILWAY STATION NORTH¨÷ßBßJßCßdßE»}}}{ßH¨stn_Zij2OgqolG¨ß8{ßF»ßGÉ´x´¢BS´y´ºTß4ßAßA{ßD|´北园´¨BEIYUAN¨÷ßBßJßCßYßE»}}}{ßH¨stn_Xc8SNChoJl¨ß8{ßF»ßGÉ´x´¢Dd´y´ºTß4ßAßA{ßD|´祝甸´¨ZHUDIAN¨÷ßBßJßCßdßE»}}}{ßH¨stn_JnYAPYyQYt¨ß8{ßF»ßGÉ´x´¢CB´y´ºTß4ßAßA{ßD|¨历山路¨¨LISHANLU¨÷ßBßJßCßdßE»}}}{ßH¨stn_nfKxc0wtsm¨ß8{ßF»ßGÉ´x´¢A0´y´ºTß4ßAßA{ßD|¨济泺路¨¨JILUOLU¨÷ßBßJßCßYßE»}}}{ßH¨stn_eSUzNHnwlz¨ß8{ßF»ßGÉ´x´¢Cu´y´ºTß4ßAßA{ßD|¨七里堡¨¨QILIPU¨÷ßBßJßCßYßE»}}}{ßH¨stn_ugj0IyxjaD¨ß8{ßF»ßGÉ´x´¢Aj´y´ºTß4ßAßA{ßD|¨生产路¨¨SHENGCHANLU¨÷ßBßJßCßdßE»}}}{ßH¨stn_6vINWCmTt-¨ß8{ßF»ßGÉ´x´¢H6´y´ºTß4ßAßA{ßD|´鲍山´¨BAOSHAN¨÷ßBßJßCßYßE»}}}{ßH¨stn_2IBrcH8DcQ¨ß8{ßF»ßGÉ´x´¢GI´y´ºTß4ßAßA{ßD|¨凤凰路¨¨FENGHUANGLU¨÷ßBßJßCßdßE»}}}{ßH¨stn_lLZUm1O9Vi¨ß8{ßF»ßGÉ´x´¢FP´y´ºTß4ßAßA{ßD|¨姜家庄¨¨JIANGJIAZHUANG¨÷ßBßJßCßYßE»}}}{ßH¨stn_sE6C1nRsQ_¨ß8{ßF»ßGÉ´x´¢Hu´y´ºTß4ßAßA{ßD|¨彭家庄¨¨PENGJIAZHUANG¨÷ßBßJßCßdßE»}}}{ßH¨misc_node_-j2sQSL53S¨ß8{ßF»ßGÉ´x´¢Dx´y´¢6Iß4ßfßf{ßgÌßh|ßi¨jn3¨¨#0073CE¨ßl÷}}}{ßH¨stn__5faay3qxO¨ß8{ßF»ßGÉ´x´¢Eq´y´º0ß4ßAßA{ßD|¨张马屯¨¨ZHANGMATUN¨÷ßBßJßCßYßE»}}}{ßH¨stn_7bsbxqZtAX¨ß8{ßF»ßGÉ´x´¢Fe´y´º0ß4ßAßA{ßD|¨王舍人¨¨WANGSHEREN¨÷ßBßJßCßYßE»}}}{ßH¨stn_UmdB-eKw00¨ß8{ßF»ßGÉ´x´ºf´y´¢1rß4ßAßA{ßD|¨裴家营¨¨PEIJIAYING¨÷ßBßIßCßJßE«}}}{ßH¨stn_737YFkbv2l¨ß8{ßF»ßGÉ´x´ºf´y´¢1Sß4ßAßA{ßD|¨济南东站¨¨JINANDONG RAILWAY STATION¨÷ßBßIßCßJßE»}}}{ßH¨stn_jDB_BIRU01¨ß8{ßF»ßGÉ´x´ºf´y´¤yß4ßAßA{ßD|´滩头´¨TANTOU¨÷ßBßIßCßJßE»}}}{ßH¨stn_cRULAiQvgk¨ß8{ßF»ßGÉ´x´ºW´y´º4ß4ßAßA{ßD|¨花园东路¨¨HUAYUANDONGLU¨÷ßBßIßCßJßE»}}}{ßH¨stn_2lFOSCtpGj¨ß8{ßF»ßGÉ´x´ºW´y´º7ß4ßAßA{ßD|¨丁家庄¨¨DINGJIAZHUANG¨÷ßBßNßCßJßE»}}}{ßH¨stn_33iX5iw9M0¨ß8{ßF»ßGÉ´x´ºW´y´¢4Rß4ßAßA{ßD|¨礼耕路¨¨LIGENGLU¨÷ßBßIßCßJßE»}}}{ßH¨stn_fp5jtpKeer¨ß8{ßF»ßGÉ´x´ºW´y´º1ß4ßAßA{ßD|¨奥体中心¨¨OLYMPIC CENTER¨÷ßBßNßCßJßE»}}}{ßH¨stn_Ja-xUDwbms¨ß8{ßF»ßGÉ´x´ºW´y´ºEß4ßAßA{ßD|¨龙奥大厦¨¨LONGAO BUILDING¨÷ßBßIßCßJßE»}}}{ßH¨stn_KPjNz7g1nw¨ß8{ßF»ßGÉ´x´ºW´y´¢5tß4ßAßA{ßD|¨孟家庄¨¨MENGJIAZHUANG¨÷ßBßNßCßJßE»}}}{ßH¨stn_Cvj3mGlPhC¨ß8{ßF»ßGÉ´x´ºW´y´¢6Nß4ßAßA{ßD|´龙洞´¨LONGDONG¨÷ßBßIßCßJßE»}}}÷¨edges¨|{ßH¨line_gd-q2DZrZ1¨¨source¨ßM¨target¨ßQß8{ßF»ßGÉß4¨perpendicular¨ß2Z{¨startFrom¨¨from¨¨offsetFrom¨É¨offsetTo¨É¨roundCornerFactor¨£I.5K}¨style¨¨single-color¨ß2g{ßh|ßißjßkßl÷}¨reconcileId¨´´}}{ßH¨line_MuEYur7dDM¨ß2XßTß2YßQß8{ßF»ßGÉß4¨diagonal¨ß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßißjßkßl÷}ß2h´´}}{ßH¨line_PDvnHA_TtR¨ß2XßUß2YßTß8{ßF»ßGÉß4ß2Zß2Z{ß2aß2bß2cÆß2dÉß2e¤A}ß2fß2gß2g{ßh|ßißjßkßl÷}ß2h´´}}{ßH¨line_lXb8czizXa¨ß2XßUß2Yßaß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÆß2dÉß2eÑ}ß2fß2gß2g{ßh|ßißjßkßl÷}ß2h´´}}{ßH¨line_oSMQMzunZb¨ß2Xßmß2Yßaß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßißjßkßl÷}ß2h´´}}{ßH¨line_fBhxm0Isg2¨ß2Xßpß2Yßmß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßißjßkßl÷}ß2h´´}}{ßH¨line_Z4dF2bSgt4¨ß2Xßsß2Yßpß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßißjßkßl÷}ß2h´´}}{ßH¨line_8C-DhDiBD0¨ß2Xßsß2Yßvß8{ßF»ßGÉß4ß2jß2j{ß2a´to´ß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßißjßkßl÷}ß2h´´}}{ßH¨line_hSY0Xxq3BP¨ß2Xßvß2Yßyß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßißjßkßl÷}ß2h´´}}{ßH¨line_ChNUK1iskE¨ß2Xß11ß2Yßyß8{ßF»ßGÉß4ß2Zß2Z{ß2aß2bß2cÉß2dÉß2eÝ2}ß2fß2gß2g{ßh|ßißjßkßl÷}ß2h´´}}{ßH¨line_5ReWx-GMiC¨ß2XßUß2Yß14ß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÌß2dÉß2eÎ}ß2fß2gß2g{ßh|ßiß1Aß1Bßl÷}ß2h´´}}{ßH¨line_xY_Co6ybnS¨ß2Xß17ß2Yß14ß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1Aß1Bßl÷}ß2h´´}}{ßH¨line_eCgCALb0rh¨ß2Xß17ß2Yß1Cß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1Aß1Bßl÷}ß2h´´}}{ßH¨line_rYfYZEdYV7¨ß2Xß1Fß2Yß1Cß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1Aß1Bßl÷}ß2h´´}}{ßH¨line_9Agn-d8_S6¨ß2Xß1Fß2Yß1Hß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1Aß1Bßl÷}ß2h´´}}{ßH¨line_ghUaZO0vkB¨ß2Xß1Hß2Yß1Kß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1Aß1Bßl÷}ß2h´´}}{ßH¨line_5YxLefToZI¨ß2Xß1Kß2Yß1Qß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1Aß1Bßl÷}ß2h´´}}{ßH¨line_n8N4Q1dli0¨ß2Xß1Qß2Yß1aß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1Aß1Bßl÷}ß2h´´}}{ßH¨line_oylJ92kZS2¨ß2Xß1aß2Yß1gß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1Aß1Bßl÷}ß2h´´}}{ßH¨line_ll9bjzHipV¨ß2Xß1gß2Yß1Tß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1Aß1Bßl÷}ß2h´´}}{ßH¨line_k9RteFntX6¨ß2Xß1Tß2Yß1Xß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1Aß1Bßl÷}ß2h´´}}{ßH¨line_moZqrwmddo¨ß2Xß1Xß2Yß1dß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1Aß1Bßl÷}ß2h´´}}{ßH¨line_6th8LqK16g¨ß2Xß1dß2Yß1Vß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1Aß1Bßl÷}ß2h´´}}{ßH¨line_DX_uSu7GNO¨ß2Xß1Vß2Yß1Nß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1Aß1Bßl÷}ß2h´´}}{ßH¨line_qUX0POenA1¨ß2Xß1Nß2Yß1oß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1Aß1Bßl÷}ß2h´´}}{ßH¨line_Dbsmfv1PRr¨ß2Xß1oß2Yß1lß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1Aß1Bßl÷}ß2h´´}}{ßH¨line_QyZ8OHRK7y¨ß2Xß1lß2Yß1jß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1Aß1Bßl÷}ß2h´´}}{ßH¨line_I7pK4ht9SE¨ß2Xß1jß2Yß1rß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1Aß1Bßl÷}ß2h´´}}{ßH¨line_s-eyLps_bU¨ß2Xß1xß2Yß1Nß8{ßF»ßGÉß4ß2Zß2Z{ß2aß2bß2cÉß2dÉß2eÝ2}ß2fß2gß2g{ßh|ßiß1vß1wßl÷}ß2h´´}}{ßH¨line_B1pu6XHIMe¨ß2Xß1xß2Yß20ß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1vß1wßl÷}ß2h´´}}{ßH¨line_PAc-kKFgol¨ß2Xß20ß2Yß23ß8{ßF»ßGÉß4ß2Zß2Z{ß2aß2bß2cÉß2dÉß2eÝ2}ß2fß2gß2g{ßh|ßiß1vß1wßl÷}ß2h´´}}{ßH¨line_Vd_wuOyfJ7¨ß2Xß23ß2Yß26ß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1vß1wßl÷}ß2h´´}}{ßH¨line_3pt5IklKYY¨ß2Xß26ß2Yß29ß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1vß1wßl÷}ß2h´´}}{ßH¨line_0M8hBrMPIo¨ß2Xß1Nß2Yß2Bß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1vß1wßl÷}ß2h´´}}{ßH¨line_sRbbsb5naw¨ß2Xß2Bß2Yß2Eß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1vß1wßl÷}ß2h´´}}{ßH¨line_swdXNlj6Oi¨ß2Xß2Eß2Yß2Hß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1vß1wßl÷}ß2h´´}}{ßH¨line_x6bSaQu-Mt¨ß2Xß2Hß2Yß2Kß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1vß1wßl÷}ß2h´´}}{ßH¨line_oNJCJrn_ZP¨ß2Xß2Kß2Yß2Nß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1vß1wßl÷}ß2h´´}}{ßH¨line_mVW6S1df9g¨ß2Xß2Nß2Yß2Qß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1vß1wßl÷}ß2h´´}}{ßH¨line_v0S3XQgo0h¨ß2Xß2Qß2Yß2Tß8{ßF»ßGÉß4ß2jß2j{ß2aß2bß2cÉß2dÉß2e¤A}ß2fß2gß2g{ßh|ßiß1vß1wßl÷}ß2h´´}}÷}¨version¨¤J}</details>

**Comment by thekingofcity** [comment]
Hi @HUQIUAN, just want to know if you are interested in auditing other works as you have fixed a lot of them in the past few months :)

**Comment by 28yfang** [comment]
您好，感谢您对画廊的贡献。
经检查，未在您提供的作品中发现问题。稍后，管理员将进行最后的确认并汇入。再次感谢您的贡献！

**Comment by thekingofcity** [comment]
> @thekingofcity 当然可以，虽然本人时间不够充足，但每周改一两个作品应该可以的:)

欢迎从项目的关于页面加入我们的Slack讨论群组，我们将与您进一步分享审核员的细节 :)
