### ISSUE TITLE
Resources: New work of madrid

### ISSUE THREAD

**Issue by Ph2O5** [railmapgen/rmp-gallery#811]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[madrid.txt](https://github.com/railmapgen/rmp-gallery/files/12679127/madrid.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. I believe some of the name offsets should be tweaked to show the station icon :)

**Comment by Ph2O5** [comment]
Thank you for the revising. The work is unfinished and needs to be amended on the offsets, the routs and the scale. Since the gallary is not for the undone works, I will keep on doing it and share it in a proper way.
