### ISSUE TITLE
Resources: Update work of fuzhou

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#820]
Hi RMP team! I would like to contribute to the gallery with the data below.
Refer to #804 
**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1695205960186.txt](https://github.com/railmapgen/rmp-gallery/files/12705884/1695205960186.txt)

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板没有问题，请您等待管理员最终汇入，感谢您的贡献。
---
您好，您所提交的範本沒有問題，請您等待管理員最終匯入，感謝您的貢獻。
---
Hello, there is no problem with the template you submitted, please wait for the administrator to finally import it, thank you for your contribution.
