### ISSUE TITLE
Resources: New work of chuzhou

### ISSUE THREAD

**Issue by Windows-Taskmgr** [railmapgen/rmp-gallery#823]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Chuzhou",
        "zh-Hans": "滁州"
    },
    "desc": {
        "en": "Chuzhou Rail Transit is an urban rail transit system serving Chuzhou City, Anhui Province, China. Its first line, Chuzhou Rail Transit, Ningchu Line, opened on June 28, 2023, making Chuzhou the 57th city in Chinese mainland and the third city in Anhui Province to open urban rail transit.",
        "zh-Hans": "滁州轨道交通（Chuzhou Rail Transit）是服务于中国安徽省滁州市的城市轨道交通系统。其首条线路滁州轨道交通宁滁线于2023年6月28日开通运营，使滁州成为中国内地第57座、安徽省第三座开通城市轨道交通的城市。"
    },
    "reference": "https://zh.wikipedia.org/wiki/滁宁城际铁路",
    "justification": "New template of Chuzhou"
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="chuzhou">{¨svgViewBoxZoom¨¢26¨svgViewBoxMin¨{´x´£-6y.-17´y´£-1d.-FH}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨bjsubway-basic¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨¨open¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨right¨¨middle¨|¨汊河¨¨CHAHE¨÷»ßA»¢3E¤PÉ¨stn_VPWdu302Nk¨ßJ¨bottom¨|¨汊河新城¨¨CHAHEXINCHENG¨÷»ßA»º0¢-PÉ¨stn_RFxNs96hPw¨ßJ¨top¨|¨相官¨¨XIANGGUAN¨÷«ßA»¢18º2É¨stn_wHzOsRebjk¨ßJßN|¨十二里半¨¨SHIERLIBAN¨÷»ßA»¤Aº2É¨stn_xNymVdPvrI¨ßJßR|¨水口¨¨SHUIKOU¨÷«ßA»¢-oº2É¨stn_sb4VROfeMm¨ßIßJ|¨林楼¨¨LINLOU¨÷»ßA»¢-1m¤PÉ¨stn_9qypuGi6Jk¨ßIßJ|¨大王郢¨¨DAWANGYING¨÷»ßA»º5¢1NÉ¨stn_7NiHugwa8X¨ßIßJ|¨苏滁商务中心¨¨SUCHU Business Center¨÷»ßA»º5¢2LÉ¨stn_nFqUlKSY0N¨ßIßJ|¨担子¨¨DANZI¨÷«ßA»º5¢3JÉ¨stn_BMfB3tsa0L¨ßIßJ|¨滁州政务中心¨¨Chuzhou Government Affairs Center¨÷»ßA»º5¢4HÉ¨stn_KrFLnA0K5X¨ßIßJ|¨琅琊山¨¨LANGYASHAN¨÷»ßA»º5¢5FÉ¨stn_ApYa44mtNX¨ßIßJ|¨花博园¨¨HUABOYUAN¨÷»ßA»º5¢6DÉ¨stn_RluEc0_Mf1¨ßIßJ|¨腰铺¨¨YAOPU¨÷«ßA»º5¢7BÉ¨stn_nCs9p_kG0h¨ßIßJ|¨滁州高铁站¨¨Chuzhou Railway Station¨÷»ßA»º5¢89É¨stn_NsCB4x_I6Q¨—{ßH¨misc_node_Mofk7-h9tl¨ß8{ßF»ßGÉ´x´¢-29´y´¢8Mß4¨bjsubway-text-line-badge¨ß13{ßD|¨宁滁线¨¨Nanjing-Chuzhou Line¨÷¨color¨|¨nanjing¨´s4´¨#ff6314¨¨#fff¨÷}}}{ßH¨misc_node_HavNlnkN8G¨ß8{ßF»ßGÉ´x´¢2p´y´¤eß4ß13ß13{ßD|ß14ß15÷ß16|ß17´s4´ß18ß19÷}}}÷¨edges¨|{ßH¨line_jLl_g4Jgvh¨¨source¨ßQ¨target¨ßMß8{ßF»ßGÉß4¨perpendicular¨ß1F{¨startFrom¨¨from¨¨offsetFrom¨É¨offsetTo¨É¨roundCornerFactor¨£I.5K}¨style¨¨single-color¨ß1M{ß16|ß17´s4´ß18ß19÷}¨reconcileId¨´´}}{ßH¨line_bfj9y1WB_y¨ß1DßUß1EßQß8{ßF»ßGÉß4¨simple¨ß1P{¨offset¨É}ß1Lß1Mß1M{ß16|ß17´s4´ß18ß19÷}ß1N´´}}{ßH¨line_UgagSIN3HZ¨ß1DßXß1EßUß8{ßF»ßGÉß4ß1Pß1P{ß1QÉ}ß1Lß1Mß1M{ß16|ß17´s4´ß18ß19÷}ß1N´´}}{ßH¨line_q1zaaXGAIc¨ß1Dßaß1EßXß8{ßF»ßGÉß4ß1Pß1P{ß1QÉ}ß1Lß1Mß1M{ß16|ß17´s4´ß18ß19÷}ß1N´´}}{ßH¨line_-OQY6Y9DBc¨ß1Dßaß1Eßdß8{ßF»ßGÉß4ß1Fß1F{ß1Gß1Hß1IÉß1JÉß1KÝ2}ß1Lß1Mß1M{ß16|ß17´s4´ß18ß19÷}ß1N´´}}{ßH¨line_CjOpRt5qCB¨ß1Dßdß1Eßgß8{ßF»ßGÉß4ß1Pß1P{ß1QÉ}ß1Lß1Mß1M{ß16|ß17´s4´ß18ß19÷}ß1N´´}}{ßH¨line_jkNpLXjFkF¨ß1Dßgß1Eßjß8{ßF»ßGÉß4ß1Pß1P{ß1QÉ}ß1Lß1Mß1M{ß16|ß17´s4´ß18ß19÷}ß1N´´}}{ßH¨line_v32mH2lBaZ¨ß1Dßjß1Eßmß8{ßF»ßGÉß4ß1Pß1P{ß1QÉ}ß1Lß1Mß1M{ß16|ß17´s4´ß18ß19÷}ß1N´´}}{ßH¨line_6wlW-Krh5O¨ß1Dßmß1Eßpß8{ßF»ßGÉß4ß1Pß1P{ß1QÉ}ß1Lß1Mß1M{ß16|ß17´s4´ß18ß19÷}ß1N´´}}{ßH¨line__r1cu1wENe¨ß1Dßpß1Eßsß8{ßF»ßGÉß4ß1Pß1P{ß1QÉ}ß1Lß1Mß1M{ß16|ß17´s4´ß18ß19÷}ß1N´´}}{ßH¨line_D-tlYSwymL¨ß1Dßsß1Eßvß8{ßF»ßGÉß4ß1Pß1P{ß1QÉ}ß1Lß1Mß1M{ß16|ß17´s4´ß18ß19÷}ß1N´´}}{ßH¨line_1fJ9KcsWtx¨ß1Dßvß1Eßyß8{ßF»ßGÉß4ß1Pß1P{ß1QÉ}ß1Lß1Mß1M{ß16|ß17´s4´ß18ß19÷}ß1N´´}}{ßH¨line_QG8EWfayCz¨ß1Dßyß1Eß11ß8{ßF»ßGÉß4ß1Pß1P{ß1QÉ}ß1Lß1Mß1M{ß16|ß17´s4´ß18ß19÷}ß1N´´}}÷}¨version¨¤J}</details>

**Comment by Takagi-Misae** [comment]
您好，您所提交的範本沒有問題，請等待管理員加入至畫廊，謝謝🙏

審核來源：
![image](https://github.com/railmapgen/rmp-gallery/assets/143057061/1c8b6e62-d803-459f-9e80-2d51a990b5e6)
