### ISSUE TITLE
Resources: New work of xiamen

### ISSUE THREAD

**Issue by axl099** [railmapgen/rmp-gallery#836]
[xiamen.txt](https://github.com/railmapgen/rmp-gallery/files/12726077/xiamen.txt)
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

**Comment by thekingofcity** [comment]
Not sure if this failed in the same way as #758 ):

**Comment by Charlis-Wong** [comment]
@thekingofcity Please close this resource, merge already #837
