### ISSUE TITLE
Resources: Update work of harbin

### ISSUE THREAD

**Issue by polygon827** [railmapgen/rmp-gallery#841]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[harbin (2).txt](https://github.com/railmapgen/rmp-gallery/files/12739738/harbin.2.txt)

**Comment by thekingofcity** [comment]
Hi, we do not accept reference such as baijiahao ):
