### ISSUE TITLE
Resources: Update work of shenyang

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#854]
Hi RMP team! I would like to contribute to the gallery with the data below.
Refer to #849 
**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1695979492171.txt](https://github.com/railmapgen/rmp-gallery/files/12763579/1695979492171.txt)

**Comment by 28yfang** [comment]
张沙布站的问题已修复，现在将进行汇入。感谢您的贡献！
