### ISSUE TITLE
Resources: New work of nagoya

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#859]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1695816052136.txt](https://github.com/railmapgen/rmp-gallery/files/12768254/1695816052136.txt)

**Comment by 28yfang** [comment]
您好，感谢您的贡献。
经检查，您的作品中含有以下问题：
港区役所站英文站名在您所提供的图片中并没有括号中的内容，建议删去。
请您在修正后重新提交，并附上本议题编号（#859），感谢！
