### ISSUE TITLE
Resources: New work of nagoya

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#861]
Hi RMP team! I would like to contribute to the gallery with the data below.
Refer to #859 @28yfang 
**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1695816052136.txt](https://github.com/railmapgen/rmp-gallery/files/12773901/1695816052136.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your work is merged and will be released soon :)
