### ISSUE TITLE
Resources: Update work of chengdu

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#867]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1691838434863.txt](https://github.com/railmapgen/rmp-gallery/files/12776656/1691838434863.txt)

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板没有问题，请您等待管理员最终汇入，感谢您的贡献。
