### ISSUE TITLE
Resources: New work of taipei

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#884]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1696051202876.txt](https://github.com/railmapgen/rmp-gallery/files/12802440/1696051202876.txt)

**Comment by langonginc** [comment]
您好，您提交的作品存在如下问题：

- `Zhonghe-Xinlu Line (O)` 线路未使用来自 palette 的颜色。
- `Circular Line (Y)` 线路未使用来自 palette 的颜色。

对于如上问题，您可以使用批量工具替换相应的颜色。

请您修改后重新提交，并附上本 issue 编号 `#884` ，感谢您的贡献。
