### ISSUE TITLE
Resources: Update work of changchun

### ISSUE THREAD

**Issue by langonginc** [railmapgen/rmp-gallery#886]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[changchun.txt](https://github.com/railmapgen/rmp-gallery/files/12813818/changchun.txt)

**Comment by 28yfang** [comment]
您好，感谢您的贡献。
经检查，您的作品含有以下问题：（没错虽然是fast track但我还是检查了一下）
东大桥站英文名错误，正确的应为DONGDAQIAO Bridge。
请在修正后重新提交，并附上本议题编号（#886），感谢！
