### ISSUE TITLE
Resources: New work of taipei

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#888]
Hi RMP team! I would like to contribute to the gallery with the data below.
Refer to #884 @langonginc 
**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1696051202876.txt](https://github.com/railmapgen/rmp-gallery/files/12817199/1696051202876.txt)

**Comment by 28yfang** [comment]
#884中提到的问题已修复，感谢您的贡献。
