### ISSUE TITLE
Resources: Update work of jinhuayiwuanddongyang

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#892]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1696505329228.txt](https://github.com/railmapgen/rmp-gallery/files/12817870/1696505329228.txt)

**Comment by 28yfang** [comment]
您好，感谢您对画廊的贡献。
经检查，您的作品含有以下问题：
1. 浙医四院站英文错误，正确的应为The Fourth Affiliated Hospital Zhejiang University School of Medicine。您写的是The Fourth Affiliated Hospital _of_ Zhejiang University School of Medicine，请改正。
2. 明清宫站英文名中建议使用 & 代替 and。

请在修正后重新提交，并附上本议题编号（#892），感谢！
