### ISSUE TITLE
Resources: Update work of changchun

### ISSUE THREAD

**Issue by langonginc** [railmapgen/rmp-gallery#894]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[Changchun](https://github.com/railmapgen/rmp-gallery/files/12826012/changchun-2.txt)

#886

**Comment by Charlis-Wong** [comment]
您好，您所提交的範本有一個站名錯誤
東大橋站的英文應該是 DONGDAQIAO Bridge，並非DONGDAQIAO
請修改後再次開啟issue繳交，並附上本issue的編號，感謝您的貢獻與配合🙏

審核來源：https://zh.wikipedia.org/wiki/%E4%B8%9C%E5%A4%A7%E6%A1%A5%E7%AB%99_(%E9%95%BF%E6%98%A5)
