### ISSUE TITLE
Resources: New work of Qingdao

### ISSUE THREAD

**Issue by Minwtraft** [railmapgen/rmp-gallery#896]
Hi RMP team! I would like to contribute to the gallery with the data below.

Refer to #882

[qingdao_8.txt](https://github.com/railmapgen/rmp-gallery/files/12826171/qingdao_8.txt)

**Comment by langonginc** [comment]
青岛的模版已经存在，您应该选择修改该模版而不是新建。感谢您的贡献。

顺便提一句，issue正文中那行加粗的文本不应删除，否则会导致 bot 无法正常工作。
