### ISSUE TITLE
Resources: Update work of jinhuayiwuanddongyang

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#900]
Hi RMP team! I would like to contribute to the gallery with the data below.
Refer to #892 @28yfang 
**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1696505329228.txt](https://github.com/railmapgen/rmp-gallery/files/12831030/1696505329228.txt)

**Comment by 28yfang** [comment]
您好，#892中提到的问题已修复，感谢您的贡献。
