### ISSUE TITLE
Resources: New work of kaohsiung

### ISSUE THREAD

**Issue by langonginc** [railmapgen/rmp-gallery#902]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[kaohsiung.txt](https://github.com/railmapgen/rmp-gallery/files/12831918/kaohsiung.txt)

**Comment by Charlis-Wong** [comment]
您好，您所提交的範本沒有問題，
但是我有一個建議
- 在橋頭火車站，左營站，高雄車站增加台鐵，高鐵的標誌
請等待管理員合拼至範本，謝謝🙏

審核來源：高雄捷運官方網站路線圖
![image](https://github.com/railmapgen/rmp-gallery/assets/143057061/a842d78d-15c9-4d4f-aa61-35c8ef5be276)
