### ISSUE TITLE
Resources: New work of taizhou

### ISSUE THREAD

**Issue by Xiao-qian111** [railmapgen/rmp-gallery#907]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Taizhou",
        "zh-Hans": "台州",
        "zh-Hant": "臺州"
    },
    "desc": {
        "en": "Taizhou Metro Map",
        "zh-Hans": "台州地铁图",
        "zh-Hant": "臺州地鐵圖"
    },
    "reference": "https://image.baidu.com/search/detail?ct=503316480&amp;z=0&amp;ipn=d&amp;word=%E5%8F%B0%E5%B7%9E%E5%9C%B0%E9%93%81%E5%9B%BE2023&amp;step_word=&amp;hs=0&amp;pn=13&amp;spn=0&amp;di=7264239678495129601&amp;pi=0&amp;rn=1&amp;tn=baiduimagedetail&amp;is=0%2C0&amp;istype=0&amp;ie=utf-8&amp;oe=utf-8&amp;in=&amp;cl=2&amp;lm=-1&amp;st=undefined&amp;cs=2711020669%2C2061745459&amp;os=3801709358%2C99741225&amp;simid=4226136225%2C720528794&amp;adpicid=0&amp;lpn=0&amp;ln=1614&amp;fr=&amp;fmq=1696670137253_R&amp;fm=&amp;ic=undefined&amp;s=undefined&amp;hd=undefined&amp;latest=undefined&amp;copyright=undefined&amp;se=&amp;sme=&amp;tab=0&amp;width=undefined&amp;height=undefined&amp;face=undefined&amp;ist=&amp;jit=&amp;cg=&amp;bdtype=0&amp;oriquery=&amp;objurl=https%3A%2F%2Ft2.focus-img.cn%2Fsh740wsh%2Fzx%2Fduplication%2F4220dafe-448b-4a99-90e5-fe55ff7da381.png&amp;fromurl=ippr_z2C%24qAzdH3FAzdH3Fpz_z%26e3Bu5v7f_z%26e3BvgAzdH3Fztx7gAzdH3Fk8c00bmjud89u0vl_z%26e3Bip4s&amp;gsm=1e&amp;rpstart=0&amp;rpnum=0&amp;islist=&amp;querylist=&amp;nojc=undefined&amp;dyTabStr=MTEsMCwzLDEsNiw0LDUsMiw3LDgsOQ%3D%3D&amp;lid=7258610204020005769",
    "justification": "New template of Taizhou Metro Map"
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="taizhou">{¨svgViewBoxZoom¨¢1c¨svgViewBoxMin¨{´x´£-27.-FD´y´£3H.3g}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨suzhourt-basic¨¦¨color¨¨nameOffsetX¨¨nameOffsetY¨¨names¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡|¨other¨ßI¨#0099db¨¨#fff¨÷¨right¨¨middle¨|¨台州火车站¨¨Taizhou Railway Station¨÷ßA»¢8s¢4qÉ¨stn_1Aj5jdYp68¨|ßIþßJßK÷ßLßM|¨学院路¨¨Xueyuan Road¨÷ßA»¢9b¢5ZÉ¨stn_OhRJyqK_d1¨|ßIþßJßK÷ßLßM|¨国博中心¨¨National Expo Center¨÷ßA»¢9C¢5yÉ¨stn_1C-q9LY0IA¨|ßIþßJßK÷ßLßM|¨汇丰路¨¨Huifeng Road¨÷ßA»¢8n¢6NÉ¨stn_dG0vIAUrdf¨|ßIþßJßK÷ßLßM|¨锦泰¨¨Jintai¨÷ßA»¢8O¢6mÉ¨stn_EyW1ElLxGc¨|ßIþßJßK÷¨left¨ßM|¨恩泽医院¨¨Enze Hospital¨÷ßA»¢7kºAÉ¨stn_YuQR8tcm3B¨|ßIþßJßK÷ßcßM|¨台州汽车南站¨¨Taizhou South Bus Station¨÷ßA»ºB¢7LÉ¨stn_zJxAA_oyE-¨|ßIþßJßK÷ßcßM|¨泽国¨¨Zeguo¨÷ßA»ºB¢9MÉ¨stn_IFyy3Zy0v5¨|ßIþßJßK÷ßcßM|¨温岭火车站¨¨Wenling Railway station¨÷ßA»ºB¢A0É¨stn_zU0MLAflY5¨|ßIþßJßK÷ßcßM|¨汇川王¨¨Huichuanwang¨÷ßA»ºB¢BDÉ¨stn_6e3ng8SYS6¨|ßIþßJßK÷ßLßM|¨温岭第一人民医院¨¨Wenling First Hospital¨÷ßA»ºB¢BmÉ¨stn_qgmCLwXhsE¨|ßIþßJßK÷ßLßM|¨九龙大道¨¨Jiulong thoroughfare¨÷ßA»¢84¢C6É¨stn_IMK-g6XS_r¨|ßIþßJßK÷ßLßM|¨万昌路¨¨Wanchang Road¨÷ßA»º9¢CQÉ¨stn_3VcPJJFKPG¨|ßIþßJßK÷ßLßM|´南屏´¨Nanping¨÷ßA»¢8i¢CkÉ¨stn_dmYcCd4lug¨|ßIþßJßK÷ßLßM|´城南´¨Chengnan¨÷ßA»¢9H¢DJÉ¨stn_1ar6Ro1K9j¨—{ßH¨misc_node_ZoWQlQK-1d¨ß8{ßF»ßGÉ´x´ºF´y´¢EWß4¨virtual¨ß16{}}}{ßH¨misc_node_iJD4leDhn3¨ß8{ßF»ßGÉ´x´¢AF´y´¢FAß4ß16ß16{}}}{ßH¨misc_node_C7vD5Sa9mN¨ß8{ßF»ßGÉ´x´ºI´y´ºQß4ß16ß16{}}}{ßH¨misc_node_qZwkAZmm5n¨ß8{ßF»ßGÉ´x´ºF´y´¢Fjß4ß16ß16{}}}{ßH¨misc_node_eLGc8yhYEV¨ß8{ßF»ßGÉ´x´¢AK´y´¢Evß4ß16ß16{}}}{ßH¨misc_node_sl0J2HNnI1¨ß8{ßF»ßGÉ´x´¢C1´y´ºTß4ß16ß16{}}}{ßH¨misc_node_HfbFVTuoPy¨ß8{ßF»ßGÉ´x´¢Aj´y´¢Eiß4¨text¨ß1D{¨content¨´图例´¨fontSize¨¤G¨lineHeight¨¤G¨textAnchor¨ßM¨dominantBaseline¨ßM¨language¨´zh´ßB|¨shanghai¨¨jsr¨¨#000000¨ßK÷¨rotate¨É¨italic¨¨normal¨¨bold¨ß1P}}}{ßH¨misc_node_05piTiPqpy¨ß8{ßF»ßGÉ´x´¢AP´y´¢FKß4ß16ß16{}}}{ßH¨misc_node_qYnJdkClDa¨ß8{ßF»ßGÉ´x´¢Ae´y´ºYß4ß16ß16{}}}{ßH¨misc_node_tLTrbC9zS4¨ß8{ßF»ßGÉ´x´ºF´y´ºYß4ß1Dß1D{ß1E¨台州市城铁路S1线¨ß1FÐß1G¤Gß1HßMß1IßMß1J´en´ßB|ß1Kß1Lß1MßK÷ß1NÉß1Oß1Pß1Qß1P}}}÷¨edges¨|{ßH¨line_TqJdBTD8bI¨¨source¨ßS¨target¨ßPß8{ßF»ßGÉß4¨perpendicular¨ß1Z{¨startFrom¨¨from¨¨offsetFrom¨É¨offsetTo¨É¨roundCornerFactor¨£I.5K}¨style¨¨single-color¨¨reconcileId¨´´ß1g{ßB|ßIþßJßK÷}}}{ßH¨line_8F4xuvXC3I¨ß1XßSß1YßVß8{ßF»ßGÉß4¨diagonal¨ß1fß1gß1h´´ß1j{ß1aß1bß1cÉß1dÉß1e¤A}ß1g{ßB|ßIþßJßK÷}}}{ßH¨line_ejjayp2y57¨ß1XßVß1YßYß8{ßF»ßGÉß4ß1jß1j{ß1aß1bß1cÉß1dÉß1e¤A}ß1fß1gß1g{ßB|ßIþßJßK÷}ß1h´´}}{ßH¨line_T65RbFfqN_¨ß1XßYß1Yßbß8{ßF»ßGÉß4ß1jß1j{ß1aß1bß1cÉß1dÉß1e¤A}ß1fß1gß1g{ßB|ßIþßJßK÷}ß1h´´}}{ßH¨line_W-n3fNWByI¨ß1Xßfß1Yßbß8{ßF»ßGÉß4ß1jß1j{ß1aß1bß1cÉß1dÉß1e¤A}ß1fß1gß1g{ßB|ßIþßJßK÷}ß1h´´}}{ßH¨line_HXTRmjjTJT¨ß1Xßfß1Yßiß8{ßF»ßGÉß4ß1jß1j{ß1aß1bß1cÉß1dÉß1e¤A}ß1fß1gß1g{ßB|ßIþßJßK÷}ß1h´´}}{ßH¨line_mfP6KOE9WP¨ß1Xßiß1Yßlß8{ßF»ßGÉß4ß1jß1j{ß1aß1bß1cÉß1dÉß1e¤A}ß1fß1gß1g{ßB|ßIþßJßK÷}ß1h´´}}{ßH¨line_57mBNG-BfV¨ß1Xßlß1Yßoß8{ßF»ßGÉß4ß1jß1j{ß1aß1bß1cÉß1dÉß1e¤A}ß1fß1gß1g{ßB|ßIþßJßK÷}ß1h´´}}{ßH¨line_uBwpgsy__o¨ß1Xßoß1Yßrß8{ßF»ßGÉß4ß1jß1j{ß1aß1bß1cÉß1dÉß1e¤A}ß1fß1gß1g{ßB|ßIþßJßK÷}ß1h´´}}{ßH¨line_4GWfZoWzev¨ß1Xßrß1Yßuß8{ßF»ßGÉß4ß1jß1j{ß1aß1bß1cÉß1dÉß1e¤A}ß1fß1gß1g{ßB|ßIþßJßK÷}ß1h´´}}{ßH¨line_gNFh3sdeRz¨ß1Xßuß1Yßxß8{ßF»ßGÉß4ß1jß1j{ß1aß1bß1cÉß1dÉß1e¤A}ß1fß1gß1g{ßB|ßIþßJßK÷}ß1h´´}}{ßH¨line_7x0_EIuXoi¨ß1Xßxß1Yß10ß8{ßF»ßGÉß4ß1jß1j{ß1aß1bß1cÉß1dÉß1e¤A}ß1fß1gß1g{ßB|ßIþßJßK÷}ß1h´´}}{ßH¨line_Chjn0qQ343¨ß1Xß10ß1Yß12ß8{ßF»ßGÉß4ß1jß1j{ß1aß1bß1cÉß1dÉß1e¤A}ß1fß1gß1g{ßB|ßIþßJßK÷}ß1h´´}}{ßH¨line_fWiiYjFG7S¨ß1Xß12ß1Yß14ß8{ßF»ßGÉß4ß1jß1j{ß1aß1bß1cÉß1dÉß1e¤A}ß1fß1gß1g{ßB|ßIþßJßK÷}ß1h´´}}{ßH¨line_apld6VY1bs¨ß1Xß15ß1Yß17ß8{ßF»ßGÉß4ß1Zß1Z{ß1aß1bß1cÉß1dÉß1eÝ2}ß1f¨mtr-light-rail¨ß1h´´ß1x{ßB|ßIþß1MßK÷}}}{ßH¨line_l_ezFj_E9b¨ß1Xß15ß1Yß18ß8{ßF»ßGÉß4ß1Zß1Z{ß1aß1bß1cÉß1dÉß1eÝ2}ß1fß1xß1h´´ß1x{ßB|ßIþß1MßK÷}}}{ßH¨line_7xJCnYKbd-¨ß1Xß19ß1Yß17ß8{ßF»ßGÉß4ß1Zß1Z{ß1aß1bß1cÉß1dÉß1eÝ2}ß1fß1xß1h´´ß1x{ßB|ßIþß1MßK÷}}}{ßH¨line_rwTDUtT3iz¨ß1Xß19ß1Yß18ß8{ßF»ßGÉß4ß1Zß1Z{ß1aß1bß1cÉß1dÉß1eÝ2}ß1fß1xß1h´´ß1x{ßB|ßIþß1MßK÷}}}{ßH¨line_FD6XQqvRro¨ß1Xß1Aß1Yß1Bß8{ßF»ßGÉß4ß1jß1j{ß1aß1bß1cÉß1dÉß1e¤A}ß1fß1xß1h´´ß1x{ßB|ßIþß1MßK÷}}}{ßH¨line_BhxDNvgdY4¨ß1Xß1Rß1Yß1Sß8{ßF»ßGÉß4ß1jß1j{ß1aß1bß1cÉß1dÉß1e¤A}ß1fß1gß1g{ßB|ßIþßJßK÷}ß1h´´}}÷}¨version¨¤J}</details>

**Comment by langonginc** [comment]
您好，很抱歉我们不接受来自百度的来源，请您更换来源，感谢您的贡献。
