### ISSUE TITLE
Resources: New work of kaohsiung

### ISSUE THREAD

**Issue by langonginc** [railmapgen/rmp-gallery#908]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[kaohsiung-2.txt](https://github.com/railmapgen/rmp-gallery/files/12837689/kaohsiung-2.txt)

#902

**Comment by Windows-Taskmgr** [comment]
您好，在 #902 中的问题已全部被修复，感谢您的贡献。
