### ISSUE TITLE
Resources: Update work of melbourne

### ISSUE THREAD

**Issue by axl099** [railmapgen/rmp-gallery#921]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[melbourne.txt](https://github.com/railmapgen/rmp-gallery/files/12867397/melbourne.txt)

**Comment by langonginc** [comment]
感谢您的贡献！

**Comment by lhq900117** [comment]
真是想不到有生之年竟然能看见中文版的墨尔本城铁路线图，太强了
