### ISSUE TITLE
Resources: New work of tokyogreatertokyoarea

### ISSUE THREAD

**Issue by Samuyuki** [railmapgen/rmp-gallery#923]
[tokyogreatertokyoarea.txt](https://github.com/railmapgen/rmp-gallery/files/12919362/tokyogreatertokyoarea.txt)
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

**Comment by Samuyuki** [comment]
如果可以的话其实希望能和地铁分开展示
这个毕竟是包括了都心50km范围的所有轨道交通系统的版本 和只有地铁的版本还是区分一下比较好

**Comment by thekingofcity** [comment]
嗨，感谢您的贡献。不过对于换乘站还是希望只有一个节点，使用线段的节点偏移来调整平行。方便的话，可以等到年底JR东和明年初自动平行整理线段实现后再提交作品？

**Comment by Samuyuki** [comment]
好的，期待新功能~
感谢工作人员们的辛勤付出~

**Comment by thekingofcity** [comment]
嗨，jr东已部份上线，欢迎使用后提出建议，并提交目前所能制作的部份以待后续更新 :)
