### ISSUE TITLE
Resources: New work of kyoto

### ISSUE THREAD

**Issue by axl099** [railmapgen/rmp-gallery#930]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[kyoto.txt](https://github.com/railmapgen/rmp-gallery/files/13042914/kyoto.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. However, the reference you provided may not be an official implementation as the page clearly stated that [Maztani](https://commons.wikimedia.org/w/index.php?title=User:Maztani&action=edit&redlink=1) made that.

![image](https://github.com/railmapgen/rmp-gallery/assets/3353040/650da1b1-1572-4185-974d-baa559ffe506)

IMO, the official Kyoto rail map can be retrieved via [路線図](https://www.city.kyoto.lg.jp/kotsu/page/0000019770.html) and from [this rail map](https://www.city.kyoto.lg.jp/kotsu/cmsfiles/contents/0000008/8995/202203jprosenzu.pdf), the stations should be changed to only use Guangzhou Metro stations.
