### ISSUE TITLE
Resources: New work of kyoto

### ISSUE THREAD

**Issue by axl099** [railmapgen/rmp-gallery#934]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[kyoto.txt](https://github.com/railmapgen/rmp-gallery/files/13060098/kyoto.txt)

**Comment by thekingofcity** [comment]
Thanks for your contribution. Your work is merged and will be available in Gallery soon :)
