### ISSUE TITLE
Donation: New work of citybuntsu

### ISSUE THREAD

**Issue by CSOND** [railmapgen/rmp-gallery#944]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[citybuntsu.txt](https://github.com/railmapgen/rmp-gallery/files/13175125/citybuntsu.txt)

**Comment by CSOND** [comment]
What I need to do next?

**Comment by thekingofcity** [comment]
Hi, thanks for your support! To match our internal record, I'd like to know when you donated. Your work will be available in Gallery as soon as we find it out :)

**Comment by CSOND** [comment]
I donated today, at 16:45.

**Comment by CSOND** [comment]
I donated at today's afternoon.

**Comment by 28yfang** [comment]
Hi, please keep this issue open until it is merged.

**Comment by CSOND** [comment]
OK

**Comment by CSOND** [comment]
So...

**Comment by thekingofcity** [comment]
Hi, we can not find a donation record today :(   Would you mind uploading a screenshot of 爱发电?
