### ISSUE TITLE
Resources: Update work of qingdao

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmp-gallery#946]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[1698337916488.txt](https://github.com/railmapgen/rmp-gallery/files/13180206/1698337916488.txt)

**Comment by langonginc** [comment]
感谢您的贡献，作品即将被汇入。
