### ISSUE TITLE
Resources: Update work of nanning

### ISSUE THREAD

**Issue by Uasaki-375** [railmapgen/rmp-gallery#948]
[南宁地铁.json](https://github.com/railmapgen/rmp-gallery/files/13191436/default.json)
**Paste or Upload below. They are meant for BOTS ONLY!!!**

**Comment by 28yfang** [comment]
您好，请已正确的格式重新开议题上传（不要删除任何文字，在粗体字下方附上txt文件）。另外，请问您的作品是否是自己重新做了一份？如果是希望您可以直接修改画廊中的。感谢您的贡献。
