### ISSUE TITLE
Resources: Update work of nanning

### ISSUE THREAD

**Issue by Uasaki-375** [railmapgen/rmp-gallery#949]
[nanning.txt](https://github.com/railmapgen/rmp-gallery/files/13194545/nanning.txt)
****This is nanning Underground System****

**Comment by 28yfang** [comment]
您好，请您通过 https://railmapgen.github.io/rmp-gallery/new 使用正确的格式重新开议题上传（不要删除任何文字，在粗体字下方附上txt文件）。
