### ISSUE TITLE
Resources: Update work of hangzhou

### ISSUE THREAD

**Issue by Hsichiene** [railmapgen/rmp-gallery#959]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**
[hangzhou.txt](https://github.com/railmapgen/rmp-gallery/files/13278662/hangzhou.txt)

**Comment by Windows-Taskmgr** [comment]
您好，我们遵循“先到先得”的原则，尊重贡献者的创作权利。由于您的作品是新做的，不是画廊中已有的作品加以修正，所以我们不会将您的作品合入，给您带来的不便尽请谅解。
