### ISSUE TITLE
Resources: New work of Wenzhou

### ISSUE THREAD

**Issue by Hsichiene** [railmapgen/rmp-gallery#964]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**
[wenzhou.txt](https://github.com/railmapgen/rmp-gallery/files/13279791/wenzhou.txt)

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板没有问题，请您等待管理员最终汇入，感谢您的贡献。
