### ISSUE TITLE
Resources: New work of Taizhou

### ISSUE THREAD

**Issue by Hsichiene** [railmapgen/rmp-gallery#966]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "zh-CN": "台州",
        "en": "Taizhou"
    },
    "desc": {
        "zh": "台州轨道交通，是服务于中国浙江省台州市的市域铁路系统，截止2022年12月台州共开通一条市域铁路线路，即台州S1号线",
        "en": "Taizhou Rail Transit is a municipal railway system serving Taizhou,Zhejiang Province,China.Its first line,Taizhou Rail Transit,was opened on December 28,2022."
    },
    "reference": "Gaode.com,Baidu.com ,map.baidu.com,",
    "justification": "As of December 2022 Taizhou Rail Transit has opened 1line of Taizhou Line S1"
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="taizhou">{¨svgViewBoxZoom¨¢2a¨svgViewBoxMin¨{´x´£-8H.-Di´y´£0.-EW}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨shmetro-basic¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨left¨¨middle¨|¨台州火车站¨¨Taizhou Huochezhan¨÷ßA»¢4g¢3YÉ¨stn_3kl_myeFm6¨ßHßI|¨学院路¨¨Xueyuan Lu¨÷ßA»¢5P¢4HÉ¨stn_RrVk3x495A¨¨right¨ßI|¨国博中心¨¨Guobo Zhongxin¨÷ßA»¢5o¢50É¨stn_d6zD2xgzQN¨ßPßI|¨汇丰路¨¨Huifeng Lu¨÷ßA»º5¢5yÉ¨stn_9BkyZ-wpvo¨ßI¨top¨|¨锦泰¨¨Jintai¨÷ßA»º1¢6cÉ¨stn_Y-VSAJL8Tm¨ßPßI|¨恩泽医院¨¨Enze Yiyuan¨÷ßA»¢3x¢7GÉ¨stn_ql103AaGol¨ßPßI|¨台州汽车南站¨¨Taizhou Qiche Nanzhan¨÷ßA»º9¢8EÉ¨stn_sTSYiz7fsV¨ßPßI|¨泽国¨¨Zeguo¨÷ßA»º9¢9CÉ¨stn_cnroLPslPA¨ßPßI|¨温岭火车站¨¨Wenling Huochezhan¨÷ßA»º9¢AAÉ¨stn_Hdqjz6k74L¨ßPßI|¨汇川王¨¨Huichuanwang¨÷ßA»¢47¢AyÉ¨stn_5ZUM3DlwCO¨ßPßI|¨温岭第一人民医院¨¨Wenling Diyi Renmin Yiyuan¨÷ßA»¢4l¢BcÉ¨stn_x0cQAR-LXe¨ßPßI|¨九龙大道¨¨Jiulong Dadao¨÷ßA»º3¢CGÉ¨stn_7t-fqTuxNW¨ßPßI|¨万昌路¨¨Wanchang Lu¨÷ßA»º5¢D9É¨stn_mPetyVadxc¨ßPßI|¨南屏¨¨Nanping¨÷ßA»º5¢E2É¨stn_WDRUB33yGN¨ßPßI|´城南´¨Chengnan¨÷ßA»º5¢EvÉ¨stn_NXEcpxp_QA¨—{ßG¨misc_node_Wz2X47fSsu¨ß8{ßE»ßFÉ´x´¢8s´y´¢34ß4¨text¨ß14{¨content¨´´¨fontSize¨¤G¨lineHeight¨¤G¨textAnchor¨ßI¨dominantBaseline¨ßI¨language¨´en´¨color¨|¨shanghai¨¨jsr¨¨#000000¨¨#fff¨÷¨rotate¨É¨italic¨¨normal¨¨bold¨ß1I}}}{ßG¨misc_node_QfRZlBzTGf¨ß8{ßE»ßFÉ´x´¢3d´y´ºDß4¨facilities¨ß1L{ß4¨railway¨}}}{ßG¨misc_node_9oVDUlgGrd¨ß8{ßE»ßFÉ´x´º1´y´¢39ß4ß1Lß1L{ß4ß1M}}}{ßG¨misc_node_YTYPWQp6yD¨ß8{ßE»ßFÉ´x´ºO´y´¢APß4ß14ß14{ß15´温岭´ß16Ïß17¤Gß18ßIß19ßIß1A¨mtr__zh¨ß1B|ß1Cß1Dß1Eß1F÷ß1GÉß1Hß1Iß1Jß1I}}}{ßG¨misc_node_upELoOlUqK¨ß8{ßE»ßFÉ´x´º1´y´¢3Oß4ß14ß14{ß15´台州´ß16Ïß17¤Gß18ßIß19ßIß1Aß1Pß1B|ß1Cß1Dß1Eß1F÷ß1GÉß1Hß1Iß1Jß1I}}}{ßG¨misc_node_IO3zc10GgR¨ß8{ßE»ßFÉ´x´¢5F´y´¢Egß4¨berlin-s-bahn-line-badge¨ß1S{¨num¨Êß1B|¨other¨ß1U¨#6363f2¨ß1F÷}}}{ßG¨misc_node_n6VsCF4msm¨ß8{ßE»ßFÉ´x´¢4v´y´¢3Tß4ß1Sß1S{ß1TÊß1B|ß1Uþß1Vß1F÷}}}÷¨edges¨|{ßG¨line_T8kwvY0RLs¨¨source¨ßZ¨target¨ßVß8{ßE»ßFÉß4¨perpendicular¨ß1b{¨startFrom¨¨from¨¨offsetFrom¨É¨offsetTo¨É¨roundCornerFactor¨£I.5K}¨style¨¨single-color¨ß1i{ß1B|ß1Uþß1Vß1F÷}¨reconcileId¨´´}}{ßG¨line_qiptd9AZGs¨ß1ZßSß1aßVß8{ßE»ßFÉß4¨diagonal¨ß1l{ß1cß1dß1eÉß1fÉß1g¤A}ß1hß1iß1i{ß1B|ß1Uþß1Vß1F÷}ß1j´´}}{ßG¨line_EzsKxOgvqf¨ß1ZßLß1aßOß8{ßE»ßFÉß4ß1lß1l{ß1cß1dß1eÉß1fÉß1g¤A}ß1hß1iß1i{ß1B|ß1Uþß1Vß1F÷}ß1j´´}}{ßG¨line_UznafS7P9N¨ß1ZßSß1aßOß8{ßE»ßFÉß4ß1lß1l{ß1cß1dß1eÉß1fÉß1g¤A}ß1hß1iß1i{ß1B|ß1Uþß1Vß1F÷}ß1j´´}}{ßG¨line_6TX-wNwEfm¨ß1ZßZß1aßcß8{ßE»ßFÉß4ß1bß1b{ß1cß1dß1eÉß1fÉß1gÝ2}ß1hß1iß1i{ß1B|ß1Uþß1Vß1F÷}ß1j´´}}{ßG¨line_l3Mv4p5wza¨ß1Zßcß1aßfß8{ßE»ßFÉß4ß1lß1l{ß1cß1dß1eÉß1fÉß1g¤A}ß1hß1iß1i{ß1B|ß1Uþß1Vß1F÷}ß1j´´}}{ßG¨line_VeRj2wnFQV¨ß1Zßfß1aßiß8{ßE»ßFÉß4ß1lß1l{ß1cß1dß1eÉß1fÉß1g¤A}ß1hß1iß1i{ß1B|ß1Uþß1Vß1F÷}ß1j´´}}{ßG¨line_YwAL_y5oOv¨ß1Zßiß1aßlß8{ßE»ßFÉß4ß1lß1l{ß1cß1dß1eÉß1fÉß1g¤A}ß1hß1iß1i{ß1B|ß1Uþß1Vß1F÷}ß1j´´}}{ßG¨line_IzoVAENQ5M¨ß1Zßlß1aßoß8{ßE»ßFÉß4ß1lß1l{ß1cß1dß1eÉß1fÉß1g¤A}ß1hß1iß1i{ß1B|ß1Uþß1Vß1F÷}ß1j´´}}{ßG¨line_q39LXGiqzT¨ß1Zßoß1aßrß8{ßE»ßFÉß4ß1lß1l{ß1cß1dß1eÉß1fÉß1g¤A}ß1hß1iß1i{ß1B|ß1Uþß1Vß1F÷}ß1j´´}}{ßG¨line_2-hl8H0_wW¨ß1Zßrß1aßuß8{ßE»ßFÉß4ß1lß1l{ß1cß1dß1eÉß1fÉß1g¤A}ß1hß1iß1i{ß1B|ß1Uþß1Vß1F÷}ß1j´´}}{ßG¨line_vsT59V6y68¨ß1Zßxß1aßuß8{ßE»ßFÉß4ß1lß1l{ß1cß1dß1eÉß1fÉß1g¤A}ß1hß1iß1i{ß1B|ß1Uþß1Vß1F÷}ß1j´´}}{ßG¨line_9AvPpZ4e61¨ß1Zßxß1aß10ß8{ßE»ßFÉß4ß1lß1l{ß1cß1dß1eÉß1fÉß1g¤A}ß1hß1iß1i{ß1B|ß1Uþß1Vß1F÷}ß1j´´}}{ßG¨line_GWVU9iUzur¨ß1Zß10ß1aß12ß8{ßE»ßFÉß4ß1lß1l{ß1cß1dß1eÉß1fÉß1g¤A}ß1hß1iß1i{ß1B|ß1Uþß1Vß1F÷}ß1j´´}}÷}¨version¨¤K}</details>

**Comment by langonginc** [comment]
抱歉，您的来源 高德地图、百度地图、百度 并不能被我们接受，请您更换官方来源，感谢您的贡献。
