### ISSUE TITLE
Unable to sort works in RMP Gallery / Fantasy

### ISSUE THREAD

**Issue by lyy0323** [railmapgen/rmp-gallery#982]
Hi, 
I've just found in RMP Gallery / Fantasy page that when I click the "sort by" pull-down list and would like the works to be sorted by update time, they're not correctly sorted. I suppose this might be a bug. Chrome browser used.

**Comment by thekingofcity** [comment]
@wongchito IMO, this should be a railmapgen/rmp-gallery issue.

**Comment by thekingofcity** [comment]
Hi, thanks for reporting the problem. We fixed this and will be available in next release :)
