### ISSUE TITLE
Resources: New work of shanghaiyananroadmediumcapacitytransit

### ISSUE THREAD

**Issue by lyy0323** [railmapgen/rmp-gallery#983]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[shanghaiyananroadmediumcapacitytransit.txt](https://github.com/railmapgen/rmp-gallery/files/13409496/shanghaiyananroadmediumcapacitytransit.txt)

**Comment by Windows-Taskmgr** [comment]
很遗憾，我们暂时不支持上传公交线路，并且我们暂不支持来自百度百科的来源，感谢您的贡献。

**Comment by langonginc** [comment]
欢迎通过捐赠来获得额外机会在“幻想世界”展示您的作品

**Comment by thekingofcity** [comment]
> 欢迎通过捐赠来获得额外机会在“幻想世界”展示您的作品

我觉得上海中运量和香港轻铁没有本质上的不同，都介于大运量地铁和普通公交中，并且也都有独立的线路图和运营 :)

**Comment by thekingofcity** [comment]
Sorry for the inconvenience, we are ready to merge this work but the work you upload does not fit in the current version. Would like to go through the Gallery upload process again and open a new issue?
