### ISSUE TITLE
Resources: Update work of shenzhen

### ISSUE THREAD

**Issue by Xiao-qian111** [railmapgen/rmp-gallery#986]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[shenzhen.txt](https://github.com/railmapgen/rmp-gallery/files/13433689/shenzhen.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. This update is merged and will be available in Gallery soon :)
