### ISSUE TITLE
Resources: Update work of lanzhou

### ISSUE THREAD

**Issue by NOBODYKAJIE** [railmapgen/rmp-gallery#990]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

<details repo="rmp-gallery" type="metadata">{
    "name": {
        "en": "Lanzhou"
    },
    "desc": {
        "en": "As of June 2023, Lanzhou rail transit has opened a total of 2 lines, including line 1 and Line 2, all using the subway system, a total of 27 stations (transfer stations double counting), the total length of the subway line 34.96 kilometers.\nAs of May 6, 2021, the highest daily passenger volume of Lanzhou rail transit was 317,800 passengers on May 1, 2021. In June 2012, the National Development and Reform Commission approved the Short-term Construction Plan of Lanzhou Urban Rail Transit (2011 ~ 2020).\nIt is clear in the planning: according to the overall urban planning and comprehensive transportation planning of Lanzhou city, the long-term urban rail transit network of Lanzhou city is composed of 6 lines, with a total length of about 207 kilometers, with a density of 0.83 kilometers/square kilometers in the core area and 0.34 kilometers/square kilometers in the central area. In the network, Line 1, 2 and 3 are the central urban line, and Line 1 is the east-west backbone line of the urban area, traversing the central urban area, connecting the core and sub-center of the city, strengthening the connection between Xigu, Anning, Qilihe and Chengguan districts, connecting the main external transportation hub and the important functional nodes of the city; Line 2 is the second east-west backbone line of the city, strengthening the connection between Anning, Qilihe, Chengguan and Yantan groups; Line 3 is a line connecting the two sides of the Yellow River in Chengguan District, strengthening the connection between Chengguan, Yanchangbao, Yantan, and Heping groups. Line 4, 5 and 6 are three city lines, namely Zhongchuan Line, Yuzhong Line and Qingshi Line, which strengthen the connection between the central city and the outer groups. It is estimated that in 2020, public transport trips in Lanzhou urban area will account for 40% of all mode trips, and rail transit will account for 15-20% of public transport trips.\nThe first phase of Lanzhou Rail Transit Line 2 (Dongfanghong Square to Yanbei section) is 9.06 kilometers in length, with 9 stations including Dongfanghong Square Station, Post and Telecommunications Building Station, Lanzhou Railway Station, Hongxing Lane Station, Tuanjie Xincun Station, Wulipu Station, Zhangsutan Station, Junjiatan Station, Yanbai Bridge Station, 1 parking lot, 1 main substation, and the control center is shared with Line 1. Among them, Dongfang Red Square station and Wulipu Station have been designed and constructed synchronously with Line 1",
        "zh-CN": "截至2023年06月，兰州轨道交通已开通运营线路共有2条，包括1、2号线，均采用地铁系统，共27座车站（换乘站重复计算），地铁线路总长34.96千米。\n截至2021年5月6日，兰州轨道交通最高日客运量为2021年5月1日的31.78万人次。2012年06月，国家发展改革委批准了《兰州市城市轨道交通近期建设规划（2011年～2020年）》。\n规划中明确：依据兰州城市总体规划和综合交通规划，兰州市远景规划城市轨道交通线网由6条线路组成，总长约207千米，核心区线网密度0.83千米/平方千米，中心城区线网密度0.34 千米/平方千米。线网中， 1、2、3号线为中心城区线，1号线是市区东西向骨干线路，横贯中心城区，连接城市核心区和副中心，加强西固、安宁、七里河、城关四区的联系，衔接主要对外交通枢纽和城市重要功能节点；2号线是市区东西向的第二条骨干线路，加强安宁、七里河、城关、雁滩组团之间的联系；3号线是沟通城关区黄河两岸的线路，强化城关、盐场堡、雁滩、和平组团的联系。4、5、6号线分别为中川线、榆中线和青什线3条市域线，加强中心城区与外围组团之间的联系。预计2020年，兰州市区公共交通出行占全方式出行量的40%，轨道交通占公共交通出行量的15～20%。\n兰州轨道交通2号线一期工程（东方红广场至雁北路段）全长9.06公里，共设东方红广场站、邮电大楼站、兰州火车站、红星巷站、团结新村站、五里铺站、张苏滩站、均家滩站、雁白大桥站等9座车站，1座停车场，1座主变电站，控制中心与1号线共用，其中东方红广场站、五里铺站已与1号线同步设计、同步施工"
    },
    "reference": "https://www.lzgdjt.com/lzgd/",
    "justification": "New template of "
}</details>

<details repo="rmp-gallery" type="real_world" compress="zipson" city="lanzhou">{¨svgViewBoxZoom¨¢2k¨svgViewBoxMin¨{´x´£-2M.-9g´y´£1l.1c}¨graph¨{¨options¨{¨type¨¨directed¨¨multi¨»¨allowSelfLoops¨»}¨attributes¨{}¨nodes¨|¦ß8¦¨shmetro-basic¨¦¨nameOffsetX¨¨nameOffsetY¨¨names¨‡ß4¨visible¨´x´´y´¨zIndex¨‡¨key¨‡¨right¨¨top¨|¨陈官营¨¨CHENGUANYING¨÷ßA»¢Ae¢89É¨stn_O8OVcZSLit¨ßH¨middle¨|¨深安大桥南¨¨Shen'an Bridge South¨÷ßA»¢Ck¢7VÉ¨stn_LzQf6Px74L¨ßMßI|¨兰州城市学院(省科技馆)¨¨Lanzhou City University\\(Gansu Science &amp; Technology Museum)¨÷ßA»¢Eb¢5yÉ¨stn_swwP1BI8a8¨ßHßI|¨兰州海关¨¨Lanzhou Customs¨÷ßA»¢GIº6É¨stn_5sRasMItj6¨ßHßI|¨马滩¨¨MATAN¨÷ßA»¢IJº4É¨stn_-rd-k3ISPG¨ßHßI|¨土门墩¨¨TUMENDUN¨÷ßA»¢Jlº2É¨stn_T3Dn2z1TaU¨ßMßI|¨兰州西站北广场¨¨Lanzhou West Railway Station North Square¨÷ßA»¢Lrº2É¨stn_T70jkfcWMO¨ßHßI|¨西站什字¨¨XIZHANSHIZI¨÷ßA»¢Niº2É¨stn_Y6u6a6vBSn¨ßHßI|¨七里河¨¨QILIHE¨÷ßA»¢Peº2É¨stn_7N8OzW4ti2¨ßHßI|¨小西湖¨¨XIAOXIHU Park¨÷ßA»¢Rkº2É¨stn_A490WQka3i¨ßHßI|¨文化宫¨¨cultural palace¨÷ßA»¢U0º2É¨stn_LBJ7YtMbsz¨ßHßI|¨西关¨¨XIGUAN¨÷ßA»¢WBº2É¨stn_RQpGW7Fzwj¨ßHßI|¨省镇府¨¨Gansu Provincial Government¨÷ßA»¢YCº2É¨stn_uz9Tc_M35Z¨—{ßG¨stn_AD0gM7uxMD¨ß8{ßE»ßFÉ´x´¢aI´y´º2ß4¨shmetro-int¨ßy{ßD|¨东方红广场¨¨DONFANGHONG Square¨÷ßBßHßCßI¨rotate¨¢1S¨height¨¤A¨width¨¤J}}}{ßG¨stn_2uBbX579sk¨ß8{ßE»ßFÉ´x´¢cJ´y´º2ß4ßAßA{ßD|¨兰州大学¨¨Lanzhou University¨÷ßBßHßCßI}}}{ßG¨stn_n7iCbdyCiy¨ß8{ßE»ßFÉ´x´¢eo´y´º2ß4ßyßy{ßD|¨五里铺¨¨WULIPU¨÷ßBßHßCßIß11ºIß12¤Aß13¤D}}}{ßG¨stn_-vGQwsmbdJ¨ß8{ßE»ßFÉ´x´¢hE´y´º2ß4ßAßA{ßD|¨省气象局¨¨Gansu Provincial Meteorological Bureau¨÷ßBßHßCßI}}}{ßG¨stn_l5-8PWLL0F¨ß8{ßE»ßFÉ´x´¢jy´y´º2ß4ßAßA{ßD|¨拱星墩¨¨GUNGXINGDUN¨÷ßBßHßCßI}}}{ßG¨stn_T31MHz10DI¨ß8{ßE»ßFÉ´x´¢mT´y´º2ß4ßAßA{ßD|¨焦家湾¨¨JIAOJIAWAN¨÷ßBßHßCßI}}}{ßG¨stn_BgpUw-g27Y¨ß8{ßE»ßFÉ´x´¢p3´y´º2ß4ßAßA{ßD|´东岗´¨DONGGANG¨÷ßBßHßCßI}}}{ßG¨stn_-zcjzbHCzY¨ß8{ßE»ßFÉ´x´¢bp´y´¢9Rß4ßAßA{ßD|¨邮电大楼¨¨Youdian Dalou¨÷ßBßHßCßI}}}{ßG¨stn_-ye9BYoevP¨ß8{ßE»ßFÉ´x´¢cs´y´¢AFß4ßAßA{ßD|¨兰州火车站¨¨LanZhou Railway Station¨÷ßBßMßC¨bottom¨}}}{ßG¨stn_7jpi22CCb2¨ß8{ßE»ßFÉ´x´¢e5´y´ºSß4ßAßA{ßD|¨红星巷¨¨Hongxingxiang0¨÷ßBßMßCßI}}}{ßG¨stn_9MNVNUByJd¨ß8{ßE»ßFÉ´x´ºK´y´¢9Cß4ßAßA{ßD|¨团结新村¨¨Tuanjie xincun¨÷ßBßHßCßI}}}{ßG¨stn_EdfKjbVbmv¨ß8{ßE»ßFÉ´x´ºK´y´¢6mß4ßAßA{ßD|¨张苏滩¨¨Zhangsutan¨÷ßBßHßCßI}}}{ßG¨stn_lPIYjhAysc¨ß8{ßE»ßFÉ´x´ºK´y´¢5jß4ßAßA{ßD|¨均家滩¨¨Junjiatan¨÷ßBßHßCßI}}}{ßG¨stn_y1ZhdeYV86¨ß8{ßE»ßFÉ´x´ºK´y´¢4Wß4ßAßA{ßD|¨雁白大桥¨¨Yanbai Bridge¨÷ßBßHßCßI}}}{ßG¨misc_node_PkxQ5lPYzl¨ß8{ßE»ßFÉ´x´ºH´y´¢8Eß4¨virtual¨ß1i{}}}{ßG¨misc_node_TGX9791IFO¨ß8{ßE»ßFÉ´x´¢9v´y´¢5tß4ß1iß1i{}}}{ßG¨misc_node_rvFuiU5cUe¨ß8{ßE»ßFÉ´x´¢E7´y´¢7Qß4ß1iß1i{}}}{ßG¨misc_node_U63h_LCIyS¨ß8{ßE»ßFÉ´x´¢H6´y´ºcß4ß1iß1i{}}}{ßG¨misc_node_g3iZMrFrK1¨ß8{ßE»ßFÉ´x´¢J2´y´ºWß4ß1iß1i{}}}{ßG¨misc_node_ei0-VkLewU¨ß8{ßE»ßFÉ´x´¢dv´y´¢3Oß4ß1iß1i{}}}{ßG¨misc_node_lZOHIMRL5-¨ß8{ßE»ßFÉ´x´¢sC´y´ºgß4ß1iß1i{}}}{ßG¨misc_node_V4gEfbkSpb¨ß8{ßE»ßFÉ´x´¢AA´y´ºcß4¨chongqingrt-num-line-badge¨ß1q{¨num¨Ê¨color¨|¨other¨ß1t¨#3cbfff¨¨#fff¨÷}}}{ßG¨misc_node_dJuUSs68-r¨ß8{ßE»ßFÉ´x´ºT´y´¢4Mß4ß1qß1q{ß1rËß1s|¨chongqing¨¨cq1¨¨#e4002b¨ß1v÷}}}{ßG¨misc_node_deXn_qv-Qy¨ß8{ßE»ßFÉ´x´¢c9´y´¢APß4¨facilities¨ß21{ß4¨railway_suzhou¨}}}{ßG¨misc_node_yJwEBZwrQs¨ß8{ßE»ßFÉ´x´¢L3´y´¢7kß4ß21ß21{ß4ß22}}}÷¨edges¨|¦ß8¦¨diagonal¨¦¨offsetFrom¨¨offsetTo¨¨roundCornerFactor¨¨startFrom¨‡¨reconcileId¨¨single-color¨¦ß1s‡¨style¨ß4ßEßF‡ßG¨source¨¨target¨‡ÉÉ¤A¨from¨´´|ß1tþß1uß1v÷ß2Bß25»É¨line_Kg_SOYUeD4¨ßLßPÉÉ¤A´to´´´|ß1tþß1uß1v÷ß2Bß25»É¨line_e19jMJSRht¨ßPßSÉÉ¤Aß2F´´|ß1tþß1uß1v÷ß2Bß25»É¨line_Z4SmPTPpbZ¨ßSßVÉÉ¤Aß2F´´|ß1tþß1uß1v÷ß2Bß25»É¨line_LMDnQGrmnG¨ßVßYÉÉ¤Aß2F´´|ß1tþß1uß1v÷ß2Bß25»É¨line_G1GUwv2Dyv¨ßbßY—{ßG¨line_rPTTYh7x1V¨ß2Dßbß2Eßqß8{ßE»ßFÉß4¨perpendicular¨ß2M{ß29ß2Fß26Éß27Éß28£I.5K}ß2Cß2Bß2B{ß1s|ß1tþß1uß1v÷}ß2A´´}}{ßG¨line_xmBZF4sM-l¨ß2Dßqß2Eßtß8{ßE»ßFÉß4ß2Mß2M{ß29ß2Fß26Éß27Éß28Ý2}ß2Cß2Bß2B{ß1s|ß1tþß1uß1v÷}ß2A´´}}{ßG¨line_gDA57ttUfu¨ß2Dßtß2Eßwß8{ßE»ßFÉß4ß25ß25{ß29ß2Fß26Éß27Éß28¤A}ß2Cß2Bß2B{ß1s|ß1tþß1uß1v÷}ß2A´´}}{ßG¨line_uT0B2g4ZiA¨ß2Dßwß2Eß1Jß8{ßE»ßFÉß4ß2Mß2M{ß29ß2Fß26Éß27Éß28Ý2}ß2Cß2Bß2B{ß1s|ß1tþß1uß1v÷}ß2A´´}}{ßG¨line_6rvs7PU6kY¨ß2Dß1Lß2Eß1hß8{ßE»ßFÉß4ß25ß25{ß29´to´ß26Éß27Éß28¤A}ß2Cß2Bß2B{ß1s|ß1tþ¨#e30000¨ß1v÷}ß2A´´}}{ßG¨line_XE1qrlTCW2¨ß2Dß1Oß2Eß1Lß8{ßE»ßFÉß4ß25ß25{ß29ß2Fß26Éß27Éß28¤A}ß2Cß2Bß2B{ß1s|ß1tþß2Rß1v÷}ß2A´´}}{ßG¨line_yxDKXmEhy-¨ß2Dß1Oß2Eß1Sß8{ßE»ßFÉß4ß2Mß2M{ß29ß2Fß26Éß27Éß28Ý2}ß2Cß2Bß2B{ß1s|ß1tþß2Rß1v÷}ß2A´´}}{ßG¨line_bgH4stXQs3¨ß2Dß1Sß2Eß1Vß8{ßE»ßFÉß4ß2Mß2M{ß29ß2Fß26Éß27Éß28Ý2}ß2Cß2Bß2B{ß1s|ß1tþß2Rß1v÷}ß2A´´}}{ßG¨line_2I2w1Mypda¨ß2Dß1Vß2Eß1bß8{ßE»ßFÉß4ß2Mß2M{ß29ß2Fß26Éß27Éß28Ý2}ß2Cß2Bß2B{ß1s|ß1tþß2Rß1v÷}ß2A´´}}{ßG¨line_IjU1xfhMCg¨ß2Dß1bß2Eß1eß8{ßE»ßFÉß4ß2Mß2M{ß29ß2Fß26Éß27Éß28Ý2}ß2Cß2Bß2B{ß1s|ß1tþß2Rß1v÷}ß2A´´}}{ßG¨line_9pukZwLZlz¨ß2Dß1jß2Eß1kß8{ßE»ßFÄß4ß25ß25{ß29ß2Fß26Éß27Éß28¤A}ß2C¨river¨ß2A´´ß2Y{ß1s|¨shanghai¨ß2Y¨#B9E3F9¨ß1v÷ß13¤K}}}{ßG¨line_h6ys-0UakX¨ß2Dß1kß2Eß1lß8{ßE»ßFÄß4ß2Mß2M{ß29ß2Fß26Éß27Éß28Ý2}ß2Cß2Yß2A´´ß2Y{ß1s|ß2Zß2Yß2aß1v÷ß13¤K}}}{ßG¨line_TOckqSAdWu¨ß2Dß1lß2Eß1mß8{ßE»ßFÄß4ß25ß25{ß29ß2Fß26Éß27Éß28¤A}ß2Cß2Yß2A´´ß2Y{ß1s|ß2Zß2Yß2aß1v÷ß13¤K}}}{ßG¨line_WhPxqI6z_s¨ß2Dß1nß2Eß1mß8{ßE»ßFÄß4ß25ß25{ß29´to´ß26Éß27Éß28¤A}ß2Cß2Yß2A´´ß2Y{ß1s|ß2Zß2Yß2aß1v÷ß13¤K}}}{ßG¨line_XvBZuBRKGU¨ß2Dß1nß2Eß1oß8{ßE»ßFÄß4ß2Mß2M{ß29ß2Fß26Éß27Éß28Ý2}ß2Cß2Yß2A´´ß2Y{ß1s|ß2Zß2Yß2aß1v÷ß13¤K}}}÷}¨version¨¤L}</details>

**Comment by thekingofcity** [comment]
Hi, you need to fill in the Justification with the reason why you make those changes :)
