### ISSUE TITLE
Resources: Update work of hongkong

### ISSUE THREAD

**Issue by xiao-slm** [railmapgen/rmp-gallery#995]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**
[hongkong.txt](https://github.com/railmapgen/rmp-gallery/files/13459500/hongkong.txt)

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. However, your save contains a text node with the default _Enter your text here_ context, font size 0, and color white. Besides, the 博覽館/AsiaWorld-Expo is duplicated. Please remove these redundant text nodes :)

**Comment by 28yfang** [comment]
Hi @xiao-slm , I checked on the official website, however the English words in the key isn't written in bold. Could you please provide your sources?

**Comment by xiao-slm** [comment]
> 嗨，我在官方网站上查看了一下，但是键中的英文单词不是用粗体写的。你能提供你的消息来源吗？

https://www.mtr.com.hk/archive/en/services/routemap.pdf

**Comment by 28yfang** [comment]
您好，根据您提供的线路图，经过与车站名称的比较，可以看到均未使用粗体字。
![image](https://github.com/railmapgen/rmp-gallery/assets/123239445/3aec47a2-aba8-4768-9ede-56d0706bedd1)

**Comment by xiao-slm** [comment]
![image](https://github.com/railmapgen/rmp-gallery/assets/146796722/e86edbec-90b9-4270-a929-a818a82f7c81)
加粗后与原图相符

**Comment by 28yfang** [comment]
原来如此
那问题修复之后再上传一次吧
