### ISSUE TITLE
Resources: Update work of hongkong

### ISSUE THREAD

**Issue by xiao-slm** [railmapgen/rmp-gallery#997]
Hi RMP team! I would like to contribute to the gallery with the data below.

**Paste or Upload below. They are meant for BOTS ONLY!!!**

[hongkong.txt](https://github.com/railmapgen/rmp-gallery/files/13462804/hongkong.txt)

**Comment by thekingofcity** [comment]
Hi, the text node with _Enter your text here_ is still not removed :(
